import { company } from "@/lib/company";
import { germanizeDeep } from "@/lib/german-text";
import {
  serviceGraphDatasetJsonLd,
  serviceGraphDatasetReference,
} from "@/lib/schema-datasets";

export function OrganizationJsonLd() {
  const jsonLd = {
    "@type": "Organization",
    "@id": `${company.url}/#organization`,
    name: company.name,
    alternateName: ["FLOXANT Service Regensburg"],
    url: company.url,
    logo: `${company.url}/logo_v10.png`,
    email: company.email,
    telephone: company.phoneRaw,
    address: {
      "@type": "PostalAddress",
      streetAddress: company.streetAddress,
      addressLocality: company.city,
      postalCode: company.postalCode,
      addressRegion: company.state,
      addressCountry: company.countryCode,
    },
    location: {
      "@type": "Place",
      name: `${company.name} ${company.city}`,
      address: {
        "@type": "PostalAddress",
        streetAddress: company.streetAddress,
        addressLocality: company.city,
        postalCode: company.postalCode,
        addressRegion: company.state,
        addressCountry: company.countryCode,
      },
      geo: {
        "@type": "GeoCoordinates",
        latitude: Number(company.geo.lat.toFixed(5)),
        longitude: Number(company.geo.lng.toFixed(5)),
      },
    },
    contactPoint: [
      {
        "@type": "ContactPoint",
        telephone: company.phoneRaw,
        email: company.email,
        contactType: "customer service",
        areaServed: "DE",
        availableLanguage: ["de", "en"],
      },
    ],
    description:
      "FLOXANT organisiert Umzug, Reinigung, Entrümpelung, Haushaltsauflösung, Gewerbereinigung, Endreinigung, Angebotsprüfung und diskrete Abstimmungen mit Schwerpunkt Regensburg. Reinigung ist auf Regensburg und den 50-km-Umkreis begrenzt.",
    areaServed: company.primaryServiceAreas.map((area) => ({
      "@type":
        area === "Bayern"
          ? "State"
          : area === "Oberpfalz" ||
              area === "Landkreis Regensburg" ||
              area.includes("200 km") ||
              area.includes("Umgebung")
            ? "AdministrativeArea"
            : "City",
      name: area,
    })),
    knowsAbout: [
      "Umzug",
      "Reinigung",
      "Entrümpelung",
      "Büroumzug",
      "Firmenentsorgung",
      "Gewerbereinigung",
      "Umzug Düsseldorf",
      "Entrümpelung Düsseldorf",
      "Haushaltsauflösung Düsseldorf",
      "Wohnungsauflösung Düsseldorf",
      "Büroreinigung Regensburg",
      "Büroreinigung Regensburg Angebot",
      "Büroreinigung Kosten Regensburg",
      "Büro Reinigungskraft Regensburg",
      "Büroreinigung nach Feierabend Regensburg",
      "Praxisreinigung Regensburg",
      "Arztpraxis Reinigung Regensburg",
      "Praxisreinigung Angebot Regensburg",
      "Reinigung Praxisräume Regensburg",
      "Praxisreinigung nach Praxisschluss Regensburg",
      "Hotelreinigung Regensburg",
      "Hotel Reinigung Firma Regensburg",
      "Zimmerreinigung Regensburg",
      "Hotel Unterhaltsreinigung Regensburg",
      "Pension Reinigung Regensburg",
      "Boardinghouse Reinigung Regensburg",
      "Fensterreinigung Regensburg",
      "Glasreinigung Regensburg",
      "Fenster putzen lassen Regensburg",
      "Schaufensterreinigung Regensburg",
      "Fensterreinigung Kosten Regensburg",
      "Baureinigung Regensburg",
      "Bauendreinigung Regensburg",
      "Baufeinreinigung Regensburg",
      "Reinigung nach Renovierung Regensburg",
      "Handwerkerstaub entfernen Regensburg",
      "Teppichreinigung Regensburg",
      "Teppichbodenreinigung Regensburg",
      "Polsterreinigung Regensburg",
      "Sofa reinigen lassen Regensburg",
      "Bürostühle reinigen Regensburg",
      "Treppenhausreinigung Regensburg",
      "Hausverwaltung Reinigung Regensburg",
      "Treppenhausreinigung Kosten Regensburg",
      "Treppenhaus reinigen lassen Regensburg",
      "WEG Reinigung Regensburg",
      "Unterhaltsreinigung Regensburg",
      "Grundreinigung Regensburg",
      "Wohnung Grundreinigung Regensburg",
      "Büro Grundreinigung Regensburg",
      "Grundreinigung nach Auszug Regensburg",
      "starke Verschmutzung reinigen Regensburg",
      "Bueroreinigung Regensburg Angebot",
      "Reinigungsplan Buero Regensburg",
      "Objektreinigung Regensburg",
      "Umzug im 200-km-Umkreis Regensburg",
      "Hotelreinigung",
      "Praxisreinigung",
      "Private Client Service",
      "Wohnungsauflösung",
      "Endreinigung",
      "Kurzfristige Reinigung",
      "Reinigung nach Veranstaltung",
      "Reinigung nach Party",
      "Eventreinigung",
      "Beiladung",
      "Umzug mit Reinigung",
      "Express-Anfrage",
      "Preisvorstellung",
      "Preisrahmen",
      "Google Maps Buchungslink",
      "Angebot günstiger prüfen",
      "Angebotscheck",
      "Plan-B-Service",
      "Schlüsselübergabe Service",
      "Übergabeprotokoll",
      "Zugang und Ablauf prüfen",
      "Leer-Rückfahrt / Rückladung",
      "Übergabeakte",
      "Auszug vorbereiten",
      "Übergabe vorbereiten",
      "Nachlass-Räumung",
      "Immobilie verkaufsbereit machen",
      "Diskreter Umzug",
      "Entsorgung Düsseldorf",
      "Regensburg",
      "Umgebung Regensburg 200 km",
      "Bayern",
    ],
    subjectOf: [
      { "@type": "WebPage", name: "FLOXANT Fakten", url: `${company.url}/floxant-fakten` },
      { "@type": "WebPage", name: "Buchung starten", url: company.businessProfilePreferredUrl },
      { "@type": "WebPage", name: "Kontakt Regensburg", url: company.contactUrl },
      { "@type": "WebPage", name: "Standorte und Einsatzgebiet", url: company.locationsUrl },
      { "@type": "WebPage", name: "Gewerbereinigung Regensburg", url: `${company.url}/regensburg/gewerbereinigung` },
      { "@type": "WebPage", name: "Büroreinigung Regensburg", url: `${company.url}/regensburg/bueroreinigung` },
      { "@type": "WebPage", name: "Praxisreinigung Regensburg", url: `${company.url}/praxisreinigung-regensburg` },
      { "@type": "WebPage", name: "Hotelreinigung Regensburg", url: `${company.url}/hotelreinigung-regensburg` },
      { "@type": "WebPage", name: "Fensterreinigung Regensburg", url: `${company.url}/fensterreinigung-regensburg` },
      { "@type": "WebPage", name: "Baureinigung Regensburg", url: `${company.url}/baureinigung-regensburg` },
      { "@type": "WebPage", name: "Teppichreinigung Regensburg", url: `${company.url}/teppichreinigung-regensburg` },
      { "@type": "WebPage", name: "Treppenhausreinigung Regensburg", url: `${company.url}/treppenhausreinigung-regensburg` },
      { "@type": "WebPage", name: "Unterhaltsreinigung Regensburg", url: `${company.url}/unterhaltsreinigung-regensburg` },
      { "@type": "WebPage", name: "Grundreinigung Regensburg", url: `${company.url}/grundreinigung-regensburg` },
      { "@type": "WebPage", name: "Kurzfristige Reinigung", url: `${company.url}/notfallreinigung-24h` },
      { "@type": "WebPage", name: "Reinigung nach Veranstaltung", url: `${company.url}/reinigung-nach-veranstaltung` },
      { "@type": "WebPage", name: "Einsatzradar Regensburg", url: `${company.url}/einsatzradar-regensburg` },
      { "@type": "WebPage", name: "Regensburg", url: `${company.url}/regensburg` },
      { "@type": "WebPage", name: "Schlüsselübergabe Service", url: `${company.url}/schluesseluebergabe` },
      { "@type": "WebPage", name: "Übergabeakte", url: `${company.url}/uebergabeakte` },
      { "@type": "WebPage", name: "Umzug mit Reinigung", url: `${company.url}/umzug-mit-reinigung` },
      { "@type": "WebPage", name: "Leer-Rückfahrt / Rückladung", url: `${company.url}/rueckfahrt-boerse` },
      { "@type": "CreativeWork", name: "FLOXANT llms.txt", url: `${company.url}/llms.txt` },
      serviceGraphDatasetReference,
    ],
    sameAs: company.sameAs,
    slogan: "Umzug, Reinigung, Entrümpelung, Entsorgung und Angebotsprüfung direkt anfragen.",
    keywords:
      "Umzug Regensburg, Reinigung Regensburg, Reinigung 50 km Regensburg, Büroreinigung Regensburg, Büroreinigung Regensburg Angebot, Büroreinigung Kosten Regensburg, Praxisreinigung Regensburg, Arztpraxis Reinigung Regensburg, Hotelreinigung Regensburg, Fensterreinigung Regensburg, Glasreinigung Regensburg, Baureinigung Regensburg, Bauendreinigung Regensburg, Teppichreinigung Regensburg, Treppenhausreinigung Regensburg, Hausverwaltung Reinigung Regensburg, Unterhaltsreinigung Regensburg, Grundreinigung Regensburg, Gewerbereinigung Regensburg, Reinigung Neutraubling, Reinigung Lappersdorf, Reinigung Pentling, Reinigung Kelheim, Reinigung Schwandorf, Reinigung Straubing, Entrümpelung Regensburg, Angebot anderer Firma prüfen",
    knowsLanguage: ["de", "en"],
    potentialAction: [
      {
        "@type": "ContactAction",
        name: "FLOXANT Anfrage starten",
        target: company.businessProfilePreferredUrl,
      },
      {
        "@type": "Action",
        name: "Kostenrahmen prüfen",
        target: `${company.url}/rechner`,
      },
      {
        "@type": "Action",
        name: "Angebot anderer Firma prüfen",
        target: `${company.url}/angebot-guenstiger-pruefen`,
      },
    ],
    hasOfferCatalog: {
      "@type": "OfferCatalog",
      name: "FLOXANT Kernleistungen und Buchungswege",
      itemListElement: [
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Buchung", url: company.businessProfilePreferredUrl } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Umzug", url: `${company.url}/umzug` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Reinigung", url: `${company.url}/reinigung` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Kurzfristige Reinigung", url: `${company.url}/notfallreinigung-24h` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Reinigung nach Veranstaltung", url: `${company.url}/reinigung-nach-veranstaltung` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Entrümpelung", url: `${company.url}/entruempelung` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Gewerbereinigung Regensburg", url: `${company.url}/regensburg/gewerbereinigung` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Büroreinigung Regensburg", url: `${company.url}/regensburg/bueroreinigung` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Praxisreinigung Regensburg", url: `${company.url}/praxisreinigung-regensburg` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Hotelreinigung Regensburg", url: `${company.url}/hotelreinigung-regensburg` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Fensterreinigung Regensburg", url: `${company.url}/fensterreinigung-regensburg` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Baureinigung Regensburg", url: `${company.url}/baureinigung-regensburg` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Teppichreinigung Regensburg", url: `${company.url}/teppichreinigung-regensburg` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Treppenhausreinigung Regensburg", url: `${company.url}/treppenhausreinigung-regensburg` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Unterhaltsreinigung Regensburg", url: `${company.url}/unterhaltsreinigung-regensburg` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Grundreinigung Regensburg", url: `${company.url}/grundreinigung-regensburg` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Plan-B-Service", url: `${company.url}/plan-b-service` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Schlüsselübergabe Service", url: `${company.url}/schluesseluebergabe` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Übergabeprotokoll und Übergabeakte", url: `${company.url}/uebergabeakte` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Leer-Rückfahrt / Rückladung", url: `${company.url}/rueckfahrt-boerse` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Angebot günstiger prüfen", url: `${company.url}/angebot-guenstiger-pruefen` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Entsorgung Düsseldorf", url: `${company.url}/entsorgung-duesseldorf` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "FLOXANT Fakten und Leistungsübersicht", url: `${company.url}/floxant-fakten` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Private Client Service", url: `${company.url}/private-client-service` } },
      ],
    },
  };

  const graph = {
    "@context": "https://schema.org",
    "@graph": [jsonLd, serviceGraphDatasetJsonLd],
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(germanizeDeep(graph)) }}
    />
  );
}
