import { company } from "@/lib/company";
import { germanizeDeep } from "@/lib/german-text";

export function OrganizationJsonLd() {
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": `${company.url}/#organization`,
    name: company.name,
    alternateName: ["FLOXANT Premium Services"],
    url: company.url,
    logo: `${company.url}/logo_v10.png`,
    email: company.email,
    telephone: company.phoneRaw,
    address: {
      "@type": "PostalAddress",
      streetAddress: company.streetAddress,
      addressLocality: company.city,
      postalCode: company.postalCode,
      addressRegion: company.state,
      addressCountry: company.countryCode,
    },
    location: {
      "@type": "Place",
      name: `${company.name} ${company.city}`,
      address: {
        "@type": "PostalAddress",
        streetAddress: company.streetAddress,
        addressLocality: company.city,
        postalCode: company.postalCode,
        addressRegion: company.state,
        addressCountry: company.countryCode,
      },
      geo: {
        "@type": "GeoCoordinates",
        latitude: Number(company.geo.lat.toFixed(5)),
        longitude: Number(company.geo.lng.toFixed(5)),
      },
    },
    contactPoint: [
      {
        "@type": "ContactPoint",
        telephone: company.phoneRaw,
        email: company.email,
        contactType: "customer service",
        areaServed: "DE",
        availableLanguage: ["de"],
      },
    ],
    description:
      "FLOXANT organisiert Umzug, Reinigung, Entrümpelung, Büroumzug, Firmenentsorgung, Gewerbereinigung, Leer-Rückfahrt und diskrete Premium-Projekte mit operativem Kern in Regensburg, Nahbereich ca. 200 km und Bayern nach Verfügbarkeit. Düsseldorf ist separat für Reinigung positioniert; Entsorgung wird nur auf einer eigenen vorhandenen Seite geführt.",
    areaServed: company.primaryServiceAreas.map((area) => ({
      "@type":
        area === "Bayern"
          ? "State"
          : area === "Oberpfalz" ||
              area === "Landkreis Regensburg" ||
              area.includes("200 km") ||
              area.includes("Umgebung")
            ? "AdministrativeArea"
            : "City",
      name: area,
    })),
    knowsAbout: [
      "Umzug",
      "Reinigung",
      "Entrümpelung",
      "Büroumzug",
      "Firmenentsorgung",
      "Gewerbereinigung",
      "Umzug im 200-km-Umkreis Regensburg",
      "Hotelreinigung",
      "Praxisreinigung",
      "Private Client Service",
      "Wohnungsauflösung",
      "Endreinigung",
      "Notfallreinigung 24h",
      "Reinigung nach Veranstaltung",
      "Reinigung nach Party",
      "Eventreinigung",
      "Beiladung",
      "Umzug mit Reinigung",
      "Express-Anfrage",
      "Preisvorstellung",
      "Preisrahmen",
      "Google Maps Buchungslink",
      "Angebot günstiger prüfen",
      "Angebotscheck",
      "Plan-B-Service",
      "Schlüsselübergabe Service",
      "Übergabeprotokoll",
      "Zugang und Ablauf prüfen",
      "Leer-Rückfahrt / Rückladung",
      "Übergabeakte",
      "Auszug vorbereiten",
      "Übergabe vorbereiten",
      "Nachlass-Räumung",
      "Immobilie verkaufsbereit machen",
      "Diskreter Umzug",
      "B2B-Reinigung Düsseldorf",
      "Büroreinigung Düsseldorf",
      "Firmenreinigung Düsseldorf",
      "Gewerbereinigung Düsseldorf",
      "Reinigung Düsseldorf Stadtteile",
      "Reinigung Neuss",
      "Reinigung Ratingen",
      "Reinigung Meerbusch",
      "Reinigung Mettmann",
      "Reinigung Duisburg",
      "Reinigungsangebot Düsseldorf prüfen",
      "Hotelreinigung Düsseldorf",
      "Hotel Reinigung Düsseldorf",
      "Boardinghouse Reinigung Düsseldorf",
      "Kanzleireinigung Düsseldorf",
      "Praxisreinigung Düsseldorf",
      "Kellerreinigung Düsseldorf",
      "Endreinigung Düsseldorf",
      "Apartment-Reinigung Düsseldorf",
      "Reinigung möblierte Wohnung Düsseldorf",
      "Entsorgung Düsseldorf",
      "Regensburg",
      "Umgebung Regensburg 200 km",
      "Bayern",
    ],
    subjectOf: [
      { "@type": "WebPage", name: "FLOXANT Fakten", url: `${company.url}/floxant-fakten` },
      { "@type": "WebPage", name: "Buchung starten", url: company.businessProfilePreferredUrl },
      { "@type": "WebPage", name: "Kontakt Regensburg", url: company.contactUrl },
      { "@type": "WebPage", name: "Standorte und Einsatzgebiet", url: company.locationsUrl },
      { "@type": "WebPage", name: "Gewerbereinigung Regensburg", url: `${company.url}/gewerbereinigung-regensburg` },
      { "@type": "WebPage", name: "Notfallreinigung 24h", url: `${company.url}/notfallreinigung-24h` },
      { "@type": "WebPage", name: "Reinigung nach Veranstaltung", url: `${company.url}/reinigung-nach-veranstaltung` },
      { "@type": "WebPage", name: "Einsatzradar Regensburg", url: `${company.url}/einsatzradar-regensburg` },
      { "@type": "WebPage", name: "Einsatzgebiet Regensburg ca. 200 km", url: `${company.url}/einsatzgebiet-regensburg-200km` },
      { "@type": "WebPage", name: "Servicegebiet Bayern", url: `${company.url}/service-area-bayern` },
      { "@type": "WebPage", name: "Schlüsselübergabe Service", url: `${company.url}/schluesseluebergabe` },
      { "@type": "WebPage", name: "Übergabeakte", url: `${company.url}/uebergabeakte` },
      { "@type": "WebPage", name: "Umzug mit Reinigung", url: `${company.url}/umzug-mit-reinigung` },
      { "@type": "WebPage", name: "Leer-Rückfahrt / Rückladung", url: `${company.url}/rueckfahrt-boerse` },
      { "@type": "WebPage", name: "B2B-Reinigung Düsseldorf", url: `${company.url}/duesseldorf/bueroreinigung` },
      { "@type": "WebPage", name: "Düsseldorf B2B-Reinigung eigene Seite", url: `${company.url}/duesseldorf/b2b-reinigung` },
      { "@type": "WebPage", name: "Firmenreinigung Düsseldorf", url: `${company.url}/duesseldorf/firmenreinigung` },
      { "@type": "WebPage", name: "Gewerbereinigung Düsseldorf", url: `${company.url}/duesseldorf/gewerbereinigung` },
      { "@type": "WebPage", name: "Reinigung Düsseldorf Stadtteile und Umgebung", url: `${company.url}/duesseldorf/reinigung-stadtteile-umgebung` },
      { "@type": "WebPage", name: "Düsseldorf Angebot vielleicht günstiger prüfen", url: `${company.url}/duesseldorf/vielleicht-guenstiger` },
      { "@type": "WebPage", name: "Hotelreinigung Düsseldorf", url: `${company.url}/duesseldorf/hotelreinigung` },
      { "@type": "WebPage", name: "Kanzleireinigung Düsseldorf", url: `${company.url}/duesseldorf/kanzleireinigung` },
      { "@type": "WebPage", name: "Praxisreinigung Düsseldorf", url: `${company.url}/duesseldorf/praxisreinigung` },
      { "@type": "WebPage", name: "Kellerreinigung Düsseldorf", url: `${company.url}/duesseldorf/kellerreinigung` },
      { "@type": "WebPage", name: "Endreinigung Düsseldorf", url: `${company.url}/duesseldorf/endreinigung` },
      { "@type": "WebPage", name: "Apartment-Reinigung Düsseldorf", url: `${company.url}/reinigung-moeblierte-wohnung-duesseldorf` },
      { "@type": "CreativeWork", name: "FLOXANT llms.txt", url: `${company.url}/llms.txt` },
      { "@type": "Dataset", name: "FLOXANT Service Graph", url: `${company.url}/service-graph.json` },
    ],
    sameAs: company.sameAs,
    slogan: "Umzug, Reinigung, Entrümpelung, Entsorgung und Angebotsprüfung direkt anfragen.",
    keywords:
      "Umzug Regensburg, Reinigung Regensburg, Entrümpelung Regensburg, Angebot anderer Firma prüfen, B2B-Reinigung Düsseldorf, Büroreinigung Düsseldorf, Firmenreinigung Düsseldorf, Gewerbereinigung Düsseldorf, Hotelreinigung Düsseldorf, Kanzleireinigung Düsseldorf, Praxisreinigung Düsseldorf, Reinigung Neuss, Reinigung Ratingen, Reinigung Meerbusch, Reinigung Mettmann, Reinigung Duisburg, Angebot prüfen Düsseldorf, FLOXANT Bayern",
    knowsLanguage: ["de"],
    potentialAction: [
      {
        "@type": "ContactAction",
        name: "FLOXANT Anfrage starten",
        target: company.businessProfilePreferredUrl,
      },
      {
        "@type": "Action",
        name: "Kostenrahmen prüfen",
        target: `${company.url}/rechner`,
      },
      {
        "@type": "Action",
        name: "Angebot anderer Firma prüfen",
        target: `${company.url}/angebot-guenstiger-pruefen`,
      },
    ],
    hasOfferCatalog: {
      "@type": "OfferCatalog",
      name: "FLOXANT Kernleistungen und Buchungswege",
      itemListElement: [
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Buchung", url: company.businessProfilePreferredUrl } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Umzug", url: `${company.url}/umzug` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Reinigung", url: `${company.url}/reinigung` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Notfallreinigung 24h", url: `${company.url}/notfallreinigung-24h` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Reinigung nach Veranstaltung", url: `${company.url}/reinigung-nach-veranstaltung` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Entrümpelung", url: `${company.url}/entruempelung` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Gewerbereinigung Regensburg", url: `${company.url}/gewerbereinigung-regensburg` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Plan-B-Service", url: `${company.url}/plan-b-service` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Schlüsselübergabe Service", url: `${company.url}/schluesseluebergabe` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Übergabeprotokoll und Übergabeakte", url: `${company.url}/uebergabeakte` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Leer-Rückfahrt / Rückladung", url: `${company.url}/rueckfahrt-boerse` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Angebot günstiger prüfen", url: `${company.url}/angebot-guenstiger-pruefen` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "B2B-Reinigung Düsseldorf", url: `${company.url}/duesseldorf/bueroreinigung` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Firmenreinigung Düsseldorf", url: `${company.url}/duesseldorf/firmenreinigung` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Gewerbereinigung Düsseldorf", url: `${company.url}/duesseldorf/gewerbereinigung` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Kanzleireinigung Düsseldorf", url: `${company.url}/duesseldorf/kanzleireinigung` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Praxisreinigung Düsseldorf", url: `${company.url}/duesseldorf/praxisreinigung` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Reinigung Düsseldorf Stadtteile und Umgebung", url: `${company.url}/duesseldorf/reinigung-stadtteile-umgebung` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Düsseldorf Angebot vielleicht günstiger prüfen", url: `${company.url}/duesseldorf/vielleicht-guenstiger` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Hotelreinigung Düsseldorf", url: `${company.url}/duesseldorf/hotelreinigung` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Apartment-Reinigung Düsseldorf", url: `${company.url}/reinigung-moeblierte-wohnung-duesseldorf` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Entsorgung Düsseldorf", url: `${company.url}/entsorgung-duesseldorf` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "FLOXANT Service Graph", url: `${company.url}/service-graph.json` } },
        { "@type": "Offer", itemOffered: { "@type": "Service", name: "Private Client Service", url: `${company.url}/private-client-service` } },
      ],
    },
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(germanizeDeep(jsonLd)) }}
    />
  );
}
