import type { TrustPolicySection } from "@/components/editorial/TrustPolicyPage";

export const editorialSectionsDe: readonly TrustPolicySection[] = [
  { id: "verantwortung", title: "Redaktionelle Verantwortung", paragraphs: ["Für öffentliche FLOXANT-Inhalte ist die organisatorische Rolle FLOXANT Redaktion verantwortlich. Namentliche Autoren oder Reviewer werden nur genannt, wenn Person, Rolle und Freigabe tatsächlich dokumentiert sind."], points: ["Kontakt für Inhaltsfragen: info@floxant.de", "Review-Status und verantwortliche Rolle gehören zur Inhaltsmetadatei", "Nicht freigegebene Entwürfe dürfen nicht indexierbar veröffentlicht werden"] },
  { id: "pruefung", title: "Wie Inhalte geprüft werden", paragraphs: ["Serviceangaben werden mit den veröffentlichten Leistungs- und Faktenregistern abgeglichen. Regionen, Kontaktwege, Leistungsgrenzen und interne Links werden technisch geprüft. Preise, Termine, Bewertungen, Projekte oder Qualifikationen werden nicht ergänzt, wenn kein belastbarer Beleg vorliegt."], points: ["Primärquellen und eigene freigegebene Unternehmensangaben bevorzugen", "Änderungsdatum nur bei einer echten inhaltlichen Änderung", "Unklare Fakten erhalten MANUAL_REVIEW statt einer öffentlichen Behauptung"] },
  { id: "ai", title: "Unterstützung durch AI", paragraphs: ["AI darf bei Strukturentwürfen, Fragenextraktion, Wiederholungserkennung, Übersetzungsentwürfen und Qualitätsprüfungen helfen. AI darf Inhalte nicht automatisch freigeben oder veröffentlichen und keine Unternehmensfakten, Preise, Bewertungen, Projekte, Standorte oder Quellen erfinden."], points: ["AI-Unterstützung wird in den Editorial-Metadaten gekennzeichnet", "Freigabe bleibt eine menschliche Aufgabe", "Aktuell ist kein öffentlicher AI-Concierge aktiviert"] },
  { id: "grenzen", title: "Inhaltliche Grenzen", paragraphs: ["Ratgeber und FAQ erklären, welche Angaben für eine Anfrage hilfreich sind und welche Faktoren den Umfang beeinflussen. Sie ersetzen keine Rechts-, Steuer-, Medizin-, Sicherheits- oder Preisberatung. Eine Anfrage ist keine Termin-, Preis- oder Verfügbarkeitszusage."] },
];

export const methodologySectionsDe: readonly TrustPolicySection[] = [
  { id: "fakten", title: "Fakten vor Formulierung", paragraphs: ["Organisation, Domain, Regionen, Kontaktwege und öffentlich zulässige Leistungen stammen aus einer zentralen Fakten- und Servicequelle. Maschinenlesbare Dateien und sichtbare Seiten sollen dieselben freigegebenen Angaben verwenden."], points: ["bestehende öffentliche Quellen erfassen", "Widersprüche als Review-Aufgabe dokumentieren", "nur bestätigte Einträge öffentlich darstellen"] },
  { id: "nutzen", title: "Eigenständiger Nutzwert", paragraphs: ["Eine Seite oder Frage wird nicht allein wegen einer Suchphrase erstellt. Sie benötigt ein eigenes Entscheidungsproblem, klare Zielgruppe, konkreten Leistungsbezug, Grenzen, passende interne Links und einen nachvollziehbaren nächsten Schritt."] },
  { id: "lokal", title: "Regionale Einordnung", paragraphs: ["Düsseldorf und Regensburg werden nur mit Leistungen verbunden, die bereits öffentlich angeboten oder im Service-Register verifiziert sind. Automatisch erzeugte Stadtteilseiten und erfundene Abdeckung sind ausgeschlossen."] },
  { id: "review", title: "Review und Messung", paragraphs: ["Nach einer kontrollierten Freigabe werden technische Qualität, Suchsignale und Conversion-Qualität beobachtet. Ein höheres Ranking wird nicht versprochen. Merge- oder Redirect-Kandidaten bleiben manuelle Entscheidungen mit eigenem Nachweis."] },
];

export const correctionSectionsDe: readonly TrustPolicySection[] = [
  { id: "melden", title: "Fehler melden", paragraphs: ["Hinweise können mit URL, betroffener Aussage und kurzer Begründung an info@floxant.de gesendet werden. Bitte keine Kundendaten oder vertraulichen Dokumente mitsenden, wenn sie für die Korrektur nicht erforderlich sind."] },
  { id: "ablauf", title: "Korrekturablauf", paragraphs: ["Der Hinweis wird einer verantwortlichen Rolle zugeordnet, mit der Faktenquelle abgeglichen und nach Dringlichkeit bewertet. Bestätigte Fehler werden sachlich korrigiert. Review- und Änderungsdatum werden nur angepasst, wenn tatsächlich Inhalt geändert wurde."], points: ["sicherheits- oder datenschutzrelevante Fehler priorisieren", "keine stillen erfundenen Quellen nachtragen", "Redirects oder Löschungen nur nach separater Prüfung"] },
  { id: "transparenz", title: "Transparenz und Grenzen", paragraphs: ["Kleine Rechtschreibkorrekturen benötigen keinen öffentlichen Änderungsvermerk. Wesentliche Änderungen an Leistung, Region, Methodik oder Aussage werden in der redaktionellen Dokumentation nachvollziehbar festgehalten. Eine Korrektur bedeutet keine Garantie für ein bestimmtes Suchergebnis."] },
];

export const editorialSectionsEn: readonly TrustPolicySection[] = [
  { id: "responsibility", title: "Editorial responsibility", paragraphs: ["Public FLOXANT content is owned by the organisational role FLOXANT editorial team. Named authors or reviewers are shown only when their identity, role and approval are documented."], points: ["Content contact: info@floxant.de", "Review status and owner belong in editorial metadata", "Unapproved drafts must not be indexable"] },
  { id: "review", title: "How content is checked", paragraphs: ["Service details are checked against the public service and facts registries. Regions, contact routes, boundaries and internal links are validated. Prices, dates, reviews, projects or qualifications are not added without reliable evidence."] },
  { id: "ai", title: "Use of AI assistance", paragraphs: ["AI may support outlines, question extraction, repetition checks, translation drafts and quality review. It may not approve or publish content automatically and may not invent company facts, prices, reviews, projects, locations or sources."], points: ["AI assistance is recorded in editorial metadata", "Approval remains a human task", "No public AI concierge is active"] },
  { id: "limits", title: "Content boundaries", paragraphs: ["Guides and FAQs explain useful enquiry details and effort factors. They are not legal, tax, medical, safety or pricing advice. An enquiry is not a confirmed date, price or availability promise."] },
];

export const methodologySectionsEn: readonly TrustPolicySection[] = [
  { id: "facts", title: "Facts before wording", paragraphs: ["Organisation, domain, regions, contact routes and publicly allowed services come from central facts and service registries. Machine-readable files and visible pages should use the same approved facts."] },
  { id: "value", title: "Distinct user value", paragraphs: ["A page or question is not created solely for a search phrase. It needs a distinct decision problem, audience, service context, boundaries, useful internal links and a clear next step."] },
  { id: "local", title: "Local context", paragraphs: ["Düsseldorf and Regensburg are linked only to services that are already publicly offered or verified in the service registry. Automatically generated district pages and invented coverage are excluded."] },
  { id: "review", title: "Review and measurement", paragraphs: ["After a controlled release, technical quality, search signals and conversion quality are monitored. Rankings are not guaranteed. Merge and redirect candidates remain manual, evidence-based decisions."] },
];

export const correctionSectionsEn: readonly TrustPolicySection[] = [
  { id: "report", title: "Report an error", paragraphs: ["Send the URL, affected statement and a short explanation to info@floxant.de. Please do not include customer data or confidential documents unless strictly required for the correction."] },
  { id: "process", title: "Correction process", paragraphs: ["A responsible role checks the note against the underlying source and assesses urgency. Confirmed errors are corrected factually. Review and modification dates change only when content actually changes."], points: ["prioritise safety and privacy issues", "do not add invented sources", "review redirects or removals separately"] },
  { id: "transparency", title: "Transparency and limits", paragraphs: ["Minor spelling corrections do not require a public change note. Material changes to services, regions, methodology or claims are recorded in editorial documentation. A correction does not guarantee a search result."] },
];
