const fs = require('fs');

const data = {
  ro: {
    klaviertransport: { meta_title: "Transport Piane {city} | FLOXANT", meta_desc: "Transport sigur.", hero_badge: "Siguranta", hero_h1: "Transport Piane", hero_p: "Echipa noastra.", badges: { piano: "-", safe: "-", insurance: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    halteverbotszone: { meta_title: "Zona de parcare {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Parcare", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    seniorenumzug: { meta_title: "Mutare Seniori {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Seniori", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    studentenumzug: { meta_title: "Studenti {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Mutare Studenti", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    familienumzug: { meta_title: "Mutare Familie {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Familie", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    entruempelung_spec: { meta_title: "Eliberari {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Eliberari", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    reinigung_spec: { meta_title: "Curatenie {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Curatenie f.", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    umzug24: { meta_title: "Mutari 24h {city}", meta_desc: "-", hero_badge: "-", hero_h1: "24h Mutare", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    kleintransport: { meta_title: "Transport Mic {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Mic Transport", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    bueroumzug: { meta_title: "Mutare Birou {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Birou", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" }
  },
  bg: {
    klaviertransport: { meta_title: "Пиано транспорт {city} | FLOXANT", meta_desc: "-", hero_badge: "-", hero_h1: "Пиана", hero_p: "-", badges: { piano: "-", safe: "-", insurance: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    halteverbotszone: { meta_title: "Зона {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Зона", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    seniorenumzug: { meta_title: "За възрастни {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Възрастни", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    studentenumzug: { meta_title: "Студенти {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Студенти", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    familienumzug: { meta_title: "Семейство {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Семейство", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    entruempelung_spec: { meta_title: "Изчистване {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Изчистване", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    reinigung_spec: { meta_title: "Почистване {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Почистване", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    umzug24: { meta_title: "24ч Транспорт {city}", meta_desc: "-", hero_badge: "-", hero_h1: "24ч Преместване", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    kleintransport: { meta_title: "Мини {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Мини", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    bueroumzug: { meta_title: "Офис {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Офис", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" }
  },
  uk: {
    klaviertransport: { meta_title: "Перевезення піаніно {city} | FLOXANT", meta_desc: "-", hero_badge: "-", hero_h1: "Піаніно", hero_p: "-", badges: { piano: "-", safe: "-", insurance: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    halteverbotszone: { meta_title: "Паркування {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Зона", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    seniorenumzug: { meta_title: "Літнім {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Літнім", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    studentenumzug: { meta_title: "Студентам {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Студентам", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    familienumzug: { meta_title: "Родинам {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Сім'я", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    entruempelung_spec: { meta_title: "Очищення {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Очищення", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    reinigung_spec: { meta_title: "Прибирання {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Прибирання", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    umzug24: { meta_title: "24 год {city}", meta_desc: "-", hero_badge: "-", hero_h1: "24 год", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    kleintransport: { meta_title: "Міні {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Дрібні", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    bueroumzug: { meta_title: "Офіс {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Офісний", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" }
  }
};

const locales = ['ro', 'bg', 'uk'];

locales.forEach(loc => {
    const file = `dictionaries/${loc}.json`;
    if (fs.existsSync(file)) {
        const dict = JSON.parse(fs.readFileSync(file, 'utf8'));
        if (!dict.pages) dict.pages = {};
        
        Object.keys(data[loc]).forEach(namespace => {
            dict.pages[namespace] = data[loc][namespace];
        });
        
        fs.writeFileSync(file, JSON.stringify(dict, null, 2));
        console.log("Updated", loc);
    }
});
