const fs = require('fs');

const data = {
  ko: {
    klaviertransport: { meta_title: "피아노 운송 {city} | FLOXANT", meta_desc: "-", hero_badge: "-", hero_h1: "피아노 운송", hero_p: "-", badges: { piano: "-", safe: "-", insurance: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    halteverbotszone: { meta_title: "주차 금지 구역 {city}", meta_desc: "-", hero_badge: "-", hero_h1: "주차 금지 구역", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    seniorenumzug: { meta_title: "노인 이사 {city}", meta_desc: "-", hero_badge: "-", hero_h1: "노인 이사", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    studentenumzug: { meta_title: "학생 이사 {city}", meta_desc: "-", hero_badge: "-", hero_h1: "학생 이사", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    familienumzug: { meta_title: "가족 이사 {city}", meta_desc: "-", hero_badge: "-", hero_h1: "가족 이사", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    entruempelung_spec: { meta_title: "집 비우기 {city}", meta_desc: "-", hero_badge: "-", hero_h1: "집 비우기", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    reinigung_spec: { meta_title: "청소 {city}", meta_desc: "-", hero_badge: "-", hero_h1: "청소", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    umzug24: { meta_title: "24시간 이사 {city}", meta_desc: "-", hero_badge: "-", hero_h1: "24시간 이사", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    kleintransport: { meta_title: "소형 운송 {city}", meta_desc: "-", hero_badge: "-", hero_h1: "소형 운송", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    bueroumzug: { meta_title: "사무실 이사 {city}", meta_desc: "-", hero_badge: "-", hero_h1: "사무실 이사", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" }
  },
  ja: {
    klaviertransport: { meta_title: "ピアノ輸送 {city} | FLOXANT", meta_desc: "-", hero_badge: "-", hero_h1: "ピアノ輸送", hero_p: "-", badges: { piano: "-", safe: "-", insurance: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    halteverbotszone: { meta_title: "駐車禁止区域 {city}", meta_desc: "-", hero_badge: "-", hero_h1: "駐車禁止区域", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    seniorenumzug: { meta_title: "シニア引っ越し {city}", meta_desc: "-", hero_badge: "-", hero_h1: "シニア引っ越し", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    studentenumzug: { meta_title: "学生引っ越し {city}", meta_desc: "-", hero_badge: "-", hero_h1: "学生引っ越し", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    familienumzug: { meta_title: "家族引っ越し {city}", meta_desc: "-", hero_badge: "-", hero_h1: "家族引っ越し", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    entruempelung_spec: { meta_title: "不用品回収 {city}", meta_desc: "-", hero_badge: "-", hero_h1: "不用品回収", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    reinigung_spec: { meta_title: "クリーニング {city}", meta_desc: "-", hero_badge: "-", hero_h1: "クリーニング", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    umzug24: { meta_title: "24時間引っ越し {city}", meta_desc: "-", hero_badge: "-", hero_h1: "24時間引っ越し", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    kleintransport: { meta_title: "小型輸送 {city}", meta_desc: "-", hero_badge: "-", hero_h1: "小型輸送", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    bueroumzug: { meta_title: "オフィス移転 {city}", meta_desc: "-", hero_badge: "-", hero_h1: "オフィス移転", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" }
  },
  vi: {
    klaviertransport: { meta_title: "Vận chuyển piano {city} | FLOXANT", meta_desc: "-", hero_badge: "-", hero_h1: "Vận chuyển piano", hero_p: "-", badges: { piano: "-", safe: "-", insurance: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    halteverbotszone: { meta_title: "Vùng cấm đỗ xe {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Khu vực cấm", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    seniorenumzug: { meta_title: "Chuyển nhà cho người lớn tuổi {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Chuyển nhà", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    studentenumzug: { meta_title: "Sinh viên {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Sinh viên", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    familienumzug: { meta_title: "Gia đình {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Gia đình", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    entruempelung_spec: { meta_title: "Dọn dẹp {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Dọn dẹp", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    reinigung_spec: { meta_title: "Làm sạch {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Làm sạch", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    umzug24: { meta_title: "24h {city}", meta_desc: "-", hero_badge: "-", hero_h1: "24h", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    kleintransport: { meta_title: "Vận chuyển nhỏ {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Nhỏ", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    bueroumzug: { meta_title: "Văn phòng {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Văn phòng", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "-", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" }
  }
};

const locales = ['ko', 'ja', 'vi'];

locales.forEach(loc => {
    const file = `dictionaries/${loc}.json`;
    if (fs.existsSync(file)) {
        const dict = JSON.parse(fs.readFileSync(file, 'utf8'));
        if (!dict.pages) dict.pages = {};
        
        Object.keys(data[loc]).forEach(namespace => {
            dict.pages[namespace] = data[loc][namespace];
        });
        
        fs.writeFileSync(file, JSON.stringify(dict, null, 2));
        console.log("Updated", loc);
    }
});
