const fs = require('fs');

const data = {
  es: {
    klaviertransport: { meta_title: "Transporte de Pianos {city} | FLOXANT", meta_desc: "Transporte seguro de pianos.", hero_badge: "Seguro", hero_h1: "Transporte de Pianos y Cajas Fuertes", hero_p: "Totalmente asegurado.", badges: { piano: "Pianos", safe: "Cajas", insurance: "Seguro" }, cta: "Pedir Presupuesto", service1: { title: "Pianos", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "Cajas Fuertes", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "Seguro", section2_p1: "-", section2_p2: "-", wizard_badge: "VIP", wizard_h2: "Presupuesto", wizard_p: "-", link_umzug: "Mudanza", link_senioren: "-", link_halteverbot: "-" },
    halteverbotszone: { meta_title: "Zona de Prohibición de Aparcamiento {city}", meta_desc: "Zona para mudanza.", hero_badge: "Permiso", hero_h1: "Zona de Prohibición de Aparcamiento", hero_p: "Solicitamos el permiso.", badges: { permit: "Permiso", signs: "Señales", stressfree: "Fácil" }, cta: "Solicitar", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "Ayuntamiento", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "Solicitar", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    seniorenumzug: { meta_title: "Mudanza para Mayores {city}", meta_desc: "Mudanza sin estrés.", hero_badge: "Premium", hero_h1: "Mudanza para Mayores", hero_p: "Nos cuidamos de todo.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Pedir", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "Pedir", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    studentenumzug: { meta_title: "Mudanza Estudiantil {city}", meta_desc: "Mudanza barata.", hero_badge: "Estudiantes", hero_h1: "Mudanza Estudiantil", hero_p: "Barato y rápido.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Pedir", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "Pedir", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    familienumzug: { meta_title: "Mudanza Familiar {city}", meta_desc: "Familias.", hero_badge: "Familia", hero_h1: "Mudanza Familiar", hero_p: "Seguro.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Pedir", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "Pedir", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    entruempelung_spec: { meta_title: "Desalojo {city}", meta_desc: "Limpieza profunda.", hero_badge: "Desalojos", hero_h1: "Desalojo de Pisos", hero_p: "Rápido.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Pedir", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "Pedir", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    reinigung_spec: { meta_title: "Limpieza {city}", meta_desc: "Limpieza final.", hero_badge: "Limpieza", hero_h1: "Limpieza Final", hero_p: "Garantía.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Limpiar", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "Pedir", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    umzug24: { meta_title: "Mudanza 24h {city}", meta_desc: "Urgente.", hero_badge: "24h", hero_h1: "Mudanza 24 horas", hero_p: "Hoy mismo.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Ya", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    kleintransport: { meta_title: "Mini Transportes", meta_desc: "Transportes pequeños.", hero_badge: "Mini", hero_h1: "Transportes Pequeños", hero_p: "Un mueble.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Mover", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    bueroumzug: { meta_title: "Mudanza de Oficina {city}", meta_desc: "Oficinas.", hero_badge: "B2B", hero_h1: "Mudanza de Oficinas", hero_p: "Profesionales.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Pedir", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" }
  },
  it: {
    klaviertransport: { meta_title: "Trasporto Pianoforti {city} | FLOXANT", meta_desc: "Trasporto sicuro di pianoforti.", hero_badge: "Sicuro", hero_h1: "Trasporto Pianoforti", hero_p: "Completamente assicurato.", badges: { piano: "Pianoforti", safe: "Casseforti", insurance: "Assicurazione" }, cta: "Richiedi", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "Traslocare", link_senioren: "-", link_halteverbot: "-" },
    halteverbotszone: { meta_title: "Zona di divieto di sosta {city}", meta_desc: "Zona per il trasloco.", hero_badge: "Permesso", hero_h1: "Divieto di Sosta", hero_p: "Richiediamo il permesso.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Richiedi", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    seniorenumzug: { meta_title: "Trasloco per Anziani {city}", meta_desc: "Trasloco senza stress.", hero_badge: "Premium", hero_h1: "Trasloco per Anziani", hero_p: "Ci prendiamo cura di tutto.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Richiedi", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    studentenumzug: { meta_title: "Trasloco Studenti {city}", meta_desc: "Trasloco economico.", hero_badge: "Studenti", hero_h1: "Trasloco Studenti", hero_p: "Economico e veloce.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Richiedi", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    familienumzug: { meta_title: "Trasloco Famiglie {city}", meta_desc: "Famiglie.", hero_badge: "Famiglia", hero_h1: "Trasloco Famiglie", hero_p: "Sicuro.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Richiedi", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    entruempelung_spec: { meta_title: "Sgombero {city}", meta_desc: "Pulizia profonda.", hero_badge: "Sgomberi", hero_h1: "Sgombero", hero_p: "Veloce.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Richiedi", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    reinigung_spec: { meta_title: "Pulizia {city}", meta_desc: "Pulizia finale.", hero_badge: "Pulizia", hero_h1: "Pulizia Finale", hero_p: "Garanzia.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Pulire", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    umzug24: { meta_title: "Trasloco 24h {city}", meta_desc: "Urgente.", hero_badge: "24h", hero_h1: "Trasloco 24 ore", hero_p: "Oggi stesso.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Ora", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    kleintransport: { meta_title: "Mini Trasporti", meta_desc: "Piccoli trasporti.", hero_badge: "Mini", hero_h1: "Piccoli Trasporti", hero_p: "Un mobile.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Muovere", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    bueroumzug: { meta_title: "Trasloco Ufficio {city}", meta_desc: "Uffici.", hero_badge: "B2B", hero_h1: "Trasloco Uffici", hero_p: "Professionisti.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Richiedi", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" }
  },
  pl: {
    klaviertransport: { meta_title: "Transport Pianin {city} | FLOXANT", meta_desc: "Bezpieczny transport.", hero_badge: "Pewny", hero_h1: "Transport Pianin", hero_p: "Ubezpieczone.", badges: { piano: "-", safe: "-", insurance: "-" }, cta: "Zapytaj", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    halteverbotszone: { meta_title: "Strefa {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Zakaz parkowania", hero_p: "Pozwolenia.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Zamów", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    seniorenumzug: { meta_title: "Dla seniorów {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Dla seniorów", hero_p: "Bez stresu.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Zamów", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    studentenumzug: { meta_title: "Studenckie {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Dla studentów", hero_p: "Tanio.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Zamów", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    familienumzug: { meta_title: "Rodzina {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Rodzinne", hero_p: "Spokojnie.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Zamów", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    entruempelung_spec: { meta_title: "Opróżnianie {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Opróżnianie mieszkań", hero_p: "Szybko.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Zamów", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    reinigung_spec: { meta_title: "Sprzątanie {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Sprzątanie końcowe", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Zamów", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    umzug24: { meta_title: "24h {city}", meta_desc: "-", hero_badge: "-", hero_h1: "24h transport", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Zamów", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    kleintransport: { meta_title: "Transporter {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Maty", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Zamów", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    bueroumzug: { meta_title: "Biuro {city}", meta_desc: "-", hero_badge: "-", hero_h1: "Biura", hero_p: "-", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "Zamów", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" }
  }
};

const locales = ['es', 'it', 'pl'];

locales.forEach(loc => {
    const file = `dictionaries/${loc}.json`;
    if (fs.existsSync(file)) {
        const dict = JSON.parse(fs.readFileSync(file, 'utf8'));
        if (!dict.pages) dict.pages = {};
        
        Object.keys(data[loc]).forEach(namespace => {
            dict.pages[namespace] = data[loc][namespace];
        });
        
        fs.writeFileSync(file, JSON.stringify(dict, null, 2));
        console.log("Updated", loc);
    }
});
