const fs = require('fs');

const data = {
  tr: {
    klaviertransport: { meta_title: "Piyano & Kasa Taşıma {city} | FLOXANT", meta_desc: "{city} profesyonel ambalajlı piyano ve kasa taşıma hizmeti.", hero_badge: "Özel Taşıma", hero_h1: "Piyano & Kasa Taşıma", hero_p: "Ağır yükler uzmanlık ve özel sigorta gerektirir. Bunu biz sağlıyoruz.", badges: { piano: "Piyano", safe: "Kasa", insurance: "Özel Sigorta" }, cta: "Ağır Taşıma İsteyin", service1: { title: "Piyano Taşıma", l1: "Özel ekipman", l2: "Koruma", l3: "İklim kontrollü", l4: "Akort" }, service2: { title: "Kasa Taşıma", l1: "2000 kg kadar", l2: "Hidrolik", l3: "Kontrol", l4: "Gizli işlem" }, section2_h2: "{city} Ağır Taşıma", section2_p1: "Dar alanlarda bile uzman çözüm.", section2_p2: "Tam gizlilik ve sigorta.", wizard_badge: "Özel Hizmet", wizard_h2: "{city} Taşıma İste", wizard_p: "Ağırlık ve detayları bildirin.", link_umzug: "Nakliyat {city}", link_senioren: "Yaşlı Nakliyatı", link_halteverbot: "Park Yasağı" },
    halteverbotszone: { meta_title: "Park Yasağı Bölgesi {city} | FLOXANT", meta_desc: "{city} taşınma için park yasağı izni alın.", hero_badge: "İzin Servisi", hero_h1: "Park Yasağı Bölgesi", hero_p: "Cezalardan kaçının. Tüm park izni işlemlerinizi biz hallediyoruz.", badges: { permit: "Şehir İzni", signs: "Kurulum", stressfree: "Stressiz Park" }, cta: "Bölge İsteyin", service1: { title: "Tam Hizmet", l1: "Belediye başvurusu", l2: "Tabela kiralama", l3: "72s öncesi kurulum", l4: "Toplama" }, service2: { title: "Tabela Kiralama", l1: "İzin başvurusu", l2: "Teslimat", l3: "Kurulum", l4: "İade" }, section2_h2: "{city} Sipariş Ver", section2_p1: "Önceden başvuru gerekir.", section2_p2: "Bürokrasiyle biz ilgilenelim.", wizard_badge: "Şehir Servisi", wizard_h2: "Kurulum İsteyin", wizard_p: "Yükleme adresini bildirin.", link_umzug: "Nakliyat {city}", link_senioren: "Yaşlı Nakliyatı", link_halteverbot: "Piyano" },
    seniorenumzug: { meta_title: "Yaşlı Evden Eve Nakliyat {city} | FLOXANT", meta_desc: "{city} yaşlılar için stressiz nakliyat.", hero_badge: "Hassas Taşıma", hero_h1: "Yaşlı Nakliyatı", hero_p: "Paketlemeden kuruluma her şeyi hallediyoruz.", badges: { permit: "Sabır", signs: "Tam Hizmet", stressfree: "Atık imhası dahil" }, cta: "Nakliyat İste", service1: { title: "Her Şey Dahil", l1: "Paketleme", l2: "Montaj", l3: "Lamba montajı", l4: "Açma" }, service2: { title: "Boşaltma", l1: "Eski eşya imhası", l2: "Temiz teslim", l3: "Bağış", l4: "Çevre dostu" }, section2_h2: "Hassas Taşıma {city}", section2_p1: "Eski eşyalardan ayrılmanın zor olduğunu biliyoruz.", section2_p2: "Özel eğitimli ekip.", wizard_badge: "Premium", wizard_h2: "Nakliye İsteyin", wizard_p: "Ücretsiz randevu.", link_umzug: "Nakliyat", link_senioren: "Park yasağı", link_halteverbot: "Temizlik" },
    studentenumzug: { meta_title: "Öğrenci Nakliyatı {city} | FLOXANT", meta_desc: "Ucuz öğrenci taşıma {city}.", hero_badge: "Öğrenci İndirimi", hero_h1: "Öğrenci Taşıma", hero_p: "Bütçeniz kısıtlı mı? {city} ucuz öğrenci taşımacılığı sunuyoruz.", badges: { permit: "Hızlı", signs: "Ucuz", stressfree: "Esnek" }, cta: "İste", service1: { title: "Araç ve Şoför", l1: "Siz taşıyın", l2: "Biz sürelim", l3: "Battaniye dahil", l4: "Yakıt dahil" }, service2: { title: "Tam taşıma", l1: "Her şey bizde", l2: "Öğrenci indirimi", l3: "Montaj", l4: "Hızlı" }, section2_h2: "{city} Taşıma", section2_p1: "Yurt veya paylaşımlı ev.", section2_p2: "Ucuz taşıma ayırtın.", wizard_badge: "İndirim", wizard_h2: "İndirim İste", wizard_p: "Ucuz fiyat alın.", link_umzug: "Nakliyat", link_senioren: "Küçük", link_halteverbot: "Park" },
    familienumzug: { meta_title: "Aile Nakliyatı {city} | FLOXANT", meta_desc: "Aileler için stressiz taşıma.", hero_badge: "Aile Hizmeti", hero_h1: "Aile Nakliyatı", hero_p: "Çocuklarla taşınmak mı? Bize güvenin.", badges: { permit: "Hızlı", signs: "Dikkatli", stressfree: "Çocuk dostu" }, cta: "Taşıma İste", service1: { title: "Paket", l1: "Oyuncak", l2: "Mutfak", l3: "Kıyafet", l4: "Kitap" }, service2: { title: "Taşıma", l1: "Güvenli", l2: "Hızlı", l3: "Sigortalı", l4: "Kurulu" }, section2_h2: "Aile Taşıma {city}", section2_p1: "Neye ihtiyaç olduğunu biliyoruz.", section2_p2: "Şimdi rezervasyon yapın.", wizard_badge: "Aile", wizard_h2: "Taşıma iste", wizard_p: "Detay verin.", link_umzug: "Nakliyat", link_senioren: "Temizlik", link_halteverbot: "Boşaltma" },
    entruempelung_spec: { meta_title: "Ev Boşaltma {city} | FLOXANT", meta_desc: "{city} ev temizliği ve atık imhası.", hero_badge: "Eşya Boşaltma", hero_h1: "Ev Boşaltma", hero_p: "Daireleri, bodrumları hızlıca boşaltıyoruz.", badges: { permit: "Hızlı", signs: "Gizli", stressfree: "Değer Testi" }, cta: "Boşaltma iste", service1: { title: "Tam boşaltma", l1: "Daire", l2: "Bodrum", l3: "Sabit fiyat", l4: "Hızlı" }, service2: { title: "Elden çıkarma", l1: "Çevre dostu", l2: "Ağır eşya", l3: "Temiz", l4: "Bağış" }, section2_h2: "Boşaltma {city}", section2_p1: "Uzman hizmet.", section2_p2: "Randevu al.", wizard_badge: "Boşalt", wizard_h2: "Boşalt", wizard_p: "Bize bildirin.", link_umzug: "Nakliyat", link_senioren: "Temiz", link_halteverbot: "Boya" },
    reinigung_spec: { meta_title: "Teslimat Temizliği {city} | FLOXANT", meta_desc: "Taşınma sonrası %100 teslimat garantisi ile temizlik.", hero_badge: "Temizlik", hero_h1: "Taşınma Temizliği", hero_p: "Stres yapmayın. {city} apartman temizliğini biz hallediyoruz.", badges: { permit: "Garanti", signs: "Ekolojik", stressfree: "Derin temiz" }, cta: "Temizlik İste", service1: { title: "Derin", l1: "Banyo mutfak", l2: "Pencere", l3: "Lekeler", l4: "Radyatör" }, service2: { title: "Garanti", l1: "Bedava onarım", l2: "Ev sahibi onaylı", l3: "Şeffaf", l4: "Hızlı" }, section2_h2: "Temizlik", section2_p1: "-", section2_p2: "Rezerve et.", wizard_badge: "Temiz", wizard_h2: "İste", wizard_p: "Bilgi girin.", link_umzug: "Nakliyat", link_senioren: "Eski", link_halteverbot: "Boş" },
    umzug24: { meta_title: "24s Acil Navigasyon {city} | FLOXANT", meta_desc: "24 saat içinde taşınma.", hero_badge: "Ekspres", hero_h1: "24 Saat Nakliyat", hero_p: "Acil bir taşınma mı gerekiyor?", badges: { permit: "Acil", signs: "Hızlı", stressfree: "Şimdi" }, cta: "Acil İste", service1: { title: "Hızlı Taşıma", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "Acil Nakliye", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "Hızlı {city}", section2_p1: "Bugün al.", section2_p2: "Yarın taşın.", wizard_badge: "Acil", wizard_h2: "Acil taşı", wizard_p: "Hemen girin.", link_umzug: "Nakliye", link_senioren: "Acil", link_halteverbot: "Özel" },
    kleintransport: { meta_title: "Küçük Nakliyat | FLOXANT", meta_desc: "Mini eşyaları güvenle taşıma.", hero_badge: "Küçük Taksi", hero_h1: "Küçük Taşımacılık", hero_p: "Birkaç eşya mı? Halletmek kolay.", badges: { permit: "Ucuz", signs: "Hızlı", stressfree: "Kolay" }, cta: "Taşı", service1: { title: "A'dan B'ye", l1: "Eşya taksi", l2: "Ebay", l3: "Ikea", l4: "Küçük yük" }, service2: { title: "Öğrenci", l1: "1 oda", l2: "Yurt", l3: "Paylaşımlı", l4: "ofis" }, section2_h2: "Küçük Eşya", section2_p1: "İdeal çözüm.", section2_p2: "Online al.", wizard_badge: "Taşı", wizard_h2: "İste", wizard_p: "Bildirin.", link_umzug: "Nakliyat", link_senioren: "Genel", link_halteverbot: "Mini" },
    bueroumzug: { meta_title: "Ofis Nakliyatı {city} | FLOXANT", meta_desc: "Profesyonel B2B taşımacılığı.", hero_badge: "B2B", hero_h1: "Ofis Taşımacılığı", hero_p: "Ofisler özel planlama gerektirir.", badges: { permit: "Hızlı", signs: "BT Güvenli", stressfree: "Resmi" }, cta: "Talep Et", service1: { title: "Bilişim", l1: "Güvenli ağ", l2: "Kablolama", l3: "Sunucu", l4: "Koruma" }, service2: { title: "Mobilya", l1: "Dosyalar", l2: "Montaj", l3: "Hızlı", l4: "Gizli" }, section2_h2: "Ofis {city}", section2_p1: "Kesin.", section2_p2: "Güvenli.", wizard_badge: "Ofis", wizard_h2: "Fiyat Al", wizard_p: "Bilgi girin.", link_umzug: "Nakliye", link_senioren: "Kurumsal", link_halteverbot: "Ticari" }
  },
  ru: {
    klaviertransport: { meta_title: "Перевозка пианино и сейфов {city} | FLOXANT", meta_desc: "Профессиональная перевозка. Полностью застраховано.", hero_badge: "Специальный транспорт", hero_h1: "Перевозка пианино и сейфов", hero_p: "Для таких работ нужны специальные навыки и страховка. Это про нас.", badges: { piano: "Пианино", safe: "Сейфы", insurance: "Страховка" }, cta: "Запросить перевозку", service1: { title: "Перевозка пианино", l1: "Спец. тележки", l2: "Защита", l3: "Климат-контроль", l4: "Настройка" }, service2: { title: "Сейфы", l1: "До 2000 кг", l2: "Гидравлика", l3: "Проверка полов", l4: "Конфиденциально" }, section2_h2: "Спецтранспорт {city}", section2_p1: "Рады помочь.", section2_p2: "Полная гарантия.", wizard_badge: "Сервис", wizard_h2: "Запросить цену", wizard_p: "Укажите вес.", link_umzug: "Переезд", link_senioren: "Услуги", link_halteverbot: "Зона" },
    halteverbotszone: { meta_title: "Зона запрета парковки {city} | FLOXANT", meta_desc: "Оформление зоны парковки в {city}.", hero_badge: "Услуги", hero_h1: "Зона запрета парковки", hero_p: "Избегайте штрафов. Мы оформим зону для вас.", badges: { permit: "Город", signs: "Установка", stressfree: "Без стресса" }, cta: "Заказать зону", service1: { title: "Полный сервис", l1: "Заявка", l2: "Аренда", l3: "Установка за 72ч", l4: "Снятие" }, service2: { title: "Только аренда", l1: "Вы подаете", l2: "Мы привозим", l3: "Вы ставите", l4: "Забираем" }, section2_h2: "Заказать парковку", section2_p1: "Сроки до 14 дней.", section2_p2: "Избавим от бюрократии.", wizard_badge: "Город", wizard_h2: "Заказать", wizard_p: "Адрес загрузки.", link_umzug: "Переезд", link_senioren: "Для стариков", link_halteverbot: "Пианино" },
    seniorenumzug: { meta_title: "Переезд для пожилых {city} | FLOXANT", meta_desc: "Спокойный переезд для пожилых. Все включено.", hero_badge: "С заботой", hero_h1: "Переезд для пожилых", hero_p: "Мы сделаем всё сами, от упаковки до сборки.", badges: { permit: "Забота", signs: "Всё включено", stressfree: "С вывозом" }, cta: "Заказать", service1: { title: "Пакет всё включено", l1: "Упаковка", l2: "Сборка", l3: "Люстры", l4: "Распаковка" }, service2: { title: "Освобождение", l1: "Утилизация", l2: "Под веник", l3: "Пожертвования", l4: "Экологично" }, section2_h2: "Бережный переезд", section2_p1: "Сложно расставаться со старым.", section2_p2: "Придем на помощь.", wizard_badge: "Премиум", wizard_h2: "Услуга", wizard_p: "Бесплатный осмотр.", link_umzug: "Переезд", link_senioren: "Сбор", link_halteverbot: "Вывоз" },
    studentenumzug: { meta_title: "Студенческий переезд {city} | FLOXANT", meta_desc: "Дешево для студентов {city}.", hero_badge: "Скидка", hero_h1: "Студенческий переезд", hero_p: "Мало бюджета? Предложим дешевый вариант.", badges: { permit: "Быстро", signs: "Дешево", stressfree: "Гибко" }, cta: "Заказать", service1: { title: "Водитель", l1: "Вы пакуете", l2: "Мы везем", l3: "Пледы", l4: "Бензин" }, service2: { title: "Полностью", l1: "Всё сами", l2: "Скидка студенту", l3: "Сборка", l4: "Быстро" }, section2_h2: "Студентам", section2_p1: "Общага или квартира.", section2_p2: "Дешево.", wizard_badge: "Акция", wizard_h2: "Запросить", wizard_p: "Выгодная цена.", link_umzug: "Переезд", link_senioren: "Мини", link_halteverbot: "Уборка" },
    familienumzug: { meta_title: "Семейный переезд {city} | FLOXANT", meta_desc: "Переезд с детьми.", hero_badge: "Семья", hero_h1: "Семейный переезд", hero_p: "Мы снимем стресс переезда с детьми.", badges: { permit: "Быстро", signs: "Надежно", stressfree: "Для детей" }, cta: "Запросить", service1: { title: "Упаковка", l1: "Игрушки", l2: "Кухня", l3: "Одежда", l4: "Книги" }, service2: { title: "Транспорт", l1: "Безопасно", l2: "Быстро", l3: "Страховка", l4: "Сборка" }, section2_h2: "Семейный {city}", section2_p1: "Знаем, что нужно.", section2_p2: "Закажи сейчас.", wizard_badge: "Семья", wizard_h2: "Переезд", wizard_p: "Детали.", link_umzug: "Переезд", link_senioren: "Мебель", link_halteverbot: "Утилизация" },
    entruempelung_spec: { meta_title: "Утилизация и очистка {city} | FLOXANT", meta_desc: "Сдача под ключ.", hero_badge: "Утилизация", hero_h1: "Очистка помещений", hero_p: "Очищаем квартиры, чердаки, подвалы.", badges: { permit: "Быстро", signs: "Анонимно", stressfree: "Учет ценностей" }, cta: "Заказать", service1: { title: "Очистка", l1: "Квартиры", l2: "Подвалы", l3: "Фикс цена", l4: "Быстро" }, service2: { title: "Выброс", l1: "Эко", l2: "Тяжести", l3: "Чисто", l4: "Отдача" }, section2_h2: "Освобождение", section2_p1: "Поможем в {city}.", section2_p2: "Просто.", wizard_badge: "Очистка", wizard_h2: "Запрос", wizard_p: "Данные.", link_umzug: "Переезд", link_senioren: "Старики", link_halteverbot: "Уборка" },
    reinigung_spec: { meta_title: "Финальная уборка {city} | FLOXANT", meta_desc: "Уборка с гарантией сдачи хозяину.", hero_badge: "Уборка", hero_h1: "Генеральная уборка", hero_p: "С гарантией сдачи ключей 100%.", badges: { permit: "Гарантия", signs: "Эко", stressfree: "Глубокая" }, cta: "Просить", service1: { title: "Уборка", l1: "Ванная", l2: "Окна", l3: "Пятна", l4: "Батареи" }, service2: { title: "Гарантия", l1: "Бесплатное исправление", l2: "Принятие", l3: "Прозрачно", l4: "Быстро" }, section2_h2: "Клининг", section2_p1: "Сияет.", section2_p2: "Бронь.", wizard_badge: "Чисто", wizard_h2: "Заказ", wizard_p: "Метры.", link_umzug: "Переезд", link_senioren: "Упаковка", link_halteverbot: "Пианино" },
    umzug24: { meta_title: "24ч Переезд {city} | FLOXANT", meta_desc: "Быстрый переезд за сутки.", hero_badge: "Экспресс", hero_h1: "Переезд за 24 часа", hero_p: "Нужно срочно съезжать?", badges: { permit: "Срочно", signs: "Быстро", stressfree: "Сейчас" }, cta: "Заказать сейчас", service1: { title: "Экспресс", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "Срочный", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "Срочно", section2_p1: "Сегодня.", section2_p2: "Завтра.", wizard_badge: "24", wizard_h2: "Срочно", wizard_p: "Давай.", link_umzug: "Переезд", link_senioren: "Офис", link_halteverbot: "Квартира" },
    kleintransport: { meta_title: "Малогабаритные перевозки | FLOXANT", meta_desc: "Безопасная перевозка пары вещей.", hero_badge: "Мини-транспорт", hero_h1: "Перевозка единичных грузов", hero_p: "Всего пара вещей? Сделаем.", badges: { permit: "Быстро", signs: "Выгодно", stressfree: "Надёжно" }, cta: "Везти", service1: { title: "А в Б", l1: "Такси для мебели", l2: "Ebay", l3: "Ikea", l4: "Мелкий груз" }, service2: { title: "Малый переезд", l1: "1 комната", l2: "Студент", l3: "Часть кВ", l4: "Офис" }, section2_h2: "Мелкий", section2_p1: "Дешево.", section2_p2: "Бери.", wizard_badge: "Груз", wizard_h2: "Запрос", wizard_p: "Пишите.", link_umzug: "Переезд", link_senioren: "Мини", link_halteverbot: "Объем" },
    bueroumzug: { meta_title: "Офисный переезд {city} | FLOXANT", meta_desc: "B2B безопасные переезды.", hero_badge: "Бизнес", hero_h1: "Офисный переезд", hero_p: "Четкое планирование для офисов.", badges: { permit: "ИТ", signs: "Доки", stressfree: "Быстро" }, cta: "Заказать", service1: { title: "Серверы", l1: "Снимаем", l2: "Вешаем", l3: "Защищаем", l4: "Страхуем" }, service2: { title: "Архивы", l1: "Пакуем", l2: "Шифруем", l3: "Аккуратно", l4: "Тихо" }, section2_h2: "Ваш бизнес", section2_p1: "Залог успеха.", section2_p2: "Идеально.", wizard_badge: "Офис", wizard_h2: "Цена", wizard_p: "Детали.", link_umzug: "Переезд", link_senioren: "Фирма", link_halteverbot: "Комп" }
  },
  fa: {
    klaviertransport: { meta_title: "جابجایی پیانو و گاوصندوق {city} | FLOXANT", meta_desc: "حمل حرفه ای پیانو.", hero_badge: "حمل ویژه", hero_h1: "جابجایی پیانو", hero_p: "نیازمند مهارت و بیمه.", badges: { piano: "پیانو", safe: "گاوصندوق", insurance: "بیمه" }, cta: "درخواست", service1: { title: "پیانو", l1: "چرخ", l2: "محافظ", l3: "دما", l4: "تنظیم" }, service2: { title: "گاوصندوق", l1: "سنگین", l2: "جک", l3: "بررسی", l4: "مخفی" }, section2_h2: "حمل سنگین", section2_p1: "تضمین", section2_p2: "امن.", wizard_badge: "ویژه", wizard_h2: "درخواست", wizard_p: "وزن.", link_umzug: "اسباب کشی", link_senioren: "سالمندان", link_halteverbot: "توقف ممنوع" },
    halteverbotszone: { meta_title: "توقف ممنوع {city} | FLOXANT", meta_desc: "دریافت مجوز توقف.", hero_badge: "مجوز", hero_h1: "توقف ممنوع", hero_p: "دوری از جریمه.", badges: { permit: "شهر", signs: "نصب", stressfree: "بدون استرس" }, cta: "ثبت", service1: { title: "کامل", l1: "رزرو", l2: "اجاره", l3: "نصب", l4: "جمع آوری" }, service2: { title: "فقط اجاره", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "مجوز", section2_p1: "زمان.", section2_p2: "آسان.", wizard_badge: "سرویس", wizard_h2: "درخواست", wizard_p: "آدرس", link_umzug: "اسباب کشی", link_senioren: "سالمندان", link_halteverbot: "پیانو" },
    seniorenumzug: { meta_title: "اسباب کشی سالمندان {city} | FLOXANT", meta_desc: "ویژه سالمندان.", hero_badge: "با دقت", hero_h1: "سالمندان", hero_p: "ما همه کار را میکنیم.", badges: { permit: "دقت", signs: "کامل", stressfree: "دورریز" }, cta: "ثبت", service1: { title: "کامل", l1: "بسته بندی", l2: "نصب", l3: "لوستر", l4: "بازکردن" }, service2: { title: "دورریز", l1: "قدیمی", l2: "تمیز", l3: "خیریه", l4: "مجاز" }, section2_h2: "با افتخار", section2_p1: "سخت است.", section2_p2: "تیم ویژه.", wizard_badge: "VIP", wizard_h2: "اسباب کشی", wizard_p: "مشاوره.", link_umzug: "اسباب کشی", link_senioren: "مجوز", link_halteverbot: "تمیز" },
    studentenumzug: { meta_title: "اسباب کشی دانشجویی {city} | FLOXANT", meta_desc: "ارزان.", hero_badge: "تخفیف", hero_h1: "دانشجویی", hero_p: "بودجه کم؟", badges: { permit: "ارزان", signs: "سریع", stressfree: "انعطاف" }, cta: "ثبت", service1: { title: "شما و ما", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "کامل", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "آموزشی", section2_p1: "خوابگاه.", section2_p2: "ارزان.", wizard_badge: "ارزان", wizard_h2: "دانشجو", wizard_p: "قیمت.", link_umzug: "اسباب کشی", link_senioren: "مینی", link_halteverbot: "تمیز" },
    familienumzug: { meta_title: "خانواده {city} | FLOXANT", meta_desc: "بدون استرس.", hero_badge: "خانواده", hero_h1: "خانواده", hero_p: "با فرزندان؟", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "ثبت", service1: { title: "بسته", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "حمل", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "خانواده", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "ثبت", wizard_p: "-", link_umzug: "اسباب کشی", link_senioren: "تجاری", link_halteverbot: "خلوت" },
    entruempelung_spec: { meta_title: "تخلیه {city} | FLOXANT", meta_desc: "تخلیه کامل.", hero_badge: "تخلیه", hero_h1: "تخلیه منازل", hero_p: "سریع و تمیز.", badges: { permit: "سریع", signs: "مخفی", stressfree: "تخفیف" }, cta: "درخواست", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "تخلیه", section2_p1: "-", section2_p2: "-", wizard_badge: "تخلیه", wizard_h2: "ثبت", wizard_p: "بدون استرس.", link_umzug: "اسباب کشی", link_senioren: "تمیز", link_halteverbot: "مجوز" },
    reinigung_spec: { meta_title: "نظافت {city} | FLOXANT", meta_desc: "تضمین صد در صد.", hero_badge: "تمیز", hero_h1: "نظافت نهایی", hero_p: "تحویل به صاحبخانه.", badges: { permit: "تضمین", signs: "-", stressfree: "-" }, cta: "نظافت", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "تمیز", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "درخواست", wizard_p: "-", link_umzug: "نقل", link_senioren: "-", link_halteverbot: "-" },
    umzug24: { meta_title: "اسباب کشی ۲۴ ساعته | FLOXANT", meta_desc: "نقل سریع.", hero_badge: "فوری", hero_h1: "۲۴ ساعته", hero_p: "اورژانسی؟", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "الان", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    kleintransport: { meta_title: "مینی | FLOXANT", meta_desc: "کوچک.", hero_badge: "کوچک", hero_h1: "وانت بار", hero_p: "کم است؟", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "وانت", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" },
    bueroumzug: { meta_title: "اداری | FLOXANT", meta_desc: "شرکتی.", hero_badge: "شرکتی", hero_h1: "اسباب کشی شرکتی", hero_p: "برنامه ریزی دقیق.", badges: { permit: "-", signs: "-", stressfree: "-" }, cta: "ثبت", service1: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, service2: { title: "-", l1: "-", l2: "-", l3: "-", l4: "-" }, section2_h2: "-", section2_p1: "-", section2_p2: "-", wizard_badge: "-", wizard_h2: "-", wizard_p: "-", link_umzug: "-", link_senioren: "-", link_halteverbot: "-" }
  }
};

const locales = ['tr', 'ru', 'fa'];

locales.forEach(loc => {
    const file = `dictionaries/${loc}.json`;
    if (fs.existsSync(file)) {
        const dict = JSON.parse(fs.readFileSync(file, 'utf8'));
        if (!dict.pages) dict.pages = {};
        
        Object.keys(data[loc]).forEach(namespace => {
            dict.pages[namespace] = data[loc][namespace];
        });
        
        fs.writeFileSync(file, JSON.stringify(dict, null, 2));
        console.log("Updated", loc);
    }
});
