"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Check, ChevronLeft, ChevronRight, Clipboard, Printer, RotateCcw } from "lucide-react";

import {
  clarityCheckItems,
  clarityCheckMethod,
  clarityStatusLabels,
  getApplicableClarityItems,
  getClarityResultLabel,
  type ClarityCheckResult,
  type ClarityCheckServiceType,
  type ClarityCheckStatus,
} from "@/lib/clarity-check";

type ClarityCheckToolProps = {
  locale: "de" | "en";
  contactHref: string;
  onResultChange?: (result: ClarityCheckResult) => void;
  formTargetId?: string;
};

const serviceOptions: Array<{ value: ClarityCheckServiceType; de: string; en: string }> = [
  { value: "cleaning", de: "Reinigung", en: "Cleaning" },
  { value: "moving", de: "Umzug", en: "Moving" },
  { value: "clearance", de: "Räumung / Entrümpelung", en: "Clearance" },
  { value: "general", de: "Andere Dienstleistung", en: "Other service" },
];

const statusOrder: ClarityCheckStatus[] = ["present", "unclear", "missing", "not-relevant"];
const storageKey = "floxant:clarity-check";
const handoffKey = "floxant:tool-handoff";

export function ClarityCheckTool({
  locale,
  contactHref,
  onResultChange,
  formTargetId,
}: ClarityCheckToolProps) {
  const [serviceType, setServiceType] = useState<ClarityCheckServiceType>("cleaning");
  const [screen, setScreen] = useState<"intro" | "questions" | "result">("intro");
  const [currentIndex, setCurrentIndex] = useState(0);
  const [statuses, setStatuses] = useState<Record<string, ClarityCheckStatus>>({});
  const [localSaveEnabled, setLocalSaveEnabled] = useState(false);
  const [copied, setCopied] = useState(false);
  const headingRef = useRef<HTMLHeadingElement>(null);
  const items = useMemo(() => getApplicableClarityItems(serviceType), [serviceType]);
  const activeItem = items[currentIndex];

  const result = useMemo<ClarityCheckResult>(() => {
    const answeredStatuses = items.map((item) => statuses[item.id]).filter(Boolean) as ClarityCheckStatus[];
    const unresolvedItems = items.filter((item) => statuses[item.id] === "unclear" || statuses[item.id] === "missing");
    const missingCount = unresolvedItems.filter((item) => statuses[item.id] === "missing").length;
    const unclearCount = unresolvedItems.length - missingCount;
    const scoreLabel = getClarityResultLabel(locale, answeredStatuses);
    const questions = unresolvedItems.map((item) => (locale === "de" ? item.followUpDe : item.followUpEn));
    const itemLabels = unresolvedItems.map((item) => locale === "de" ? item.titleDe : item.titleEn);
    const summary = locale === "de"
      ? `${clarityCheckMethod.de.name}: ${scoreLabel}. Fehlend: ${missingCount}. Unklar: ${unclearCount}. Rückfragen: ${questions.join(" ") || "Keine Rückfrage aus dem Check."}`
      : `${clarityCheckMethod.en.name}: ${scoreLabel}. Missing: ${missingCount}. Unclear: ${unclearCount}. Questions: ${questions.join(" ") || "No question generated by the check."}`;

    return {
      completed: screen === "result",
      serviceType,
      statuses,
      scoreLevel: missingCount >= 3 ? "hoch" : missingCount > 0 || unclearCount >= 3 ? "mittel" : "gering",
      scoreLabel,
      scoreValue: missingCount + unclearCount,
      categories: [...new Set(unresolvedItems.map((item) => item.category))],
      items: itemLabels,
      questions,
      summary,
    };
  }, [items, locale, screen, serviceType, statuses]);

  useEffect(() => {
    headingRef.current?.focus();
  }, [currentIndex, screen]);

  useEffect(() => {
    onResultChange?.(result);
  }, [onResultChange, result]);

  useEffect(() => {
    if (!localSaveEnabled) return;
    window.localStorage.setItem(storageKey, JSON.stringify({ serviceType, statuses }));
  }, [localSaveEnabled, serviceType, statuses]);

  function startCheck() {
    setStatuses({});
    setCurrentIndex(0);
    setScreen("questions");
    setCopied(false);
  }

  function selectStatus(status: ClarityCheckStatus) {
    setStatuses((current) => ({ ...current, [activeItem.id]: status }));
    setCopied(false);
  }

  function goForward() {
    if (!statuses[activeItem.id]) return;
    if (currentIndex === items.length - 1) {
      setScreen("result");
      return;
    }
    setCurrentIndex((value) => value + 1);
  }

  function goBack() {
    if (currentIndex === 0) {
      setScreen("intro");
      return;
    }
    setCurrentIndex((value) => value - 1);
  }

  function toggleLocalSave(enabled: boolean) {
    setLocalSaveEnabled(enabled);
    if (!enabled) window.localStorage.removeItem(storageKey);
  }

  async function copyResult() {
    try {
      await navigator.clipboard.writeText(result.summary);
      setCopied(true);
    } catch {
      setCopied(false);
    }
  }

  function prepareHandoff() {
    window.sessionStorage.setItem(handoffKey, result.summary);
    if (formTargetId) {
      document.getElementById(formTargetId)?.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }

  const text = locale === "de"
    ? {
        eyebrow: "FLOXANT Klarheitscheck",
        introTitle: "Zwölf Punkte vor einer Zusage strukturiert klären",
        intro:
          "Wählen Sie für jeden Punkt, ob die Angabe vorhanden, unklar, fehlend oder nicht relevant ist. Es werden keine Angebotsdaten übertragen.",
        service: "Art des Angebots",
        start: "Klarheitscheck starten",
        localSave: "Zwischenstand nur auf diesem Gerät speichern",
        localSaveHelp: "Optional. Die Angaben bleiben im localStorage dieses Browsers und werden nicht an FLOXANT gesendet.",
        item: "Prüfpunkt",
        of: "von",
        why: "Warum das wichtig ist",
        missing: "Typische fehlende Angabe",
        back: "Zurück",
        next: "Weiter",
        finish: "Auswertung anzeigen",
        resultTitle: "Auswertung des Klarheitschecks",
        present: "Vorhandene Angaben",
        unclear: "Unklare Angaben",
        missingList: "Fehlende Angaben",
        questions: "Empfohlene Rückfragen",
        noItems: "Keine Punkte in dieser Gruppe.",
        nextStep: "Vor einer Zusage offene Punkte schriftlich klären. FLOXANT bewertet weder Anbieter noch Rechtslage.",
        copy: "Ergebnis kopieren",
        copied: "Ergebnis kopiert",
        print: "Ergebnis drucken",
        handoff: formTargetId ? "In Angebotsanfrage übernehmen" : "Kontaktformular mit Ergebnis öffnen",
        restart: "Neu starten",
      }
    : {
        eyebrow: "FLOXANT Scope Check",
        introTitle: "Clarify twelve scope points before accepting a quote",
        intro:
          "For each point, choose present, unclear, missing or not relevant. No quote data is transmitted while you use the tool.",
        service: "Type of quote",
        start: "Start the Scope Check",
        localSave: "Save progress on this device only",
        localSaveHelp: "Optional. The data stays in this browser's localStorage and is not sent to FLOXANT.",
        item: "Check point",
        of: "of",
        why: "Why this matters",
        missing: "Typical missing detail",
        back: "Back",
        next: "Next",
        finish: "Show result",
        resultTitle: "Scope Check result",
        present: "Present details",
        unclear: "Unclear details",
        missingList: "Missing details",
        questions: "Suggested questions",
        noItems: "No points in this group.",
        nextStep: "Clarify open points in writing before accepting. FLOXANT does not rate the provider or give legal advice.",
        copy: "Copy result",
        copied: "Result copied",
        print: "Print result",
        handoff: formTargetId ? "Use in the request form" : "Open the contact form with this result",
        restart: "Start again",
      };

  if (screen === "intro") {
    return (
      <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-xl shadow-slate-950/5 sm:p-8" aria-labelledby="clarity-check-title">
        <p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">{text.eyebrow}</p>
        <h2 id="clarity-check-title" ref={headingRef} tabIndex={-1} className="mt-3 text-3xl font-black tracking-tight text-slate-950 sm:text-4xl">
          {text.introTitle}
        </h2>
        <p className="mt-4 max-w-3xl text-base leading-8 text-slate-700">{text.intro}</p>
        <fieldset className="mt-7">
          <legend className="text-sm font-black text-slate-950">{text.service}</legend>
          <div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {serviceOptions.map((option) => (
              <label key={option.value} className={`cursor-pointer rounded-xl border p-4 text-sm font-bold transition focus-within:ring-2 focus-within:ring-blue-500 ${serviceType === option.value ? "border-blue-500 bg-blue-50 text-blue-950" : "border-slate-200 bg-white text-slate-700"}`}>
                <input type="radio" name="clarity-service" value={option.value} checked={serviceType === option.value} onChange={() => setServiceType(option.value)} className="mr-2" />
                {locale === "de" ? option.de : option.en}
              </label>
            ))}
          </div>
        </fieldset>
        <label className="mt-6 flex items-start gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm font-semibold leading-6 text-slate-700">
          <input type="checkbox" checked={localSaveEnabled} onChange={(event) => toggleLocalSave(event.target.checked)} className="mt-1 h-5 w-5" />
          <span><span className="block font-black text-slate-950">{text.localSave}</span>{text.localSaveHelp}</span>
        </label>
        <button type="button" onClick={startCheck} className="mt-6 inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-slate-950 px-6 text-sm font-black text-white hover:bg-blue-700">
          {text.start}<ChevronRight className="h-4 w-4" aria-hidden="true" />
        </button>
      </section>
    );
  }

  if (screen === "questions") {
    const selectedStatus = statuses[activeItem.id];
    return (
      <section className="rounded-[2rem] border border-slate-200 bg-white p-5 shadow-xl shadow-slate-950/5 sm:p-8" aria-labelledby="clarity-question-title">
        <div className="flex flex-wrap items-center justify-between gap-3 text-sm font-bold text-slate-600">
          <span>{text.item} {currentIndex + 1} {text.of} {items.length}</span>
          <span>{locale === "de" ? clarityCheckMethod.de.name : clarityCheckMethod.en.name}</span>
        </div>
        <div className="mt-4 grid grid-cols-12 gap-1" aria-hidden="true">
          {items.map((item, index) => <span key={item.id} className={`h-2 rounded-full ${index <= currentIndex ? "bg-blue-600" : "bg-slate-200"}`} />)}
        </div>
        <h2 id="clarity-question-title" ref={headingRef} tabIndex={-1} className="mt-7 text-3xl font-black tracking-tight text-slate-950">
          {locale === "de" ? activeItem.titleDe : activeItem.titleEn}
        </h2>
        <p className="mt-4 text-base leading-8 text-slate-700">{locale === "de" ? activeItem.explanationDe : activeItem.explanationEn}</p>
        <div className="mt-5 grid gap-3 sm:grid-cols-2">
          <div className="rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm leading-7 text-blue-950"><strong className="block">{text.why}</strong>{locale === "de" ? activeItem.whyImportantDe : activeItem.whyImportantEn}</div>
          <div className="rounded-xl border border-amber-100 bg-amber-50 p-4 text-sm leading-7 text-amber-950"><strong className="block">{text.missing}</strong>{locale === "de" ? activeItem.typicalMissingDe : activeItem.typicalMissingEn}</div>
        </div>
        <fieldset className="mt-6">
          <legend className="sr-only">{locale === "de" ? "Status auswählen" : "Select a status"}</legend>
          <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            {statusOrder.map((status) => (
              <label key={status} className={`cursor-pointer rounded-xl border p-4 text-sm font-black transition focus-within:ring-2 focus-within:ring-blue-500 ${selectedStatus === status ? "border-blue-600 bg-blue-50 text-blue-950" : "border-slate-200 bg-white text-slate-700"}`}>
                <input type="radio" name={`clarity-${activeItem.id}`} value={status} checked={selectedStatus === status} onChange={() => selectStatus(status)} className="mr-2" />
                {clarityStatusLabels[locale][status]}
              </label>
            ))}
          </div>
        </fieldset>
        <div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-between">
          <button type="button" onClick={goBack} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-5 text-sm font-black text-slate-800"><ChevronLeft className="h-4 w-4" />{text.back}</button>
          <button type="button" onClick={goForward} disabled={!selectedStatus} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 text-sm font-black text-white disabled:cursor-not-allowed disabled:opacity-45">
            {currentIndex === items.length - 1 ? text.finish : text.next}<ChevronRight className="h-4 w-4" />
          </button>
        </div>
      </section>
    );
  }

  const groupedItems = (status: ClarityCheckStatus) => clarityCheckItems.filter((item) => statuses[item.id] === status);
  return (
    <section className="print:shadow-none rounded-[2rem] border border-slate-200 bg-white p-5 shadow-xl shadow-slate-950/5 sm:p-8" aria-labelledby="clarity-result-title" aria-live="polite">
      <p className="text-xs font-black uppercase tracking-[0.16em] text-blue-700">{text.eyebrow}</p>
      <h2 id="clarity-result-title" ref={headingRef} tabIndex={-1} className="mt-3 text-3xl font-black tracking-tight text-slate-950">{text.resultTitle}</h2>
      <p className="mt-4 rounded-xl border border-blue-200 bg-blue-50 p-5 text-xl font-black text-blue-950">{result.scoreLabel}</p>
      <div className="mt-6 grid gap-4 lg:grid-cols-3">
        {([
          ["present", text.present],
          ["unclear", text.unclear],
          ["missing", text.missingList],
        ] as const).map(([status, label]) => {
          const group = groupedItems(status);
          return <article key={status} className="rounded-xl border border-slate-200 bg-slate-50 p-4"><h3 className="font-black text-slate-950">{label} ({group.length})</h3>{group.length ? <ul className="mt-3 grid gap-2 text-sm leading-6 text-slate-700">{group.map((item) => <li key={item.id} className="flex gap-2"><Check className="mt-1 h-4 w-4 shrink-0 text-blue-700" />{locale === "de" ? item.titleDe : item.titleEn}</li>)}</ul> : <p className="mt-3 text-sm text-slate-600">{text.noItems}</p>}</article>;
        })}
      </div>
      <article className="mt-5 rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-black text-slate-950">{text.questions}</h3>{result.questions.length ? <ol className="mt-3 grid gap-2 text-sm leading-7 text-slate-700">{result.questions.map((question, index) => <li key={question}><strong>{index + 1}.</strong> {question}</li>)}</ol> : <p className="mt-3 text-sm text-slate-600">{text.noItems}</p>}</article>
      <p className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold leading-7 text-amber-950">{text.nextStep}</p>
      <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:flex-wrap print:hidden">
        <button type="button" onClick={copyResult} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 text-sm font-black text-white"><Clipboard className="h-4 w-4" />{copied ? text.copied : text.copy}</button>
        <button type="button" onClick={() => window.print()} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-5 text-sm font-black text-slate-800"><Printer className="h-4 w-4" />{text.print}</button>
        <a href={formTargetId ? `#${formTargetId}` : contactHref} onClick={prepareHandoff} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl bg-blue-700 px-5 text-sm font-black text-white">{text.handoff}<ChevronRight className="h-4 w-4" /></a>
        <button type="button" onClick={startCheck} className="inline-flex min-h-12 items-center justify-center gap-2 rounded-xl border border-slate-300 bg-white px-5 text-sm font-black text-slate-800"><RotateCcw className="h-4 w-4" />{text.restart}</button>
      </div>
    </section>
  );
}
