import { company } from "@/lib/company";
import { germanizeDeep } from "@/lib/german-text";
import {
  serviceGraphDatasetJsonLd,
  serviceGraphDatasetReference,
} from "@/lib/schema-datasets";
import { getSchemaKnowAboutAliases } from "@/lib/search-intent-aliases";

export function JsonLd({ lang = "de" }: { lang?: string }) {
  const multilingualAliases = getSchemaKnowAboutAliases(36);
  const graph = {
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "Organization",
        "@id": `${company.url}/#organization`,
        name: company.name,
        url: company.url,
        email: company.email,
        telephone: company.phoneRaw,
        logo: `${company.url}/logo_v10.png`,
        description:
          "FLOXANT organisiert Umzug, Entrümpelung, Transport und Angebotsprüfung ab Regensburg; Reinigung wird in Regensburg und im Umkreis von 50 km geprüft.",
        knowsAbout: [
          "Umzug",
          "Reinigung",
          "Entrümpelung",
          "Büroumzug",
          "Firmenentsorgung",
          "Büroentsorgung",
          "Büroinventar entsorgen",
          "Private Client Service",
          "FLOXANT Private Client",
          "Luxusumzug",
          "Anwesenreinigung",
          "Wohnungsauflösung",
          "Endreinigung",
          "Kurzfristige Reinigung",
          "Reinigung nach Veranstaltung",
          "Reinigung nach Party",
          "Eventreinigung",
          "Beiladung",
          "Leer-Rückfahrt",
          "Leer-Rückfahrt für Firmen",
          "Rücktransport nach Regensburg",
          "Umzug mit Reinigung",
          "Kurzfristige Reinigung",
          "Reinigung nach Veranstaltung",
          "Express-Anfrage",
          "Kleinmengen-Entsorgung",
          "Einsatzgebiet Regensburg",
          "Oberpfalz",
          "Niederbayern",
          "Preisvorstellung",
          "Preisrahmen",
          "unverbindliche Vorprüfung",
          "Regensburg",
          "Umzugsunternehmen",
          "Reinigungsfirma",
          "Reinigung Regensburg 50 km",
          "Reinigung Landkreis Regensburg",
          "Putzfirma Regensburg",
          "Putzservice Regensburg",
          "Reinigung Kosten Regensburg",
          "Reinigung Angebot Regensburg",
          "Gebäudereinigung Regensburg",
          "Reinigung Altstadt Regensburg",
          "Reinigung Innenstadt Regensburg",
          "Reinigung Kumpfmühl Regensburg",
          "Reinigung Galgenberg Regensburg",
          "Reinigung Westenviertel Regensburg",
          "Reinigung Prüfening Regensburg",
          "Reinigung Gewerbepark Regensburg",
          "Reinigung Neutraubling",
          "Reinigung Barbing",
          "Reinigung Lappersdorf",
          "Reinigung Wenzenbach",
          "Angebot anderer Firma prüfen",
          "Umzugsangebot prüfen",
          "Reinigungsangebot prüfen",
          "Entsorgungsangebot prüfen",
          "Büroreinigung Regensburg",
          "Büroreinigung Regensburg Angebot",
          "Büroreinigung Kosten Regensburg",
          "Büro Reinigungskraft Regensburg",
          "Praxisreinigung Regensburg",
          "Arztpraxis Reinigung Regensburg",
          "Praxisreinigung Angebot Regensburg",
          "Reinigung Praxisräume Regensburg",
          "Hotelreinigung Regensburg",
          "Hotel Reinigung Firma Regensburg",
          "Zimmerreinigung Regensburg",
          "Hotel Unterhaltsreinigung Regensburg",
          "Pension Reinigung Regensburg",
          "Boardinghouse Reinigung Regensburg",
          "Fensterreinigung Regensburg",
          "Glasreinigung Regensburg",
          "Schaufensterreinigung Regensburg",
          "Baureinigung Regensburg",
          "Bauendreinigung Regensburg",
          "Baufeinreinigung Regensburg",
          "Teppichreinigung Regensburg",
          "Teppichbodenreinigung Regensburg",
          "Polsterreinigung Regensburg",
          "Sofa reinigen lassen Regensburg",
          "IT Raum Reinigung Regensburg",
          "Serverraum-nahe Reinigung Regensburg",
          "Treppenhausreinigung Regensburg",
          "Hausverwaltung Reinigung Regensburg",
          "Treppenhausreinigung Kosten Regensburg",
          "Unterhaltsreinigung Regensburg",
          "Grundreinigung Regensburg",
          "Wohnung Grundreinigung Regensburg",
          "Büro Grundreinigung Regensburg",
          "Grundreinigung nach Auszug Regensburg",
          "starke Verschmutzung reinigen Regensburg",
          "Bueroreinigung Regensburg Angebot",
          "Reinigungsplan Buero Regensburg",
          "Objektreinigung Regensburg",
          ...multilingualAliases,
          "Google Maps Buchung",
          "Kurze Antworten für lokale Dienstleistungen",
        ],
        slogan: "Umzug, Reinigung, Entrümpelung und Angebotsprüfung direkt anfragen.",
        keywords: [
          "Umzug Regensburg",
          "Reinigung Regensburg",
          "Putzfirma Regensburg",
          "Putzservice Regensburg",
          "Reinigung Kosten Regensburg",
          "Reinigung Altstadt Regensburg",
          "Reinigung Innenstadt Regensburg",
          "Reinigung Gewerbepark Regensburg",
          "Reinigung Neutraubling",
          "Büroreinigung Regensburg",
          "Büroreinigung Regensburg Angebot",
          "Praxisreinigung Regensburg",
          "Arztpraxis Reinigung Regensburg",
          "Fensterreinigung Regensburg",
          "Baureinigung Regensburg",
          "Teppichreinigung Regensburg",
          "Treppenhausreinigung Regensburg",
          "Unterhaltsreinigung Regensburg",
          "Grundreinigung Regensburg",
          "IT Raum Reinigung Regensburg",
          "Wohnung Grundreinigung Regensburg",
          "Bueroreinigung Regensburg Angebot",
          "Entrümpelung Regensburg",
          "Angebot prüfen lassen",
          "FLOXANT",
          "Reinigung Regensburg 50 km",
          "Reinigung Landkreis Regensburg",
          ...multilingualAliases.slice(0, 18),
        ].join(", "),
        knowsLanguage: ["de", "en"],
        areaServed: [
          { "@type": "City", name: "Regensburg" },
          { "@type": "AdministrativeArea", name: "Landkreis Regensburg" },
          { "@type": "GeoCircle", name: "Reinigung Regensburg plus 50 km" },
        ],
        subjectOf: [
          { "@type": "WebPage", name: "FLOXANT Fakten", url: `${company.url}/floxant-fakten` },
          serviceGraphDatasetReference,
          { "@type": "WebPage", name: "Angebot anderer Firma prüfen", url: `${company.url}/angebot-guenstiger-pruefen` },
          { "@type": "WebPage", name: "Plan-B-Service", url: `${company.url}/plan-b-service` },
          { "@type": "CreativeWork", name: "FLOXANT llms.txt", url: `${company.url}/llms.txt` },
        ],
        sameAs: [
          "https://www.instagram.com/floxant_logistik",
          "https://www.facebook.com/floxant",
        ],
        address: {
          "@type": "PostalAddress",
          streetAddress: company.streetAddress,
          addressLocality: company.city,
          postalCode: company.postalCode,
          addressCountry: company.countryCode,
        },
        contactPoint: {
          "@type": "ContactPoint",
          telephone: company.phoneRaw,
          contactType: "customer service",
          areaServed: "DE-BY",
          availableLanguage: ["de", "en"],
        },
        potentialAction: [
          {
            "@type": "ContactAction",
            name: "FLOXANT direkt anfragen",
            target: company.businessProfilePreferredUrl,
          },
          {
            "@type": "Action",
            name: "Preisrahmen prüfen",
            target: `${company.url}/rechner`,
          },
          {
            "@type": "Action",
            name: "Angebot anderer Firma prüfen",
            target: `${company.url}/angebot-guenstiger-pruefen`,
          },
        ],
      },
      serviceGraphDatasetJsonLd,
      {
        "@type": "WebSite",
        "@id": `${company.url}/#website`,
        url: company.url,
        name: company.name,
        inLanguage: lang,
        publisher: {
          "@id": `${company.url}/#organization`,
        },
        potentialAction: [
          {
            "@type": "Action",
            name: "Buchung starten",
            target: {
              "@type": "EntryPoint",
              urlTemplate: `${company.url}/buchung`,
            },
          },
          {
            "@type": "Action",
            name: "Kostenrahmen prüfen",
            target: {
              "@type": "EntryPoint",
              urlTemplate: `${company.url}/rechner`,
            },
          },
          {
            "@type": "Action",
            name: "Angebot prüfen und Alternative anfragen",
            target: {
              "@type": "EntryPoint",
              urlTemplate: `${company.url}/angebot-guenstiger-pruefen`,
            },
          },
        ],
        about: [
          { "@type": "Thing", name: "Umzug" },
          { "@type": "Thing", name: "Reinigung" },
          { "@type": "Thing", name: "Angebotsprüfung" },
          { "@type": "Thing", name: "Preisrahmen" },
          { "@type": "Thing", name: "Google Maps Buchung" },
          { "@type": "Thing", name: "Entrümpelung" },
          { "@type": "Place", name: "Regensburg" },
          { "@type": "AdministrativeArea", name: "Landkreis Regensburg" },
        ],
        hasPart: [
          { "@type": "WebPage", name: "FLOXANT Rechner", url: `${company.url}/rechner` },
          { "@type": "WebPage", name: "Umzug", url: `${company.url}/umzug` },
          { "@type": "WebPage", name: "Reinigung", url: `${company.url}/reinigung` },
          { "@type": "WebPage", name: "Büroreinigung Regensburg", url: `${company.url}/regensburg/bueroreinigung` },
          { "@type": "WebPage", name: "Praxisreinigung Regensburg", url: `${company.url}/praxisreinigung-regensburg` },
          { "@type": "WebPage", name: "Hotelreinigung Regensburg", url: `${company.url}/hotelreinigung-regensburg` },
          { "@type": "WebPage", name: "Fensterreinigung Regensburg", url: `${company.url}/fensterreinigung-regensburg` },
          { "@type": "WebPage", name: "Baureinigung Regensburg", url: `${company.url}/baureinigung-regensburg` },
          { "@type": "WebPage", name: "Teppichreinigung Regensburg", url: `${company.url}/teppichreinigung-regensburg` },
          { "@type": "WebPage", name: "Treppenhausreinigung Regensburg", url: `${company.url}/treppenhausreinigung-regensburg` },
          { "@type": "WebPage", name: "Unterhaltsreinigung Regensburg", url: `${company.url}/unterhaltsreinigung-regensburg` },
          { "@type": "WebPage", name: "Grundreinigung Regensburg", url: `${company.url}/grundreinigung-regensburg` },
          { "@type": "WebPage", name: "Kurzfristige Reinigung", url: `${company.url}/notfallreinigung-24h` },
          { "@type": "WebPage", name: "Reinigung nach Veranstaltung", url: `${company.url}/reinigung-nach-veranstaltung` },
          { "@type": "WebPage", name: "Entrümpelung", url: `${company.url}/entruempelung` },
          { "@type": "WebPage", name: "Büroumzug", url: `${company.url}/bueroumzug` },
          { "@type": "WebPage", name: "Firmenentsorgung", url: `${company.url}/firmenentsorgung` },
          { "@type": "WebPage", name: "FLOXANT Private Client", url: `${company.url}/private-client-service` },
          { "@type": "WebPage", name: "Regensburg", url: `${company.url}/regensburg` },
          { "@type": "WebPage", name: "FLOXANT Fakten", url: `${company.url}/floxant-fakten` },
          { "@type": "WebPage", name: "Beiladung", url: `${company.url}/beiladung` },
          { "@type": "WebPage", name: "Leer-Rückfahrt", url: `${company.url}/leerfahrt-rueckfahrt` },
          { "@type": "WebPage", name: "Umzug mit Reinigung", url: `${company.url}/umzug-mit-reinigung` },
          { "@type": "WebPage", name: "Express-Anfrage", url: `${company.url}/express-anfrage` },
          { "@type": "WebPage", name: "Anfrage mit Preisvorstellung", url: `${company.url}/anfrage-mit-preisrahmen` },
          { "@type": "WebPage", name: "Kleinmengen-Entsorgung", url: `${company.url}/kleinmengen-entsorgung` },
          { "@type": "WebPage", name: "FLOXANT Blog", url: `${company.url}/blog` },
        ],
      },
    ],
  };

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(germanizeDeep(graph)) }}
    />
  );
}
