export type BlogPostMeta = {
 slug: string;
 category: string;
 readTime: string;
 title: string;
 description: string;
 featured?: boolean;
};

export const blogPosts: BlogPostMeta[] = [
 {
  slug: "leer-rueckfahrt-regensburg-firmen-moebeltransport",
  category: "Leer-Rückfahrt",
  readTime: "7 Min.",
  title: "Leer-Rückfahrt nach Regensburg: fairer Transport für Firmen und Möbel",
  description: "Wann freie Rückfahrten für Büroinventar, Möbel, Kartons und Teilmengen sinnvoll sind und welche Grenzen gelten.",
  featured: true,
 },
 {
  slug: "bueroumzug-regensburg-kostenfaktoren-checkliste",
  category: "Büroumzug",
  readTime: "8 Min.",
  title: "Büroumzug in Regensburg: Kostenfaktoren und Checkliste",
  description: "Arbeitsplätze, IT, Archiv, Zugang und Zeitfenster: so wird ein Firmenumzug realistisch vorbereitet.",
  featured: true,
 },
 {
  slug: "firmenentsorgung-buero-inventar-regensburg",
  category: "Firmenentsorgung",
  readTime: "6 Min.",
  title: "Firmenentsorgung in Regensburg: Büroinventar sauber abholen lassen",
  description: "Welche Büro- und Gewerbegegenstände ohne Sonderabfall-Risiko angefragt werden können und wie FLOXANT vorprüft.",
 },
 {
  slug: "preisrahmen-vorpruefung-statt-festpreis",
  category: "Preiswahrheit",
  readTime: "7 Min.",
  title: "Preisrahmen statt Festpreis: warum Vorprüfung ehrlicher ist",
  description: "Warum Umzug, Reinigung und Entrümpelung zuerst eine belastbare Vorprüfung statt künstlich exakter Onlinepreise brauchen.",
  featured: true,
 },
 {
  slug: "budget-planung-umzug-kosten",
  category: "Budget",
  readTime: "6 Min.",
  title: "Budgetplanung beim Umzug: Preisvorstellung richtig nutzen",
  description: "Wie Kunden ein Zielbudget sinnvoll nennen und warum Preisvorstellung und System-Einschätzung getrennt bleiben.",
 },
 {
  slug: "service-kombination-umzug-reinigung-entruempelung",
  category: "Service-Kombi",
  readTime: "8 Min.",
  title: "Umzug, Reinigung und Entrümpelung kombinieren",
  description: "Wann ein kombinierter Ablauf für Übergabe, Räumung und Transport sinnvoll ist und wie FLOXANT ihn strukturiert.",
  featured: true,
 },
 {
  slug: "signatur-services-floxant-bayern",
  category: "Signatur-Services",
  readTime: "6 Min.",
  title: "FLOXANT Signatur-Services: wann welcher Zusatzservice passt",
  description: "Beiladung, Express-Anfrage, Preisvorstellung und Schlüsselübergabe als klare Einstiege für konkrete Kundensituationen.",
  featured: true,
 },
 {
  slug: "regensburg-bayern-servicegebiet-richtig-planen",
  category: "Local SEO",
  readTime: "6 Min.",
  title: "Regensburg und Bayern als Servicegebiet richtig planen",
  description: "Warum Region, Strecke und Verfügbarkeit bei FLOXANT für Preisrahmen, Termin und Umsetzung entscheidend sind.",
 },
 {
  slug: "entruempelung-bayern-leitfaden",
  category: "Entrümpelung",
  readTime: "7 Min.",
  title: "Entrümpelung in Bayern: Ablauf, Grenzen und Vorbereitung",
  description: "Wie Räumung, Materialarten, Zugang und Entsorgung sinnvoll vorbereitet werden, bevor eine Anfrage startet.",
 },
 {
  slug: "entrumpelung-kosten-bayern",
  category: "Kosten",
  readTime: "7 Min.",
  title: "Entrümpelungskosten in Bayern realistisch einordnen",
  description: "Warum Volumen, Material, Laufwege, Demontage und Dringlichkeit den Preisrahmen stärker bestimmen als Pauschalen.",
 },
 {
  slug: "umzug-kosten-regensburg",
  category: "Umzug",
  readTime: "8 Min.",
  title: "Umzugskosten in Regensburg realistisch einordnen",
  description: "Preisfaktoren, Zugang, Strecke und Planung für Ihren Umzug in Regensburg.",
  featured: true,
 },
 {
  slug: "endreinigung-regensburg-checkliste",
  category: "Reinigung",
  readTime: "7 Min.",
  title: "Endreinigung in Regensburg: Checkliste für Wohnung, Haus und Übergabe",
  description: "Welche Leistungen sind vor der Wohnungsübergabe wirklich sinnvoll? Eine klare Checkliste für Regensburg und Bayern.",
  featured: true,
 },
 {
  slug: "reinigung-checkliste-uebergabe",
  category: "Reinigung",
  readTime: "6 Min.",
  title: "Reinigung vor Übergabe: Checkliste für klare Ergebnisse",
  description: "Welche Räume, Flächen, Fenster, Küche, Bad und Details vor einer Übergabe wirklich geprüft werden sollten.",
 },
 {
  slug: "beiladung-bayern-wann-lohnt-es-sich",
  category: "Beiladung",
  readTime: "6 Min.",
  title: "Beiladung in Bayern: Wann sie sich lohnt und wann ein voller Umzug besser ist",
  description: "Für Kleintransporte, einzelne Möbel und flexible Strecken: so bewerten Sie Beiladung realistisch.",
  featured: true,
 },
 {
  slug: "umzug-mit-reinigung-regensburg",
  category: "Kombiservice",
  readTime: "7 Min.",
  title: "Umzug mit Reinigung in Regensburg: Wann sich der Kombiservice lohnt",
  description: "Warum Umzug, Reinigung und Schlüsselübergabe oft besser als ein koordinierter Ablauf funktionieren.",
 },
 {
  slug: "preisvorstellung-umzug-anfrage",
  category: "Preisvorstellung",
  readTime: "6 Min.",
  title: "Preisvorstellung bei der Umzugsanfrage: sinnvoll oder riskant?",
  description: "Wie Kunden ihr Budget sinnvoll nennen und warum Preisvorstellung und Vorprüfung getrennt bleiben sollten.",
 },
 {
  slug: "schluesseluebergabe-ohne-stress",
  category: "Übergabe",
  readTime: "6 Min.",
  title: "Schlüsselübergabe ohne Stress: so bleibt der Ablauf sauber",
  description: "Was bei Übergabe, Reinigung, Restmengen und Timing wirklich zählt.",
 },
 {
  slug: "einlagerung-beim-umzug-wann-sinnvoll",
  category: "Einlagerung",
  readTime: "6 Min.",
  title: "Einlagerung beim Umzug: wann sie sinnvoll ist und wann nicht",
  description: "Für Zwischenphasen, Bauverzug und flexible Übergaben: so ordnen Sie Einlagerung richtig ein.",
 },
 {
  slug: "express-umzug-regensburg",
  category: "Express",
  readTime: "5 Min.",
  title: "Express-Umzug in Regensburg: was kurzfristig wirklich machbar ist",
  description: "Wie Eilanfragen sinnvoll vorbereitet werden und welche Angaben für eine schnelle Vorprüfung wichtig sind.",
 },
 {
  slug: "umzug-checkliste",
  category: "Checkliste",
  readTime: "6 Min.",
  title: "Umzug-Checkliste: die wichtigsten Schritte vor dem Termin",
  description: "Eine kompakte Reihenfolge für Vorbereitung, Kartons, Zugang, Haltezone, Übergabe und letzte Abstimmung.",
 },
 {
  slug: "umzug-regensburg-tipps",
  category: "Regensburg",
  readTime: "6 Min.",
  title: "Umzug in Regensburg: lokale Tipps für Planung und Zugang",
  description: "Was bei Altstadt, Etagen, Haltezonen, Laufwegen und Terminplanung in Regensburg besonders wichtig ist.",
 },
 {
  slug: "umzug-tipps-bayern",
  category: "Bayern",
  readTime: "6 Min.",
  title: "Umzug in Bayern: Strecke, Termin und Zusatzleistungen planen",
  description: "Wie regionale Entfernung, Verfügbarkeit, Montage, Reinigung und Beiladung vor der Anfrage eingeordnet werden.",
 },
 {
  slug: "umzug-planen-schritt-fuer-schritt",
  category: "Planung",
  readTime: "7 Min.",
  title: "Umzug planen Schritt für Schritt",
  description: "Eine strukturierte Reihenfolge für Vorbereitung, Terminierung und Durchführung.",
 },
 {
  slug: "wohnungsuebergabe-protokoll-guide",
  category: "Übergabe",
  readTime: "6 Min.",
  title: "Wohnungsübergabe: worauf Vermieter und Mieter achten sollten",
  description: "Ein klarer Leitfaden für Protokoll, Zustand, Reinigung und letzte To-dos.",
 },
 {
  slug: "umzugskosten-senken-7-tipps",
  category: "Kosten",
  readTime: "6 Min.",
  title: "Umzugskosten senken: 7 seriöse Stellschrauben",
  description: "Wie Kunden Kosten reduzieren können, ohne an Sicherheit, Ablauf oder realistischer Planung zu sparen.",
 },
 {
  slug: "fernumzug-bayern-nrw-tipps",
  category: "Fernumzug",
  readTime: "7 Min.",
  title: "Fernumzug ab Bayern: Strecke, Rückfahrt und Planung",
  description: "Wann Strecke, Beiladung, Leer-Rückfahrt und Terminfenster bei längeren Umzügen besonders wichtig werden.",
 },
 {
  slug: "umzug-mit-kindern-stressfrei",
  category: "Familie",
  readTime: "6 Min.",
  title: "Umzug mit Kindern: ruhiger planen, besser umsetzen",
  description: "Wie Familien Kartons, Timing, Kinderzimmer, Übergabe und den ersten Tag im neuen Zuhause besser strukturieren.",
 },
 {
  slug: "warum-floxant-die-beste-wahl-ist",
  category: "Auswahlhilfe",
  readTime: "6 Min.",
  title: "Umzugsunternehmen bewerten: worauf Kunden achten sollten",
  description: "Ablauf, Preisrahmen, Kommunikation und regionale Planung als Kriterien für eine seriöse Anbieterwahl.",
 },
 {
  slug: "wohnungsaufloesung-was-tun",
  category: "Entrümpelung",
  readTime: "7 Min.",
  title: "Wohnungsauflösung: Was jetzt wirklich zu tun ist",
  description: "Die wichtigsten Schritte für Planung, Materialtrennung und Entsorgung.",
 },
];
