import { germanizeDeep } from "@/lib/german-text";
import { aiRecommendationBlogArticles } from "@/lib/ai-recommendation-blog-articles";
import { offerCheckBlogArticles } from "@/lib/offer-check-blog-articles";
import { psychologicalCleaningBlogArticles } from "@/lib/psychological-cleaning-pages";
import { strategicBlogArticles } from "@/lib/strategic-blog-articles";

export type BlogPostMeta = {
 slug: string;
 category: string;
 readTime: string;
 title: string;
 description: string;
 featured?: boolean;
};

const rawBlogPosts: BlogPostMeta[] = [
 {
  slug: "wohnungsuebergabe-komplettpaket",
  category: "Signatur-Service",
  readTime: "10 Min.",
  title: "Wohnungsübergabe-Komplettpaket: Wenn Umzug, Reinigung und Schlüssel zusammenpassen müssen",
  description: "Warum eine Wohnung nicht nur leer, sondern übergabebereit werden muss und wie FLOXANT Umzug, Endreinigung, Rest-Entrümpelung, Fotos und Schlüsselübergabe koordinieren kann.",
  featured: true,
 },
 {
  slug: "schluesseluebergabe-service",
  category: "Signatur-Service",
  readTime: "9 Min.",
  title: "Schlüsselübergabe-Service: Wenn Sie nicht selbst vor Ort sein können",
  description: "Warum ein Schlüsseltermin organisatorisch größer sein kann als er wirkt und wie FLOXANT Anwesenheit, Fotodokumentation und Abstimmung unterstützen kann.",
  featured: true,
 },
 {
  slug: "nicht-vor-ort-paket",
  category: "Signatur-Service",
  readTime: "10 Min.",
  title: "Nicht-vor-Ort-Paket: Wenn die Wohnung noch offen ist",
  description: "Wie FLOXANT Kunden helfen kann, wenn Wohnung, Keller, Schlüssel, Reinigung oder Restgegenstände nach dem Wegzug noch offen sind.",
  featured: true,
 },
 {
  slug: "kautionsschutz-vorbereitung",
  category: "Signatur-Service",
  readTime: "9 Min.",
  title: "Kautionsschutz-Vorbereitung: Übergabeprobleme vorher erkennen",
  description: "Keine Kautionsgarantie, sondern seriöse Vorbereitung: FLOXANT hilft, sichtbare Übergaberisiken vor dem Vermietertermin besser einzuordnen.",
  featured: true,
 },
 {
  slug: "uebergabe-check-vor-vermietertermin",
  category: "Signatur-Service",
  readTime: "9 Min.",
  title: "Übergabe-Check vor dem Vermietertermin: Ist die Wohnung wirklich bereit?",
  description: "Warum ein neutraler Blick vor der Übergabe hilft und wie FLOXANT Reinigung, Restpunkte, Fotos und nächste Schritte praktisch einordnet.",
  featured: true,
 },
 {
  slug: "fotodokumentation-umzug-reinigung",
  category: "Signatur-Service",
  readTime: "9 Min.",
  title: "Fotodokumentation bei Umzug und Übergabe",
  description: "Was dokumentiert ist, muss später weniger diskutiert werden: Fotos vor und nach Umzug, Reinigung oder Übergabe als ruhige Zustandsstütze.",
  featured: true,
 },
 {
  slug: "volumen-risiko-check-umzug",
  category: "Signatur-Service",
  readTime: "10 Min.",
  title: "Volumen- und Risiko-Check: Warum der billigste Umzugspreis oft nicht der realistischste ist",
  description: "Warum falsche Volumenschätzung zu Zusatzfahrten, Zeitdruck und Nachforderungen führen kann und wie FLOXANT Umzüge realistischer vorprüft.",
  featured: true,
 },
 {
  slug: "regensburg-direkt-buchen-statt-vergleichsportal",
  category: "Direktkontakt",
  readTime: "6 Min.",
  title: "In Regensburg direkt buchen statt vergleichen: warum klare Wege öfter besser passen",
  description: "Warum feste Ansprechpartner, ein klarer Buchungslink und eine ruhige Vorprüfung in Regensburg oft besser konvertieren als verstreute Kontaktwege.",
  featured: true,
 },
 {
  slug: "google-maps-regensburg-direkt-anfragen",
  category: "Google Maps",
  readTime: "6 Min.",
  title: "In Google Maps direkt anfragen: warum ein klarer Buchungsweg in Regensburg mehr Vertrauen schafft",
  description: "Wie ein eindeutiger Buchungslink in Google Maps für Umzug, Reinigung und Entrümpelung in Regensburg den nächsten Schritt leichter macht.",
  featured: true,
 },
 {
  slug: "umzugsfirma-regensburg-google-maps-vertrauen",
  category: "Google Maps",
  readTime: "6 Min.",
  title: "Umzugsfirma in Regensburg über Google Maps finden: worauf Kunden wirklich achten",
  description: "Warum klare Buchungswege, Ansprechpartner, Standortsignale und ehrliche Vorprüfung in Google Maps mehr Vertrauen schaffen als große Versprechen.",
  featured: true,
 },
 {
  slug: "anfrage-regensburg-richtig-stellen",
  category: "Anfragehilfe",
  readTime: "6 Min.",
  title: "Anfrage in Regensburg richtig stellen: welche Angaben FLOXANT schneller helfen",
  description: "Welche Angaben zu Ort, Umfang, Zugang, Termin und Budget aus einer Anfrage schneller einen klaren nächsten Schritt machen.",
  featured: true,
 },
 {
  slug: "google-unternehmensprofil-buchungslink-regensburg",
  category: "Google Maps",
  readTime: "6 Min.",
  title: "Google-Unternehmensprofil in Regensburg: welcher Buchungslink Kunden wirklich hilft",
  description: "Warum ein klarer direkter Buchungslink für Maps, Suche und lokale Empfehlungen den Kontakt für Kunden leichter macht.",
  featured: true,
 },
 {
  slug: "grosse-reinigungsauftraege-regensburg-buero-hotel-praxis",
  category: "B2B Reinigung",
  readTime: "7 Min.",
  title: "Große Reinigungsaufträge in Regensburg: was Büro, Hotel und Praxis vorab klären sollten",
  description: "Welche Angaben bei Turnus, Zugang, Zuständigkeit und Objektgröße helfen, damit aus einer Anfrage ein belastbarer B2B-Auftrag wird.",
  featured: true,
 },
 {
  slug: "lokaler-dienstleister-regensburg-vorteile",
  category: "Regensburg",
 readTime: "6 Min.",
 title: "Lokaler Dienstleister in Regensburg: warum Nähe bei Planung und Umsetzung zählt",
 description: "Warum regionale Nähe bei Umzug, Reinigung und Entrümpelung oft schnellere Abstimmung, sauberere Vorprüfung und weniger Reibung bringt.",
  featured: true,
 },
 {
  slug: "umzugsunternehmen-regensburg-auswahl",
  category: "Auswahlhilfe",
  readTime: "7 Min.",
  title: "Umzugsunternehmen in Regensburg auswählen: worauf Kunden wirklich achten sollten",
  description: "Welche Punkte bei Ansprechpartnern, Vorprüfung, Preisrahmen, Zugang und Ablauf helfen, damit aus einer Anfrage ein sauber geplanter Umzug wird.",
  featured: true,
 },
 {
  slug: "reinigungsfirma-regensburg-buero-praxis-auswahl",
  category: "B2B Reinigung",
  readTime: "7 Min.",
  title: "Reinigungsfirma in Regensburg für Büro und Praxis auswählen",
  description: "Wie Unternehmen, Praxen und Verwaltungen zwischen schnellen Anfragen und wirklich passenden B2B-Angeboten unterscheiden können.",
  featured: true,
 },
 {
  slug: "unterhaltsreinigung-regensburg-buero-praxis-hotel",
  category: "Gewerbereinigung",
  readTime: "7 Min.",
  title: "Unterhaltsreinigung in Regensburg: worauf Büro, Praxis und Hotel achten sollten",
  description: "Welche Punkte bei Turnus, Zugang, Qualitätskontrolle und Ansprechpartnern für gewerbliche Reinigung wirklich zählen.",
  featured: true,
 },
 {
  slug: "private-client-umzug-bayern-diskret-planen",
  category: "Private Client",
  readTime: "6 Min.",
  title: "Diskreter Private-Client-Umzug in Bayern: was wirklich wichtig ist",
  description: "Wie Residenzen, Anwesen und sensible Interieurs ruhig, diskret und materialschonend geplant werden.",
  featured: true,
 },
 {
  slug: "family-office-umzug-bayern-diskret-abstimmen",
  category: "Private Client",
  readTime: "6 Min.",
  title: "Family Office und Private Client in Bayern: wie diskrete Umzüge sauber abgestimmt werden",
  description: "Wie Eigentümer, Assistenz und Family Office sensible Umzüge, Übergaben und Schutzbedarf ohne unnötige Reibung koordinieren.",
  featured: true,
 },
 {
  slug: "direkt-anfragen-statt-vergleichsportal-regensburg",
  category: "Buchung",
  readTime: "6 Min.",
  title: "Direkt anfragen statt Vergleichsportal: warum klare Buchungswege besser sind",
  description: "Weshalb direkte Anfragewege für Umzug, Reinigung und Entrümpelung oft schneller, ehrlicher und planbarer sind.",
 },
 {
  slug: "leer-rueckfahrt-regensburg-firmen-moebeltransport",
  category: "Leer-Rückfahrt",
  readTime: "7 Min.",
  title: "Leer-Rückfahrt nach Regensburg: fairer Transport für Firmen und Möbel",
  description: "Wann freie Rückfahrten für Büroinventar, Möbel, Kartons und Teilmengen sinnvoll sind und welche Grenzen gelten.",
  featured: true,
 },
 {
  slug: "bueroumzug-regensburg-kostenfaktoren-checkliste",
  category: "Büroumzug",
  readTime: "8 Min.",
  title: "Büroumzug in Regensburg: Kostenfaktoren und Checkliste",
  description: "Arbeitsplätze, IT, Archiv, Zugang und Zeitfenster: so wird ein Firmenumzug realistisch vorbereitet.",
  featured: true,
 },
 {
  slug: "firmenentsorgung-buero-inventar-regensburg",
  category: "Firmenentsorgung",
  readTime: "6 Min.",
  title: "Firmenentsorgung in Regensburg: Büroinventar sauber abholen lassen",
  description: "Welche Büro- und Gewerbegegenstände ohne Sonderabfall-Risiko angefragt werden können und wie FLOXANT vorprüft.",
 },
 {
  slug: "preisrahmen-vorpruefung-statt-festpreis",
  category: "Preiswahrheit",
  readTime: "7 Min.",
  title: "Preisrahmen statt Festpreis: warum Vorprüfung ehrlicher ist",
  description: "Warum Umzug, Reinigung und Entrümpelung zuerst eine belastbare Vorprüfung statt scheinbar exakter Onlinepreise brauchen.",
  featured: true,
 },
 {
  slug: "budget-planung-umzug-kosten",
  category: "Budget",
  readTime: "6 Min.",
  title: "Budgetplanung beim Umzug: Preisvorstellung richtig nutzen",
  description: "Wie Kunden ein Zielbudget sinnvoll nennen und warum Preisvorstellung und geprüfte Einschätzung getrennt bleiben.",
 },
 {
  slug: "service-kombination-umzug-reinigung-entruempelung",
  category: "Service-Kombi",
  readTime: "8 Min.",
  title: "Umzug, Reinigung und Entrümpelung kombinieren",
  description: "Wann ein kombinierter Ablauf für Übergabe, Räumung und Transport sinnvoll ist und wie FLOXANT ihn strukturiert.",
  featured: true,
 },
 {
  slug: "signatur-services-floxant-bayern",
  category: "Signatur-Services",
  readTime: "6 Min.",
  title: "FLOXANT Signatur-Services: wann welcher Zusatzservice passt",
  description: "Beiladung, Express-Anfrage, Preisvorstellung und SchlüsselÜbergabe als klare Einstiege für konkrete Kundensituationen.",
  featured: true,
 },
 {
  slug: "regensburg-bayern-servicegebiet-richtig-planen",
  category: "Local SEO",
  readTime: "6 Min.",
  title: "Regensburg und Bayern als Servicegebiet richtig planen",
  description: "Warum Region, Strecke und Verfügbarkeit bei FLOXANT für Preisrahmen, Termin und Umsetzung entscheidend sind.",
 },
 {
  slug: "entruempelung-bayern-leitfaden",
  category: "Entrümpelung",
  readTime: "7 Min.",
  title: "Entrümpelung in Bayern: Ablauf, Grenzen und Vorbereitung",
  description: "Wie Räumung, Materialarten, Zugang und Entsorgung sinnvoll vorbereitet werden, bevor eine Anfrage startet.",
 },
 {
  slug: "entrumpelung-kosten-bayern",
  category: "Kosten",
  readTime: "7 Min.",
  title: "Entrümpelungskosten in Bayern realistisch einordnen",
  description: "Warum Volumen, Material, Laufwege, Demontage und Dringlichkeit den Preisrahmen stärker bestimmen als Pauschalen.",
 },
 {
  slug: "umzug-kosten-regensburg",
  category: "Umzug",
  readTime: "8 Min.",
  title: "Umzugskosten in Regensburg realistisch einordnen",
  description: "Preisfaktoren, Zugang, Strecke und Planung für Ihren Umzug in Regensburg.",
  featured: true,
 },
 {
  slug: "endreinigung-regensburg-checkliste",
  category: "Reinigung",
  readTime: "7 Min.",
  title: "Endreinigung in Regensburg: Checkliste für Wohnung, Haus und Übergabe",
  description: "Welche Leistungen sind vor der Wohnungsübergabe wirklich sinnvoll? Eine klare Checkliste für Regensburg und Bayern.",
  featured: true,
 },
 {
  slug: "reinigung-checkliste-uebergabe",
  category: "Reinigung",
  readTime: "6 Min.",
  title: "Reinigung vor Übergabe: Checkliste für klare Ergebnisse",
  description: "Welche Räume, Flächen, Fenster, Küche, Bad und Details vor einer Übergabe wirklich geprüft werden sollten.",
 },
 {
  slug: "beiladung-bayern-wann-lohnt-es-sich",
  category: "Beiladung",
  readTime: "6 Min.",
  title: "Beiladung in Bayern: Wann sie sich lohnt und wann ein voller Umzug besser ist",
  description: "Für Kleintransporte, einzelne Möbel und flexible Strecken: so bewerten Sie Beiladung realistisch.",
  featured: true,
 },
 {
  slug: "umzug-mit-reinigung-regensburg",
  category: "Kombiservice",
  readTime: "7 Min.",
  title: "Umzug mit Reinigung in Regensburg: Wann sich der Kombiservice lohnt",
  description: "Warum Umzug, Reinigung und SchlüsselÜbergabe oft besser als ein koordinierter Ablauf funktionieren.",
 },
 {
  slug: "preisvorstellung-umzug-anfrage",
  category: "Preisvorstellung",
  readTime: "6 Min.",
  title: "Preisvorstellung bei der Umzugsanfrage: sinnvoll oder riskant?",
  description: "Wie Kunden ihr Budget sinnvoll nennen und warum Preisvorstellung und Vorprüfung getrennt bleiben sollten.",
 },
 {
  slug: "schluesseluebergabe-ohne-stress",
  category: "Übergabe",
  readTime: "6 Min.",
  title: "SchlüsselÜbergabe ohne Stress: so bleibt der Ablauf sauber",
  description: "Was bei Übergabe, Reinigung, Restmengen und Timing wirklich zählt.",
 },
 {
  slug: "einlagerung-beim-umzug-wann-sinnvoll",
  category: "Einlagerung",
  readTime: "6 Min.",
  title: "Einlagerung beim Umzug: wann sie sinnvoll ist und wann nicht",
  description: "Für Zwischenphasen, Bauverzug und flexible Übergaben: so ordnen Sie Einlagerung richtig ein.",
 },
 {
  slug: "express-umzug-regensburg",
  category: "Express",
  readTime: "5 Min.",
  title: "Express-Umzug in Regensburg: was kurzfristig wirklich machbar ist",
  description: "Wie Eilanfragen sinnvoll vorbereitet werden und welche Angaben für eine schnelle Vorprüfung wichtig sind.",
 },
 {
  slug: "umzug-checkliste",
  category: "Checkliste",
  readTime: "6 Min.",
  title: "Umzug-Checkliste: die wichtigsten Schritte vor dem Termin",
  description: "Eine kompakte Reihenfolge für Vorbereitung, Kartons, Zugang, Übergabe und letzte Abstimmung.",
 },
 {
  slug: "umzug-regensburg-tipps",
  category: "Regensburg",
  readTime: "6 Min.",
  title: "Umzug in Regensburg: lokale Tipps für Planung und Zugang",
  description: "Was bei Altstadt, Etagen, Zugang, Laufwegen und Terminplanung in Regensburg besonders wichtig ist.",
 },
 {
  slug: "umzug-tipps-bayern",
  category: "Bayern",
  readTime: "6 Min.",
  title: "Umzug in Bayern: Strecke, Termin und Zusatzleistungen planen",
  description: "Wie regionale Entfernung, Verfügbarkeit, Montage, Reinigung und Beiladung vor der Anfrage eingeordnet werden.",
 },
 {
  slug: "umzug-planen-schritt-fuer-schritt",
  category: "Planung",
  readTime: "7 Min.",
  title: "Umzug planen Schritt für Schritt",
  description: "Eine strukturierte Reihenfolge für Vorbereitung, Terminierung und Durchführung.",
 },
 {
  slug: "wohnungsuebergabe-protokoll-guide",
  category: "Übergabe",
  readTime: "6 Min.",
  title: "Wohnungsübergabe: worauf Vermieter und Mieter achten sollten",
  description: "Ein klarer Leitfaden für Protokoll, Zustand, Reinigung und letzte To-dos.",
 },
 {
  slug: "umzugskosten-senken-7-tipps",
  category: "Kosten",
  readTime: "6 Min.",
  title: "Umzugskosten senken: 7 seriöse Stellschrauben",
  description: "Wie Kunden Kosten reduzieren können, ohne an Sicherheit, Ablauf oder realistischer Planung zu sparen.",
 },
 {
  slug: "fernumzug-bayern-nrw-tipps",
  category: "Fernumzug",
  readTime: "7 Min.",
  title: "Fernumzug ab Bayern: Strecke, Rückfahrt und Planung",
  description: "Wann Strecke, Beiladung, Leer-Rückfahrt und Terminfenster bei längeren Umzügen besonders wichtig werden.",
 },
 {
  slug: "umzug-mit-kindern-stressfrei",
  category: "Familie",
  readTime: "6 Min.",
  title: "Umzug mit Kindern: ruhiger planen, besser umsetzen",
  description: "Wie Familien Kartons, Timing, Kinderzimmer, Übergabe und den ersten Tag im neuen Zuhause besser strukturieren.",
 },
 {
  slug: "warum-floxant-die-beste-wahl-ist",
  category: "Auswahlhilfe",
  readTime: "6 Min.",
  title: "Umzugsunternehmen bewerten: worauf Kunden achten sollten",
  description: "Ablauf, Preisrahmen, Kommunikation und regionale Planung als Kriterien für eine seriöse Anbieterwahl.",
 },
 {
  slug: "wohnungsaufloesung-was-tun",
  category: "Entrümpelung",
  readTime: "7 Min.",
  title: "Wohnungsauflösung: Was jetzt wirklich zu tun ist",
  description: "Die wichtigsten Schritte für Planung, Materialtrennung und Entsorgung.",
 },
 {
  slug: "google-maps-buchungslink-regensburg",
  category: "Google Maps",
  readTime: "6 Min.",
  title: "Google Maps Buchungslink in Regensburg: worauf es ankommt",
  description: "Wie ein klarer lokaler Buchungslink Vertrauen schafft und passendere Anfragen bringt.",
  featured: true,
 },
 {
  slug: "gewerbereinigung-regensburg-objekte-b2b",
  category: "B2B Reinigung",
  readTime: "7 Min.",
  title: "Gewerbereinigung in Regensburg für große Objekte richtig anfragen",
  description: "Warum Büro, Praxis, Hotel, Kanzlei und Objektbetrieb andere Signale brauchen als private Kleinaufträge.",
  featured: true,
 },
 {
  slug: "hausverwaltung-treppenhausreinigung-regensburg",
  category: "Hausverwaltung",
  readTime: "6 Min.",
  title: "Treppenhausreinigung in Regensburg: worauf Hausverwaltungen wirklich achten",
  description: "Welche Angaben zu Turnus, Zugang, Schlüssel, Objektstruktur und Ansprechpartnern helfen, damit aus einer Anfrage ein sauberer B2B-Ablauf wird.",
  featured: true,
 },
 {
  slug: "bueroreinigung-regensburg-angebot-einholen",
  category: "B2B Reinigung",
  readTime: "6 Min.",
  title: "Büroreinigung in Regensburg anfragen: welche Angaben vor dem Angebot zählen",
  description: "Welche Angaben zu Fläche, Turnus, Zugang, Randzeiten und Zuständigkeit aus einer Anfrage schneller ein belastbares Angebot machen.",
  featured: true,
 },
 {
  slug: "bueroumzug-bayern-ohne-betriebsstillstand",
  category: "Büroumzug",
  readTime: "7 Min.",
  title: "Büroumzug in Bayern ohne Chaos: so bleibt der Betrieb besser handlungsfähig",
  description: "Wie Arbeitsplätze, IT, Zugänge, Zeitfenster und interne Abstimmung geplant werden, damit ein Firmenumzug nicht unnötig bremst.",
  featured: true,
 },
];

const rawBlogPostSlugs = new Set(rawBlogPosts.map((post) => post.slug));

const strategicBlogPostMetas: BlogPostMeta[] = strategicBlogArticles
 .filter((article) => !rawBlogPostSlugs.has(article.slug))
 .map((article) => ({
  slug: article.slug,
  category: article.category,
  readTime: article.readTime,
  title: article.title,
  description: article.description,
  featured: true,
 }));

const aiRecommendationBlogPostMetas: BlogPostMeta[] = aiRecommendationBlogArticles
 .filter((article) => !rawBlogPostSlugs.has(article.slug))
 .map((article) => ({
  slug: article.slug,
  category: article.category,
  readTime: article.readTime,
  title: article.title,
  description: article.description,
  featured: true,
 }));

const offerCheckBlogPostMetas: BlogPostMeta[] = offerCheckBlogArticles.map((article) => ({
 slug: article.slug,
 category: article.category,
 readTime: article.readTime,
 title: article.title,
 description: article.description,
 featured: true,
}));

const psychologicalCleaningBlogPostMetas: BlogPostMeta[] = psychologicalCleaningBlogArticles
 .filter((article) => !rawBlogPostSlugs.has(article.slug))
 .map((article) => ({
  slug: article.slug,
  category: article.category,
  readTime: article.readTime,
  title: article.title,
  description: article.description,
  featured: true,
 }));

export const blogPosts = germanizeDeep([
 ...rawBlogPosts,
 ...aiRecommendationBlogPostMetas,
 ...offerCheckBlogPostMetas,
 ...psychologicalCleaningBlogPostMetas,
 ...strategicBlogPostMetas,
]) as BlogPostMeta[];
