export const company = {
  name: "FLOXANT",
  email: "info@floxant.de",
  phone: "+49 1577 1105087",
  phoneRaw: "+4915771105087",
  address: "Johanna-Kinkel-Straße 1 + 2, 93049 Regensburg, Deutschland",
  streetAddress: "Johanna-Kinkel-Straße 1 + 2",
  postalCode: "93049",
  city: "Regensburg",
  state: "Bayern",
  country: "Deutschland",
  countryCode: "DE",
  vatId: "DE45971484",
  url: "https://www.floxant.de",
  bookingUrl: "https://www.floxant.de/buchung",
  contactUrl: "https://www.floxant.de/kontakt",
  locationsUrl: "https://www.floxant.de/standorte",
  serviceAreaUrl: "https://www.floxant.de/service-area-bayern",
  businessProfilePreferredUrl: "https://www.floxant.de/buchung",
  mapsPreferredEntryUrl: "https://www.floxant.de/buchung",
  mapsSearchUrl:
    "https://www.google.com/maps/search/?api=1&query=Johanna-Kinkel-Stra%C3%9Fe%201%20%2B%202%2C%2093049%20Regensburg%2C%20Deutschland",
  geo: {
    lat: 49.0134,
    lng: 12.1016,
  },
  sameAs: [
    "https://www.instagram.com/floxant_logistik",
    "https://www.facebook.com/floxant",
  ],
  primaryServiceAreas: [
    "Regensburg",
    "Landkreis Regensburg",
    "Umgebung Regensburg ca. 200 km",
    "Oberpfalz",
    "Bayern",
    "München",
    "Nürnberg",
    "Augsburg",
    "Landshut",
    "Passau",
  ],
  keyGeoTargets: [
    "Regensburg",
    "Landkreis Regensburg",
    "Umgebung Regensburg ca. 200 km",
    "Nürnberg",
    "München",
    "Augsburg",
    "Landshut",
    "Passau",
    "Ingolstadt",
    "Schwandorf",
    "Oberpfalz",
    "Bayern",
  ],
  primaryCategories: [
    "Umzugsunternehmen",
    "Reinigungsfirma",
    "Entrümpelungsservice",
    "Büroumzug",
  ],
  coreServices: [
    "Umzug",
    "Reinigung",
    "Entrümpelung",
    "Büroumzug",
    "Einlagerung",
    "Akteneinlagerung",
    "Firmenentsorgung",
    "Gewerbereinigung",
    "Leer-Rückfahrt",
    "Rückladung",
    "Schlüsselübergabe",
    "Übergabeprotokoll",
    "Plan-B-Service",
    "Übergabevorbereitung",
    "Private Client Service",
  ],
};
