export function germanizeText(value?: string | null) {
  if (!value) return "";

  const replacements: Array<[RegExp, string]> = [
    [/\bFuer\b/g, "Für"],
    [/\bfuer\b/g, "für"],
    [/\bUeber/g, "Über"],
    [/\bueber/g, "über"],
    [/\bBuerokratie\b/g, "Bürokratie"],
    [/\bbuerokratie\b/g, "bürokratie"],
    [/\bBueroumzug\b/g, "Büroumzug"],
    [/\bbueroumzug\b/g, "Büroumzug"],
    [/\bBueroentsorgung\b/g, "Büroentsorgung"],
    [/\bbueroentsorgung\b/g, "Büroentsorgung"],
    [/\bBueroinventar\b/g, "Büroinventar"],
    [/\bBueros\b/g, "Büros"],
    [/\bBuero\b/g, "Büro"],
    [/\bbuero\b/g, "Büro"],
    [/\bEntruempelung\b/g, "Entrümpelung"],
    [/\bentruempelung\b/g, "Entrümpelung"],
    [/\bWohnungsaufloesung\b/g, "Wohnungsauflösung"],
    [/\bwohnungsaufloesung\b/g, "Wohnungsauflösung"],
    [/\bAufloesung\b/g, "Auflösung"],
    [/\baufloesung\b/g, "auflösung"],
    [/\bRueckfahrt\b/g, "Rückfahrt"],
    [/\brueckfahrt\b/g, "Rückfahrt"],
    [/\bRuecktransport\b/g, "Rücktransport"],
    [/\bruecktransport\b/g, "Rücktransport"],
    [/\bRueckruf\b/g, "Rückruf"],
    [/\brueckruf\b/g, "Rückruf"],
    [/\bMuenchen\b/g, "München"],
    [/\bNuernberg\b/g, "Nürnberg"],
    [/\bWuerzburg\b/g, "Würzburg"],
    [/\bFuerth\b/g, "Fürth"],
    [/\bKoeln\b/g, "Köln"],
    [/\bWuerttemberg\b/g, "Württemberg"],
    [/\bSchluesseluebergabe\b/g, "Schlüsselübergabe"],
    [/\bSchluessel\b/g, "Schlüssel"],
    [/\bMoebel\b/g, "Möbel"],
    [/\bmoebel\b/g, "Möbel"],
    [/\bKueche\b/g, "Küche"],
    [/\bkueche\b/g, "Küche"],
    [/\bRaeum/g, "Räum"],
    [/\braeum/g, "räum"],
    [/\bPruefung\b/g, "Prüfung"],
    [/\bpruefung\b/g, "prüfung"],
    [/\bVorpruefung\b/g, "Vorprüfung"],
    [/\bvorpruefung\b/g, "Vorprüfung"],
    [/\bPruef/g, "Prüf"],
    [/\bpruef/g, "prüf"],
    [/\bGeprueft\b/g, "Geprüft"],
    [/\bgeprueft\b/g, "geprüft"],
    [/\bLoesung\b/g, "Lösung"],
    [/\bloesung\b/g, "lösung"],
    [/\bUebergabe\b/g, "Übergabe"],
    [/\buebergabe\b/g, "Übergabe"],
    [/\bUebertragung\b/g, "Übertragung"],
    [/\buebertragung\b/g, "Übertragung"],
    [/\bUmzuege\b/g, "Umzüge"],
    [/\bumzuege\b/g, "Umzüge"],
    [/\bUmzueg/g, "Umzüg"],
    [/\bumzueg/g, "umzüg"],
    [/\bHaende\b/g, "Hände"],
    [/\bhaende\b/g, "Hände"],
    [/\bHaeuser\b/g, "Häuser"],
    [/\bhaeuser\b/g, "Häuser"],
    [/\bHaeufige\b/g, "Häufige"],
    [/\bhaeufige\b/g, "häufige"],
    [/\bmoechte\b/g, "möchte"],
    [/\bmoechten\b/g, "möchten"],
    [/\bMoeglich\b/g, "Möglich"],
    [/\bmoeglich\b/g, "möglich"],
    [/\bgroessere\b/g, "größere"],
    [/\bgroesst/g, "größt"],
    [/\bzusaetzlich/g, "zusätzlich"],
    [/\bnaechst/g, "nächst"],
    [/\bregelmaessig/g, "regelmäßig"],
    [/\bverlaesslich/g, "verlässlich"],
    [/\bVerfuegbarkeit\b/g, "Verfügbarkeit"],
    [/\bverfuegbarkeit\b/g, "Verfügbarkeit"],
  ];

  return replacements.reduce((text, [pattern, replacement]) => text.replace(pattern, replacement), value);
}

export function germanText(value: string | null | undefined, fallback: string) {
  const raw = (value || "").trim();
  return germanizeText(raw || fallback);
}
