export type PracticalGuide = {
  slug: string;
  region: "duesseldorf" | "regensburg";
  title: string;
  description: string;
  answer: string;
  serviceHref: string;
  serviceLabel: string;
  existing?: boolean;
  sections: { title: string; paragraphs: string[]; bullets?: string[] }[];
};

export const practicalGuides: PracticalGuide[] = [
  {
    slug: "bueroreinigung-duesseldorf-umfang-rhythmus", region: "duesseldorf",
    title: "Büroreinigung in Düsseldorf: Welcher Umfang und Rhythmus passen?",
    description: "Welche Bürobereiche wie oft gereinigt werden sollten: Aufgaben sinnvoll aufteilen, Nutzung berücksichtigen und einen verständlichen Reinigungsplan erstellen.",
    answer: "Der passende Reinigungsrhythmus richtet sich nach der Nutzung der einzelnen Räume. Küche, Sanitärbereiche und stark genutzte Laufwege brauchen andere Intervalle als ein selten belegter Besprechungsraum. Legen Sie deshalb zuerst Aufgaben je Bereich fest und entscheiden Sie dann über die Häufigkeit.",
    serviceHref: "/duesseldorf/bueroreinigung", serviceLabel: "Büroreinigung in Düsseldorf",
    sections: [
      {title:"Was gehört zur regelmäßigen Büroreinigung?", paragraphs:["Eine brauchbare Aufgabenliste unterscheidet Arbeitsplätze, Besprechungsräume, Empfang, Laufwege, Küche und Sanitärbereiche. Bei Arbeitsplätzen geht es beispielsweise um frei zugängliche Oberflächen und Böden; Unterlagen und persönliche Gegenstände bleiben an ihrem Platz. Elektronik braucht eine ausdrücklich abgestimmte Behandlung.","Halten Sie auch fest, welche Aufgaben nicht bei jedem Besuch nötig sind. Fenster, Rahmen, hohe Ablagen und eine intensive Bodenreinigung lassen sich in größeren Abständen ergänzen. Ein Angebot wird verständlicher, wenn diese Positionen getrennt genannt sind."]},
      {title:"Wie finden Sie den richtigen Turnus?", paragraphs:["Betrachten Sie die tatsächliche Belegung und den Kundenverkehr. Ein häufig genutzter Empfang wird anders beansprucht als ein leerstehendes Büro. Auch gemeinsam genutzte Küchen und Sanitärbereiche benötigen einen eigenen Rhythmus. Die Quadratmeterzahl allein beantwortet diese Frage nicht.","Beginnen Sie mit einer kurzen Übersicht: Raum, Nutzung, Aufgabe und gewünschte Häufigkeit. Nach den ersten vereinbarten Terminen lässt sich besprechen, ob einzelne Bereiche häufiger oder seltener gereinigt werden sollten. So wird aus einer pauschalen Vorgabe ein Plan für Ihren Betrieb."],bullets:["Täglich prüfen: Wo entstehen im Betrieb sichtbare Verschmutzungen?", "Je Reinigungstermin: Welche Flächen sollen zuverlässig erledigt werden?", "In größeren Abständen: Welche Zusatzarbeiten sind sinnvoll?", "Bei Bedarf: Was ändert sich durch Veranstaltungen oder Umbauten?"]},
      {title:"Ein Beispiel für die Aufteilung", paragraphs:["Angenommen, ein Büro hat zwölf Arbeitsplätze, einen Besprechungsraum und eine gemeinsam genutzte Küche. Die Küche wird jeden Arbeitstag genutzt, der Besprechungsraum nur an zwei Tagen. Dann muss nicht jeder Raum mit derselben Häufigkeit gereinigt werden. Die Aufgabenliste kann die Küche und Laufwege stärker gewichten und den Besprechungsraum nach tatsächlicher Nutzung einplanen.","Das ist ein Planungsbeispiel, kein vorgeschriebener Turnus. Entscheidend sind Ihr gewünschter Zustand, die Belegung und die Aufgaben, die Ihr Team bereits selbst übernimmt."]},
      {title:"Reinigungszeiten und Zugang organisieren", paragraphs:["Stimmen Sie Zeiten so ab, dass Reinigung und Arbeit zusammenpassen. Nennen Sie Kernzeiten, Telefonkonferenzen, Publikumsverkehr und Räume, die nur begleitet betreten werden dürfen. Frühere oder spätere Zeiten sind eine Frage der gemeinsamen Terminplanung.","Eine feste Kontaktperson vereinfacht Änderungen. Besprechen Sie außerdem Schlüssel, Alarmanlage, verschlossene Bereiche und den Abstellplatz für Material. Sensible Dokumente sollten vor der Reinigung so aufbewahrt werden, wie es Ihre internen Regeln vorsehen."]},
      {title:"Welche Angaben reichen für ein Angebot?", paragraphs:["Für den Erstkontakt genügen Standort, ungefähre Fläche, Raumarten und der gewünschte Rhythmus. Ergänzend helfen Reinigungszeiten, Zahl der Sanitärbereiche, Bodenbeläge und besondere Aufgaben. Fotos sind freiwillig und sollten keine vertraulichen Unterlagen zeigen.","FLOXANT übernimmt Büroreinigung in Düsseldorf und 75 km Umgebung als Luftlinie. Im persönlichen Angebot werden Aufgaben, Intervalle, Zugang und Preis abgestimmt. Anfahrt und konkrete Einsatzadresse gehören zur Planung."]},
    ],
  },
  {
    slug:"fensterreinigung-duesseldorf-preisfaktoren", region:"duesseldorf",
    title:"Fensterreinigung in Düsseldorf: Was bestimmt den Preis?",
    description:"Glas, Rahmen, Falze und Erreichbarkeit: So beschreiben Sie Ihre Fenster und erkennen, welche Arbeiten im Reinigungsangebot enthalten sind.",
    answer:"Der Aufwand hängt von Glasmenge, Fensteraufteilung, gewünschten Seiten, Rahmen und Falzen sowie der Erreichbarkeit ab. Zwei Wohnungen mit gleich vielen Fenstern können deshalb unterschiedliche Reinigungsaufträge ergeben. Eine kurze Fensterliste und einige freiwillige Fotos sind hilfreicher als nur die Wohnfläche.",
    serviceHref:"/duesseldorf/fensterreinigung", serviceLabel:"Fensterreinigung in Düsseldorf",
    sections:[
      {title:"Glasreinigung, Rahmen und Falze unterscheiden",paragraphs:["Mit Glasreinigung sind zunächst die vereinbarten Glasflächen gemeint. Innen- und Außenseiten sollten im Angebot ausdrücklich erkennbar sein. Rahmen sind die sichtbaren Bauteile um das Glas; Falze sind die Bereiche, die beim Öffnen zwischen Rahmen und Flügel zugänglich werden.","Wenn Sie auch Rahmen, Falze und Fensterbänke gereinigt haben möchten, nennen Sie diese einzeln. Dort können sich andere Rückstände sammeln als auf der Scheibe. Dadurch ändert sich der Zeitbedarf, auch wenn die Glasfläche dieselbe bleibt."]},
      {title:"Warum Fensterzahl allein nicht reicht",paragraphs:["Ein kleines, gut zugängliches Fenster ist ein anderer Auftrag als eine bodentiefe Glasfront mit mehreren Flügeln. Sprossen, Oberlichter und feste Glasteile bringen zusätzliche Kanten oder Zugangsfragen mit sich. Balkontüren und große Schaufenster sollten daher mit in die Liste.","Für eine erste Beschreibung genügt eine grobe Aufteilung, etwa: vier normale Fenster, zwei Balkontüren und eine feste Glasfläche. Schreiben Sie dazu, was geöffnet werden kann und ob innen, außen oder beides gewünscht ist."],bullets:["Anzahl und ungefähre Größe", "Öffnungsart und feste Glasteile", "Innen- und Außenseiten", "Rahmen, Falze und Fensterbänke", "Besondere Rückstände und Beschichtungen"]},
      {title:"Erreichbarkeit verändert die Planung",paragraphs:["Wichtig sind Höhe, Etage, Hindernisse und der Platz vor dem Fenster. Ein Fenster kann groß, aber vom Boden gut erreichbar sein. Ein kleines Oberlicht kann dagegen zusätzlichen Aufwand verursachen. Beschreiben Sie deshalb die Zugangssituation von beiden Seiten.","FLOXANT stimmt die sichere Durchführung vor dem Auftrag ab. Für Fotos müssen Sie sich weder hinauslehnen noch auf Möbel steigen. Übersichtsaufnahmen aus normal zugänglichen Bereichen reichen; unklare Stellen lassen sich persönlich besprechen."]},
      {title:"Beispiel: dasselbe Glas, anderer Umfang",paragraphs:["Bei einer Wohnung können Sie nur die inneren Glasflächen reinigen lassen oder zusätzlich Außenseiten, Rahmen und Falze beauftragen. Der zweite Auftrag umfasst mehr Arbeit, obwohl Fensterzahl und Wohnfläche unverändert bleiben. Angebote sollten deshalb anhand derselben Aufgaben verglichen werden.","Auch Rückstände nach Renovierung sind ein zusätzlicher Punkt. Farbe, Kleber oder Mörtel lassen sich nicht wie gewöhnlicher Staub behandeln. Nennen Sie solche Stellen vorab und vermeiden Sie eigenständiges Kratzen an unbekannten Oberflächen."]},
      {title:"So bereiten Sie den Termin vor",paragraphs:["Räumen Sie Fensterbänke und den Zugang frei, soweit das ohne Schwierigkeiten möglich ist. Teilen Sie mit, wenn schwere Möbel den Zugang versperren oder ein Fenster nicht geöffnet werden kann. Niemand muss für die Anfrage bereits alle Vorarbeiten erledigt haben.","Für Ihr persönliches Angebot in Düsseldorf und 75 km Umgebung genügen zunächst eine kurze Fensterbeschreibung und die gewünschten Arbeiten. Anzahl, Zugang, Zustand und Anfahrt werden gemeinsam berücksichtigt; pauschale Fantasiepreise helfen dabei nicht."]},
    ],
  },
  {
    slug:"grundreinigung-oder-unterhaltsreinigung", region:"duesseldorf",
    title:"Grundreinigung oder Unterhaltsreinigung: Was passt zu Ihrem Objekt?",
    description:"Den Unterschied verstehen und die passende Reinigung auswählen: regelmäßige Pflege, intensive Reinigung und sinnvolle Kombinationen für Wohnung oder Betrieb.",
    answer:"Unterhaltsreinigung erledigt regelmäßig wiederkehrende Aufgaben. Grundreinigung behandelt ausgewählte Bereiche einmalig intensiver. Wenn starke Rückstände vorhanden sind und anschließend ein gepflegter Zustand erhalten werden soll, kann eine abgestimmte Grundreinigung mit späterer Unterhaltsreinigung sinnvoll sein.",
    serviceHref:"/duesseldorf/grundreinigung", serviceLabel:"Grundreinigung in Düsseldorf",
    sections:[
      {title:"Unterhaltsreinigung hält den Alltag in Ordnung",paragraphs:["Die Unterhaltsreinigung folgt einem Aufgabenplan. Dazu können Böden, zugängliche Oberflächen, Sanitärbereiche und Küchen gehören. Die Intervalle richten sich nach Nutzung und gewünschtem Zustand. Nicht jeder Raum muss dieselben Aufgaben oder denselben Rhythmus bekommen.","Sie passt, wenn ein grundsätzlich gepflegtes Objekt regelmäßig gereinigt werden soll. Ein Büro mit wechselnder Belegung braucht beispielsweise eine andere Verteilung als ein Treppenhaus. Der Plan beschreibt, was bei jedem Besuch und was in größeren Abständen erledigt wird."]},
      {title:"Grundreinigung setzt gezielte Schwerpunkte",paragraphs:["Bei einer Grundreinigung wird intensiver an vereinbarten Bereichen gearbeitet. Das können stärker verschmutzte Böden, Küchen- und Sanitärbereiche oder schwer zugängliche Ecken sein. Der Begriff allein legt aber keinen vollständigen Leistungsumfang fest.","Besprechen Sie konkrete Flächen und Rückstände. Eine intensive Reinigung ist keine Sanierung: Schäden, Verfärbungen oder Abnutzung lassen sich nicht automatisch entfernen. Material, Oberflächenzustand und mögliche Verfahren werden deshalb vorher abgestimmt."]},
      {title:"Drei Fragen helfen bei der Auswahl",paragraphs:["Schauen Sie zuerst auf das Problem, dann auf die Bezeichnung der Leistung. Geht es um täglich neu entstehenden Schmutz, um länger vorhandene Rückstände oder um beides? Eine klare Antwort verhindert, dass viel gereinigt wird, aber die eigentliche Aufgabe offenbleibt."],bullets:["Entsteht die Verschmutzung regelmäßig durch die normale Nutzung? Dann passt ein wiederkehrender Aufgabenplan.", "Sind bestimmte Flächen deutlich stärker verschmutzt? Benennen Sie diese als Schwerpunkte für eine intensive Reinigung.", "Sind gerade Bau- oder Renovierungsarbeiten beendet? Dann müssen Staub und Materialrückstände gesondert beschrieben werden.", "Soll ein verbesserter Zustand erhalten bleiben? Planen Sie die späteren Pflegeaufgaben gleich mit."]},
      {title:"Ein nachvollziehbares Beispiel",paragraphs:["In einem Laden sind die täglichen Laufwege gepflegt, an den Rändern und unter verschiebbaren Einbauten liegen jedoch ältere Rückstände. Hier kann eine gezielte intensive Reinigung dieser Flächen sinnvoll sein. Anschließend wird der normale Plan um zugängliche Randbereiche ergänzt.","Für eine kaum genutzte, bereits gepflegte Wohnung wäre derselbe Umfang möglicherweise unnötig. Dort kann eine einmalige normale Reinigung ausreichen. Beide Beispiele sind Entscheidungshilfen und keine Aussage über einen konkreten Kundenauftrag."]},
      {title:"Was im Angebot stehen sollte",paragraphs:["Ein verständliches Angebot benennt Flächen, Aufgaben, gewünschte Intensität und optionale Arbeiten. Bei regelmäßiger Reinigung kommen Intervalle und Zeiten hinzu. Fenster, Geräteinnenräume und Sonderflächen sollten eindeutig zugeordnet werden.","Beschreiben Sie FLOXANT kurz Objekt, Fläche und das Problem, das Sie lösen möchten. Fotos sind freiwillig. Die Reinigung wird in Düsseldorf oder Regensburg und jeweils 75 km Umgebung geplant; Preis und Anfahrt richten sich nach dem konkreten Auftrag."]},
    ],
  },
  {
    slug:"wohnung-nach-renovierung-reinigen", region:"duesseldorf",
    title:"Wohnung nach Renovierung reinigen: In welcher Reihenfolge?",
    description:"Nach der Renovierung systematisch reinigen: Arbeiten abschließen, Baustaub entfernen, empfindliche Oberflächen berücksichtigen und Räume Schritt für Schritt vorbereiten.",
    answer:"Beginnen Sie erst, wenn staubende Arbeiten abgeschlossen sind. Räumen Sie freigegebene Reste weg, entfernen Sie losen Staub mit einem für den vorhandenen Staub geeigneten Verfahren und reinigen Sie anschließend die jeweiligen Oberflächen nach ihren Pflegevorgaben. Arbeiten Sie von oben nach unten und erledigen Sie Böden zuletzt.",
    serviceHref:"/duesseldorf/baureinigung", serviceLabel:"Reinigung nach Renovierung in Düsseldorf",
    sections:[
      {title:"Zuerst klären, welche Arbeiten noch laufen",paragraphs:["Schleifen, Bohren und Nacharbeiten können frisch gereinigte Flächen erneut verschmutzen. Legen Sie deshalb vor der Endreinigung fest, welche Arbeiten abgeschlossen sind und wo noch Handwerker Zugang benötigen. Frische Beschichtungen und Fugen müssen entsprechend den jeweiligen Herstellerangaben behandelt werden.","Unterscheiden Sie außerdem Verpackungen, freigegebene Baureste und Gegenstände, die noch gebraucht werden. Rechnungen, Ersatzteile und übriges Material sollten nicht versehentlich mit entsorgt werden. Die Abfuhr von Baustoffen ist eine eigene Aufgabe und gehört nicht automatisch zur Reinigung."]},
      {title:"Losen Staub vor der feuchten Reinigung aufnehmen",paragraphs:["Staub liegt oft auch auf Türrahmen, Leisten, Schränken und Heizkörpern. Werden nur die Böden gewischt, können Rückstände später von höher gelegenen Flächen wieder herunterfallen. Eine systematische Reihenfolge verhindert doppelte Arbeit.","Wählen Sie Geräte und Vorgehen passend zum vorhandenen Staub und zur Oberfläche. Unbekannte Bau- oder Schadstoffrückstände gehören zunächst fachlich geklärt. Dieser Ratgeber gibt dafür keine Freigabe zur Eigenreinigung. Für gewöhnliche, bekannte Rückstände gelten die Pflege- und Gerätehinweise des jeweiligen Herstellers."]},
      {title:"Empfindliche Oberflächen getrennt behandeln",paragraphs:["Holz, Naturstein, beschichtete Böden, Glas und Armaturen reagieren unterschiedlich auf Mittel und mechanische Bearbeitung. Bewahren Sie vorhandene Pflegeinformationen auf und zeigen Sie besonders empfindliche Flächen vor Beginn. Ein einziges Mittel für die gesamte Wohnung ist keine verlässliche Planung.","Farb- oder Kleberreste sollten nicht auf Verdacht abgekratzt werden. Benennen Sie das Material und zeigen Sie die Stelle. Eine kleine Prüfung an geeigneter unauffälliger Stelle kann Teil der abgestimmten Durchführung sein; sie ersetzt keine Kenntnis des Materials."]},
      {title:"Raum für Raum abschließen",paragraphs:["Ein möglicher Ablauf ist: obere Ablagen und Rahmen, zugängliche Einbauten, Türen und Fensterbereiche, anschließend Bad und Küche sowie zuletzt die Böden. Halten Sie bereits gereinigte Bereiche möglichst frei von Material und Laufverkehr.","Beispiel: Wenn im Schlafzimmer bereits alles fertig ist, die Küche aber noch montiert wird, kann das Schlafzimmer getrennt vorbereitet werden. Die abschließende Reinigung der Laufwege folgt sinnvollerweise nach der letzten Montage. Das konkrete Vorgehen hängt vom Baufortschritt ab."],bullets:["Fertige und noch bearbeitete Räume kennzeichnen", "Pflegehinweise und bekannte Materialien bereitlegen", "Rückstände und mögliche Schäden getrennt dokumentieren", "Einbauten und Geräte nur im vereinbarten Umfang reinigen", "Böden und letzte Laufwege am Ende bearbeiten"]},
      {title:"Welche Angaben helfen einem Reinigungsdienst?",paragraphs:["Nennen Sie Wohnfläche, betroffene Räume, Art der Renovierung und den Stand der Arbeiten. Hilfreich sind außerdem Bodenbeläge, besondere Oberflächen, stärkere Rückstände und der geplante Einzug. Fotos sind freiwillig und erleichtern die Abstimmung.","FLOXANT vereinbart die Reinigung nach Renovierung passend zu den beschriebenen Flächen. Intensität, Zugang, Anfahrt und Zusatzarbeiten bestimmen den Aufwand. Unklare Materialien oder verbleibende Handwerkerarbeiten werden vor dem Termin besprochen."]},
    ],
  },
  {
    slug:"hotel-apartmentreinigung-duesseldorf-gaestewechsel", region:"duesseldorf",
    title:"Hotel- und Apartmentreinigung in Düsseldorf: Wie gelingt der Gästewechsel?",
    description:"Gästewechsel praktisch organisieren: Zeitfenster, Zimmerliste, Wäsche, Nachfüllaufgaben und Rückmeldung für Hotel- und Apartmentreinigung abstimmen.",
    answer:"Ein geordneter Gästewechsel braucht eine aktuelle Liste freier Einheiten, eine klare Aufgabenliste und eine Kontaktperson für Abweichungen. Reinigungszeit, Wäsche, Material und Zugang müssen zusammenpassen. Planen Sie auch eine Rückmeldung ein, bevor die nächste Belegung beginnt.",
    serviceHref:"/duesseldorf/hotelreinigung", serviceLabel:"Hotel- und Apartmentreinigung in Düsseldorf",
    sections:[
      {title:"Mit einer verlässlichen Einheitenliste beginnen",paragraphs:["Übergeben Sie nicht nur eine Gesamtzahl, sondern die tatsächlich freigegebenen Zimmer oder Apartments. Für jede Einheit helfen Kennung, Abreisezeit, nächste Anreise und Besonderheiten. Verspätete Abreisen und noch belegte Räume müssen erkennbar bleiben.","Eine feste Kontaktperson sollte Änderungen weitergeben. Damit vermeiden Sie, dass Reinigungspersonal vor verschlossenen Türen wartet oder eine Einheit zu früh betritt. Bei mehreren Häusern gehören auch Wege und Schlüsselwechsel in die Planung."]},
      {title:"Aufgaben so beschreiben, dass nichts vorausgesetzt wird",paragraphs:["Trennen Sie Wohn- oder Schlafbereich, Bad und gegebenenfalls Küche. Zur Aufgabenliste können Böden, zugängliche Oberflächen, Sanitärbereiche und vereinbarte Küchenarbeiten gehören. Fenster und intensive Detailreinigung lassen sich in längeren Intervallen einplanen.","Housekeeping kann mehr als Reinigung bedeuten. Betten beziehen, Handtücher bereitlegen, Verbrauchsmaterial nachfüllen und Inventar nach Liste kontrollieren sollten deshalb ausdrücklich vereinbart werden. Auch wer saubere Wäsche und Material bereitstellt, muss klar sein."],bullets:["Welche Einheit ist zur Reinigung freigegeben?", "Welche Standardaufgaben und Zusatzarbeiten gelten?", "Wo liegen Wäsche und Verbrauchsmaterial?", "Wohin kommen gebrauchte Textilien?", "Wer erhält die Rückmeldung und entscheidet bei Abweichungen?"]},
      {title:"Zeitfenster realistisch verteilen",paragraphs:["Zwischen Abreise und Anreise müssen Zugang, Reinigung und Rückmeldung möglich sein. Größe, Bad- und Küchenumfang sowie der tatsächliche Zustand beeinflussen den Aufwand. Ein identisches Zeitfenster für unterschiedlich ausgestattete Einheiten kann deshalb zu Engpässen führen.","Beispiel: Zwei ähnlich große Apartments unterscheiden sich dadurch, dass nur eines eine häufig genutzte Küche hat. Die Küchenaufgaben müssen im Ablauf dieses Apartments berücksichtigt werden. Eine solche Unterscheidung ist hilfreicher als ein einheitlicher Minutenwert ohne Leistungsbeschreibung."]},
      {title:"Abweichungen melden, ohne den Ablauf zu verlieren",paragraphs:["Legen Sie fest, wie sichtbare Schäden, fehlende Ausstattung oder ungewöhnlich aufwendige Verschmutzungen gemeldet werden. Eine kurze sachliche Rückmeldung an die Kontaktperson hilft bei der Entscheidung. Die Reinigungskraft sollte keine Reparatur oder zusätzliche Leistung stillschweigend versprechen müssen.","Notieren Sie bei der Rückmeldung, welche Einheit fertig ist und welche Punkte offen sind. Wenn Fotos vereinbart werden, sollten darauf keine persönlichen Gegenstände oder Gästedaten unnötig erfasst werden. Für die eigene Organisation genügt häufig eine knappe Aufgaben- und Statusliste."]},
      {title:"Ein Angebot für Ihre Unterkunft vorbereiten",paragraphs:["Für den Erstkontakt reichen Standort, Einheitenzahl, ungefähre Größe und Wechselrhythmus. Anschließend lassen sich Bäder, Küchen, Wäsche, Material, Zugang und mögliche Zeitfenster ergänzen.","FLOXANT übernimmt vereinbarte Hotel- und Apartmentreinigung in Düsseldorf und 75 km Umgebung als Luftlinie. Umfang, Preis und Termin werden passend zu Ihrem Betrieb abgestimmt. Wäscheservice, Reparaturen oder jederzeitige Zusatztermine sind kein automatischer Bestandteil der Reinigung."]},
    ],
  },
  {
    slug:"umzug-regensburg-tipps", region:"regensburg", existing:true,
    title:"Umzug in Regensburg planen: Etagen, Laufwege, Möbel und Fotos",
    description:"Einen Umzug in Regensburg übersichtlich vorbereiten: Zugänge prüfen, Möbel auflisten, Pack- und Montagearbeiten aufteilen und hilfreiche Fotos auswählen.",
    answer:"Für einen planbaren Umzug brauchen Sie Start, Ziel, Termin, eine grobe Möbelliste und Angaben zu beiden Zugängen. Etagen, Aufzug und der Weg zum Fahrzeug beeinflussen den Aufwand ebenso wie die Möbelmenge. Beginnen Sie mit diesen Eckdaten; weitere Details lassen sich im Gespräch ergänzen.",
    serviceHref:"/regensburg/umzug", serviceLabel:"Umzug in Regensburg",
    sections:[
      {title:"Beide Adressen gleich sorgfältig betrachten",paragraphs:["Notieren Sie für Start und Ziel Etage, Aufzug, Hauseingang und den voraussichtlichen Ladepunkt. Ein Aufzug hilft nur, wenn die betreffenden Möbel hineinpassen und er zum Termin genutzt werden kann. Enge Türen, Zwischenstufen und Innenhöfe gehören ebenfalls in die Beschreibung.","In dichter bebauten Straßen und Altstadtlagen kann der Weg vom Fahrzeug zur Tür länger sein als gedacht. Beschreiben Sie die tatsächliche Situation und vorhandene Einschränkungen. Dieser Ratgeber macht keine Aussage zu Genehmigungen oder reservierten Ladeflächen; diese Punkte müssen für die konkrete Adresse geklärt werden."]},
      {title:"Möbel und Kartons vollständig erfassen",paragraphs:["Gehen Sie Raum für Raum durch Wohnung, Keller und andere Nebenräume. Eine grobe Liste großer Möbel ist hilfreicher als nur die Zimmerzahl. Nennen Sie etwa Schränke, Betten, Sofa, Tisch, Haushaltsgeräte und die erwartete Kartonmenge.","Kennzeichnen Sie Möbel, die zerlegt werden sollen, sowie Stücke mit ungewöhnlichen Maßen oder hohem Gewicht. Wenn Maße oder Gewicht unbekannt sind, sagen Sie das offen. Ein Foto erleichtert die Rückfrage; eine genaue Volumenberechnung ist für den Erstkontakt nicht nötig."],bullets:["Große Möbel je Raum", "Grobe Kartonzahl und noch ungepackte Bereiche", "Keller, Balkon und andere Nebenräume", "Demontage und erneute Montage", "Schwere oder empfindliche Einzelstücke"]},
      {title:"Welche Fotos helfen wirklich?",paragraphs:["Übersichtsaufnahmen zeigen Möbelmenge und Raumaufteilung. Ergänzen Sie bei Bedarf Hauseingang, Treppenhaus, Aufzug, enge Durchgänge und große Einzelstücke. Ein Foto vom Laufweg zwischen Eingang und möglichem Ladepunkt kann eine längere Erklärung ersetzen.","Fotos sind freiwillig. Lassen Sie persönliche Unterlagen, Namensschilder und andere unnötige Details möglichst aus dem Bild. Für eine brauchbare Anfrage reichen zunächst auch eine kurze Beschreibung und eine Rückrufmöglichkeit."]},
      {title:"Aufgaben und Reihenfolge vorher festlegen",paragraphs:["Klären Sie, wer packt, Möbel vorbereitet und am Ziel die Räume zuordnet. Kartons mit dem Zielraum zu beschriften, erleichtert das Abstellen. Dinge, die Sie am Umzugstag persönlich brauchen, sollten separat erreichbar bleiben.","Wenn danach Reinigung oder Entrümpelung gewünscht ist, planen Sie die Reihenfolge: erst freigegebene Gegenstände räumen, dann transportieren, anschließend die frei gewordenen Räume reinigen. FLOXANT kann die vereinbarten Leistungen aufeinander abstimmen; zusätzliche Aufgaben werden im Angebot benannt."]},
      {title:"Was den Preis und den Termin beeinflusst",paragraphs:["Möbelmenge, Strecke, Etagen, Aufzug, Laufwege, Ladepunkt, Montage und Packhilfe bestimmen den Aufwand. Änderungen an diesen Punkten sollten Sie früh mitteilen. Ein nachvollziehbares Angebot beschreibt die vereinbarten Arbeiten und ihre Voraussetzungen.","FLOXANT plant lokale Umzüge in Regensburg und 75 km Umgebung. Ein weiter entferntes Umzugsziel ist eine gesonderte Strecke und kein zusätzlicher Standort. Beschreiben Sie Start, Ziel und Terminwunsch kurz; danach stimmen wir Transport, Zusatzarbeiten und Preis persönlich ab."]},
    ],
  },
  {
    slug:"endreinigung-regensburg-checkliste", region:"regensburg", existing:true,
    title:"Endreinigung in Regensburg: Wohnung für die Übergabe vorbereiten",
    description:"Praktische Checkliste für die Endreinigung vor der Wohnungsübergabe: Räume leeren, Bad und Küche einplanen, Extras festlegen und den Termin abstimmen.",
    answer:"Planen Sie die Endreinigung nach dem Ausräumen und vor der Übergabe. Legen Sie fest, welche Böden, Oberflächen, Küchen- und Sanitärbereiche gereinigt werden sollen. Fenster und Einbauten sind eigene Positionen. Maßgeblich ist der besprochene Umfang; Reinigung ersetzt keine Reparatur und keine Vereinbarung zur Wohnungsabnahme.",
    serviceHref:"/regensburg/reinigung-nach-umzug", serviceLabel:"Endreinigung nach dem Umzug in Regensburg",
    sections:[
      {title:"Erst räumen, dann den Umfang festlegen",paragraphs:["Wenn Möbel und Kartons entfernt sind, werden Böden, Ecken und Einbauten besser zugänglich. Verbliebene Gegenstände sollten eindeutig zugeordnet werden: Was bleibt, was holen Sie noch ab und was soll gesondert geräumt werden? Ein Reinigungsauftrag umfasst keine automatische Entrümpelung.","Gehen Sie danach einmal durch alle Räume. Notieren Sie den gewünschten Zustand und besondere Stellen. Vorhandene Schäden oder Abnutzung sollten von Verschmutzung unterschieden werden, damit das Reinigungsziel realistisch bleibt."]},
      {title:"Eine Checkliste nach Bereichen",paragraphs:["Statt nur „komplett reinigen“ zu vereinbaren, lohnt sich eine überschaubare Liste. So sehen beide Seiten, welche Aufgaben dazugehören. Küche und Bad können wegen ihrer Ausstattung mehr Detailarbeit erfordern als ein leerer Wohnraum."],bullets:["Böden: Material, freie Fläche und stärkere Rückstände", "Bad: Waschbecken, Dusche oder Wanne, WC und vereinbarte Oberflächen", "Küche: zugängliche Flächen sowie auf Wunsch leere Schränke und Geräteinnenräume", "Zimmer: Türen, Schalter, erreichbare Ablagen und Einbauten", "Fenster: Glas innen und außen, Rahmen und Falze nach Vereinbarung", "Nebenräume: Keller oder Balkon nur im beschriebenen Umfang"]},
      {title:"Termin und Zugang mit dem Umzug abstimmen",paragraphs:["Eine Reinigung vor der letzten Möbelabholung führt leicht zu erneuten Laufspuren. Planen Sie sie deshalb möglichst nach dem Ausräumen und mit Abstand zu späteren Arbeiten. Wenn Räume noch genutzt werden, teilen Sie dies vorab mit.","Klären Sie Schlüssel, Ansprechpartner, Wasser- und Stromzugang sowie den Zeitpunkt der Rückgabe. Ein fester Übergabetermin gehört früh in die Anfrage, damit die Reinigungszeit gemeinsam abgestimmt werden kann."]},
      {title:"Ein Beispiel für sinnvolle Zusatzarbeiten",paragraphs:["In einer leeren Wohnung werden Böden, Bad, Küchenflächen und Türen gereinigt. Die Einbauküche bleibt, der Backofen und die Innenseiten der Schränke sollen ebenfalls gereinigt werden. Diese Aufgaben gehören ausdrücklich in die Liste, weil sie über eine reine Oberflächenreinigung hinausgehen.","Die Fenster können im selben Auftrag ergänzt oder separat vereinbart werden. Ob jede Zusatzarbeit nötig ist, hängt vom Zustand und Ihrem gewünschten Ergebnis ab. Das Beispiel beschreibt einen möglichen Umfang, keinen dokumentierten Kundeneinsatz."]},
      {title:"Angebot einholen und Ergebnis besprechen",paragraphs:["Für eine erste Anfrage genügen Wohnfläche, Zimmerzahl, Zustand und Termin. Teilen Sie mit, ob die Wohnung leer ist und welche Extras Sie wünschen. Freiwillige Fotos von Küche, Bad und stärkeren Rückständen erleichtern die Einschätzung.","FLOXANT übernimmt die vereinbarte Endreinigung in Regensburg und 75 km Umgebung. Preisfaktoren sind vor allem Fläche, Zustand, Möblierung, zusätzliche Detailarbeit, Zugang und Anfahrt. Nach dem Auftrag lassen sich die besprochenen Bereiche gemeinsam durchgehen; über die Wohnungsabnahme entscheiden die Beteiligten."]},
    ],
  },
  {
    slug:"entruempelung-vor-wohnungsuebergabe", region:"regensburg", existing:true,
    title:"Entrümpelung in Regensburg: Aufwand, Trennung und Reinigung planen",
    description:"Entrümpelung vor der Übergabe vorbereiten: Gegenstände freigeben, Mengen und Laufwege erfassen, Materialien abstimmen und die anschließende Reinigung planen.",
    answer:"Der Aufwand einer Entrümpelung hängt von Menge, Gewicht, Materialarten und Tragewegen ab. Entscheiden Sie zuerst, was bleiben soll. Danach können freigegebene Gegenstände geräumt und der vereinbarte Abtransport organisiert werden. Eine anschließende Reinigung braucht einen eigenen, klar beschriebenen Umfang.",
    serviceHref:"/regensburg/entruempelung", serviceLabel:"Entrümpelung in Regensburg",
    sections:[
      {title:"Behalten und Räumen eindeutig trennen",paragraphs:["Sichern Sie zuerst persönliche Unterlagen, Schlüssel, Wertgegenstände und Erinnerungsstücke. Markieren Sie, welche Möbel bleiben, abgeholt oder geräumt werden sollen. Eine einfache Liste oder eindeutige Kennzeichnung verhindert Missverständnisse.","Bei mehreren beteiligten Personen braucht es eine Kontaktperson und klare Freigaben. Niemand muss für den Erstkontakt bereits alles aussortiert haben. Wenn Sie Unterstützung bei der Vorbereitung benötigen, beschreiben Sie den Stand offen; Sortieraufwand beeinflusst die Planung."]},
      {title:"Menge und Zugänge erfassen",paragraphs:["Wohnfläche allein sagt wenig über die zu räumende Menge aus. Ein kleiner voller Keller kann mehr Trage- und Sortierarbeit verursachen als ein fast leeres Zimmer. Fotos jedes Raums und eine Liste größerer Möbel helfen bei der Einschätzung.","Beschreiben Sie Etage, Aufzug, Treppen, Türen und den Weg zum Fahrzeug. Ergänzen Sie Keller, Dachboden, Garage und schwer zugängliche Bereiche. Bei großen oder schweren Gegenständen sind Maße und bekannte Besonderheiten nützlich."],bullets:["Räume und Nebenflächen", "Große Möbel und grobe Füllmenge", "Etage, Aufzug und Treppen", "Laufweg und möglicher Ladepunkt", "Gegenstände mit besonderem Gewicht oder unklaren Inhalten"]},
      {title:"Materialarten vorher besprechen",paragraphs:["Hausrat, Möbel, Elektrogeräte und andere Materialien benötigen eine abgestimmte Behandlung. Nennen Sie besondere Stoffe, Behälter oder unbekannte Inhalte vorab. Unklare Materialien sollten nicht eigenständig vermischt oder geöffnet werden, um sie für die Anfrage zu fotografieren.","Welche Gegenstände FLOXANT übernimmt und wie der vereinbarte Abtransport erfolgt, wird vor dem Auftrag festgelegt. Dieser Ratgeber nennt keine kommunalen Annahmebedingungen oder Entsorgungspreise; diese sind für den konkreten Auftrag und Materialtyp gesondert zu klären."]},
      {title:"Räumung und Reinigung sind zwei Schritte",paragraphs:["Nach dem Entfernen der Gegenstände werden Flächen sichtbar, die vorher verdeckt waren. Legen Sie fest, ob anschließend nur freigegebene Reste entfernt oder Böden, Küche, Bad und Einbauten gereinigt werden sollen. „Leer“ und „gereinigt“ beschreiben unterschiedliche Ergebnisse.","Beispiel: Ein Keller soll geräumt werden, die Wohnung darüber zusätzlich eine Endreinigung erhalten. Dann enthält das Angebot zwei klar benannte Bereiche mit unterschiedlichen Aufgaben. Fenster oder Geräteinnenräume können bei der Wohnung ergänzt werden, ohne sie für den Kellerauftrag vorauszusetzen."]},
      {title:"Welche Angaben ein persönliches Angebot ermöglichen",paragraphs:["Nennen Sie Einsatzort, Räume, ungefähre Menge und Terminwunsch. Fotos sind freiwillig. Angaben zu Freigaben, Zugang, Trennung und gewünschtem Endzustand helfen anschließend bei einem Angebot mit verständlichem Umfang.","FLOXANT räumt vereinbarte Gegenstände in Regensburg und 75 km Umgebung. Menge, Gewicht, Materialarten, Sortieraufwand, Etagen, Laufwege, Anfahrt und zusätzliche Reinigung bestimmen den Preis. Persönliche Gegenstände und offene Entscheidungen werden vor Beginn besprochen."]},
    ],
  },
];

export function getPracticalGuide(slug: string) {
  const guide = practicalGuides.find((entry) => entry.slug === slug);
  if (!guide) throw new Error(`Unknown practical guide: ${slug}`);
  return guide;
}
