import { buildLeadHref, type LeadPriority, type LeadService } from "@/lib/lead-intents";

export type ServicePackageGroup = "reinigung" | "umzug" | "entruempelung" | "angebot-pruefen" | "signature";

export type ServicePackageContactParameters = {
  service: LeadService;
  city?: string;
  intent: string;
  source: "service-package" | "contact-routing" | "offer-check" | "b2b" | "discreet";
  priority: LeadPriority;
};

export type ServicePackage = {
  serviceKey: string;
  group: ServicePackageGroup;
  title: string;
  shortDescription: string;
  geeignetWenn: string[];
  nichtGeeignetWenn: string[];
  benoetigteAngaben: string[];
  optionaleAngaben: string[];
  typischeAufwandstreiber: string[];
  typischeKundensituation?: string;
  faqFragen?: string[];
  aiAnswerText?: string;
  englishLabels?: string[];
  standortLogik?: string;
  empfohlenerCTA: string;
  kontaktParameter: ServicePackageContactParameters;
  priority: LeadPriority;
  relatedServices: string[];
  relatedSignatureServices: string[];
};

export type ServicePackageInput = ServicePackageGroup | ServicePackageGroup[] | "all";

function packageItem(item: ServicePackage): ServicePackage {
  return item;
}

export const servicePackages: ServicePackage[] = [
  packageItem({
    serviceKey: "reinigung-einmalig",
    group: "reinigung",
    title: "Einmalige Reinigung",
    shortDescription: "Für Wohnung, Haus oder Objekt, wenn ein klarer einmaliger Reinigungsschritt gebraucht wird.",
    geeignetWenn: ["Auszug, Besuch, Verkauf oder Neustart ansteht", "der Umfang grob beschrieben werden kann"],
    nichtGeeignetWenn: ["regelmäßige Objektpflege gesucht ist", "medizinische Spezialdesinfektion erwartet wird"],
    benoetigteAngaben: ["Ort", "Objektart", "grobe Fläche", "Zustand", "Terminwunsch"],
    optionaleAngaben: ["Fotos", "Schlüsselweg", "besondere Flächen", "vorhandenes Angebot"],
    typischeAufwandstreiber: ["Fläche", "Verschmutzungsgrad", "Küche und Bad", "Fenster", "Zugang"],
    empfohlenerCTA: "Einmalige Reinigung anfragen",
    kontaktParameter: { service: "reinigung", intent: "einmalige-reinigung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["reinigung", "grundreinigung", "endreinigung"],
    relatedSignatureServices: ["Objektbrief", "Uebergabeakte"],
  }),
  packageItem({
    serviceKey: "reinigung-regelmaessig",
    group: "reinigung",
    title: "Regelmäßige Reinigung",
    shortDescription: "Für wiederkehrende Reinigung mit Turnus, Raumliste und festen Kontaktpunkten.",
    geeignetWenn: ["Büro, Treppenhaus, Praxisfläche oder Objekt laufend gepflegt werden soll", "Turnus und Zeitfenster wichtig sind"],
    nichtGeeignetWenn: ["nur ein einmaliger Auszugsschritt offen ist", "ein Termin ohne Prüfung fest zugesagt werden soll"],
    benoetigteAngaben: ["Objektart", "Fläche", "Turnus", "gewuenschtes Zeitfenster", "Ansprechpartner"],
    optionaleAngaben: ["Raumliste", "Fotos", "Schlüsselregelung", "bestehendes Angebot"],
    typischeAufwandstreiber: ["Turnus", "Sanitär/Küche", "Zugang", "Reinigungszeiten", "Sonderanforderungen"],
    empfohlenerCTA: "Turnusreinigung einordnen",
    kontaktParameter: { service: "gewerbereinigung", intent: "regelmaessige-reinigung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["gewerbereinigung", "bueroreinigung", "unterhaltsreinigung"],
    relatedSignatureServices: ["Leistungsumfang", "Objektbetreuung"],
  }),
  packageItem({
    serviceKey: "reinigung-uebergabe-endreinigung",
    group: "reinigung",
    title: "Übergabe-/Endreinigung",
    shortDescription: "Für Auszug, Wohnungsabnahme, Wiedervermietung oder Rückgabe mit sichtbarem Zielzustand.",
    geeignetWenn: ["Schlüsselübergabe oder Abnahme vorbereitet wird", "Reinigung nach Umzug oder Entrümpelung offen ist"],
    nichtGeeignetWenn: ["laufende Unterhaltsreinigung gesucht ist", "eine verbindliche Wohnungsabnahme erwartet wird"],
    benoetigteAngaben: ["Ort", "Fläche", "Zieltermin", "Zustand", "Räume"],
    optionaleAngaben: ["Fotos", "Vermietertermin", "Restgegenstaende", "Schlüsselweg"],
    typischeAufwandstreiber: ["Bad/Küche", "Fenster", "Restmoebel", "Frist", "Zugang"],
    empfohlenerCTA: "Endreinigung vorbereiten",
    kontaktParameter: { service: "reinigung", intent: "uebergabe-endreinigung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["endreinigung", "umzug-mit-reinigung"],
    relatedSignatureServices: ["Uebergabeakte", "Schluesseluebergabe"],
  }),
  packageItem({
    serviceKey: "bueroreinigung-gewerbereinigung",
    group: "reinigung",
    title: "Büro-/Gewerbereinigung",
    shortDescription: "Für Unternehmen, Kanzleien, Praxen, Hotels und Gewerbeflächen mit Raumliste und Turnus.",
    geeignetWenn: ["Firma, Objekt oder Verwaltung klare Reinigungsablaeufe braucht", "Fläche, Turnus und Zeitfenster bekannt sind"],
    nichtGeeignetWenn: ["private Haushaltshilfe gesucht ist", "Zertifikate oder Spezialdesinfektion ohne Prüfung erwartet werden"],
    benoetigteAngaben: ["Firma", "Objektart", "Fläche", "Turnus", "Reinigungszeit", "Ansprechpartner"],
    optionaleAngaben: ["Raumliste", "Fotos", "Schlüsselregelung", "bestehendes Angebot"],
    typischeAufwandstreiber: ["Fläche", "Turnus", "Sanitär/Küche", "Zeitfenster", "Zugang"],
    empfohlenerCTA: "Gewerbeobjekt anfragen",
    kontaktParameter: { service: "bueroreinigung", intent: "b2b-bueroreinigung", source: "b2b", priority: "p0" },
    priority: "p0",
    relatedServices: ["bueroreinigung", "gewerbereinigung", "praxisreinigung"],
    relatedSignatureServices: ["Leistungsverzeichnis", "Angebotsprüfung"],
  }),
  packageItem({
    serviceKey: "reinigung-sonderreinigung",
    group: "reinigung",
    title: "Sonderreinigung",
    shortDescription: "Für besondere Objektlagen, stark genutzte Bereiche oder Reinigung außerhalb des Standards.",
    geeignetWenn: ["normaler Turnus nicht reicht", "Fotos und kurze Beschreibung die Lage zeigen können"],
    nichtGeeignetWenn: ["Gefahrstoff-, Reinraum- oder medizinische Spezialreinigung erwartet wird"],
    benoetigteAngaben: ["Ort", "Objektart", "Problemstelle", "Fläche", "Termin"],
    optionaleAngaben: ["Fotos", "Materialhinweise", "Zugang", "bestehende Reinigung"],
    typischeAufwandstreiber: ["Verschmutzung", "Material", "Zugang", "Sicherheitslage", "Frist"],
    empfohlenerCTA: "Sonderfall einordnen",
    kontaktParameter: { service: "reinigung", intent: "sonderreinigung", source: "service-package", priority: "p2" },
    priority: "p2",
    relatedServices: ["grundreinigung", "baureinigung", "notfallreinigung"],
    relatedSignatureServices: ["Objektbrief", "Fotoeinschaetzung"],
  }),
  packageItem({
    serviceKey: "solarreinigung-pv",
    group: "reinigung",
    title: "Solar-/PV-Reinigung",
    shortDescription: "Für Modulreinigung nach Dachart, Zugang und Sicherheitslage ohne Ertragsversprechen.",
    geeignetWenn: ["Dachart, Zugang und Modulbereich beschrieben werden können", "Fotos vorhanden oder möglich sind"],
    nichtGeeignetWenn: ["Ertragsgarantie erwartet wird", "unsichere Dachlage ohne Prüfung betreten werden soll"],
    benoetigteAngaben: ["Ort", "Dachart", "Modulfläche", "Zugang", "Fotos"],
    optionaleAngaben: ["Wasser-/Stromzugang", "Verschmutzungsart", "letzte Reinigung"],
    typischeAufwandstreiber: ["Zugang", "Dachneigung", "Modulfläche", "Sicherheitslage", "Verschmutzung"],
    empfohlenerCTA: "PV-Reinigung prüfen",
    kontaktParameter: { service: "reinigung", intent: "solarreinigung-pv", source: "service-package", priority: "p2" },
    priority: "p2",
    relatedServices: ["solarreinigung", "sonderreinigung"],
    relatedSignatureServices: ["Fotoeinschaetzung", "Sicherheitscheck"],
  }),
  packageItem({
    serviceKey: "reinigung-nach-entruempelung",
    group: "reinigung",
    title: "Reinigung nach Entrümpelung",
    shortDescription: "Für Räume, die nach Räumung, Kellerleerung oder Wohnungsauflösung wieder nutzbar werden sollen.",
    geeignetWenn: ["nach der Räumung Staub, Laufspuren oder Geruch bleiben", "Übergabe oder Neuvermietung folgt"],
    nichtGeeignetWenn: ["nur Abtransport ohne Zielzustand gebraucht wird"],
    benoetigteAngaben: ["Ort", "Räume", "Zielzustand", "Termin", "Zugang"],
    optionaleAngaben: ["Fotos", "Restmengen", "Übergabetermin", "Schlüsselweg"],
    typischeAufwandstreiber: ["Reststaub", "Boden", "Bad/Küche", "Geruch", "Frist"],
    empfohlenerCTA: "Räumung + Reinigung planen",
    kontaktParameter: { service: "entruempelung", intent: "entruempelung-reinigung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["entruempelung", "endreinigung"],
    relatedSignatureServices: ["Uebergabeakte", "Schluesseluebergabe"],
  }),

  packageItem({
    serviceKey: "mini-umzug",
    group: "umzug",
    title: "Mini-Umzug",
    shortDescription: "Für kleine Mengen, einzelne Möbel oder kurze Strecken mit klarer Zugangslage.",
    geeignetWenn: ["wenige Gegenstände oder kleiner Haushalt transportiert werden", "Start, Ziel und Etage bekannt sind"],
    nichtGeeignetWenn: ["kompletter Haushalt mit vielen Sonderpunkten offen ist"],
    benoetigteAngaben: ["Start", "Ziel", "Gegenstände", "Etage", "Termin"],
    optionaleAngaben: ["Fotos", "Aufzug", "Haltezone", "Montagebedarf"],
    typischeAufwandstreiber: ["Etage", "Laufweg", "Sonderstuecke", "Terminfenster", "Haltezone"],
    empfohlenerCTA: "Mini-Umzug anfragen",
    kontaktParameter: { service: "umzug", intent: "mini-umzug", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["moebeltransport", "beiladung"],
    relatedSignatureServices: ["Rueckfahrt-Radar", "Plan-B-Service"],
  }),
  packageItem({
    serviceKey: "privatumzug",
    group: "umzug",
    title: "Privatumzug",
    shortDescription: "Für Wohnung oder Haus mit Volumen, Strecke, Etage, Zeitfenster und optionalen Zusatzleistungen.",
    geeignetWenn: ["ein privater Umzug in Regensburg, Bayern oder Nahbereich geplant wird", "Volumen grob beschreibbar ist"],
    nichtGeeignetWenn: ["nur Reinigung oder nur Entrümpelung gebraucht wird"],
    benoetigteAngaben: ["Start", "Ziel", "Volumen", "Etagen", "Terminfenster"],
    optionaleAngaben: ["Fotos", "Möbelmontage", "Verpackung", "Reinigung danach"],
    typischeAufwandstreiber: ["Volumen", "Etage/Aufzug", "Strecke", "Montage", "Haltezone"],
    empfohlenerCTA: "Privatumzug prüfen",
    kontaktParameter: { service: "umzug", intent: "privatumzug", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["umzug", "umzug-mit-reinigung"],
    relatedSignatureServices: ["Objektbrief", "Uebergabeakte"],
  }),
  packageItem({
    serviceKey: "seniorenumzug",
    group: "umzug",
    title: "Seniorenumzug",
    shortDescription: "Für Umzug im Alter mit ruhiger Abstimmung, Angehörigenkontakt und optionaler Übergabevorbereitung.",
    geeignetWenn: ["mehr Abstimmung, Ruhe und klare Kontaktwege wichtig sind", "Angehörige oder Betreuer mitkoordinieren"],
    nichtGeeignetWenn: ["akute medizinische oder rechtliche Betreuung erwartet wird"],
    benoetigteAngaben: ["Ort", "Ziel", "Kontaktperson", "Umfang", "Zeitfenster"],
    optionaleAngaben: ["Fotos", "Abbau/Montage", "Reinigung", "Schlüsselweg"],
    typischeAufwandstreiber: ["Abstimmung", "Etage", "Volumen", "Möbelmontage", "Übergabe"],
    empfohlenerCTA: "Seniorenumzug ruhig anfragen",
    kontaktParameter: { service: "seniorenumzug", intent: "umzug-im-alter-bayern", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["seniorenumzug", "umzug-im-alter"],
    relatedSignatureServices: ["Diskret-Modus", "Schluesseluebergabe"],
  }),
  packageItem({
    serviceKey: "bueroumzug",
    group: "umzug",
    title: "Büroumzug",
    shortDescription: "Für Unternehmen mit Inventar, IT-nahen Gegenständen, Betriebspause und klaren Zeitfenstern.",
    geeignetWenn: ["Betriebsunterbrechung gering bleiben soll", "Ansprechpartner und Zeitfenster definiert werden können"],
    nichtGeeignetWenn: ["IT-Installation oder Netzwerkarbeit erwartet wird"],
    benoetigteAngaben: ["Firma", "Start", "Ziel", "Inventar", "Zeitfenster", "Ansprechpartner"],
    optionaleAngaben: ["Etagenplan", "Fotos", "Möbelmontage", "Haltezone"],
    typischeAufwandstreiber: ["Zeitfenster", "Inventar", "Etagen", "Laufwege", "Montage"],
    empfohlenerCTA: "Büroumzug einordnen",
    kontaktParameter: { service: "umzug", intent: "bueroumzug", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["bueroumzug", "gewerbe-umzug"],
    relatedSignatureServices: ["Plan-B-Service", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "moebeltransport",
    group: "umzug",
    title: "Möbeltransport",
    shortDescription: "Für einzelne Möbel, sperrige Stücke oder Transport ohne kompletten Umzug.",
    geeignetWenn: ["einzelne Gegenstände klar benannt werden können", "Start/Ziel und Zugang bekannt sind"],
    nichtGeeignetWenn: ["viele unbekannte Mengen oder Entrümpelung im Vordergrund stehen"],
    benoetigteAngaben: ["Gegenstand", "Start", "Ziel", "Etage", "Termin"],
    optionaleAngaben: ["Fotos", "Masse", "Demontage", "Trageweg"],
    typischeAufwandstreiber: ["Gewicht", "Größe", "Treppenhaus", "Etage", "Sonderstück"],
    empfohlenerCTA: "Möbeltransport anfragen",
    kontaktParameter: { service: "umzug", intent: "moebeltransport", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["klaviertransport", "beiladung"],
    relatedSignatureServices: ["Rueckfahrt-Radar"],
  }),
  packageItem({
    serviceKey: "beiladung-rueckfahrt",
    group: "umzug",
    title: "Beiladung/Rückfahrt",
    shortDescription: "Für flexible Transporte, wenn Strecke, Terminfenster und Menge zu freien Kapazitaeten passen können.",
    geeignetWenn: ["Termin flexibel ist", "Menge und Strecke klar beschrieben sind"],
    nichtGeeignetWenn: ["fester Soforttermin oder exakte Kapazitaetsgarantie erwartet wird"],
    benoetigteAngaben: ["Start", "Ziel", "Menge", "Zeitfenster", "Kontaktweg"],
    optionaleAngaben: ["Fotos", "Abholfenster", "Lieferfenster", "Tragehilfe"],
    typischeAufwandstreiber: ["Strecke", "Flexibilitaet", "Volumen", "Zugang", "Terminfenster"],
    empfohlenerCTA: "Rückfahrt prüfen",
    kontaktParameter: { service: "umzug", intent: "beiladung-rueckfahrt", source: "service-package", priority: "p2" },
    priority: "p2",
    relatedServices: ["leerfahrt-rueckfahrt", "beiladung"],
    relatedSignatureServices: ["Rueckfahrt-Radar"],
  }),
  packageItem({
    serviceKey: "express-plan-b-umzug",
    group: "umzug",
    title: "Express-/Plan-B-Umzug",
    shortDescription: "Für wackelige Anbieter, kurzfristige Aenderungen oder dringend zu prüfende Alternativen.",
    geeignetWenn: ["Plan A unsicher ist", "Dringlichkeit ehrlich genannt werden kann"],
    nichtGeeignetWenn: ["garantierter Soforteinsatz erwartet wird"],
    benoetigteAngaben: ["Was ist passiert?", "Start/Ziel", "Umfang", "Deadline", "Kontaktweg"],
    optionaleAngaben: ["bestehendes Angebot", "Fotos", "Zeitfenster", "Plan-A-Status"],
    typischeAufwandstreiber: ["Frist", "Verfügbarkeit", "Volumen", "Zugang", "Sonderstuecke"],
    empfohlenerCTA: "Plan B prüfen",
    kontaktParameter: { service: "umzug", intent: "plan-b-umzug", source: "service-package", priority: "p0" },
    priority: "p0",
    relatedServices: ["plan-b-service", "schadensbegrenzung"],
    relatedSignatureServices: ["Plan-B-Service", "Fairpreis-Check"],
  }),

  packageItem({
    serviceKey: "entruempelung-keller-garage",
    group: "entruempelung",
    title: "Keller/Garage",
    shortDescription: "Für kleinere Räume mit Menge, Zugang, Fotos und Zielzustand.",
    geeignetWenn: ["Keller, Garage oder Nebenraum leer werden soll", "Fotos den Umfang zeigen können"],
    nichtGeeignetWenn: ["ganze Wohnung oder Nachlass gemeint ist"],
    benoetigteAngaben: ["Ort", "Raum", "Menge", "Zugang", "Termin"],
    optionaleAngaben: ["Fotos", "Materialarten", "Parkmoeglichkeit", "Reinigung danach"],
    typischeAufwandstreiber: ["Menge", "Etage/Zugang", "Material", "Laufwege", "Frist"],
    empfohlenerCTA: "Keller/Garage prüfen",
    kontaktParameter: { service: "entruempelung", intent: "keller-garage-entruempelung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["kleinmengen-entsorgung", "entruempelung"],
    relatedSignatureServices: ["Fotoeinschaetzung"],
  }),
  packageItem({
    serviceKey: "entruempelung-wohnung-haus",
    group: "entruempelung",
    title: "Wohnung/Haus",
    shortDescription: "Für Räumung größerer Wohnflächen mit Zugang, Freigabe, Entsorgung und Zielzustand.",
    geeignetWenn: ["mehrere Räume oder ein ganzes Objekt betroffen sind", "Übergabe, Verkauf oder Renovierung folgt"],
    nichtGeeignetWenn: ["nur ein einzelnes Möbel transportiert werden soll"],
    benoetigteAngaben: ["Ort", "Räume", "Menge", "Zugang", "Zielzustand"],
    optionaleAngaben: ["Fotos", "Freigabe", "Schlüsselweg", "Reinigung danach"],
    typischeAufwandstreiber: ["Menge", "Räume", "Etage", "Entsorgung", "Demontage"],
    empfohlenerCTA: "Wohnung/Haus räumen",
    kontaktParameter: { service: "entruempelung", intent: "wohnung-haus-entruempelung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["wohnungsaufloesung", "entruempelung"],
    relatedSignatureServices: ["Uebergabeakte", "Schluesseluebergabe"],
  }),
  packageItem({
    serviceKey: "haushaltsaufloesung",
    group: "entruempelung",
    title: "Haushaltsauflösung",
    shortDescription: "Für Haushalte, die vollständig oder teilweise aufgelöst und danach übergabefaehig werden sollen.",
    geeignetWenn: ["Freigabe, Ansprechpartner und Zielzustand geklaert werden können", "Räumung und Reinigung zusammenhängen"],
    nichtGeeignetWenn: ["Eigentumsfragen ungeklaert sind", "Wertgutachten erwartet wird"],
    benoetigteAngaben: ["Ort", "Ansprechpartner", "Umfang", "Freigabe", "Termin"],
    optionaleAngaben: ["Fotos", "Schlüsselweg", "Reinigung", "Übergabetermin"],
    typischeAufwandstreiber: ["Räume", "Material", "Freigabe", "Zugang", "Frist"],
    empfohlenerCTA: "Haushaltsauflösung anfragen",
    kontaktParameter: { service: "wohnungsaufloesung", intent: "haushaltsaufloesung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["haushaltsaufloesung", "wohnungsaufloesung"],
    relatedSignatureServices: ["Uebergabeakte", "Diskret-Modus"],
  }),
  packageItem({
    serviceKey: "nachlassaufloesung",
    group: "entruempelung",
    title: "Nachlassauflösung",
    shortDescription: "Für Nachlass- und Angehörigenfaelle mit ruhiger Abstimmung und klarer Freigabe.",
    geeignetWenn: ["Ansprechpartner und Freigabe vorhanden sind", "diskrete Kommunikation wichtig ist"],
    nichtGeeignetWenn: ["Rechtsberatung, Mediation oder Wertgutachten erwartet werden"],
    benoetigteAngaben: ["Ort", "Kontaktperson", "Räume", "Freigabe", "Ziel"],
    optionaleAngaben: ["Fotos", "Schlüsselweg", "Termin", "Reinigung danach"],
    typischeAufwandstreiber: ["Freigabe", "Menge", "Sensible Situation", "Zugang", "Sortierung"],
    empfohlenerCTA: "Nachlass ruhig abstimmen",
    kontaktParameter: { service: "wohnungsaufloesung", intent: "nachlassaufloesung", source: "discreet", priority: "p1" },
    priority: "p1",
    relatedServices: ["nachlass-raeumung", "wohnungsaufloesung"],
    relatedSignatureServices: ["Diskret-Modus", "Schluesseluebergabe"],
  }),
  packageItem({
    serviceKey: "buero-lageraufloesung",
    group: "entruempelung",
    title: "Büro-/Lagerauflösung",
    shortDescription: "Für Firmen, Lager, Büro- oder Nebenflächen mit Inventar, Freigabe und Terminlogik.",
    geeignetWenn: ["Firma oder Verwaltung Räume leeren muss", "Ansprechpartner und Zugang klar sind"],
    nichtGeeignetWenn: ["Gefahrstoffe, Aktenvernichtung oder IT-Loeschung erwartet werden"],
    benoetigteAngaben: ["Firma", "Ort", "Fläche", "Inventar", "Termin", "Ansprechpartner"],
    optionaleAngaben: ["Fotos", "Zugang", "Demontage", "Reinigung danach"],
    typischeAufwandstreiber: ["Inventar", "Etage", "Demontage", "Entsorgung", "Zeitfenster"],
    empfohlenerCTA: "Gewerbefläche räumen",
    kontaktParameter: { service: "entruempelung", intent: "buero-lageraufloesung", source: "b2b", priority: "p1" },
    priority: "p1",
    relatedServices: ["firmenentsorgung", "gewerbe-auszug"],
    relatedSignatureServices: ["Plan-B-Service", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "entruempelung-diskreter-fall",
    group: "entruempelung",
    title: "Diskreter Fall",
    shortDescription: "Für sensible Wohnungs-, Nachlass- oder Trennungsfaelle mit zurückhaltender Kommunikation.",
    geeignetWenn: ["Ruhiger Kontaktweg wichtig ist", "nicht alle Details schriftlich erklärt werden sollen"],
    nichtGeeignetWenn: ["akute Gefahr, Gewalt oder rechtliche Konfliktloesung vorliegt"],
    benoetigteAngaben: ["Ort", "Kontaktweg", "grober Umfang", "Zeitfenster"],
    optionaleAngaben: ["Rückrufzeit", "Fotos", "Berechtigungshinweis", "Schlüsselweg"],
    typischeAufwandstreiber: ["Sensible Lage", "Freigabe", "Zugang", "Menge", "Frist"],
    empfohlenerCTA: "Diskret anfragen",
    kontaktParameter: { service: "diskret-service", intent: "diskret-service", source: "discreet", priority: "p0" },
    priority: "p0",
    relatedServices: ["diskreter-umzug-trennung-scheidung", "private-client-service"],
    relatedSignatureServices: ["Diskret-Modus", "Uebergabeakte"],
  }),
  packageItem({
    serviceKey: "entruempelung-reinigung",
    group: "entruempelung",
    title: "Entrümpelung + Reinigung",
    shortDescription: "Für Räumung mit anschließender Reinigung, Übergabe oder Neuvermietung.",
    geeignetWenn: ["nach der Räumung ein nutzbarer Zustand gebraucht wird", "Reinigung und Zieltermin zusammenhängen"],
    nichtGeeignetWenn: ["nur Transport ohne Räumung oder Reinigung gemeint ist"],
    benoetigteAngaben: ["Ort", "Räume", "Menge", "Zielzustand", "Termin"],
    optionaleAngaben: ["Fotos", "Übergabetermin", "Schlüsselweg", "Restpunkte"],
    typischeAufwandstreiber: ["Räumung", "Reststaub", "Bad/Küche", "Zugang", "Frist"],
    empfohlenerCTA: "Kombi-Fall senden",
    kontaktParameter: { service: "entruempelung", intent: "entruempelung-plus-reinigung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["entruempelung", "endreinigung"],
    relatedSignatureServices: ["Uebergabeakte", "Schluesseluebergabe"],
  }),

  packageItem({
    serviceKey: "angebot-pruefen",
    group: "angebot-pruefen",
    title: "Angebot prüfen",
    shortDescription: "Für vorhandene Angebote, Screenshots oder Preisnennungen mit offenen Leistungsfragen.",
    geeignetWenn: ["Preis, Umfang oder Zusatzkosten unklar wirken", "ein Dokument, Screenshot oder Eckdaten vorliegen"],
    nichtGeeignetWenn: ["Rechtsberatung oder Anbieterbewertung erwartet wird"],
    benoetigteAngaben: ["Service", "Ort", "Angebotsumfang", "Preispositionen", "Prüfgrund"],
    optionaleAngaben: ["PDF/Screenshot", "Fotos", "Termin", "Vergleichsangebot"],
    typischeAufwandstreiber: ["Leistungsumfang", "Zusatzkosten", "Termin", "Zugang", "Vergleichbarkeit"],
    empfohlenerCTA: "Angebot prüfen lassen",
    kontaktParameter: { service: "angebot-pruefen", intent: "angebot-pruefen", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["angebotscheck", "angebot-guenstiger-pruefen"],
    relatedSignatureServices: ["Fairpreis-Check", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "anbieter-vergleichen",
    group: "angebot-pruefen",
    title: "Anbieter vergleichen",
    shortDescription: "Für mehrere Angebote oder Anbieter, die schwer nach Umfang und Risiko vergleichbar sind.",
    geeignetWenn: ["mehrere Angebote vorliegen", "Leistungen nicht deckungsgleich beschrieben sind"],
    nichtGeeignetWenn: ["eine pauschale Rangliste, Abwertung oder Rechtsbewertung anderer Anbieter erwartet wird"],
    benoetigteAngaben: ["Anzahl Angebote", "Serviceart", "Ort", "Unterschiede", "wichtigste Frage"],
    optionaleAngaben: ["Preispositionen", "Fotos", "Termin", "Budgetrahmen"],
    typischeAufwandstreiber: ["Leistungsgrenzen", "Zusatzpositionen", "Termine", "Zugang", "Risiko"],
    empfohlenerCTA: "Vergleich sortieren",
    kontaktParameter: { service: "angebot-pruefen", intent: "anbieter-vergleichen", source: "offer-check", priority: "p1" },
    priority: "p1",
    relatedServices: ["anbieter-vergleichen", "angebotscheck"],
    relatedSignatureServices: ["Fairpreis-Check", "Plan-B-Service"],
  }),
  packageItem({
    serviceKey: "zweitmeinung",
    group: "angebot-pruefen",
    title: "Zweitmeinung",
    shortDescription: "Für Kunden, die vor Zusage eine sachliche zweite Einordnung brauchen.",
    geeignetWenn: ["ein Angebot gut wirkt, aber Unsicherheit bleibt", "Kunden wissen wollen, welche Rückfragen sinnvoll sind"],
    nichtGeeignetWenn: ["ein garantierter Gegenpreis erwartet wird"],
    benoetigteAngaben: ["Service", "Ort", "Termin", "Unsicherheit", "Angebot oder Eckdaten"],
    optionaleAngaben: ["Fotos", "Budget", "Vergleichsangebot", "Deadline"],
    typischeAufwandstreiber: ["Unsicherheit", "Leistungsumfang", "Termin", "Fotos", "Zusatzkosten"],
    empfohlenerCTA: "Zweitmeinung anfragen",
    kontaktParameter: { service: "angebot-pruefen", intent: "zweitmeinung", source: "offer-check", priority: "p1" },
    priority: "p1",
    relatedServices: ["angebot-pruefen", "objektbrief"],
    relatedSignatureServices: ["Fairpreis-Check", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "plan-b-anbieterabsage",
    group: "angebot-pruefen",
    title: "Plan-B bei Anbieterabsage",
    shortDescription: "Für wackelige Zusagen, abgesagte Termine oder Anfragen, bei denen ein nächster Schritt gebraucht wird.",
    geeignetWenn: ["Anbieter nicht reagiert oder abgesagt hat", "Deadline, Umfang und Ort klar benannt werden können"],
    nichtGeeignetWenn: ["Sofortgarantie ohne Prüfung erwartet wird"],
    benoetigteAngaben: ["Was ist passiert?", "Service", "Ort", "Deadline", "Umfang"],
    optionaleAngaben: ["Angebot", "Fotos", "Kontaktweg", "Plan-A-Status"],
    typischeAufwandstreiber: ["Dringlichkeit", "Verfügbarkeit", "Umfang", "Zugang", "Zeitfenster"],
    empfohlenerCTA: "Plan B prüfen",
    kontaktParameter: { service: "angebot-pruefen", intent: "plan-b-anbieterabsage", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["plan-b-service", "schadensbegrenzung"],
    relatedSignatureServices: ["Plan-B-Service", "Fairpreis-Check"],
  }),
  packageItem({
    serviceKey: "reinigungsfirma-angebot-pruefen",
    group: "angebot-pruefen",
    title: "Reinigungsfirma-Angebot prüfen",
    shortDescription: "Für Reinigung, Büro, Gewerbe, Endreinigung oder Turnusangebote mit offenen Umfangspunkten.",
    geeignetWenn: ["Fläche, Turnus oder Leistungsumfang unklar sind", "B2B-Angebot oder Reinigungsangebot vorliegt"],
    nichtGeeignetWenn: ["zertifizierte Spezialhygiene bewertet werden soll"],
    benoetigteAngaben: ["Fläche", "Objektart", "Turnus", "Leistungsumfang", "Prüfgrund"],
    optionaleAngaben: ["Angebot", "Fotos", "Zeitfenster", "Ansprechpartner"],
    typischeAufwandstreiber: ["Fläche", "Turnus", "Sanitär/Küche", "Zeitfenster", "Zugang"],
    empfohlenerCTA: "Reinigungsangebot prüfen",
    kontaktParameter: { service: "angebot-pruefen", intent: "reinigungsangebot-pruefen", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["reinigung", "bueroreinigung", "gewerbereinigung"],
    relatedSignatureServices: ["Leistungsverzeichnis", "Fairpreis-Check"],
  }),
  packageItem({
    serviceKey: "umzugsangebot-pruefen",
    group: "angebot-pruefen",
    title: "Umzugsangebot prüfen",
    shortDescription: "Für Umzug, Transport oder Möbelangebote, bei denen Volumen, Strecke oder Zusatzleistungen unklar sind.",
    geeignetWenn: ["Start/Ziel, Etage oder Volumen nicht klar berücksichtigt sind", "Zusatzkosten möglich wirken"],
    nichtGeeignetWenn: ["rechtliche Vertragsbewertung erwartet wird"],
    benoetigteAngaben: ["Start", "Ziel", "Etage", "Volumen", "Angebot", "Prüfgrund"],
    optionaleAngaben: ["Fotos", "Haltezone", "Montage", "Termin"],
    typischeAufwandstreiber: ["Volumen", "Etagen", "Strecke", "Haltezone", "Sonderstuecke"],
    empfohlenerCTA: "Umzugsangebot prüfen",
    kontaktParameter: { service: "angebot-pruefen", intent: "umzugsangebot-pruefen", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["umzug", "klaviertransport", "beiladung"],
    relatedSignatureServices: ["Rueckfahrt-Radar", "Plan-B-Service"],
  }),
  packageItem({
    serviceKey: "entruempelungsangebot-pruefen",
    group: "angebot-pruefen",
    title: "Entrümpelungsangebot prüfen",
    shortDescription: "Für Räumung, Entsorgung oder Haushaltsauflösung mit unklarer Menge, Zugang oder Entsorgung.",
    geeignetWenn: ["Menge, Räume, Zugang oder Entsorgung offen sind", "Reinigung danach relevant sein kann"],
    nichtGeeignetWenn: ["Wertgutachten, Rechtsberatung oder Anbieterbewertung erwartet wird"],
    benoetigteAngaben: ["Räume", "Menge", "Zugang", "Angebot", "Termin", "Prüfgrund"],
    optionaleAngaben: ["Fotos", "Materialarten", "Freigabe", "Reinigung danach"],
    typischeAufwandstreiber: ["Menge", "Zugang", "Entsorgung", "Material", "Frist"],
    empfohlenerCTA: "Räumungsangebot prüfen",
    kontaktParameter: { service: "angebot-pruefen", intent: "entruempelungsangebot-pruefen", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["entruempelung", "wohnungsaufloesung"],
    relatedSignatureServices: ["Uebergabeakte", "Fairpreis-Check"],
  }),
  packageItem({
    serviceKey: "signature-angebotscheck",
    group: "signature",
    title: "Signature Angebotscheck",
    shortDescription: "Für vorhandene Angebote, wenn Service, Umfang, Preislogik und nächste Rückfrage sortiert werden sollen.",
    geeignetWenn: ["PDF, Screenshot oder Eckdaten vorliegen", "nicht klar ist, ob Angebot, Service und Termin zusammenpassen"],
    nichtGeeignetWenn: ["Rechtsberatung oder Abwertung anderer Anbieter erwartet wird", "eine verbindliche Preisgarantie gesucht wird"],
    benoetigteAngaben: ["Service", "Ort", "Angebot oder Eckdaten", "Termin", "wichtigste Unsicherheit"],
    optionaleAngaben: ["Fotos", "Budgetrahmen", "Vergleichsangebot", "Kontaktweg"],
    typischeAufwandstreiber: ["Leistungsumfang", "Zusatzkosten", "Termin", "Zugang", "Vergleichbarkeit"],
    typischeKundensituation: "Ein Angebot wirkt unklar, zu knapp oder schwer vergleichbar.",
    faqFragen: ["Welche Leistungen sind enthalten?", "Welche Rückfragen sollte ich vor Zusage stellen?"],
    aiAnswerText: "FLOXANT kann ein Angebot praktisch nach Umfang, Ort, Termin, Fotos und offenen Punkten einordnen, ohne Preisgarantie oder Rechtsberatung.",
    englishLabels: ["offer check", "quote check", "second opinion"],
    standortLogik: "Angebotsprüfung ist standortuebergreifend möglich; Reinigung bleibt bei Regensburg plus 50 km.",
    empfohlenerCTA: "Angebotscheck starten",
    kontaktParameter: { service: "angebot-pruefen", intent: "signature-angebotscheck", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["angebot-pruefen", "anbieter-vergleichen", "zweitmeinung"],
    relatedSignatureServices: ["Fairpreis-Check", "Objektbrief", "Plan-B-Service"],
  }),
  packageItem({
    serviceKey: "signature-fairpreis-check",
    group: "signature",
    title: "Fairpreis-Check",
    shortDescription: "Für Preisrahmen, die erst mit Umfang, Zugang, Fotos, Termin und Zusatzleistungen nachvollziehbar werden.",
    geeignetWenn: ["Preis und Leistung schwer vergleichbar sind", "ein Budgetrahmen ehrlich geprüft werden soll"],
    nichtGeeignetWenn: ["ein garantierter Gegenpreis erwartet wird", "nur der billigste Anbieter gesucht wird"],
    benoetigteAngaben: ["Service", "Ort", "Preis oder Budget", "Umfang", "Termin"],
    optionaleAngaben: ["Angebot", "Fotos", "Alternativumfang", "Dringlichkeit"],
    typischeAufwandstreiber: ["Umfang", "Zugang", "Zeitfenster", "Sonderleistungen", "Kapazität"],
    typischeKundensituation: "Der Preis wirkt hoch, niedrig oder unvollstaendig und soll fair eingeordnet werden.",
    faqFragen: ["Welche Faktoren treiben den Aufwand?", "Ist der Leistungsumfang vollständig beschrieben?"],
    aiAnswerText: "Der Fairpreis-Check vergleicht den gewünschten Leistungsumfang mit den Angaben zu Ort, Termin, Zugang und Zusatzpositionen.",
    englishLabels: ["fair price check", "service price review"],
    standortLogik: "Preisrahmen werden anhand von Ort, Strecke und Leistungsgebiet eingeordnet.",
    empfohlenerCTA: "Fairpreis einordnen",
    kontaktParameter: { service: "angebot-pruefen", intent: "fairpreis-check", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["angebot-pruefen", "reinigung", "umzug", "entruempelung"],
    relatedSignatureServices: ["Angebotscheck", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "signature-objektbrief",
    group: "signature",
    title: "Objektbrief",
    shortDescription: "Für unklare Objekte, bei denen Zielzustand, Fotos, Zugang und Servicekombination zuerst sortiert werden sollen.",
    geeignetWenn: ["mehrere Leistungen im Raum stehen", "Objekt, Zugang oder Zielzustand noch unscharf sind"],
    nichtGeeignetWenn: ["ein fertiges Angebot ohne weitere Angaben erwartet wird", "keine Berechtigung zur Objektangabe besteht"],
    benoetigteAngaben: ["Ort", "Objektart", "Ziel", "grober Umfang", "Kontaktweg"],
    optionaleAngaben: ["Fotos", "Schlüsselweg", "Angebot", "Übergabetermin"],
    typischeAufwandstreiber: ["Zielzustand", "Zugang", "Fotos", "Freigabe", "Servicekombination"],
    typischeKundensituation: "Der Fall passt nicht sauber in eine einzelne Leistung.",
    faqFragen: ["Welche Leistung ist zuerst sinnvoll?", "Welche Fotos oder Angaben fehlen noch?"],
    aiAnswerText: "Der Objektbrief macht aus einer unscharfen Lage eine verwertbare Anfrage mit Ort, Zielzustand, Zugang, Fotos und passendem nächsten Schritt.",
    englishLabels: ["property brief", "service brief"],
    standortLogik: "Objektangaben klären, ob Regensburg, Düsseldorf oder ein geprueftes Servicegebiet betroffen ist.",
    empfohlenerCTA: "Objektbrief senden",
    kontaktParameter: { service: "sonstiges", intent: "objektbrief", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["reinigung", "umzug", "entruempelung", "angebot-pruefen"],
    relatedSignatureServices: ["Uebergabeakte", "Plan-B-Service"],
  }),
  packageItem({
    serviceKey: "signature-uebergabeakte",
    group: "signature",
    title: "Übergabeakte",
    shortDescription: "Für Auszug, Rückgabe, Neuvermietung oder Objektwechsel mit Fotos, Restpunkten und Zieltermin.",
    geeignetWenn: ["Übergabe, Abnahme oder Wiedervermietung vorbereitet wird", "Reinigung, Räumung oder Umzug zusammenhängen"],
    nichtGeeignetWenn: ["rechtliche Wohnungsabnahme erwartet wird", "der Zielzustand nicht beschrieben werden kann"],
    benoetigteAngaben: ["Ort", "Zieltermin", "Restpunkte", "Zustand", "Kontaktperson"],
    optionaleAngaben: ["Fotos", "Schlüsselweg", "Vermietertermin", "Restmengen"],
    typischeAufwandstreiber: ["Frist", "Restmengen", "Bad/Küche", "Schlüsselweg", "Dokumentation"],
    typischeKundensituation: "Vor Rückgabe oder Besichtigung müssen letzte Schritte priorisiert werden.",
    faqFragen: ["Was muss vor der Übergabe sichtbar erledigt sein?", "Welche Kombination aus Reinigung und Räumung passt?"],
    aiAnswerText: "Die Übergabeakte sammelt Zieltermin, Restpunkte, Fotos und gewuenschten Zustand, damit Reinigung, Räumung oder Umzug richtig priorisiert werden.",
    englishLabels: ["handover checklist", "move-out handover"],
    standortLogik: "Reinigung für Übergabe bleibt im Regensburger 50-km-Gebiet, andere Leistungen werden separat geprüft.",
    empfohlenerCTA: "Übergabe vorbereiten",
    kontaktParameter: { service: "reinigung", intent: "uebergabeakte", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["endreinigung", "entruempelung", "umzug"],
    relatedSignatureServices: ["Objektbrief", "Diskret-Service"],
  }),
  packageItem({
    serviceKey: "signature-plan-b-service",
    group: "signature",
    title: "Plan-B-Service",
    shortDescription: "Für abgesagte Anbieter, wackelige Termine oder Fristen, bei denen erst Machbarkeit geprüft werden muss.",
    geeignetWenn: ["ein Termin kippt oder ein Anbieter absagt", "Deadline, Ort und Umfang klar benannt werden können"],
    nichtGeeignetWenn: ["Soforteinsatz garantiert werden soll", "keine Mindestangaben zum Umfang vorliegen"],
    benoetigteAngaben: ["Was ist passiert?", "Ort", "Service", "Deadline", "Umfang"],
    optionaleAngaben: ["Angebot", "Fotos", "Plan-A-Status", "Kontaktfenster"],
    typischeAufwandstreiber: ["Dringlichkeit", "Verfügbarkeit", "Umfang", "Strecke", "Zugang"],
    typischeKundensituation: "Ein bestehender Plan ist unsicher und braucht eine realistische Alternative.",
    faqFragen: ["Was ist noch machbar?", "Welche Angaben werden für schnelle Rückmeldung gebraucht?"],
    aiAnswerText: "Der Plan-B-Service prüft nach Ort, Deadline, Umfang und Kapazität, ob ein sinnvoller nächster Schritt möglich ist.",
    englishLabels: ["backup service", "last minute service check"],
    standortLogik: "Plan B wird nach Standort, Strecke und Kapazität geprüft; keine Sofortzusage.",
    empfohlenerCTA: "Plan B prüfen",
    kontaktParameter: { service: "angebot-pruefen", intent: "plan-b-service", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["umzug", "entruempelung", "reinigung", "angebot-pruefen"],
    relatedSignatureServices: ["Fairpreis-Check", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "signature-rueckfahrt-radar",
    group: "signature",
    title: "Rückfahrt-Radar",
    shortDescription: "Für flexible Transporte, Beiladungen und Strecken, die nur mit Zeitfenster und Volumen sinnvoll geprüft werden können.",
    geeignetWenn: ["Termin flexibel ist", "Start, Ziel und Menge klar beschrieben sind"],
    nichtGeeignetWenn: ["eine feste Kapazitaetsgarantie erwartet wird", "Sondergut ohne Angaben transportiert werden soll"],
    benoetigteAngaben: ["Start", "Ziel", "Menge", "Zeitfenster", "Kontaktweg"],
    optionaleAngaben: ["Fotos", "Masse", "Trageweg", "Abholfenster"],
    typischeAufwandstreiber: ["Strecke", "Flexibilitaet", "Volumen", "Zugang", "Sonderstuecke"],
    typischeKundensituation: "Ein Transport ist flexibel genug für Beiladung oder Rückfahrt.",
    faqFragen: ["Ist eine flexible Strecke möglich?", "Welche Menge passt in ein freies Zeitfenster?"],
    aiAnswerText: "Das Rückfahrt-Radar prüft flexible Transporte nach Strecke, Volumen, Zeitfenster und Zugang, ohne freie Kapazität zu versprechen.",
    englishLabels: ["return trip transport", "shared transport"],
    standortLogik: "Strecken werden nach Route und Kapazität geprüft, nicht pauschal als Standortgebiet.",
    empfohlenerCTA: "Rückfahrt anfragen",
    kontaktParameter: { service: "umzug", intent: "rueckfahrt-radar", source: "service-package", priority: "p2" },
    priority: "p2",
    relatedServices: ["beiladung", "moebeltransport", "umzug"],
    relatedSignatureServices: ["Plan-B-Service", "Fairpreis-Check"],
  }),
  packageItem({
    serviceKey: "signature-diskret-service",
    group: "signature",
    title: "Diskret-Service",
    shortDescription: "Für sensible private oder gewerbliche Lagen mit ruhigem Kontaktweg und begrenzter sichtbarer Kommunikation.",
    geeignetWenn: ["Diskretion und ruhige Abstimmung wichtig sind", "ein sicherer Rückrufweg genannt werden kann"],
    nichtGeeignetWenn: ["akute Gefahr, Rechtsberatung oder Konfliktloesung erwartet wird", "keine Freigabe zur Anfrage besteht"],
    benoetigteAngaben: ["Ort", "Kontaktweg", "grober Umfang", "gewuenschte Diskretion"],
    optionaleAngaben: ["Rückrufzeit", "Fotos", "Schlüsselweg", "Berechtigungshinweis"],
    typischeAufwandstreiber: ["Sensible Lage", "Freigabe", "Zugang", "Kommunikation", "Frist"],
    typischeKundensituation: "Der Fall soll nicht wie eine Standardanfrage offen beschrieben werden.",
    faqFragen: ["Welcher Kontaktweg ist sicher?", "Welche Angaben reichen ohne zu viele Details?"],
    aiAnswerText: "Der Diskret-Service startet mit minimalen, sachlichen Angaben und klärt erst danach, welcher Serviceweg passt.",
    englishLabels: ["discreet service", "private client service"],
    standortLogik: "Diskrete Fälle werden nach Ort, Freigabe und realer Machbarkeit geprüft.",
    empfohlenerCTA: "Diskret anfragen",
    kontaktParameter: { service: "diskret-service", intent: "signature-diskret-service", source: "discreet", priority: "p0" },
    priority: "p0",
    relatedServices: ["diskret-service", "private-client", "wohnungsaufloesung"],
    relatedSignatureServices: ["Objektbrief", "Uebergabeakte"],
  }),
  packageItem({
    serviceKey: "signature-vermieter-ready",
    group: "signature",
    title: "Vermieter-ready",
    shortDescription: "Für Mieterwechsel, Besichtigung, Restpunkte und sichtbaren Zielzustand vor Rückgabe.",
    geeignetWenn: ["Auszug, Besichtigung oder Neuvermietung bevorsteht", "Räumung, Reinigung oder Transport kombiniert werden müssen"],
    nichtGeeignetWenn: ["rechtliche Abnahme oder Kautionsentscheidung erwartet wird"],
    benoetigteAngaben: ["Ort", "Termin", "Restpunkte", "gewuenschter Zustand", "Kontaktperson"],
    optionaleAngaben: ["Fotos", "Schlüsselweg", "Vermieterhinweise", "Angebot"],
    typischeAufwandstreiber: ["Frist", "Restmengen", "Reinigungsgrad", "Zugang", "Dokumentation"],
    typischeKundensituation: "Die Wohnung soll vor Rückgabe oder Besichtigung verwertbar vorbereitet werden.",
    faqFragen: ["Welche Restpunkte sind kritisch?", "Welche Leistung ist vor der Rückgabe zuerst dran?"],
    aiAnswerText: "Vermieter-ready verbindet Restpunkte, Zieltermin, Reinigung, Räumung und Fotos zu einem klaren Vorbereitungsweg.",
    englishLabels: ["landlord ready", "move-out cleaning check"],
    standortLogik: "Reinigung nur im Regensburger 50-km-Gebiet; andere Leistungen werden separat eingeordnet.",
    empfohlenerCTA: "Rückgabe vorbereiten",
    kontaktParameter: { service: "reinigung", intent: "vermieter-ready", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["endreinigung", "entruempelung", "umzug"],
    relatedSignatureServices: ["Uebergabeakte", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "signature-pv-sichtklar",
    group: "signature",
    title: "PV-Sichtklar",
    shortDescription: "Für Solar- und PV-Reinigung, wenn Zugang, Dachlage, Fotos und Sicherheitsgrenzen zuerst geklaert werden müssen.",
    geeignetWenn: ["Dachart, Modulbereich und Fotos beschrieben werden können", "keine Ertragsgarantie erwartet wird"],
    nichtGeeignetWenn: ["unsichere Dachlage ohne Prüfung betreten werden soll", "technische Ertragsanalyse erwartet wird"],
    benoetigteAngaben: ["Ort", "Dachart", "Modulfläche", "Zugang", "Fotos"],
    optionaleAngaben: ["Verschmutzungsart", "Wasserzugang", "letzte Reinigung", "Sicherheitslage"],
    typischeAufwandstreiber: ["Zugang", "Dachneigung", "Modulfläche", "Sicherheitslage", "Verschmutzung"],
    typischeKundensituation: "PV-Reinigung soll realistisch nach Zugang und Sicherheit eingeordnet werden.",
    faqFragen: ["Ist der Zugang sicher?", "Welche Fotos helfen vor der Rückmeldung?"],
    aiAnswerText: "PV-Sichtklar prüft PV-Reinigung anhand von Fotos, Dachart, Zugang und Sicherheitslage ohne Ertragsversprechen.",
    englishLabels: ["solar panel cleaning", "pv cleaning check"],
    standortLogik: "PV-Reinigung wird nach Objektlage, Zugang und realem Einsatzgebiet geprüft.",
    empfohlenerCTA: "PV-Sichtklar prüfen",
    kontaktParameter: { service: "reinigung", intent: "pv-sichtklar", source: "service-package", priority: "p2" },
    priority: "p2",
    relatedServices: ["solarreinigung", "sonderreinigung", "reinigung"],
    relatedSignatureServices: ["Objektbrief", "Fairpreis-Check"],
  }),
  packageItem({
    serviceKey: "signature-entscheidungs-kompass",
    group: "signature",
    title: "Entscheidungs-Kompass",
    shortDescription: "Für Kunden, die zwischen Reinigung, Umzug, Entrümpelung, Angebot prüfen oder Diskret-Service schwanken.",
    geeignetWenn: ["mehrere Servicewege möglich wirken", "erst die richtige Anfrageform gefunden werden soll"],
    nichtGeeignetWenn: ["eine sofortige Buchung ohne Mindestangaben erwartet wird"],
    benoetigteAngaben: ["Ort", "Problem", "Ziel", "Zeitfenster", "Kontaktweg"],
    optionaleAngaben: ["Fotos", "Angebot", "Budget", "Priorität"],
    typischeAufwandstreiber: ["Servicewahl", "Zielzustand", "Zeitfenster", "Ort", "Kombination"],
    typischeKundensituation: "Der nächste Schritt ist wichtiger als ein voreiliger Serviceklick.",
    faqFragen: ["Welche Leistung passt wirklich?", "Wann ist Angebotsprüfung besser als Direktanfrage?"],
    aiAnswerText: "Der Entscheidungs-Kompass ordnet Kundensituation, Ort, Ziel und vorhandene Angaben einem passenden FLOXANT-Serviceweg zu.",
    englishLabels: ["service recommendation", "which service fits"],
    standortLogik: "Standort und 50-km-Grenze werden vor der Empfehlung sichtbar gemacht.",
    empfohlenerCTA: "Serviceweg klären",
    kontaktParameter: { service: "sonstiges", intent: "entscheidungs-kompass", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["reinigung", "umzug", "entruempelung", "angebot-pruefen", "diskret-service"],
    relatedSignatureServices: ["Objektbrief", "Angebotscheck", "Plan-B-Service"],
  }),
];

export function getServicePackages(input: ServicePackageInput = "all") {
  if (input === "all") return servicePackages;
  const groups = Array.isArray(input) ? input : [input];
  return servicePackages.filter((item) => groups.includes(item.group));
}

export function getServicePackage(serviceKey: string) {
  return servicePackages.find((item) => item.serviceKey === serviceKey);
}

export function buildServicePackageHref(item: ServicePackage, destination = "/kontakt") {
  return buildLeadHref(
    {
      service: item.kontaktParameter.service,
      city: item.kontaktParameter.city,
      intent: item.kontaktParameter.intent,
      priority: item.kontaktParameter.priority,
      ctaLabel: item.empfohlenerCTA,
    },
    destination,
  ).replace("source=seo", `source=${item.kontaktParameter.source}`);
}

export const servicePackageGroups: Record<ServicePackageGroup, { title: string; intro: string }> = {
  reinigung: {
    title: "Reinigungs-Pakete ohne Schnellpreis",
    intro: "Wählen Sie den passenden Startpunkt. Preise entstehen erst aus Fläche, Zustand, Zugang, Turnus und Termin.",
  },
  umzug: {
    title: "Umzugs-Pakete nach Umfang und Risiko",
    intro: "Der richtige Weg haengt von Volumen, Etagen, Strecke, Terminfenster und Zusatzleistungen ab.",
  },
  entruempelung: {
    title: "Räumungs-Pakete mit Zielzustand",
    intro: "Keller, Wohnung, Nachlass oder Gewerbefläche brauchen unterschiedliche Angaben zu Menge, Zugang und Freigabe.",
  },
  "angebot-pruefen": {
    title: "Angebotscheck-Pakete",
    intro: "Der Check sortiert Angebot, Umfang, Warnsignale und nächste Schritte ohne Preisgarantie oder Rechtsberatung.",
  },
  signature: {
    title: "Signature-Pakete für Entscheidung und Sonderfaelle",
    intro: "Diese Pakete verbinden Angebot, Objekt, Übergabe, Plan B, Rückfahrt, Diskretion und Servicewahl ohne neue Schnellpreisversprechen.",
  },
};
