import { buildLeadHref, type LeadPriority, type LeadService } from "@/lib/lead-intents";

export type ServicePackageGroup = "reinigung" | "umzug" | "entruempelung" | "angebot-pruefen" | "signature";

export type ServicePackageContactParameters = {
  service: LeadService;
  city?: string;
  intent: string;
  source: "service-package" | "contact-routing" | "offer-check" | "b2b" | "discreet";
  priority: LeadPriority;
};

export type ServicePackage = {
  serviceKey: string;
  group: ServicePackageGroup;
  title: string;
  shortDescription: string;
  geeignetWenn: string[];
  nichtGeeignetWenn: string[];
  benoetigteAngaben: string[];
  optionaleAngaben: string[];
  typischeAufwandstreiber: string[];
  typischeKundensituation?: string;
  faqFragen?: string[];
  aiAnswerText?: string;
  englishLabels?: string[];
  standortLogik?: string;
  empfohlenerCTA: string;
  kontaktParameter: ServicePackageContactParameters;
  priority: LeadPriority;
  relatedServices: string[];
  relatedSignatureServices: string[];
};

export type ServicePackageInput = ServicePackageGroup | ServicePackageGroup[] | "all";

function packageItem(item: ServicePackage): ServicePackage {
  return item;
}

export const servicePackages: ServicePackage[] = [
  packageItem({
    serviceKey: "reinigung-einmalig",
    group: "reinigung",
    title: "Einmalige Reinigung",
    shortDescription: "Fuer Wohnung, Haus oder Objekt, wenn ein klarer einmaliger Reinigungsschritt gebraucht wird.",
    geeignetWenn: ["Auszug, Besuch, Verkauf oder Neustart ansteht", "der Umfang grob beschrieben werden kann"],
    nichtGeeignetWenn: ["regelmaessige Objektpflege gesucht ist", "medizinische Spezialdesinfektion erwartet wird"],
    benoetigteAngaben: ["Ort", "Objektart", "grobe Flaeche", "Zustand", "Terminwunsch"],
    optionaleAngaben: ["Fotos", "Schluesselweg", "besondere Flaechen", "vorhandenes Angebot"],
    typischeAufwandstreiber: ["Flaeche", "Verschmutzungsgrad", "Kueche und Bad", "Fenster", "Zugang"],
    empfohlenerCTA: "Einmalige Reinigung anfragen",
    kontaktParameter: { service: "reinigung", intent: "einmalige-reinigung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["reinigung", "grundreinigung", "endreinigung"],
    relatedSignatureServices: ["Objektbrief", "Uebergabeakte"],
  }),
  packageItem({
    serviceKey: "reinigung-regelmaessig",
    group: "reinigung",
    title: "Regelmaessige Reinigung",
    shortDescription: "Fuer wiederkehrende Reinigung mit Turnus, Raumliste und festen Kontaktpunkten.",
    geeignetWenn: ["Buero, Treppenhaus, Praxisflaeche oder Objekt laufend gepflegt werden soll", "Turnus und Zeitfenster wichtig sind"],
    nichtGeeignetWenn: ["nur ein einmaliger Auszugsschritt offen ist", "ein Termin ohne Prüfung fest zugesagt werden soll"],
    benoetigteAngaben: ["Objektart", "Flaeche", "Turnus", "gewuenschtes Zeitfenster", "Ansprechpartner"],
    optionaleAngaben: ["Raumliste", "Fotos", "Schluesselregelung", "bestehendes Angebot"],
    typischeAufwandstreiber: ["Turnus", "Sanitaer/Kueche", "Zugang", "Reinigungszeiten", "Sonderanforderungen"],
    empfohlenerCTA: "Turnusreinigung einordnen",
    kontaktParameter: { service: "gewerbereinigung", intent: "regelmaessige-reinigung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["gewerbereinigung", "bueroreinigung", "unterhaltsreinigung"],
    relatedSignatureServices: ["Leistungsumfang", "Objektbetreuung"],
  }),
  packageItem({
    serviceKey: "reinigung-uebergabe-endreinigung",
    group: "reinigung",
    title: "Uebergabe-/Endreinigung",
    shortDescription: "Fuer Auszug, Wohnungsabnahme, Wiedervermietung oder Rueckgabe mit sichtbarem Zielzustand.",
    geeignetWenn: ["Schluesseluebergabe oder Abnahme vorbereitet wird", "Reinigung nach Umzug oder Entruempelung offen ist"],
    nichtGeeignetWenn: ["laufende Unterhaltsreinigung gesucht ist", "eine verbindliche Wohnungsabnahme erwartet wird"],
    benoetigteAngaben: ["Ort", "Flaeche", "Zieltermin", "Zustand", "Raeume"],
    optionaleAngaben: ["Fotos", "Vermietertermin", "Restgegenstaende", "Schluesselweg"],
    typischeAufwandstreiber: ["Bad/Kueche", "Fenster", "Restmoebel", "Frist", "Zugang"],
    empfohlenerCTA: "Endreinigung vorbereiten",
    kontaktParameter: { service: "reinigung", intent: "uebergabe-endreinigung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["endreinigung", "umzug-mit-reinigung"],
    relatedSignatureServices: ["Uebergabeakte", "Schluesseluebergabe"],
  }),
  packageItem({
    serviceKey: "bueroreinigung-gewerbereinigung",
    group: "reinigung",
    title: "Buero-/Gewerbereinigung",
    shortDescription: "Fuer Unternehmen, Kanzleien, Praxen, Hotels und Gewerbeflaechen mit Raumliste und Turnus.",
    geeignetWenn: ["Firma, Objekt oder Verwaltung klare Reinigungsablaeufe braucht", "Flaeche, Turnus und Zeitfenster bekannt sind"],
    nichtGeeignetWenn: ["private Haushaltshilfe gesucht ist", "Zertifikate oder Spezialdesinfektion ohne Pruefung erwartet werden"],
    benoetigteAngaben: ["Firma", "Objektart", "Flaeche", "Turnus", "Reinigungszeit", "Ansprechpartner"],
    optionaleAngaben: ["Raumliste", "Fotos", "Schluesselregelung", "bestehendes Angebot"],
    typischeAufwandstreiber: ["Flaeche", "Turnus", "Sanitaer/Kueche", "Zeitfenster", "Zugang"],
    empfohlenerCTA: "Gewerbeobjekt anfragen",
    kontaktParameter: { service: "bueroreinigung", intent: "b2b-bueroreinigung", source: "b2b", priority: "p0" },
    priority: "p0",
    relatedServices: ["bueroreinigung", "gewerbereinigung", "praxisreinigung"],
    relatedSignatureServices: ["Leistungsverzeichnis", "Angebotsprüfung"],
  }),
  packageItem({
    serviceKey: "reinigung-sonderreinigung",
    group: "reinigung",
    title: "Sonderreinigung",
    shortDescription: "Fuer besondere Objektlagen, stark genutzte Bereiche oder Reinigung ausserhalb des Standards.",
    geeignetWenn: ["normaler Turnus nicht reicht", "Fotos und kurze Beschreibung die Lage zeigen koennen"],
    nichtGeeignetWenn: ["Gefahrstoff-, Reinraum- oder medizinische Spezialreinigung erwartet wird"],
    benoetigteAngaben: ["Ort", "Objektart", "Problemstelle", "Flaeche", "Termin"],
    optionaleAngaben: ["Fotos", "Materialhinweise", "Zugang", "bestehende Reinigung"],
    typischeAufwandstreiber: ["Verschmutzung", "Material", "Zugang", "Sicherheitslage", "Frist"],
    empfohlenerCTA: "Sonderfall einordnen",
    kontaktParameter: { service: "reinigung", intent: "sonderreinigung", source: "service-package", priority: "p2" },
    priority: "p2",
    relatedServices: ["grundreinigung", "baureinigung", "notfallreinigung"],
    relatedSignatureServices: ["Objektbrief", "Fotoeinschaetzung"],
  }),
  packageItem({
    serviceKey: "solarreinigung-pv",
    group: "reinigung",
    title: "Solar-/PV-Reinigung",
    shortDescription: "Fuer Modulreinigung nach Dachart, Zugang und Sicherheitslage ohne Ertragsversprechen.",
    geeignetWenn: ["Dachart, Zugang und Modulbereich beschrieben werden koennen", "Fotos vorhanden oder moeglich sind"],
    nichtGeeignetWenn: ["Ertragsgarantie erwartet wird", "unsichere Dachlage ohne Pruefung betreten werden soll"],
    benoetigteAngaben: ["Ort", "Dachart", "Modulflaeche", "Zugang", "Fotos"],
    optionaleAngaben: ["Wasser-/Stromzugang", "Verschmutzungsart", "letzte Reinigung"],
    typischeAufwandstreiber: ["Zugang", "Dachneigung", "Modulflaeche", "Sicherheitslage", "Verschmutzung"],
    empfohlenerCTA: "PV-Reinigung pruefen",
    kontaktParameter: { service: "reinigung", intent: "solarreinigung-pv", source: "service-package", priority: "p2" },
    priority: "p2",
    relatedServices: ["solarreinigung", "sonderreinigung"],
    relatedSignatureServices: ["Fotoeinschaetzung", "Sicherheitscheck"],
  }),
  packageItem({
    serviceKey: "reinigung-nach-entruempelung",
    group: "reinigung",
    title: "Reinigung nach Entruempelung",
    shortDescription: "Fuer Raeume, die nach Raeumung, Kellerleerung oder Wohnungsaufloesung wieder nutzbar werden sollen.",
    geeignetWenn: ["nach der Raeumung Staub, Laufspuren oder Geruch bleiben", "Uebergabe oder Neuvermietung folgt"],
    nichtGeeignetWenn: ["nur Abtransport ohne Zielzustand gebraucht wird"],
    benoetigteAngaben: ["Ort", "Raeume", "Zielzustand", "Termin", "Zugang"],
    optionaleAngaben: ["Fotos", "Restmengen", "Uebergabetermin", "Schluesselweg"],
    typischeAufwandstreiber: ["Reststaub", "Boden", "Bad/Kueche", "Geruch", "Frist"],
    empfohlenerCTA: "Raeumung + Reinigung planen",
    kontaktParameter: { service: "entruempelung", intent: "entruempelung-reinigung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["entruempelung", "endreinigung"],
    relatedSignatureServices: ["Uebergabeakte", "Schluesseluebergabe"],
  }),

  packageItem({
    serviceKey: "mini-umzug",
    group: "umzug",
    title: "Mini-Umzug",
    shortDescription: "Fuer kleine Mengen, einzelne Moebel oder kurze Strecken mit klarer Zugangslage.",
    geeignetWenn: ["wenige Gegenstaende oder kleiner Haushalt transportiert werden", "Start, Ziel und Etage bekannt sind"],
    nichtGeeignetWenn: ["kompletter Haushalt mit vielen Sonderpunkten offen ist"],
    benoetigteAngaben: ["Start", "Ziel", "Gegenstaende", "Etage", "Termin"],
    optionaleAngaben: ["Fotos", "Aufzug", "Haltezone", "Montagebedarf"],
    typischeAufwandstreiber: ["Etage", "Laufweg", "Sonderstuecke", "Terminfenster", "Haltezone"],
    empfohlenerCTA: "Mini-Umzug anfragen",
    kontaktParameter: { service: "umzug", intent: "mini-umzug", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["moebeltransport", "beiladung"],
    relatedSignatureServices: ["Rueckfahrt-Radar", "Plan-B-Service"],
  }),
  packageItem({
    serviceKey: "privatumzug",
    group: "umzug",
    title: "Privatumzug",
    shortDescription: "Fuer Wohnung oder Haus mit Volumen, Strecke, Etage, Zeitfenster und optionalen Zusatzleistungen.",
    geeignetWenn: ["ein privater Umzug in Regensburg, Bayern oder Nahbereich geplant wird", "Volumen grob beschreibbar ist"],
    nichtGeeignetWenn: ["nur Reinigung oder nur Entruempelung gebraucht wird"],
    benoetigteAngaben: ["Start", "Ziel", "Volumen", "Etagen", "Terminfenster"],
    optionaleAngaben: ["Fotos", "Moebelmontage", "Verpackung", "Reinigung danach"],
    typischeAufwandstreiber: ["Volumen", "Etage/Aufzug", "Strecke", "Montage", "Haltezone"],
    empfohlenerCTA: "Privatumzug pruefen",
    kontaktParameter: { service: "umzug", intent: "privatumzug", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["umzug", "umzug-mit-reinigung"],
    relatedSignatureServices: ["Objektbrief", "Uebergabeakte"],
  }),
  packageItem({
    serviceKey: "seniorenumzug",
    group: "umzug",
    title: "Seniorenumzug",
    shortDescription: "Fuer Umzug im Alter mit ruhiger Abstimmung, Angehoerigenkontakt und optionaler Uebergabevorbereitung.",
    geeignetWenn: ["mehr Abstimmung, Ruhe und klare Kontaktwege wichtig sind", "Angehoerige oder Betreuer mitkoordinieren"],
    nichtGeeignetWenn: ["akute medizinische oder rechtliche Betreuung erwartet wird"],
    benoetigteAngaben: ["Ort", "Ziel", "Kontaktperson", "Umfang", "Zeitfenster"],
    optionaleAngaben: ["Fotos", "Abbau/Montage", "Reinigung", "Schluesselweg"],
    typischeAufwandstreiber: ["Abstimmung", "Etage", "Volumen", "Moebelmontage", "Uebergabe"],
    empfohlenerCTA: "Seniorenumzug ruhig anfragen",
    kontaktParameter: { service: "seniorenumzug", intent: "umzug-im-alter-bayern", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["seniorenumzug", "umzug-im-alter"],
    relatedSignatureServices: ["Diskret-Modus", "Schluesseluebergabe"],
  }),
  packageItem({
    serviceKey: "bueroumzug",
    group: "umzug",
    title: "Bueroumzug",
    shortDescription: "Fuer Unternehmen mit Inventar, IT-nahen Gegenstaenden, Betriebspause und klaren Zeitfenstern.",
    geeignetWenn: ["Betriebsunterbrechung gering bleiben soll", "Ansprechpartner und Zeitfenster definiert werden koennen"],
    nichtGeeignetWenn: ["IT-Installation oder Netzwerkarbeit erwartet wird"],
    benoetigteAngaben: ["Firma", "Start", "Ziel", "Inventar", "Zeitfenster", "Ansprechpartner"],
    optionaleAngaben: ["Etagenplan", "Fotos", "Moebelmontage", "Haltezone"],
    typischeAufwandstreiber: ["Zeitfenster", "Inventar", "Etagen", "Laufwege", "Montage"],
    empfohlenerCTA: "Bueroumzug einordnen",
    kontaktParameter: { service: "umzug", intent: "bueroumzug", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["bueroumzug", "gewerbe-umzug"],
    relatedSignatureServices: ["Plan-B-Service", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "moebeltransport",
    group: "umzug",
    title: "Moebeltransport",
    shortDescription: "Fuer einzelne Moebel, sperrige Stuecke oder Transport ohne kompletten Umzug.",
    geeignetWenn: ["einzelne Gegenstaende klar benannt werden koennen", "Start/Ziel und Zugang bekannt sind"],
    nichtGeeignetWenn: ["viele unbekannte Mengen oder Entruempelung im Vordergrund stehen"],
    benoetigteAngaben: ["Gegenstand", "Start", "Ziel", "Etage", "Termin"],
    optionaleAngaben: ["Fotos", "Masse", "Demontage", "Trageweg"],
    typischeAufwandstreiber: ["Gewicht", "Groesse", "Treppenhaus", "Etage", "Sonderstueck"],
    empfohlenerCTA: "Moebeltransport anfragen",
    kontaktParameter: { service: "umzug", intent: "moebeltransport", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["klaviertransport", "beiladung"],
    relatedSignatureServices: ["Rueckfahrt-Radar"],
  }),
  packageItem({
    serviceKey: "beiladung-rueckfahrt",
    group: "umzug",
    title: "Beiladung/Rueckfahrt",
    shortDescription: "Fuer flexible Transporte, wenn Strecke, Terminfenster und Menge zu freien Kapazitaeten passen koennen.",
    geeignetWenn: ["Termin flexibel ist", "Menge und Strecke klar beschrieben sind"],
    nichtGeeignetWenn: ["fester Soforttermin oder exakte Kapazitaetsgarantie erwartet wird"],
    benoetigteAngaben: ["Start", "Ziel", "Menge", "Zeitfenster", "Kontaktweg"],
    optionaleAngaben: ["Fotos", "Abholfenster", "Lieferfenster", "Tragehilfe"],
    typischeAufwandstreiber: ["Strecke", "Flexibilitaet", "Volumen", "Zugang", "Terminfenster"],
    empfohlenerCTA: "Rueckfahrt pruefen",
    kontaktParameter: { service: "umzug", intent: "beiladung-rueckfahrt", source: "service-package", priority: "p2" },
    priority: "p2",
    relatedServices: ["leerfahrt-rueckfahrt", "beiladung"],
    relatedSignatureServices: ["Rueckfahrt-Radar"],
  }),
  packageItem({
    serviceKey: "express-plan-b-umzug",
    group: "umzug",
    title: "Express-/Plan-B-Umzug",
    shortDescription: "Fuer wackelige Anbieter, kurzfristige Aenderungen oder dringend zu pruefende Alternativen.",
    geeignetWenn: ["Plan A unsicher ist", "Dringlichkeit ehrlich genannt werden kann"],
    nichtGeeignetWenn: ["garantierter Soforteinsatz erwartet wird"],
    benoetigteAngaben: ["Was ist passiert?", "Start/Ziel", "Umfang", "Deadline", "Kontaktweg"],
    optionaleAngaben: ["bestehendes Angebot", "Fotos", "Zeitfenster", "Plan-A-Status"],
    typischeAufwandstreiber: ["Frist", "Verfuegbarkeit", "Volumen", "Zugang", "Sonderstuecke"],
    empfohlenerCTA: "Plan B pruefen",
    kontaktParameter: { service: "umzug", intent: "plan-b-umzug", source: "service-package", priority: "p0" },
    priority: "p0",
    relatedServices: ["plan-b-service", "schadensbegrenzung"],
    relatedSignatureServices: ["Plan-B-Service", "Fairpreis-Check"],
  }),

  packageItem({
    serviceKey: "entruempelung-keller-garage",
    group: "entruempelung",
    title: "Keller/Garage",
    shortDescription: "Fuer kleinere Raeume mit Menge, Zugang, Fotos und Zielzustand.",
    geeignetWenn: ["Keller, Garage oder Nebenraum leer werden soll", "Fotos den Umfang zeigen koennen"],
    nichtGeeignetWenn: ["ganze Wohnung oder Nachlass gemeint ist"],
    benoetigteAngaben: ["Ort", "Raum", "Menge", "Zugang", "Termin"],
    optionaleAngaben: ["Fotos", "Materialarten", "Parkmoeglichkeit", "Reinigung danach"],
    typischeAufwandstreiber: ["Menge", "Etage/Zugang", "Material", "Laufwege", "Frist"],
    empfohlenerCTA: "Keller/Garage pruefen",
    kontaktParameter: { service: "entruempelung", intent: "keller-garage-entruempelung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["kleinmengen-entsorgung", "entruempelung"],
    relatedSignatureServices: ["Fotoeinschaetzung"],
  }),
  packageItem({
    serviceKey: "entruempelung-wohnung-haus",
    group: "entruempelung",
    title: "Wohnung/Haus",
    shortDescription: "Fuer Raeumung groesserer Wohnflaechen mit Zugang, Freigabe, Entsorgung und Zielzustand.",
    geeignetWenn: ["mehrere Raeume oder ein ganzes Objekt betroffen sind", "Uebergabe, Verkauf oder Renovierung folgt"],
    nichtGeeignetWenn: ["nur ein einzelnes Moebel transportiert werden soll"],
    benoetigteAngaben: ["Ort", "Raeume", "Menge", "Zugang", "Zielzustand"],
    optionaleAngaben: ["Fotos", "Freigabe", "Schluesselweg", "Reinigung danach"],
    typischeAufwandstreiber: ["Menge", "Raeume", "Etage", "Entsorgung", "Demontage"],
    empfohlenerCTA: "Wohnung/Haus raeumen",
    kontaktParameter: { service: "entruempelung", intent: "wohnung-haus-entruempelung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["wohnungsaufloesung", "entruempelung"],
    relatedSignatureServices: ["Uebergabeakte", "Schluesseluebergabe"],
  }),
  packageItem({
    serviceKey: "haushaltsaufloesung",
    group: "entruempelung",
    title: "Haushaltsaufloesung",
    shortDescription: "Fuer Haushalte, die vollstaendig oder teilweise aufgeloest und danach uebergabefaehig werden sollen.",
    geeignetWenn: ["Freigabe, Ansprechpartner und Zielzustand geklaert werden koennen", "Raeumung und Reinigung zusammenhaengen"],
    nichtGeeignetWenn: ["Eigentumsfragen ungeklaert sind", "Wertgutachten erwartet wird"],
    benoetigteAngaben: ["Ort", "Ansprechpartner", "Umfang", "Freigabe", "Termin"],
    optionaleAngaben: ["Fotos", "Schluesselweg", "Reinigung", "Uebergabetermin"],
    typischeAufwandstreiber: ["Raeume", "Material", "Freigabe", "Zugang", "Frist"],
    empfohlenerCTA: "Haushaltsaufloesung anfragen",
    kontaktParameter: { service: "wohnungsaufloesung", intent: "haushaltsaufloesung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["haushaltsaufloesung", "wohnungsaufloesung"],
    relatedSignatureServices: ["Uebergabeakte", "Diskret-Modus"],
  }),
  packageItem({
    serviceKey: "nachlassaufloesung",
    group: "entruempelung",
    title: "Nachlassaufloesung",
    shortDescription: "Fuer Nachlass- und Angehoerigenfaelle mit ruhiger Abstimmung und klarer Freigabe.",
    geeignetWenn: ["Ansprechpartner und Freigabe vorhanden sind", "diskrete Kommunikation wichtig ist"],
    nichtGeeignetWenn: ["Rechtsberatung, Mediation oder Wertgutachten erwartet werden"],
    benoetigteAngaben: ["Ort", "Kontaktperson", "Raeume", "Freigabe", "Ziel"],
    optionaleAngaben: ["Fotos", "Schluesselweg", "Termin", "Reinigung danach"],
    typischeAufwandstreiber: ["Freigabe", "Menge", "Sensible Situation", "Zugang", "Sortierung"],
    empfohlenerCTA: "Nachlass ruhig abstimmen",
    kontaktParameter: { service: "wohnungsaufloesung", intent: "nachlassaufloesung", source: "discreet", priority: "p1" },
    priority: "p1",
    relatedServices: ["nachlass-raeumung", "wohnungsaufloesung"],
    relatedSignatureServices: ["Diskret-Modus", "Schluesseluebergabe"],
  }),
  packageItem({
    serviceKey: "buero-lageraufloesung",
    group: "entruempelung",
    title: "Buero-/Lageraufloesung",
    shortDescription: "Fuer Firmen, Lager, Buero- oder Nebenflaechen mit Inventar, Freigabe und Terminlogik.",
    geeignetWenn: ["Firma oder Verwaltung Raeume leeren muss", "Ansprechpartner und Zugang klar sind"],
    nichtGeeignetWenn: ["Gefahrstoffe, Aktenvernichtung oder IT-Loeschung erwartet werden"],
    benoetigteAngaben: ["Firma", "Ort", "Flaeche", "Inventar", "Termin", "Ansprechpartner"],
    optionaleAngaben: ["Fotos", "Zugang", "Demontage", "Reinigung danach"],
    typischeAufwandstreiber: ["Inventar", "Etage", "Demontage", "Entsorgung", "Zeitfenster"],
    empfohlenerCTA: "Gewerbeflaeche raeumen",
    kontaktParameter: { service: "entruempelung", intent: "buero-lageraufloesung", source: "b2b", priority: "p1" },
    priority: "p1",
    relatedServices: ["firmenentsorgung", "gewerbe-auszug"],
    relatedSignatureServices: ["Plan-B-Service", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "entruempelung-diskreter-fall",
    group: "entruempelung",
    title: "Diskreter Fall",
    shortDescription: "Fuer sensible Wohnungs-, Nachlass- oder Trennungsfaelle mit zurueckhaltender Kommunikation.",
    geeignetWenn: ["Ruhiger Kontaktweg wichtig ist", "nicht alle Details schriftlich erklaert werden sollen"],
    nichtGeeignetWenn: ["akute Gefahr, Gewalt oder rechtliche Konfliktloesung vorliegt"],
    benoetigteAngaben: ["Ort", "Kontaktweg", "grober Umfang", "Zeitfenster"],
    optionaleAngaben: ["Rueckrufzeit", "Fotos", "Berechtigungshinweis", "Schluesselweg"],
    typischeAufwandstreiber: ["Sensible Lage", "Freigabe", "Zugang", "Menge", "Frist"],
    empfohlenerCTA: "Diskret anfragen",
    kontaktParameter: { service: "diskret-service", intent: "diskret-service", source: "discreet", priority: "p0" },
    priority: "p0",
    relatedServices: ["diskreter-umzug-trennung-scheidung", "private-client-service"],
    relatedSignatureServices: ["Diskret-Modus", "Uebergabeakte"],
  }),
  packageItem({
    serviceKey: "entruempelung-reinigung",
    group: "entruempelung",
    title: "Entruempelung + Reinigung",
    shortDescription: "Fuer Raeumung mit anschliessender Reinigung, Uebergabe oder Neuvermietung.",
    geeignetWenn: ["nach der Raeumung ein nutzbarer Zustand gebraucht wird", "Reinigung und Zieltermin zusammenhaengen"],
    nichtGeeignetWenn: ["nur Transport ohne Raeumung oder Reinigung gemeint ist"],
    benoetigteAngaben: ["Ort", "Raeume", "Menge", "Zielzustand", "Termin"],
    optionaleAngaben: ["Fotos", "Uebergabetermin", "Schluesselweg", "Restpunkte"],
    typischeAufwandstreiber: ["Raeumung", "Reststaub", "Bad/Kueche", "Zugang", "Frist"],
    empfohlenerCTA: "Kombi-Fall senden",
    kontaktParameter: { service: "entruempelung", intent: "entruempelung-plus-reinigung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["entruempelung", "endreinigung"],
    relatedSignatureServices: ["Uebergabeakte", "Schluesseluebergabe"],
  }),

  packageItem({
    serviceKey: "angebot-pruefen",
    group: "angebot-pruefen",
    title: "Angebot pruefen",
    shortDescription: "Fuer vorhandene Angebote, Screenshots oder Preisnennungen mit offenen Leistungsfragen.",
    geeignetWenn: ["Preis, Umfang oder Zusatzkosten unklar wirken", "ein Dokument, Screenshot oder Eckdaten vorliegen"],
    nichtGeeignetWenn: ["Rechtsberatung oder Anbieterbewertung erwartet wird"],
    benoetigteAngaben: ["Service", "Ort", "Angebotsumfang", "Preispositionen", "Pruefgrund"],
    optionaleAngaben: ["PDF/Screenshot", "Fotos", "Termin", "Vergleichsangebot"],
    typischeAufwandstreiber: ["Leistungsumfang", "Zusatzkosten", "Termin", "Zugang", "Vergleichbarkeit"],
    empfohlenerCTA: "Angebot pruefen lassen",
    kontaktParameter: { service: "angebot-pruefen", intent: "angebot-pruefen", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["angebotscheck", "angebot-guenstiger-pruefen"],
    relatedSignatureServices: ["Fairpreis-Check", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "anbieter-vergleichen",
    group: "angebot-pruefen",
    title: "Anbieter vergleichen",
    shortDescription: "Fuer mehrere Angebote oder Anbieter, die schwer nach Umfang und Risiko vergleichbar sind.",
    geeignetWenn: ["mehrere Angebote vorliegen", "Leistungen nicht deckungsgleich beschrieben sind"],
    nichtGeeignetWenn: ["eine pauschale Rangliste, Abwertung oder Rechtsbewertung anderer Anbieter erwartet wird"],
    benoetigteAngaben: ["Anzahl Angebote", "Serviceart", "Ort", "Unterschiede", "wichtigste Frage"],
    optionaleAngaben: ["Preispositionen", "Fotos", "Termin", "Budgetrahmen"],
    typischeAufwandstreiber: ["Leistungsgrenzen", "Zusatzpositionen", "Termine", "Zugang", "Risiko"],
    empfohlenerCTA: "Vergleich sortieren",
    kontaktParameter: { service: "angebot-pruefen", intent: "anbieter-vergleichen", source: "offer-check", priority: "p1" },
    priority: "p1",
    relatedServices: ["anbieter-vergleichen", "angebotscheck"],
    relatedSignatureServices: ["Fairpreis-Check", "Plan-B-Service"],
  }),
  packageItem({
    serviceKey: "zweitmeinung",
    group: "angebot-pruefen",
    title: "Zweitmeinung",
    shortDescription: "Fuer Kunden, die vor Zusage eine sachliche zweite Einordnung brauchen.",
    geeignetWenn: ["ein Angebot gut wirkt, aber Unsicherheit bleibt", "Kunden wissen wollen, welche Rueckfragen sinnvoll sind"],
    nichtGeeignetWenn: ["ein garantierter Gegenpreis erwartet wird"],
    benoetigteAngaben: ["Service", "Ort", "Termin", "Unsicherheit", "Angebot oder Eckdaten"],
    optionaleAngaben: ["Fotos", "Budget", "Vergleichsangebot", "Deadline"],
    typischeAufwandstreiber: ["Unsicherheit", "Leistungsumfang", "Termin", "Fotos", "Zusatzkosten"],
    empfohlenerCTA: "Zweitmeinung anfragen",
    kontaktParameter: { service: "angebot-pruefen", intent: "zweitmeinung", source: "offer-check", priority: "p1" },
    priority: "p1",
    relatedServices: ["angebot-pruefen", "objektbrief"],
    relatedSignatureServices: ["Fairpreis-Check", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "plan-b-anbieterabsage",
    group: "angebot-pruefen",
    title: "Plan-B bei Anbieterabsage",
    shortDescription: "Fuer wackelige Zusagen, abgesagte Termine oder Anfragen, bei denen ein naechster Schritt gebraucht wird.",
    geeignetWenn: ["Anbieter nicht reagiert oder abgesagt hat", "Deadline, Umfang und Ort klar benannt werden koennen"],
    nichtGeeignetWenn: ["Sofortgarantie ohne Pruefung erwartet wird"],
    benoetigteAngaben: ["Was ist passiert?", "Service", "Ort", "Deadline", "Umfang"],
    optionaleAngaben: ["Angebot", "Fotos", "Kontaktweg", "Plan-A-Status"],
    typischeAufwandstreiber: ["Dringlichkeit", "Verfuegbarkeit", "Umfang", "Zugang", "Zeitfenster"],
    empfohlenerCTA: "Plan B pruefen",
    kontaktParameter: { service: "angebot-pruefen", intent: "plan-b-anbieterabsage", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["plan-b-service", "schadensbegrenzung"],
    relatedSignatureServices: ["Plan-B-Service", "Fairpreis-Check"],
  }),
  packageItem({
    serviceKey: "reinigungsfirma-angebot-pruefen",
    group: "angebot-pruefen",
    title: "Reinigungsfirma-Angebot pruefen",
    shortDescription: "Fuer Reinigung, Buero, Gewerbe, Endreinigung oder Turnusangebote mit offenen Umfangspunkten.",
    geeignetWenn: ["Flaeche, Turnus oder Leistungsumfang unklar sind", "B2B-Angebot oder Reinigungsangebot vorliegt"],
    nichtGeeignetWenn: ["zertifizierte Spezialhygiene bewertet werden soll"],
    benoetigteAngaben: ["Flaeche", "Objektart", "Turnus", "Leistungsumfang", "Pruefgrund"],
    optionaleAngaben: ["Angebot", "Fotos", "Zeitfenster", "Ansprechpartner"],
    typischeAufwandstreiber: ["Flaeche", "Turnus", "Sanitaer/Kueche", "Zeitfenster", "Zugang"],
    empfohlenerCTA: "Reinigungsangebot pruefen",
    kontaktParameter: { service: "angebot-pruefen", intent: "reinigungsangebot-pruefen", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["reinigung", "bueroreinigung", "gewerbereinigung"],
    relatedSignatureServices: ["Leistungsverzeichnis", "Fairpreis-Check"],
  }),
  packageItem({
    serviceKey: "umzugsangebot-pruefen",
    group: "angebot-pruefen",
    title: "Umzugsangebot pruefen",
    shortDescription: "Fuer Umzug, Transport oder Moebelangebote, bei denen Volumen, Strecke oder Zusatzleistungen unklar sind.",
    geeignetWenn: ["Start/Ziel, Etage oder Volumen nicht klar beruecksichtigt sind", "Zusatzkosten moeglich wirken"],
    nichtGeeignetWenn: ["rechtliche Vertragsbewertung erwartet wird"],
    benoetigteAngaben: ["Start", "Ziel", "Etage", "Volumen", "Angebot", "Pruefgrund"],
    optionaleAngaben: ["Fotos", "Haltezone", "Montage", "Termin"],
    typischeAufwandstreiber: ["Volumen", "Etagen", "Strecke", "Haltezone", "Sonderstuecke"],
    empfohlenerCTA: "Umzugsangebot pruefen",
    kontaktParameter: { service: "angebot-pruefen", intent: "umzugsangebot-pruefen", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["umzug", "klaviertransport", "beiladung"],
    relatedSignatureServices: ["Rueckfahrt-Radar", "Plan-B-Service"],
  }),
  packageItem({
    serviceKey: "entruempelungsangebot-pruefen",
    group: "angebot-pruefen",
    title: "Entruempelungsangebot pruefen",
    shortDescription: "Fuer Raeumung, Entsorgung oder Haushaltsaufloesung mit unklarer Menge, Zugang oder Entsorgung.",
    geeignetWenn: ["Menge, Raeume, Zugang oder Entsorgung offen sind", "Reinigung danach relevant sein kann"],
    nichtGeeignetWenn: ["Wertgutachten, Rechtsberatung oder Anbieterbewertung erwartet wird"],
    benoetigteAngaben: ["Raeume", "Menge", "Zugang", "Angebot", "Termin", "Pruefgrund"],
    optionaleAngaben: ["Fotos", "Materialarten", "Freigabe", "Reinigung danach"],
    typischeAufwandstreiber: ["Menge", "Zugang", "Entsorgung", "Material", "Frist"],
    empfohlenerCTA: "Raeumungsangebot pruefen",
    kontaktParameter: { service: "angebot-pruefen", intent: "entruempelungsangebot-pruefen", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["entruempelung", "wohnungsaufloesung"],
    relatedSignatureServices: ["Uebergabeakte", "Fairpreis-Check"],
  }),
  packageItem({
    serviceKey: "signature-angebotscheck",
    group: "signature",
    title: "Signature Angebotscheck",
    shortDescription: "Fuer vorhandene Angebote, wenn Service, Umfang, Preislogik und naechste Rueckfrage sortiert werden sollen.",
    geeignetWenn: ["PDF, Screenshot oder Eckdaten vorliegen", "nicht klar ist, ob Angebot, Service und Termin zusammenpassen"],
    nichtGeeignetWenn: ["Rechtsberatung oder Abwertung anderer Anbieter erwartet wird", "eine verbindliche Preisgarantie gesucht wird"],
    benoetigteAngaben: ["Service", "Ort", "Angebot oder Eckdaten", "Termin", "wichtigste Unsicherheit"],
    optionaleAngaben: ["Fotos", "Budgetrahmen", "Vergleichsangebot", "Kontaktweg"],
    typischeAufwandstreiber: ["Leistungsumfang", "Zusatzkosten", "Termin", "Zugang", "Vergleichbarkeit"],
    typischeKundensituation: "Ein Angebot wirkt unklar, zu knapp oder schwer vergleichbar.",
    faqFragen: ["Welche Leistungen sind enthalten?", "Welche Rueckfragen sollte ich vor Zusage stellen?"],
    aiAnswerText: "FLOXANT kann ein Angebot praktisch nach Umfang, Ort, Termin, Fotos und offenen Punkten einordnen, ohne Preisgarantie oder Rechtsberatung.",
    englishLabels: ["offer check", "quote check", "second opinion"],
    standortLogik: "Angebotspruefung ist standortuebergreifend moeglich; Reinigung bleibt bei Regensburg plus 50 km.",
    empfohlenerCTA: "Angebotscheck starten",
    kontaktParameter: { service: "angebot-pruefen", intent: "signature-angebotscheck", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["angebot-pruefen", "anbieter-vergleichen", "zweitmeinung"],
    relatedSignatureServices: ["Fairpreis-Check", "Objektbrief", "Plan-B-Service"],
  }),
  packageItem({
    serviceKey: "signature-fairpreis-check",
    group: "signature",
    title: "Fairpreis-Check",
    shortDescription: "Fuer Preisrahmen, die erst mit Umfang, Zugang, Fotos, Termin und Zusatzleistungen nachvollziehbar werden.",
    geeignetWenn: ["Preis und Leistung schwer vergleichbar sind", "ein Budgetrahmen ehrlich geprueft werden soll"],
    nichtGeeignetWenn: ["ein garantierter Gegenpreis erwartet wird", "nur der billigste Anbieter gesucht wird"],
    benoetigteAngaben: ["Service", "Ort", "Preis oder Budget", "Umfang", "Termin"],
    optionaleAngaben: ["Angebot", "Fotos", "Alternativumfang", "Dringlichkeit"],
    typischeAufwandstreiber: ["Umfang", "Zugang", "Zeitfenster", "Sonderleistungen", "Kapazitaet"],
    typischeKundensituation: "Der Preis wirkt hoch, niedrig oder unvollstaendig und soll fair eingeordnet werden.",
    faqFragen: ["Welche Faktoren treiben den Aufwand?", "Ist der Leistungsumfang vollstaendig beschrieben?"],
    aiAnswerText: "Der Fairpreis-Check vergleicht den gewünschten Leistungsumfang mit den Angaben zu Ort, Termin, Zugang und Zusatzpositionen.",
    englishLabels: ["fair price check", "service price review"],
    standortLogik: "Preisrahmen werden anhand von Ort, Strecke und Leistungsgebiet eingeordnet.",
    empfohlenerCTA: "Fairpreis einordnen",
    kontaktParameter: { service: "angebot-pruefen", intent: "fairpreis-check", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["angebot-pruefen", "reinigung", "umzug", "entruempelung"],
    relatedSignatureServices: ["Angebotscheck", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "signature-objektbrief",
    group: "signature",
    title: "Objektbrief",
    shortDescription: "Fuer unklare Objekte, bei denen Zielzustand, Fotos, Zugang und Servicekombination zuerst sortiert werden sollen.",
    geeignetWenn: ["mehrere Leistungen im Raum stehen", "Objekt, Zugang oder Zielzustand noch unscharf sind"],
    nichtGeeignetWenn: ["ein fertiges Angebot ohne weitere Angaben erwartet wird", "keine Berechtigung zur Objektangabe besteht"],
    benoetigteAngaben: ["Ort", "Objektart", "Ziel", "grober Umfang", "Kontaktweg"],
    optionaleAngaben: ["Fotos", "Schluesselweg", "Angebot", "Uebergabetermin"],
    typischeAufwandstreiber: ["Zielzustand", "Zugang", "Fotos", "Freigabe", "Servicekombination"],
    typischeKundensituation: "Der Fall passt nicht sauber in eine einzelne Leistung.",
    faqFragen: ["Welche Leistung ist zuerst sinnvoll?", "Welche Fotos oder Angaben fehlen noch?"],
    aiAnswerText: "Der Objektbrief macht aus einer unscharfen Lage eine verwertbare Anfrage mit Ort, Zielzustand, Zugang, Fotos und passendem naechsten Schritt.",
    englishLabels: ["property brief", "service brief"],
    standortLogik: "Objektangaben klaeren, ob Regensburg, Duesseldorf oder ein geprueftes Servicegebiet betroffen ist.",
    empfohlenerCTA: "Objektbrief senden",
    kontaktParameter: { service: "sonstiges", intent: "objektbrief", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["reinigung", "umzug", "entruempelung", "angebot-pruefen"],
    relatedSignatureServices: ["Uebergabeakte", "Plan-B-Service"],
  }),
  packageItem({
    serviceKey: "signature-uebergabeakte",
    group: "signature",
    title: "Uebergabeakte",
    shortDescription: "Fuer Auszug, Rueckgabe, Neuvermietung oder Objektwechsel mit Fotos, Restpunkten und Zieltermin.",
    geeignetWenn: ["Uebergabe, Abnahme oder Wiedervermietung vorbereitet wird", "Reinigung, Raeumung oder Umzug zusammenhaengen"],
    nichtGeeignetWenn: ["rechtliche Wohnungsabnahme erwartet wird", "der Zielzustand nicht beschrieben werden kann"],
    benoetigteAngaben: ["Ort", "Zieltermin", "Restpunkte", "Zustand", "Kontaktperson"],
    optionaleAngaben: ["Fotos", "Schluesselweg", "Vermietertermin", "Restmengen"],
    typischeAufwandstreiber: ["Frist", "Restmengen", "Bad/Kueche", "Schluesselweg", "Dokumentation"],
    typischeKundensituation: "Vor Rueckgabe oder Besichtigung muessen letzte Schritte priorisiert werden.",
    faqFragen: ["Was muss vor der Uebergabe sichtbar erledigt sein?", "Welche Kombination aus Reinigung und Raeumung passt?"],
    aiAnswerText: "Die Uebergabeakte sammelt Zieltermin, Restpunkte, Fotos und gewuenschten Zustand, damit Reinigung, Raeumung oder Umzug richtig priorisiert werden.",
    englishLabels: ["handover checklist", "move-out handover"],
    standortLogik: "Reinigung fuer Uebergabe bleibt im Regensburger 50-km-Gebiet, andere Leistungen werden separat geprueft.",
    empfohlenerCTA: "Uebergabe vorbereiten",
    kontaktParameter: { service: "reinigung", intent: "uebergabeakte", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["endreinigung", "entruempelung", "umzug"],
    relatedSignatureServices: ["Objektbrief", "Diskret-Service"],
  }),
  packageItem({
    serviceKey: "signature-plan-b-service",
    group: "signature",
    title: "Plan-B-Service",
    shortDescription: "Fuer abgesagte Anbieter, wackelige Termine oder Fristen, bei denen erst Machbarkeit geprueft werden muss.",
    geeignetWenn: ["ein Termin kippt oder ein Anbieter absagt", "Deadline, Ort und Umfang klar benannt werden koennen"],
    nichtGeeignetWenn: ["Soforteinsatz garantiert werden soll", "keine Mindestangaben zum Umfang vorliegen"],
    benoetigteAngaben: ["Was ist passiert?", "Ort", "Service", "Deadline", "Umfang"],
    optionaleAngaben: ["Angebot", "Fotos", "Plan-A-Status", "Kontaktfenster"],
    typischeAufwandstreiber: ["Dringlichkeit", "Verfuegbarkeit", "Umfang", "Strecke", "Zugang"],
    typischeKundensituation: "Ein bestehender Plan ist unsicher und braucht eine realistische Alternative.",
    faqFragen: ["Was ist noch machbar?", "Welche Angaben werden fuer schnelle Rueckmeldung gebraucht?"],
    aiAnswerText: "Der Plan-B-Service prueft nach Ort, Deadline, Umfang und Kapazitaet, ob ein sinnvoller naechster Schritt moeglich ist.",
    englishLabels: ["backup service", "last minute service check"],
    standortLogik: "Plan B wird nach Standort, Strecke und Kapazitaet geprueft; keine Sofortzusage.",
    empfohlenerCTA: "Plan B pruefen",
    kontaktParameter: { service: "angebot-pruefen", intent: "plan-b-service", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["umzug", "entruempelung", "reinigung", "angebot-pruefen"],
    relatedSignatureServices: ["Fairpreis-Check", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "signature-rueckfahrt-radar",
    group: "signature",
    title: "Rueckfahrt-Radar",
    shortDescription: "Fuer flexible Transporte, Beiladungen und Strecken, die nur mit Zeitfenster und Volumen sinnvoll geprueft werden koennen.",
    geeignetWenn: ["Termin flexibel ist", "Start, Ziel und Menge klar beschrieben sind"],
    nichtGeeignetWenn: ["eine feste Kapazitaetsgarantie erwartet wird", "Sondergut ohne Angaben transportiert werden soll"],
    benoetigteAngaben: ["Start", "Ziel", "Menge", "Zeitfenster", "Kontaktweg"],
    optionaleAngaben: ["Fotos", "Masse", "Trageweg", "Abholfenster"],
    typischeAufwandstreiber: ["Strecke", "Flexibilitaet", "Volumen", "Zugang", "Sonderstuecke"],
    typischeKundensituation: "Ein Transport ist flexibel genug fuer Beiladung oder Rueckfahrt.",
    faqFragen: ["Ist eine flexible Strecke moeglich?", "Welche Menge passt in ein freies Zeitfenster?"],
    aiAnswerText: "Das Rueckfahrt-Radar prueft flexible Transporte nach Strecke, Volumen, Zeitfenster und Zugang, ohne freie Kapazitaet zu versprechen.",
    englishLabels: ["return trip transport", "shared transport"],
    standortLogik: "Strecken werden nach Route und Kapazitaet geprueft, nicht pauschal als Standortgebiet.",
    empfohlenerCTA: "Rueckfahrt anfragen",
    kontaktParameter: { service: "umzug", intent: "rueckfahrt-radar", source: "service-package", priority: "p2" },
    priority: "p2",
    relatedServices: ["beiladung", "moebeltransport", "umzug"],
    relatedSignatureServices: ["Plan-B-Service", "Fairpreis-Check"],
  }),
  packageItem({
    serviceKey: "signature-diskret-service",
    group: "signature",
    title: "Diskret-Service",
    shortDescription: "Fuer sensible private oder gewerbliche Lagen mit ruhigem Kontaktweg und begrenzter sichtbarer Kommunikation.",
    geeignetWenn: ["Diskretion und ruhige Abstimmung wichtig sind", "ein sicherer Rueckrufweg genannt werden kann"],
    nichtGeeignetWenn: ["akute Gefahr, Rechtsberatung oder Konfliktloesung erwartet wird", "keine Freigabe zur Anfrage besteht"],
    benoetigteAngaben: ["Ort", "Kontaktweg", "grober Umfang", "gewuenschte Diskretion"],
    optionaleAngaben: ["Rueckrufzeit", "Fotos", "Schluesselweg", "Berechtigungshinweis"],
    typischeAufwandstreiber: ["Sensible Lage", "Freigabe", "Zugang", "Kommunikation", "Frist"],
    typischeKundensituation: "Der Fall soll nicht wie eine Standardanfrage offen beschrieben werden.",
    faqFragen: ["Welcher Kontaktweg ist sicher?", "Welche Angaben reichen ohne zu viele Details?"],
    aiAnswerText: "Der Diskret-Service startet mit minimalen, sachlichen Angaben und klaert erst danach, welcher Serviceweg passt.",
    englishLabels: ["discreet service", "private client service"],
    standortLogik: "Diskrete Faelle werden nach Ort, Freigabe und realer Machbarkeit geprueft.",
    empfohlenerCTA: "Diskret anfragen",
    kontaktParameter: { service: "diskret-service", intent: "signature-diskret-service", source: "discreet", priority: "p0" },
    priority: "p0",
    relatedServices: ["diskret-service", "private-client", "wohnungsaufloesung"],
    relatedSignatureServices: ["Objektbrief", "Uebergabeakte"],
  }),
  packageItem({
    serviceKey: "signature-vermieter-ready",
    group: "signature",
    title: "Vermieter-ready",
    shortDescription: "Fuer Mieterwechsel, Besichtigung, Restpunkte und sichtbaren Zielzustand vor Rueckgabe.",
    geeignetWenn: ["Auszug, Besichtigung oder Neuvermietung bevorsteht", "Raeumung, Reinigung oder Transport kombiniert werden muessen"],
    nichtGeeignetWenn: ["rechtliche Abnahme oder Kautionsentscheidung erwartet wird"],
    benoetigteAngaben: ["Ort", "Termin", "Restpunkte", "gewuenschter Zustand", "Kontaktperson"],
    optionaleAngaben: ["Fotos", "Schluesselweg", "Vermieterhinweise", "Angebot"],
    typischeAufwandstreiber: ["Frist", "Restmengen", "Reinigungsgrad", "Zugang", "Dokumentation"],
    typischeKundensituation: "Die Wohnung soll vor Rueckgabe oder Besichtigung verwertbar vorbereitet werden.",
    faqFragen: ["Welche Restpunkte sind kritisch?", "Welche Leistung ist vor der Rueckgabe zuerst dran?"],
    aiAnswerText: "Vermieter-ready verbindet Restpunkte, Zieltermin, Reinigung, Raeumung und Fotos zu einem klaren Vorbereitungsweg.",
    englishLabels: ["landlord ready", "move-out cleaning check"],
    standortLogik: "Reinigung nur im Regensburger 50-km-Gebiet; andere Leistungen werden separat eingeordnet.",
    empfohlenerCTA: "Rueckgabe vorbereiten",
    kontaktParameter: { service: "reinigung", intent: "vermieter-ready", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["endreinigung", "entruempelung", "umzug"],
    relatedSignatureServices: ["Uebergabeakte", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "signature-pv-sichtklar",
    group: "signature",
    title: "PV-Sichtklar",
    shortDescription: "Fuer Solar- und PV-Reinigung, wenn Zugang, Dachlage, Fotos und Sicherheitsgrenzen zuerst geklaert werden muessen.",
    geeignetWenn: ["Dachart, Modulbereich und Fotos beschrieben werden koennen", "keine Ertragsgarantie erwartet wird"],
    nichtGeeignetWenn: ["unsichere Dachlage ohne Pruefung betreten werden soll", "technische Ertragsanalyse erwartet wird"],
    benoetigteAngaben: ["Ort", "Dachart", "Modulflaeche", "Zugang", "Fotos"],
    optionaleAngaben: ["Verschmutzungsart", "Wasserzugang", "letzte Reinigung", "Sicherheitslage"],
    typischeAufwandstreiber: ["Zugang", "Dachneigung", "Modulflaeche", "Sicherheitslage", "Verschmutzung"],
    typischeKundensituation: "PV-Reinigung soll realistisch nach Zugang und Sicherheit eingeordnet werden.",
    faqFragen: ["Ist der Zugang sicher?", "Welche Fotos helfen vor der Rueckmeldung?"],
    aiAnswerText: "PV-Sichtklar prueft PV-Reinigung anhand von Fotos, Dachart, Zugang und Sicherheitslage ohne Ertragsversprechen.",
    englishLabels: ["solar panel cleaning", "pv cleaning check"],
    standortLogik: "PV-Reinigung wird nach Objektlage, Zugang und realem Einsatzgebiet geprueft.",
    empfohlenerCTA: "PV-Sichtklar pruefen",
    kontaktParameter: { service: "reinigung", intent: "pv-sichtklar", source: "service-package", priority: "p2" },
    priority: "p2",
    relatedServices: ["solarreinigung", "sonderreinigung", "reinigung"],
    relatedSignatureServices: ["Objektbrief", "Fairpreis-Check"],
  }),
  packageItem({
    serviceKey: "signature-entscheidungs-kompass",
    group: "signature",
    title: "Entscheidungs-Kompass",
    shortDescription: "Fuer Kunden, die zwischen Reinigung, Umzug, Entruempelung, Angebot pruefen oder Diskret-Service schwanken.",
    geeignetWenn: ["mehrere Servicewege moeglich wirken", "erst die richtige Anfrageform gefunden werden soll"],
    nichtGeeignetWenn: ["eine sofortige Buchung ohne Mindestangaben erwartet wird"],
    benoetigteAngaben: ["Ort", "Problem", "Ziel", "Zeitfenster", "Kontaktweg"],
    optionaleAngaben: ["Fotos", "Angebot", "Budget", "Prioritaet"],
    typischeAufwandstreiber: ["Servicewahl", "Zielzustand", "Zeitfenster", "Ort", "Kombination"],
    typischeKundensituation: "Der naechste Schritt ist wichtiger als ein voreiliger Serviceklick.",
    faqFragen: ["Welche Leistung passt wirklich?", "Wann ist Angebotspruefung besser als Direktanfrage?"],
    aiAnswerText: "Der Entscheidungs-Kompass ordnet Kundensituation, Ort, Ziel und vorhandene Angaben einem passenden FLOXANT-Serviceweg zu.",
    englishLabels: ["service recommendation", "which service fits"],
    standortLogik: "Standort und 50-km-Grenze werden vor der Empfehlung sichtbar gemacht.",
    empfohlenerCTA: "Serviceweg klaeren",
    kontaktParameter: { service: "sonstiges", intent: "entscheidungs-kompass", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["reinigung", "umzug", "entruempelung", "angebot-pruefen", "diskret-service"],
    relatedSignatureServices: ["Objektbrief", "Angebotscheck", "Plan-B-Service"],
  }),
];

export function getServicePackages(input: ServicePackageInput = "all") {
  if (input === "all") return servicePackages;
  const groups = Array.isArray(input) ? input : [input];
  return servicePackages.filter((item) => groups.includes(item.group));
}

export function getServicePackage(serviceKey: string) {
  return servicePackages.find((item) => item.serviceKey === serviceKey);
}

export function buildServicePackageHref(item: ServicePackage, destination = "/kontakt") {
  return buildLeadHref(
    {
      service: item.kontaktParameter.service,
      city: item.kontaktParameter.city,
      intent: item.kontaktParameter.intent,
      priority: item.kontaktParameter.priority,
      ctaLabel: item.empfohlenerCTA,
    },
    destination,
  ).replace("source=seo", `source=${item.kontaktParameter.source}`);
}

export const servicePackageGroups: Record<ServicePackageGroup, { title: string; intro: string }> = {
  reinigung: {
    title: "Reinigungs-Pakete ohne Schnellpreis",
    intro: "Waehlen Sie den passenden Startpunkt. Preise entstehen erst aus Flaeche, Zustand, Zugang, Turnus und Termin.",
  },
  umzug: {
    title: "Umzugs-Pakete nach Umfang und Risiko",
    intro: "Der richtige Weg haengt von Volumen, Etagen, Strecke, Terminfenster und Zusatzleistungen ab.",
  },
  entruempelung: {
    title: "Raeumungs-Pakete mit Zielzustand",
    intro: "Keller, Wohnung, Nachlass oder Gewerbeflaeche brauchen unterschiedliche Angaben zu Menge, Zugang und Freigabe.",
  },
  "angebot-pruefen": {
    title: "Angebotscheck-Pakete",
    intro: "Der Check sortiert Angebot, Umfang, Warnsignale und naechste Schritte ohne Preisgarantie oder Rechtsberatung.",
  },
  signature: {
    title: "Besondere Leistungen für unterschiedliche Situationen",
    intro: "Diese Leistungen verbinden Angebot, Objekt, Übergabe, Plan B, Rückfahrt, Diskretion und Servicewahl ohne ein Preisversprechen vor der Prüfung.",
  },
};
