import { buildLeadHref, type LeadPriority, type LeadService } from "@/lib/lead-intents";

export type ServicePackageGroup = "reinigung" | "umzug" | "entruempelung" | "angebot-pruefen";

export type ServicePackageContactParameters = {
  service: LeadService;
  city?: string;
  intent: string;
  source: "service-package" | "contact-routing" | "offer-check" | "b2b" | "discreet";
  priority: LeadPriority;
};

export type ServicePackage = {
  serviceKey: string;
  group: ServicePackageGroup;
  title: string;
  shortDescription: string;
  geeignetWenn: string[];
  nichtGeeignetWenn: string[];
  benoetigteAngaben: string[];
  optionaleAngaben: string[];
  typischeAufwandstreiber: string[];
  empfohlenerCTA: string;
  kontaktParameter: ServicePackageContactParameters;
  priority: LeadPriority;
  relatedServices: string[];
  relatedSignatureServices: string[];
};

export type ServicePackageInput = ServicePackageGroup | ServicePackageGroup[] | "all";

function packageItem(item: ServicePackage): ServicePackage {
  return item;
}

export const servicePackages: ServicePackage[] = [
  packageItem({
    serviceKey: "reinigung-einmalig",
    group: "reinigung",
    title: "Einmalige Reinigung",
    shortDescription: "Fuer Wohnung, Haus oder Objekt, wenn ein klarer einmaliger Reinigungsschritt gebraucht wird.",
    geeignetWenn: ["Auszug, Besuch, Verkauf oder Neustart ansteht", "der Umfang grob beschrieben werden kann"],
    nichtGeeignetWenn: ["regelmaessige Objektpflege gesucht ist", "medizinische Spezialdesinfektion erwartet wird"],
    benoetigteAngaben: ["Ort", "Objektart", "grobe Flaeche", "Zustand", "Terminwunsch"],
    optionaleAngaben: ["Fotos", "Schluesselweg", "besondere Flaechen", "vorhandenes Angebot"],
    typischeAufwandstreiber: ["Flaeche", "Verschmutzungsgrad", "Kueche und Bad", "Fenster", "Zugang"],
    empfohlenerCTA: "Einmalige Reinigung anfragen",
    kontaktParameter: { service: "reinigung", intent: "einmalige-reinigung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["reinigung", "grundreinigung", "endreinigung"],
    relatedSignatureServices: ["Objektbrief", "Uebergabeakte"],
  }),
  packageItem({
    serviceKey: "reinigung-regelmaessig",
    group: "reinigung",
    title: "Regelmaessige Reinigung",
    shortDescription: "Fuer wiederkehrende Reinigung mit Turnus, Raumliste und festen Kontaktpunkten.",
    geeignetWenn: ["Buero, Treppenhaus, Praxisflaeche oder Objekt laufend gepflegt werden soll", "Turnus und Zeitfenster wichtig sind"],
    nichtGeeignetWenn: ["nur ein einmaliger Auszugsschritt offen ist", "ein Soforttermin garantiert werden soll"],
    benoetigteAngaben: ["Objektart", "Flaeche", "Turnus", "gewuenschtes Zeitfenster", "Ansprechpartner"],
    optionaleAngaben: ["Raumliste", "Fotos", "Schluesselregelung", "bestehendes Angebot"],
    typischeAufwandstreiber: ["Turnus", "Sanitaer/Kueche", "Zugang", "Reinigungszeiten", "Sonderanforderungen"],
    empfohlenerCTA: "Turnusreinigung einordnen",
    kontaktParameter: { service: "gewerbereinigung", intent: "regelmaessige-reinigung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["gewerbereinigung", "bueroreinigung", "unterhaltsreinigung"],
    relatedSignatureServices: ["Leistungsumfang", "Objektbetreuung"],
  }),
  packageItem({
    serviceKey: "reinigung-uebergabe-endreinigung",
    group: "reinigung",
    title: "Uebergabe-/Endreinigung",
    shortDescription: "Fuer Auszug, Wohnungsabnahme, Wiedervermietung oder Rueckgabe mit sichtbarem Zielzustand.",
    geeignetWenn: ["Schluesseluebergabe oder Abnahme vorbereitet wird", "Reinigung nach Umzug oder Entruempelung offen ist"],
    nichtGeeignetWenn: ["laufende Unterhaltsreinigung gesucht ist", "eine verbindliche Wohnungsabnahme erwartet wird"],
    benoetigteAngaben: ["Ort", "Flaeche", "Zieltermin", "Zustand", "Raeume"],
    optionaleAngaben: ["Fotos", "Vermietertermin", "Restgegenstaende", "Schluesselweg"],
    typischeAufwandstreiber: ["Bad/Kueche", "Fenster", "Restmoebel", "Frist", "Zugang"],
    empfohlenerCTA: "Endreinigung vorbereiten",
    kontaktParameter: { service: "reinigung", intent: "uebergabe-endreinigung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["endreinigung", "umzug-mit-reinigung"],
    relatedSignatureServices: ["Uebergabeakte", "Schluesseluebergabe"],
  }),
  packageItem({
    serviceKey: "bueroreinigung-gewerbereinigung",
    group: "reinigung",
    title: "Buero-/Gewerbereinigung",
    shortDescription: "Fuer Unternehmen, Kanzleien, Praxen, Hotels und Gewerbeflaechen mit Raumliste und Turnus.",
    geeignetWenn: ["Firma, Objekt oder Verwaltung klare Reinigungsablaeufe braucht", "Flaeche, Turnus und Zeitfenster bekannt sind"],
    nichtGeeignetWenn: ["private Haushaltshilfe gesucht ist", "Zertifikate oder Spezialdesinfektion ohne Pruefung erwartet werden"],
    benoetigteAngaben: ["Firma", "Objektart", "Flaeche", "Turnus", "Reinigungszeit", "Ansprechpartner"],
    optionaleAngaben: ["Raumliste", "Fotos", "Schluesselregelung", "bestehendes Angebot"],
    typischeAufwandstreiber: ["Flaeche", "Turnus", "Sanitaer/Kueche", "Zeitfenster", "Zugang"],
    empfohlenerCTA: "Gewerbeobjekt anfragen",
    kontaktParameter: { service: "bueroreinigung", intent: "b2b-bueroreinigung", source: "b2b", priority: "p0" },
    priority: "p0",
    relatedServices: ["bueroreinigung", "gewerbereinigung", "praxisreinigung"],
    relatedSignatureServices: ["Leistungsverzeichnis", "Angebotspruefung"],
  }),
  packageItem({
    serviceKey: "reinigung-sonderreinigung",
    group: "reinigung",
    title: "Sonderreinigung",
    shortDescription: "Fuer besondere Objektlagen, stark genutzte Bereiche oder Reinigung ausserhalb des Standards.",
    geeignetWenn: ["normaler Turnus nicht reicht", "Fotos und kurze Beschreibung die Lage zeigen koennen"],
    nichtGeeignetWenn: ["Gefahrstoff-, Reinraum- oder medizinische Spezialreinigung erwartet wird"],
    benoetigteAngaben: ["Ort", "Objektart", "Problemstelle", "Flaeche", "Termin"],
    optionaleAngaben: ["Fotos", "Materialhinweise", "Zugang", "bestehende Reinigung"],
    typischeAufwandstreiber: ["Verschmutzung", "Material", "Zugang", "Sicherheitslage", "Frist"],
    empfohlenerCTA: "Sonderfall einordnen",
    kontaktParameter: { service: "reinigung", intent: "sonderreinigung", source: "service-package", priority: "p2" },
    priority: "p2",
    relatedServices: ["grundreinigung", "baureinigung", "notfallreinigung"],
    relatedSignatureServices: ["Objektbrief", "Fotoeinschaetzung"],
  }),
  packageItem({
    serviceKey: "solarreinigung-pv",
    group: "reinigung",
    title: "Solar-/PV-Reinigung",
    shortDescription: "Fuer Modulreinigung nach Dachart, Zugang und Sicherheitslage ohne Ertragsversprechen.",
    geeignetWenn: ["Dachart, Zugang und Modulbereich beschrieben werden koennen", "Fotos vorhanden oder moeglich sind"],
    nichtGeeignetWenn: ["Ertragsgarantie erwartet wird", "unsichere Dachlage ohne Pruefung betreten werden soll"],
    benoetigteAngaben: ["Ort", "Dachart", "Modulflaeche", "Zugang", "Fotos"],
    optionaleAngaben: ["Wasser-/Stromzugang", "Verschmutzungsart", "letzte Reinigung"],
    typischeAufwandstreiber: ["Zugang", "Dachneigung", "Modulflaeche", "Sicherheitslage", "Verschmutzung"],
    empfohlenerCTA: "PV-Reinigung pruefen",
    kontaktParameter: { service: "reinigung", intent: "solarreinigung-pv", source: "service-package", priority: "p2" },
    priority: "p2",
    relatedServices: ["solarreinigung", "sonderreinigung"],
    relatedSignatureServices: ["Fotoeinschaetzung", "Sicherheitscheck"],
  }),
  packageItem({
    serviceKey: "reinigung-nach-entruempelung",
    group: "reinigung",
    title: "Reinigung nach Entruempelung",
    shortDescription: "Fuer Raeume, die nach Raeumung, Kellerleerung oder Wohnungsaufloesung wieder nutzbar werden sollen.",
    geeignetWenn: ["nach der Raeumung Staub, Laufspuren oder Geruch bleiben", "Uebergabe oder Neuvermietung folgt"],
    nichtGeeignetWenn: ["nur Abtransport ohne Zielzustand gebraucht wird"],
    benoetigteAngaben: ["Ort", "Raeume", "Zielzustand", "Termin", "Zugang"],
    optionaleAngaben: ["Fotos", "Restmengen", "Uebergabetermin", "Schluesselweg"],
    typischeAufwandstreiber: ["Reststaub", "Boden", "Bad/Kueche", "Geruch", "Frist"],
    empfohlenerCTA: "Raeumung + Reinigung planen",
    kontaktParameter: { service: "entruempelung", intent: "entruempelung-reinigung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["entruempelung", "endreinigung"],
    relatedSignatureServices: ["Uebergabeakte", "Schluesseluebergabe"],
  }),

  packageItem({
    serviceKey: "mini-umzug",
    group: "umzug",
    title: "Mini-Umzug",
    shortDescription: "Fuer kleine Mengen, einzelne Moebel oder kurze Strecken mit klarer Zugangslage.",
    geeignetWenn: ["wenige Gegenstaende oder kleiner Haushalt transportiert werden", "Start, Ziel und Etage bekannt sind"],
    nichtGeeignetWenn: ["kompletter Haushalt mit vielen Sonderpunkten offen ist"],
    benoetigteAngaben: ["Start", "Ziel", "Gegenstaende", "Etage", "Termin"],
    optionaleAngaben: ["Fotos", "Aufzug", "Haltezone", "Montagebedarf"],
    typischeAufwandstreiber: ["Etage", "Laufweg", "Sonderstuecke", "Terminfenster", "Haltezone"],
    empfohlenerCTA: "Mini-Umzug anfragen",
    kontaktParameter: { service: "umzug", intent: "mini-umzug", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["moebeltransport", "beiladung"],
    relatedSignatureServices: ["Rueckfahrt-Radar", "Plan-B-Service"],
  }),
  packageItem({
    serviceKey: "privatumzug",
    group: "umzug",
    title: "Privatumzug",
    shortDescription: "Fuer Wohnung oder Haus mit Volumen, Strecke, Etage, Zeitfenster und optionalen Zusatzleistungen.",
    geeignetWenn: ["ein privater Umzug in Regensburg, Bayern oder Nahbereich geplant wird", "Volumen grob beschreibbar ist"],
    nichtGeeignetWenn: ["nur Reinigung oder nur Entruempelung gebraucht wird"],
    benoetigteAngaben: ["Start", "Ziel", "Volumen", "Etagen", "Terminfenster"],
    optionaleAngaben: ["Fotos", "Moebelmontage", "Verpackung", "Reinigung danach"],
    typischeAufwandstreiber: ["Volumen", "Etage/Aufzug", "Strecke", "Montage", "Haltezone"],
    empfohlenerCTA: "Privatumzug pruefen",
    kontaktParameter: { service: "umzug", intent: "privatumzug", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["umzug", "umzug-mit-reinigung"],
    relatedSignatureServices: ["Objektbrief", "Uebergabeakte"],
  }),
  packageItem({
    serviceKey: "seniorenumzug",
    group: "umzug",
    title: "Seniorenumzug",
    shortDescription: "Fuer Umzug im Alter mit ruhiger Abstimmung, Angehoerigenkontakt und optionaler Uebergabevorbereitung.",
    geeignetWenn: ["mehr Abstimmung, Ruhe und klare Kontaktwege wichtig sind", "Angehoerige oder Betreuer mitkoordinieren"],
    nichtGeeignetWenn: ["akute medizinische oder rechtliche Betreuung erwartet wird"],
    benoetigteAngaben: ["Ort", "Ziel", "Kontaktperson", "Umfang", "Zeitfenster"],
    optionaleAngaben: ["Fotos", "Abbau/Montage", "Reinigung", "Schluesselweg"],
    typischeAufwandstreiber: ["Abstimmung", "Etage", "Volumen", "Moebelmontage", "Uebergabe"],
    empfohlenerCTA: "Seniorenumzug ruhig anfragen",
    kontaktParameter: { service: "seniorenumzug", intent: "umzug-im-alter-bayern", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["seniorenumzug", "umzug-im-alter"],
    relatedSignatureServices: ["Diskret-Modus", "Schluesseluebergabe"],
  }),
  packageItem({
    serviceKey: "bueroumzug",
    group: "umzug",
    title: "Bueroumzug",
    shortDescription: "Fuer Unternehmen mit Inventar, IT-nahen Gegenstaenden, Betriebspause und klaren Zeitfenstern.",
    geeignetWenn: ["Betriebsunterbrechung gering bleiben soll", "Ansprechpartner und Zeitfenster definiert werden koennen"],
    nichtGeeignetWenn: ["IT-Installation oder Netzwerkarbeit erwartet wird"],
    benoetigteAngaben: ["Firma", "Start", "Ziel", "Inventar", "Zeitfenster", "Ansprechpartner"],
    optionaleAngaben: ["Etagenplan", "Fotos", "Moebelmontage", "Haltezone"],
    typischeAufwandstreiber: ["Zeitfenster", "Inventar", "Etagen", "Laufwege", "Montage"],
    empfohlenerCTA: "Bueroumzug einordnen",
    kontaktParameter: { service: "umzug", intent: "bueroumzug", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["bueroumzug", "gewerbe-umzug"],
    relatedSignatureServices: ["Plan-B-Service", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "moebeltransport",
    group: "umzug",
    title: "Moebeltransport",
    shortDescription: "Fuer einzelne Moebel, sperrige Stuecke oder Transport ohne kompletten Umzug.",
    geeignetWenn: ["einzelne Gegenstaende klar benannt werden koennen", "Start/Ziel und Zugang bekannt sind"],
    nichtGeeignetWenn: ["viele unbekannte Mengen oder Entruempelung im Vordergrund stehen"],
    benoetigteAngaben: ["Gegenstand", "Start", "Ziel", "Etage", "Termin"],
    optionaleAngaben: ["Fotos", "Masse", "Demontage", "Trageweg"],
    typischeAufwandstreiber: ["Gewicht", "Groesse", "Treppenhaus", "Etage", "Sonderstueck"],
    empfohlenerCTA: "Moebeltransport anfragen",
    kontaktParameter: { service: "umzug", intent: "moebeltransport", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["klaviertransport", "beiladung"],
    relatedSignatureServices: ["Rueckfahrt-Radar"],
  }),
  packageItem({
    serviceKey: "beiladung-rueckfahrt",
    group: "umzug",
    title: "Beiladung/Rueckfahrt",
    shortDescription: "Fuer flexible Transporte, wenn Strecke, Terminfenster und Menge zu freien Kapazitaeten passen koennen.",
    geeignetWenn: ["Termin flexibel ist", "Menge und Strecke klar beschrieben sind"],
    nichtGeeignetWenn: ["fester Soforttermin oder exakte Kapazitaetsgarantie erwartet wird"],
    benoetigteAngaben: ["Start", "Ziel", "Menge", "Zeitfenster", "Kontaktweg"],
    optionaleAngaben: ["Fotos", "Abholfenster", "Lieferfenster", "Tragehilfe"],
    typischeAufwandstreiber: ["Strecke", "Flexibilitaet", "Volumen", "Zugang", "Terminfenster"],
    empfohlenerCTA: "Rueckfahrt pruefen",
    kontaktParameter: { service: "umzug", intent: "beiladung-rueckfahrt", source: "service-package", priority: "p2" },
    priority: "p2",
    relatedServices: ["leerfahrt-rueckfahrt", "beiladung"],
    relatedSignatureServices: ["Rueckfahrt-Radar"],
  }),
  packageItem({
    serviceKey: "express-plan-b-umzug",
    group: "umzug",
    title: "Express-/Plan-B-Umzug",
    shortDescription: "Fuer wackelige Anbieter, kurzfristige Aenderungen oder dringend zu pruefende Alternativen.",
    geeignetWenn: ["Plan A unsicher ist", "Dringlichkeit ehrlich genannt werden kann"],
    nichtGeeignetWenn: ["garantierter Soforteinsatz erwartet wird"],
    benoetigteAngaben: ["Was ist passiert?", "Start/Ziel", "Umfang", "Deadline", "Kontaktweg"],
    optionaleAngaben: ["bestehendes Angebot", "Fotos", "Zeitfenster", "Plan-A-Status"],
    typischeAufwandstreiber: ["Frist", "Verfuegbarkeit", "Volumen", "Zugang", "Sonderstuecke"],
    empfohlenerCTA: "Plan B pruefen",
    kontaktParameter: { service: "umzug", intent: "plan-b-umzug", source: "service-package", priority: "p0" },
    priority: "p0",
    relatedServices: ["plan-b-service", "schadensbegrenzung"],
    relatedSignatureServices: ["Plan-B-Service", "Fairpreis-Check"],
  }),

  packageItem({
    serviceKey: "entruempelung-keller-garage",
    group: "entruempelung",
    title: "Keller/Garage",
    shortDescription: "Fuer kleinere Raeume mit Menge, Zugang, Fotos und Zielzustand.",
    geeignetWenn: ["Keller, Garage oder Nebenraum leer werden soll", "Fotos den Umfang zeigen koennen"],
    nichtGeeignetWenn: ["ganze Wohnung oder Nachlass gemeint ist"],
    benoetigteAngaben: ["Ort", "Raum", "Menge", "Zugang", "Termin"],
    optionaleAngaben: ["Fotos", "Materialarten", "Parkmoeglichkeit", "Reinigung danach"],
    typischeAufwandstreiber: ["Menge", "Etage/Zugang", "Material", "Laufwege", "Frist"],
    empfohlenerCTA: "Keller/Garage pruefen",
    kontaktParameter: { service: "entruempelung", intent: "keller-garage-entruempelung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["kleinmengen-entsorgung", "entruempelung"],
    relatedSignatureServices: ["Fotoeinschaetzung"],
  }),
  packageItem({
    serviceKey: "entruempelung-wohnung-haus",
    group: "entruempelung",
    title: "Wohnung/Haus",
    shortDescription: "Fuer Raeumung groesserer Wohnflaechen mit Zugang, Freigabe, Entsorgung und Zielzustand.",
    geeignetWenn: ["mehrere Raeume oder ein ganzes Objekt betroffen sind", "Uebergabe, Verkauf oder Renovierung folgt"],
    nichtGeeignetWenn: ["nur ein einzelnes Moebel transportiert werden soll"],
    benoetigteAngaben: ["Ort", "Raeume", "Menge", "Zugang", "Zielzustand"],
    optionaleAngaben: ["Fotos", "Freigabe", "Schluesselweg", "Reinigung danach"],
    typischeAufwandstreiber: ["Menge", "Raeume", "Etage", "Entsorgung", "Demontage"],
    empfohlenerCTA: "Wohnung/Haus raeumen",
    kontaktParameter: { service: "entruempelung", intent: "wohnung-haus-entruempelung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["wohnungsaufloesung", "entruempelung"],
    relatedSignatureServices: ["Uebergabeakte", "Schluesseluebergabe"],
  }),
  packageItem({
    serviceKey: "haushaltsaufloesung",
    group: "entruempelung",
    title: "Haushaltsaufloesung",
    shortDescription: "Fuer Haushalte, die vollstaendig oder teilweise aufgeloest und danach uebergabefaehig werden sollen.",
    geeignetWenn: ["Freigabe, Ansprechpartner und Zielzustand geklaert werden koennen", "Raeumung und Reinigung zusammenhaengen"],
    nichtGeeignetWenn: ["Eigentumsfragen ungeklaert sind", "Wertgutachten erwartet wird"],
    benoetigteAngaben: ["Ort", "Ansprechpartner", "Umfang", "Freigabe", "Termin"],
    optionaleAngaben: ["Fotos", "Schluesselweg", "Reinigung", "Uebergabetermin"],
    typischeAufwandstreiber: ["Raeume", "Material", "Freigabe", "Zugang", "Frist"],
    empfohlenerCTA: "Haushaltsaufloesung anfragen",
    kontaktParameter: { service: "wohnungsaufloesung", intent: "haushaltsaufloesung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["haushaltsaufloesung", "wohnungsaufloesung"],
    relatedSignatureServices: ["Uebergabeakte", "Diskret-Modus"],
  }),
  packageItem({
    serviceKey: "nachlassaufloesung",
    group: "entruempelung",
    title: "Nachlassaufloesung",
    shortDescription: "Fuer Nachlass- und Angehoerigenfaelle mit ruhiger Abstimmung und klarer Freigabe.",
    geeignetWenn: ["Ansprechpartner und Freigabe vorhanden sind", "diskrete Kommunikation wichtig ist"],
    nichtGeeignetWenn: ["Rechtsberatung, Mediation oder Wertgutachten erwartet werden"],
    benoetigteAngaben: ["Ort", "Kontaktperson", "Raeume", "Freigabe", "Ziel"],
    optionaleAngaben: ["Fotos", "Schluesselweg", "Termin", "Reinigung danach"],
    typischeAufwandstreiber: ["Freigabe", "Menge", "Sensible Situation", "Zugang", "Sortierung"],
    empfohlenerCTA: "Nachlass ruhig abstimmen",
    kontaktParameter: { service: "wohnungsaufloesung", intent: "nachlassaufloesung", source: "discreet", priority: "p1" },
    priority: "p1",
    relatedServices: ["nachlass-raeumung", "wohnungsaufloesung"],
    relatedSignatureServices: ["Diskret-Modus", "Schluesseluebergabe"],
  }),
  packageItem({
    serviceKey: "buero-lageraufloesung",
    group: "entruempelung",
    title: "Buero-/Lageraufloesung",
    shortDescription: "Fuer Firmen, Lager, Buero- oder Nebenflaechen mit Inventar, Freigabe und Terminlogik.",
    geeignetWenn: ["Firma oder Verwaltung Raeume leeren muss", "Ansprechpartner und Zugang klar sind"],
    nichtGeeignetWenn: ["Gefahrstoffe, Aktenvernichtung oder IT-Loeschung erwartet werden"],
    benoetigteAngaben: ["Firma", "Ort", "Flaeche", "Inventar", "Termin", "Ansprechpartner"],
    optionaleAngaben: ["Fotos", "Zugang", "Demontage", "Reinigung danach"],
    typischeAufwandstreiber: ["Inventar", "Etage", "Demontage", "Entsorgung", "Zeitfenster"],
    empfohlenerCTA: "Gewerbeflaeche raeumen",
    kontaktParameter: { service: "entruempelung", intent: "buero-lageraufloesung", source: "b2b", priority: "p1" },
    priority: "p1",
    relatedServices: ["firmenentsorgung", "gewerbe-auszug"],
    relatedSignatureServices: ["Plan-B-Service", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "entruempelung-diskreter-fall",
    group: "entruempelung",
    title: "Diskreter Fall",
    shortDescription: "Fuer sensible Wohnungs-, Nachlass- oder Trennungsfaelle mit zurueckhaltender Kommunikation.",
    geeignetWenn: ["Ruhiger Kontaktweg wichtig ist", "nicht alle Details schriftlich erklaert werden sollen"],
    nichtGeeignetWenn: ["akute Gefahr, Gewalt oder rechtliche Konfliktloesung vorliegt"],
    benoetigteAngaben: ["Ort", "Kontaktweg", "grober Umfang", "Zeitfenster"],
    optionaleAngaben: ["Rueckrufzeit", "Fotos", "Berechtigungshinweis", "Schluesselweg"],
    typischeAufwandstreiber: ["Sensible Lage", "Freigabe", "Zugang", "Menge", "Frist"],
    empfohlenerCTA: "Diskret anfragen",
    kontaktParameter: { service: "diskret-service", intent: "diskret-service", source: "discreet", priority: "p0" },
    priority: "p0",
    relatedServices: ["diskreter-umzug-trennung-scheidung", "private-client-service"],
    relatedSignatureServices: ["Diskret-Modus", "Uebergabeakte"],
  }),
  packageItem({
    serviceKey: "entruempelung-reinigung",
    group: "entruempelung",
    title: "Entruempelung + Reinigung",
    shortDescription: "Fuer Raeumung mit anschliessender Reinigung, Uebergabe oder Neuvermietung.",
    geeignetWenn: ["nach der Raeumung ein nutzbarer Zustand gebraucht wird", "Reinigung und Zieltermin zusammenhaengen"],
    nichtGeeignetWenn: ["nur Transport ohne Raeumung oder Reinigung gemeint ist"],
    benoetigteAngaben: ["Ort", "Raeume", "Menge", "Zielzustand", "Termin"],
    optionaleAngaben: ["Fotos", "Uebergabetermin", "Schluesselweg", "Restpunkte"],
    typischeAufwandstreiber: ["Raeumung", "Reststaub", "Bad/Kueche", "Zugang", "Frist"],
    empfohlenerCTA: "Kombi-Fall senden",
    kontaktParameter: { service: "entruempelung", intent: "entruempelung-plus-reinigung", source: "service-package", priority: "p1" },
    priority: "p1",
    relatedServices: ["entruempelung", "endreinigung"],
    relatedSignatureServices: ["Uebergabeakte", "Schluesseluebergabe"],
  }),

  packageItem({
    serviceKey: "angebot-pruefen",
    group: "angebot-pruefen",
    title: "Angebot pruefen",
    shortDescription: "Fuer vorhandene Angebote, Screenshots oder Preisnennungen mit offenen Leistungsfragen.",
    geeignetWenn: ["Preis, Umfang oder Zusatzkosten unklar wirken", "ein Dokument, Screenshot oder Eckdaten vorliegen"],
    nichtGeeignetWenn: ["Rechtsberatung oder Anbieterbewertung erwartet wird"],
    benoetigteAngaben: ["Service", "Ort", "Angebotsumfang", "Preispositionen", "Pruefgrund"],
    optionaleAngaben: ["PDF/Screenshot", "Fotos", "Termin", "Vergleichsangebot"],
    typischeAufwandstreiber: ["Leistungsumfang", "Zusatzkosten", "Termin", "Zugang", "Vergleichbarkeit"],
    empfohlenerCTA: "Angebot pruefen lassen",
    kontaktParameter: { service: "angebot-pruefen", intent: "angebot-pruefen", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["angebotscheck", "angebot-guenstiger-pruefen"],
    relatedSignatureServices: ["Fairpreis-Check", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "anbieter-vergleichen",
    group: "angebot-pruefen",
    title: "Anbieter vergleichen",
    shortDescription: "Fuer mehrere Angebote oder Anbieter, die schwer nach Umfang und Risiko vergleichbar sind.",
    geeignetWenn: ["mehrere Angebote vorliegen", "Leistungen nicht deckungsgleich beschrieben sind"],
    nichtGeeignetWenn: ["Ranking, Bewertung oder Diffamierung anderer Anbieter erwartet wird"],
    benoetigteAngaben: ["Anzahl Angebote", "Serviceart", "Ort", "Unterschiede", "wichtigste Frage"],
    optionaleAngaben: ["Preispositionen", "Fotos", "Termin", "Budgetrahmen"],
    typischeAufwandstreiber: ["Leistungsgrenzen", "Zusatzpositionen", "Termine", "Zugang", "Risiko"],
    empfohlenerCTA: "Vergleich sortieren",
    kontaktParameter: { service: "angebot-pruefen", intent: "anbieter-vergleichen", source: "offer-check", priority: "p1" },
    priority: "p1",
    relatedServices: ["anbieter-vergleichen", "angebotscheck"],
    relatedSignatureServices: ["Fairpreis-Check", "Plan-B-Service"],
  }),
  packageItem({
    serviceKey: "zweitmeinung",
    group: "angebot-pruefen",
    title: "Zweitmeinung",
    shortDescription: "Fuer Kunden, die vor Zusage eine sachliche zweite Einordnung brauchen.",
    geeignetWenn: ["ein Angebot gut wirkt, aber Unsicherheit bleibt", "Kunden wissen wollen, welche Rueckfragen sinnvoll sind"],
    nichtGeeignetWenn: ["ein garantierter Gegenpreis erwartet wird"],
    benoetigteAngaben: ["Service", "Ort", "Termin", "Unsicherheit", "Angebot oder Eckdaten"],
    optionaleAngaben: ["Fotos", "Budget", "Vergleichsangebot", "Deadline"],
    typischeAufwandstreiber: ["Unsicherheit", "Leistungsumfang", "Termin", "Fotos", "Zusatzkosten"],
    empfohlenerCTA: "Zweitmeinung anfragen",
    kontaktParameter: { service: "angebot-pruefen", intent: "zweitmeinung", source: "offer-check", priority: "p1" },
    priority: "p1",
    relatedServices: ["angebot-pruefen", "objektbrief"],
    relatedSignatureServices: ["Fairpreis-Check", "Objektbrief"],
  }),
  packageItem({
    serviceKey: "plan-b-anbieterabsage",
    group: "angebot-pruefen",
    title: "Plan-B bei Anbieterabsage",
    shortDescription: "Fuer wackelige Zusagen, abgesagte Termine oder Anfragen, bei denen ein naechster Schritt gebraucht wird.",
    geeignetWenn: ["Anbieter nicht reagiert oder abgesagt hat", "Deadline, Umfang und Ort klar benannt werden koennen"],
    nichtGeeignetWenn: ["Sofortgarantie ohne Pruefung erwartet wird"],
    benoetigteAngaben: ["Was ist passiert?", "Service", "Ort", "Deadline", "Umfang"],
    optionaleAngaben: ["Angebot", "Fotos", "Kontaktweg", "Plan-A-Status"],
    typischeAufwandstreiber: ["Dringlichkeit", "Verfuegbarkeit", "Umfang", "Zugang", "Zeitfenster"],
    empfohlenerCTA: "Plan B pruefen",
    kontaktParameter: { service: "angebot-pruefen", intent: "plan-b-anbieterabsage", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["plan-b-service", "schadensbegrenzung"],
    relatedSignatureServices: ["Plan-B-Service", "Fairpreis-Check"],
  }),
  packageItem({
    serviceKey: "reinigungsfirma-angebot-pruefen",
    group: "angebot-pruefen",
    title: "Reinigungsfirma-Angebot pruefen",
    shortDescription: "Fuer Reinigung, Buero, Gewerbe, Endreinigung oder Turnusangebote mit offenen Umfangspunkten.",
    geeignetWenn: ["Flaeche, Turnus oder Leistungsumfang unklar sind", "B2B-Angebot oder Reinigungsangebot vorliegt"],
    nichtGeeignetWenn: ["zertifizierte Spezialhygiene bewertet werden soll"],
    benoetigteAngaben: ["Flaeche", "Objektart", "Turnus", "Leistungsumfang", "Pruefgrund"],
    optionaleAngaben: ["Angebot", "Fotos", "Zeitfenster", "Ansprechpartner"],
    typischeAufwandstreiber: ["Flaeche", "Turnus", "Sanitaer/Kueche", "Zeitfenster", "Zugang"],
    empfohlenerCTA: "Reinigungsangebot pruefen",
    kontaktParameter: { service: "angebot-pruefen", intent: "reinigungsangebot-pruefen", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["reinigung", "bueroreinigung", "gewerbereinigung"],
    relatedSignatureServices: ["Leistungsverzeichnis", "Fairpreis-Check"],
  }),
  packageItem({
    serviceKey: "umzugsangebot-pruefen",
    group: "angebot-pruefen",
    title: "Umzugsangebot pruefen",
    shortDescription: "Fuer Umzug, Transport oder Moebelangebote, bei denen Volumen, Strecke oder Zusatzleistungen unklar sind.",
    geeignetWenn: ["Start/Ziel, Etage oder Volumen nicht klar beruecksichtigt sind", "Zusatzkosten moeglich wirken"],
    nichtGeeignetWenn: ["rechtliche Vertragsbewertung erwartet wird"],
    benoetigteAngaben: ["Start", "Ziel", "Etage", "Volumen", "Angebot", "Pruefgrund"],
    optionaleAngaben: ["Fotos", "Haltezone", "Montage", "Termin"],
    typischeAufwandstreiber: ["Volumen", "Etagen", "Strecke", "Haltezone", "Sonderstuecke"],
    empfohlenerCTA: "Umzugsangebot pruefen",
    kontaktParameter: { service: "angebot-pruefen", intent: "umzugsangebot-pruefen", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["umzug", "klaviertransport", "beiladung"],
    relatedSignatureServices: ["Rueckfahrt-Radar", "Plan-B-Service"],
  }),
  packageItem({
    serviceKey: "entruempelungsangebot-pruefen",
    group: "angebot-pruefen",
    title: "Entruempelungsangebot pruefen",
    shortDescription: "Fuer Raeumung, Entsorgung oder Haushaltsaufloesung mit unklarer Menge, Zugang oder Entsorgung.",
    geeignetWenn: ["Menge, Raeume, Zugang oder Entsorgung offen sind", "Reinigung danach relevant sein kann"],
    nichtGeeignetWenn: ["Wertgutachten, Rechtsberatung oder Anbieterbewertung erwartet wird"],
    benoetigteAngaben: ["Raeume", "Menge", "Zugang", "Angebot", "Termin", "Pruefgrund"],
    optionaleAngaben: ["Fotos", "Materialarten", "Freigabe", "Reinigung danach"],
    typischeAufwandstreiber: ["Menge", "Zugang", "Entsorgung", "Material", "Frist"],
    empfohlenerCTA: "Raeumungsangebot pruefen",
    kontaktParameter: { service: "angebot-pruefen", intent: "entruempelungsangebot-pruefen", source: "offer-check", priority: "p0" },
    priority: "p0",
    relatedServices: ["entruempelung", "wohnungsaufloesung"],
    relatedSignatureServices: ["Uebergabeakte", "Fairpreis-Check"],
  }),
];

export function getServicePackages(input: ServicePackageInput = "all") {
  if (input === "all") return servicePackages;
  const groups = Array.isArray(input) ? input : [input];
  return servicePackages.filter((item) => groups.includes(item.group));
}

export function getServicePackage(serviceKey: string) {
  return servicePackages.find((item) => item.serviceKey === serviceKey);
}

export function buildServicePackageHref(item: ServicePackage, destination = "/kontakt") {
  return buildLeadHref(
    {
      service: item.kontaktParameter.service,
      city: item.kontaktParameter.city,
      intent: item.kontaktParameter.intent,
      priority: item.kontaktParameter.priority,
      ctaLabel: item.empfohlenerCTA,
    },
    destination,
  ).replace("source=seo", `source=${item.kontaktParameter.source}`);
}

export const servicePackageGroups: Record<ServicePackageGroup, { title: string; intro: string }> = {
  reinigung: {
    title: "Reinigungs-Pakete ohne Schnellpreis",
    intro: "Waehlen Sie den passenden Startpunkt. Preise entstehen erst aus Flaeche, Zustand, Zugang, Turnus und Termin.",
  },
  umzug: {
    title: "Umzugs-Pakete nach Umfang und Risiko",
    intro: "Der richtige Weg haengt von Volumen, Etagen, Strecke, Terminfenster und Zusatzleistungen ab.",
  },
  entruempelung: {
    title: "Raeumungs-Pakete mit Zielzustand",
    intro: "Keller, Wohnung, Nachlass oder Gewerbeflaeche brauchen unterschiedliche Angaben zu Menge, Zugang und Freigabe.",
  },
  "angebot-pruefen": {
    title: "Angebotscheck-Pakete",
    intro: "Der Check sortiert Angebot, Umfang, Warnsignale und naechste Schritte ohne Preisgarantie oder Rechtsberatung.",
  },
};
