export type NavigationPriority = "P0" | "P1" | "P2" | "P3";
export type NavigationVisibility = "main-nav" | "service-hub" | "location-hub" | "footer" | "contact-form" | "internal";

export type ServiceNavigationItem = {
  serviceKey: string;
  name: string;
  explanation: string;
  group: "reinigung" | "umzug_transport" | "entruempelung_aufloesung" | "angebot_pruefen" | "signature" | "standort";
  subgroup: string;
  customer: string;
  situation: string;
  primaryRoute: string;
  secondaryRoute?: string;
  duesseldorf: boolean;
  regensburg: boolean;
  serviceArea50km: boolean;
  contactParams: string;
  offerCheckUseful: boolean;
  signatureServices: readonly string[];
  specialServices: readonly string[];
  visibility: readonly NavigationVisibility[];
  priority: NavigationPriority;
};

export const serviceNavigationTaxonomy: readonly ServiceNavigationItem[] = [
  {
    serviceKey: "reinigung",
    name: "Reinigung",
    explanation: "Allgemeine Reinigung für Wohnung, Objekt, Auszug oder Übergabe.",
    group: "reinigung",
    subgroup: "Basisreinigung",
    customer: "Privat und Gewerbe",
    situation: "Objekt soll sauber, übergabefähig oder wieder nutzbar werden.",
    primaryRoute: "/reinigung",
    secondaryRoute: "/duesseldorf/reinigung",
    duesseldorf: true,
    regensburg: true,
    serviceArea50km: true,
    contactParams: "service=reinigung",
    offerCheckUseful: true,
    signatureServices: ["Objektbrief", "Übergabeakte", "Angebotscheck"],
    specialServices: ["Grundreinigung", "Endreinigung", "Reinigung nach Entrümpelung"],
    visibility: ["main-nav", "service-hub", "location-hub", "footer", "contact-form"],
    priority: "P0",
  },
  {
    serviceKey: "bueroreinigung",
    name: "Büroreinigung",
    explanation: "Büros, Kanzleien und Teams mit Raumliste, Turnus und Zeitfenster.",
    group: "reinigung",
    subgroup: "B2B-Reinigung",
    customer: "Gewerbekunden",
    situation: "Regelmäßige oder einmalige Büroreinigung soll vergleichbar werden.",
    primaryRoute: "/reinigung#bueroreinigung",
    secondaryRoute: "/duesseldorf/bueroreinigung",
    duesseldorf: true,
    regensburg: true,
    serviceArea50km: true,
    contactParams: "service=bueroreinigung",
    offerCheckUseful: true,
    signatureServices: ["Büro-Startklar-Service", "Fairpreis-Check"],
    specialServices: ["Unterhaltsreinigung", "Praxisreinigung", "Gewerbereinigung"],
    visibility: ["service-hub", "location-hub", "contact-form"],
    priority: "P0",
  },
  {
    serviceKey: "gewerbereinigung",
    name: "Gewerbereinigung",
    explanation: "Gewerbe, Praxis, Hotel oder gemischte Flächen nach Nutzung und Zugang.",
    group: "reinigung",
    subgroup: "B2B-Reinigung",
    customer: "Unternehmen und Verwaltungen",
    situation: "Fläche, Turnus und Zuständigkeit müssen vor Anfrage klar werden.",
    primaryRoute: "/reinigung#gewerbereinigung",
    secondaryRoute: "/duesseldorf/gewerbereinigung",
    duesseldorf: true,
    regensburg: true,
    serviceArea50km: true,
    contactParams: "service=gewerbereinigung",
    offerCheckUseful: true,
    signatureServices: ["Büro-Startklar-Service", "Objektbrief"],
    specialServices: ["Büroreinigung", "Praxisreinigung", "Hotelreinigung"],
    visibility: ["service-hub", "location-hub", "contact-form"],
    priority: "P0",
  },
  {
    serviceKey: "fensterreinigung",
    name: "Fenster- und Glasreinigung",
    explanation: "Fenster, Glas, Rahmen und erreichbare Außenbereiche nach Zugang und Höhe.",
    group: "reinigung",
    subgroup: "Spezialreinigung",
    customer: "Privat, Gewerbe und Hausverwaltung",
    situation: "Anzahl, Seite, Höhe und Zugang fehlen in vielen Anfragen.",
    primaryRoute: "/reinigung#fensterreinigung",
    secondaryRoute: "/duesseldorf/fensterreinigung",
    duesseldorf: true,
    regensburg: true,
    serviceArea50km: true,
    contactParams: "service=fensterreinigung",
    offerCheckUseful: true,
    signatureServices: ["PV-Sichtklar-Service"],
    specialServices: ["Glasreinigung", "Fassadenreinigung"],
    visibility: ["service-hub", "location-hub", "contact-form"],
    priority: "P1",
  },
  {
    serviceKey: "umzug",
    name: "Umzug und Transport",
    explanation: "Wohnungswechsel, Mini-Umzug, Möbeltransport oder Rückfahrt mit Route und Volumen.",
    group: "umzug_transport",
    subgroup: "Umzug",
    customer: "Privat und Gewerbe",
    situation: "Start, Ziel, Etage, Laufweg und Termin müssen zusammenpassen.",
    primaryRoute: "/regensburg/umzug",
    secondaryRoute: "/umzug-regensburg",
    duesseldorf: true,
    regensburg: true,
    serviceArea50km: true,
    contactParams: "service=umzug",
    offerCheckUseful: true,
    signatureServices: ["Rückfahrt-Radar", "Plan-B-Service"],
    specialServices: ["Kleintransport", "Klaviertransport", "Beiladung"],
    visibility: ["main-nav", "service-hub", "location-hub", "footer", "contact-form"],
    priority: "P0",
  },
  {
    serviceKey: "klaviertransport",
    name: "Klaviertransport",
    explanation: "Sonderstück-Transport mit Gewicht, Etage, Zugang und Strecke.",
    group: "umzug_transport",
    subgroup: "Sondertransport",
    customer: "Privat, Musiker, Einrichtungen",
    situation: "Ein schweres oder empfindliches Stück muss separat geplant werden.",
    primaryRoute: "/klaviertransport-regensburg",
    secondaryRoute: "/klaviertransport",
    duesseldorf: false,
    regensburg: true,
    serviceArea50km: true,
    contactParams: "service=klaviertransport&city=regensburg",
    offerCheckUseful: true,
    signatureServices: ["Rückfahrt-Radar", "Objektbrief"],
    specialServices: ["Möbeltransport", "Kleintransport"],
    visibility: ["service-hub", "location-hub", "contact-form"],
    priority: "P1",
  },
  {
    serviceKey: "seniorenumzug",
    name: "Seniorenumzug",
    explanation: "Umzug im Alter mit Angehörigen, Umfang, Reduzierung und Übergabe ruhig einordnen.",
    group: "umzug_transport",
    subgroup: "Sensible Umzüge",
    customer: "Senioren, Angehörige und organisierende Kontaktpersonen",
    situation: "Umzug, Entrümpelung, Reinigung oder Übergabe müssen zusammen vorbereitet werden.",
    primaryRoute: "/seniorenumzug-bayern",
    secondaryRoute: "/regensburg/seniorenumzug",
    duesseldorf: false,
    regensburg: true,
    serviceArea50km: true,
    contactParams: "service=seniorenumzug&intent=seniorenumzug-anfragen",
    offerCheckUseful: true,
    signatureServices: ["Diskret-Service", "Objektbrief", "Übergabeakte"],
    specialServices: ["Entrümpelung", "Reinigung", "Plan-B-Service"],
    visibility: ["service-hub", "location-hub", "footer", "contact-form"],
    priority: "P1",
  },
  {
    serviceKey: "entruempelung",
    name: "Entrümpelung und Räumung",
    explanation: "Keller, Wohnung, Nebenraum, Lager oder Restmengen nach Fotos und Zugang.",
    group: "entruempelung_aufloesung",
    subgroup: "Räumung",
    customer: "Privat, Gewerbe, Hausverwaltung",
    situation: "Menge, Material, Zugang und Zielzustand sind noch unscharf.",
    primaryRoute: "/regensburg/entruempelung",
    secondaryRoute: "/entruempelung-regensburg",
    duesseldorf: true,
    regensburg: true,
    serviceArea50km: true,
    contactParams: "service=entruempelung",
    offerCheckUseful: true,
    signatureServices: ["Diskret-Service", "Übergabeakte"],
    specialServices: ["Haushaltsauflösung", "Nachlass", "Reinigung nach Entrümpelung"],
    visibility: ["main-nav", "service-hub", "location-hub", "footer", "contact-form"],
    priority: "P0",
  },
  {
    serviceKey: "haushaltsaufloesung",
    name: "Haushaltsauflösung",
    explanation: "Wohnung oder Haushalt mit Freigabe, Fotos, Restmengen und sensibler Abstimmung.",
    group: "entruempelung_aufloesung",
    subgroup: "Auflösung",
    customer: "Angehörige, Eigentümer, Verwaltungen",
    situation: "Haushalt, Nachlass oder Übergabe muss ruhig sortiert werden.",
    primaryRoute: "/regensburg/haushaltsaufloesung",
    secondaryRoute: "/wohnungsaufloesung-regensburg",
    duesseldorf: true,
    regensburg: true,
    serviceArea50km: true,
    contactParams: "service=haushaltsaufloesung",
    offerCheckUseful: true,
    signatureServices: ["Diskret-Service", "Objektbrief"],
    specialServices: ["Wohnungsauflösung", "Entrümpelung", "Reinigung"],
    visibility: ["service-hub", "location-hub", "contact-form"],
    priority: "P1",
  },
  {
    serviceKey: "angebot-pruefen",
    name: "Angebot prüfen",
    explanation: "Vorhandenes Angebot, Screenshot oder Preis nach Umfang und Annahmen einordnen.",
    group: "angebot_pruefen",
    subgroup: "Vergleich",
    customer: "Privat und Gewerbe",
    situation: "Preis, Umfang oder Anbieterannahmen wirken unklar.",
    primaryRoute: "/angebot-guenstiger-pruefen",
    secondaryRoute: "/angebotscheck",
    duesseldorf: true,
    regensburg: true,
    serviceArea50km: true,
    contactParams: "service=angebot-pruefen&intent=angebot-pruefen",
    offerCheckUseful: true,
    signatureServices: ["Fairpreis-Check", "Entscheidungs-Kompass"],
    specialServices: ["Anbieter vergleichen", "Plan-B bei Anbieterabsage"],
    visibility: ["main-nav", "service-hub", "location-hub", "footer", "contact-form"],
    priority: "P0",
  },
  {
    serviceKey: "diskret-service",
    name: "Diskret-Service",
    explanation: "Sensible Anfrage mit minimalem Erstkontakt und ruhigem Kontaktweg.",
    group: "signature",
    subgroup: "Diskretion",
    customer: "Privat, Angehörige, sensible Situationen",
    situation: "Details sollen nicht im ersten Schritt breit geteilt werden.",
    primaryRoute: "/diskreter-umzug-trennung-scheidung",
    secondaryRoute: "/signature-services",
    duesseldorf: true,
    regensburg: true,
    serviceArea50km: true,
    contactParams: "service=diskret-service&intent=diskret-service",
    offerCheckUseful: false,
    signatureServices: ["Diskret-Service", "Private-Client-Service"],
    specialServices: ["Haushaltsauflösung", "Entrümpelung"],
    visibility: ["service-hub", "location-hub", "footer", "contact-form"],
    priority: "P0",
  },
  {
    serviceKey: "plan-b-service",
    name: "Plan-B-Service",
    explanation: "Wenn Anbieter ausfällt, Termin kippt oder ein Fall neu sortiert werden muss.",
    group: "signature",
    subgroup: "Dringlichkeit",
    customer: "Privat und Gewerbe",
    situation: "Es braucht schnell eine realistische zweite Einordnung ohne Sofortgarantie.",
    primaryRoute: "/plan-b-service",
    secondaryRoute: "/signature-services",
    duesseldorf: true,
    regensburg: true,
    serviceArea50km: true,
    contactParams: "service=angebot-pruefen&intent=plan-b-service",
    offerCheckUseful: true,
    signatureServices: ["Plan-B-Service", "Entscheidungs-Kompass"],
    specialServices: ["Angebotscheck", "Express-Anfrage"],
    visibility: ["service-hub", "location-hub", "footer", "contact-form"],
    priority: "P0",
  },
  {
    serviceKey: "pv-sichtklar",
    name: "PV-Sichtklar-Service",
    explanation: "PV- und Solarreinigung nach Dachart, Zugang, Fotos und Sicherheitsgrenzen.",
    group: "signature",
    subgroup: "PV und Glas",
    customer: "Privat und Gewerbe",
    situation: "PV/Glas/Fassade ist verschmutzt, aber Zugang und Sicherheit sind offen.",
    primaryRoute: "/pv-anlagen-reinigung",
    secondaryRoute: "/regensburg/solarreinigung",
    duesseldorf: false,
    regensburg: true,
    serviceArea50km: true,
    contactParams: "service=reinigung&city=regensburg&intent=pv-sichtklar",
    offerCheckUseful: true,
    signatureServices: ["PV-Sichtklar-Service", "Fairpreis-Check"],
    specialServices: ["Solarreinigung", "Glasreinigung", "Fassadenreinigung"],
    visibility: ["service-hub", "location-hub", "contact-form"],
    priority: "P1",
  },
];

export const primaryHeaderLinks = [
  { label: "Düsseldorf", href: "/duesseldorf" },
  { label: "Regensburg", href: "/regensburg" },
  { label: "Angebot prüfen", href: "/angebot-guenstiger-pruefen" },
  { label: "Besondere Lösungen", href: "/signature-services" },
  { label: "Kontakt", href: "/kontakt" },
] as const;

export const mobileQuickLinks = [
  { label: "Leistungen", href: "/leistungen" },
  ...primaryHeaderLinks,
  { label: "Unsicher?", href: "/kontakt?service=sonstiges&intent=unsichere-anfrage&source=mobile-nav" },
] as const;

export const footerNavigationGroups = [
  {
    title: "Leistungen",
    links: [
      { label: "Reinigung", href: "/reinigung" },
      { label: "Umzug", href: "/regensburg/umzug" },
      { label: "Seniorenumzug", href: "/seniorenumzug-bayern" },
      { label: "Entrümpelung", href: "/regensburg/entruempelung" },
      { label: "Angebot prüfen", href: "/angebot-guenstiger-pruefen" },
    ],
  },
  {
    title: "Standorte",
    links: [
      { label: "Düsseldorf", href: "/duesseldorf" },
      { label: "Regensburg", href: "/regensburg" },
      { label: "Servicegebiet ca. 50 km", href: "/regensburg" },
    ],
  },
  {
    title: "Besondere Lösungen",
    links: [
      { label: "Angebotscheck", href: "/angebotscheck" },
      { label: "Plan-B-Service", href: "/plan-b-service" },
      { label: "Diskret-Service", href: "/diskreter-umzug-trennung-scheidung" },
      { label: "Objektbrief", href: "/objektbrief" },
      { label: "Rückfahrt-Radar", href: "/rueckfahrt-boerse" },
    ],
  },
  {
    title: "Kontakt",
    links: [
      { label: "Kontaktseite", href: "/kontakt" },
      { label: "Anfrage stellen", href: "/kontakt?service=sonstiges&intent=unsichere-anfrage&source=footer" },
      { label: "Angebot prüfen", href: "/kontakt?service=angebot-pruefen&intent=angebot-pruefen&source=footer" },
    ],
  },
] as const;

export const decisionCompassItems = [
  {
    problem: "Wohnung muss übergeben werden",
    recommendation: "Reinigung, Entrümpelung, Übergabeakte oder Objektbrief prüfen.",
    href: "/kontakt?service=reinigung&intent=wohnungsuebergabe&source=decision-compass",
  },
  {
    problem: "Angebot wirkt unklar oder teuer",
    recommendation: "Angebotscheck, Fairpreis-Check oder Anbieter vergleichen.",
    href: "/angebot-guenstiger-pruefen",
  },
  {
    problem: "Anbieter hat abgesagt",
    recommendation: "Plan-B-Service mit Frist, Ort, Fotos und vorhandenem Angebot starten.",
    href: "/kontakt?service=angebot-pruefen&intent=plan-b-anbieterabsage&source=decision-compass",
  },
  {
    problem: "Sensibler Fall",
    recommendation: "Diskret-Service, Haushaltsauflösung oder Entrümpelung mit sicherem Kontaktweg.",
    href: "/kontakt?service=diskret-service&intent=diskret-service&source=decision-compass",
  },
  {
    problem: "Büro oder Gewerbe",
    recommendation: "Büroreinigung, Gewerbereinigung, Büro-Startklar oder Angebotsprüfung.",
    href: "/kontakt?service=bueroreinigung&intent=b2b-bueroreinigung&source=decision-compass",
  },
  {
    problem: "Umzug mit Sonderstück",
    recommendation: "Umzug, Klaviertransport, Möbeltransport oder Rückfahrt/Beiladung.",
    href: "/kontakt?service=klaviertransport&city=regensburg&intent=sondertransport&source=decision-compass",
  },
  {
    problem: "PV, Glas oder Fassade verschmutzt",
    recommendation: "Solarreinigung, PV-Sichtklar, Glasreinigung oder Fassadenreinigung nach Zugang prüfen.",
    href: "/kontakt?service=reinigung&city=regensburg&intent=pv-sichtklar&source=decision-compass",
  },
] as const;

export const englishIntentLinks = [
  { label: "Cleaning service", href: "/kontakt?service=cleaning&city=regensburg&intent=english-cleaning&source=english-intent" },
  { label: "Office cleaning", href: "/kontakt?service=office-cleaning&city=regensburg&intent=english-office-cleaning&source=english-intent" },
  { label: "Moving help", href: "/kontakt?service=moving&city=regensburg&intent=english-moving&source=english-intent" },
  { label: "House clearance", href: "/kontakt?service=house-clearance&intent=english-house-clearance&source=english-intent" },
  { label: "Piano transport", href: "/kontakt?service=piano-transport&city=regensburg&intent=english-piano-transport&source=english-intent" },
  { label: "Offer check", href: "/kontakt?service=offer-check&intent=english-offer-check&source=english-intent" },
] as const;

export function getTaxonomyByGroup(group: ServiceNavigationItem["group"]) {
  return serviceNavigationTaxonomy.filter((item) => item.group === group);
}
