/**
 * FLOXANT Sitemap Configuration
 * Centralized route definitions for the current sitemap architecture.
 * DE, EN and RU are indexable.
 */

export const BASE_URL = "https://www.floxant.de";
export const LASTMOD = new Date().toISOString().split("T")[0];

/** Active locales with dedicated sitemap files */
export const MAJOR_LOCALES = ["de", "en", "ru"] as const;

// --- Route Definitions ---

/** Homepage */
export const HOMEPAGE = "";

/** Core service pages */
export const CORE_SERVICES = [
    "umzug",
    "bueroumzug",
    "fernumzug",
    "reinigung",
    "entruempelung",
    "kleintransporte",
    "montage",
    "halteverbotszone",
] as const;

/** City/Geo pages */
export const CITY_PAGES = [
    "umzug-bayern",
    "umzug-muenchen",
    "umzug-nuernberg",
    "umzug-augsburg",
    "umzug-regensburg",
    "umzug-passau",
    "umzug-neumarkt",
    "umzug-schwandorf",
    "umzug-amberg",
    "umzug-feucht",
    "umzug-straubing",
    "umzug-landshut",
    "umzug-ingolstadt",
    "umzug-weiden",
    "umzug-neutraubling",
    "umzug-obertraubling",
    "umzug-pentling",
    "umzug-lappersdorf",
    "umzug-regenstauf",
    "umzug-zeitlarn",
    "umzug-wenzenbach",
    "umzug-tegernheim",
    "umzug-donaustauf",
    "umzug-barbing",
    "umzug-alteglofsheim",
    "umzug-hagelstadt",
    "umzug-koefering",
    "umzug-thalmassing",
    "umzug-bad-abbach",
    "umzug-kelheim",
    "umzug-saal-an-der-donau",
    "umzug-abensberg",
    "umzug-neustadt-an-der-donau",
    "umzug-langquaid",
    "umzug-schierling",
    "umzug-nittendorf",
    "umzug-sinzing",
    "umzug-deuerling",
    "umzug-laaber",
    "umzug-beratzhausen",
    "umzug-hemau",
    "umzug-brunn",
    "umzug-duggendorf",
    "umzug-kallmuenz",
    "umzug-holzheim-am-forst",
    "umzug-wolfsegg",
    "umzug-pettendorf",
    "umzug-pielenhofen",
    "umzug-hohenfels",
    "umzug-parsberg",
    "umzug-lupburg",
    "umzug-velburg",
    "umzug-seubersdorf",
    "umzug-burglengenfeld",
    "umzug-teublitz",
    "umzug-maxhuette-haidhof",
    "umzug-nittenau",
    "umzug-bernhardswald",
    "umzug-altenthann",
    "umzug-brennberg",
    "umzug-woerth-an-der-donau",
    "umzug-wiesent",
    "umzug-pfatter",
    "umzug-mintraching",
    "umzug-riekofen",
    "umzug-aufhausen",
    "umzug-suenching",
    "umzug-moetzing",
    "umzug-geiselhoering",
    "umzug-mallersdorf-pfaffenberg",
    "umzug-ergoldsbach",
    "umzug-neufahrn-in-niederbayern",
    "umzug-rottenburg-an-der-laaber",
    "umzug-pfeffenhausen",
    "umzug-dietfurt",
    "umzug-berching",
    "umzug-freystadt",
    "umzug-postbauer-heng",
    "umzug-altdorf-bei-nuernberg",
    "umzug-lauf-an-der-pegnitz",
    "umzug-schwabach",
    "umzug-roth",
    "umzug-wendelstein",
    "umzug-mainburg",
    "umzug-moosburg",
    "umzug-freising",
    "umzug-erding",
    "umzug-pfaffenhofen",
    "umzug-wolnzach",
    "umzug-geisenfeld",
    "umzug-vohburg",
    "umzug-dachau",
    "umzug-fuerstenfeldbruck",
    "umzug-olching",
    "umzug-mammendorf",
    "umzug-mering",
    "umzug-friedberg",
    "umzug-kissing",
    "umzug-koenigsbrunn",
    "umzug-fuerth",
    "umzug-erlangen",
    "umzug-herzogenaurach",
    "umzug-zirndorf",
    "umzug-oberasbach",
    "umzug-wuerzburg",
    "umzug-bamberg",
    "umzug-bayreuth",
    "umzug-coburg",
    "umzug-schweinfurt",
    "umzug-ansbach",
    "umzug-forchheim",
    "umzug-rosenheim",
    "umzug-starnberg",
    "umzug-germering",
    "umzug-unterhaching",
    "umzug-garching",
    "umzug-bad-toelz",
    "umzug-landsberg-am-lech",
    "umzug-weilheim-in-oberbayern",
    "umzug-traunstein",
    "umzug-kempten",
    "umzug-memmingen",
    "umzug-kaufbeuren",
    "umzug-neu-ulm",
    "umzug-gersthofen",
    "umzug-neusaess",
    "umzug-guenzburg",
    "umzug-dingolfing",
    "umzug-deggendorf",
    "umzug-vilshofen",
    "umzug-pocking",
    "umzug-plattling",
    "umzug-cham",
    "umzug-tirschenreuth",
    "umzug-sulzbach-rosenberg",
    "umzug-oberpfalz",
    "umzug-landkreis-regensburg",
    "umzug-hausen",
    "umzug-kulmbach",
    "umzug-guenzburg",
    "umzug-lindau",
    "umzug-muenchen-schwabing",
    "umzug-muenchen-bogenhausen",
    "umzug-nuernberg-gostenhof",
] as const;

/** Service-specific city pages */
export const SERVICE_CITY_PAGES = [
    "reinigung-regensburg",
    "entruempelung-regensburg",
    "bueroumzug-regensburg",
    "reinigung-muenchen",
    "reinigung-nuernberg",
    "reinigung-augsburg",
    "reinigung-passau",
    "reinigung-landshut",
    "entruempelung-muenchen",
    "entruempelung-nuernberg",
    "entruempelung-augsburg",
    "entruempelung-passau",
    "entruempelung-landshut",
    "seniorenumzug-regensburg",
    "seniorenumzug-nuernberg",
    "seniorenumzug-muenchen",
    "halteverbotszone-regensburg",
    "halteverbotszone-nuernberg",
    "halteverbotszone-muenchen",
    "klaviertransport-passau",
    "klaviertransport-straubing",
    "klaviertransport-rosenheim",
    "klaviertransport-amberg",
    "klaviertransport-weiden",
    "klaviertransport-freising",
    "klaviertransport-dachau",
    "bueroumzug-muenchen",
    "bueroumzug-nuernberg",
    "bueroumzug-augsburg",
    "bueroumzug-ingolstadt",
    "bueroumzug-landshut",
    "seniorenumzug-augsburg",
    "seniorenumzug-landshut",
    "seniorenumzug-passau",
    "seniorenumzug-ingolstadt",
    "reinigung-rosenheim",
    "entruempelung-rosenheim",
    "reinigung-wuerzburg",
    "entruempelung-wuerzburg",
    "reinigung-deggendorf",
    "entruempelung-deggendorf",
    "reinigung-ingolstadt",
    "entruempelung-ingolstadt",
    "reinigung-straubing",
    "entruempelung-straubing",
    "reinigung-kempten",
    "entruempelung-kempten",
    "reinigung-amberg",
    "entruempelung-amberg",
    "reinigung-weiden",
    "entruempelung-weiden",
    "reinigung-freising",
    "entruempelung-freising",
    "reinigung-dachau",
    "entruempelung-dachau",
    "reinigung-erlangen",
    "entruempelung-erlangen",
    "entruempelung-bamberg",
    "entruempelung-bayreuth",
    "entruempelung-fuerth",
    "entruempelung-kaufbeuren",
    "entruempelung-memmingen",
    "umzug-berlin",
    "umzug-hamburg",
    "umzug-koeln",
    "umzug-frankfurt",
    "umzug-stuttgart",
    "umzug-duesseldorf",
    "umzug-leipzig",
    "umzug-dortmund",
    "umzug-essen",
    "umzug-bremen",
    "umzug-reinigung-regensburg",
    "reinigung-fuerth",
    "reinigung-erlangen",
    "reinigung-bamberg",
    "reinigung-bayreuth",
    "reinigung-kulmbach",
    "reinigung-starnberg",
    "reinigung-garmisch-partenkirchen",
] as const;

/** Bavaria authority pages */
export const BAVARIA_AUTHORITY_PAGES = [
    "entruempelung-bayern",
    "reinigung-bayern",
    "wohnungsaufloesung-bayern",
    "service-area-bayern",
] as const;

/** Signature SEO landing pages */
export const SIGNATURE_SEO_PAGES = [
    "24h-umzug-bayern",
    "studentenumzug-regensburg",
    "familienumzug-bayern",
    "seniorenumzug-bayern",
    "kurzfristiger-umzug-bayern",
    "notfall-umzug-bayern",
    "studentenumzug-bayern",
] as const;

/** Hub landing pages */
export const HUB_PAGES = [
    "wissen",
    "alternativen",
    "standorte",
] as const;

/** Long-tail / cost pages */
export const LONGTAIL_PAGES = [
    "umzugskosten-bayern",
    "entruempelung-kosten-regensburg",
] as const;

/** Ratgeber / Blog pages */
export const RATGEBER_PAGES = [
    "ratgeber",
    "ratgeber/umzug-kosten-regensburg",
    "ratgeber/checkliste-umzug",
    "ratgeber/gute-umzugsfirma-finden",
    "ratgeber/entruempelung-kosten-pro-m3",
    "ratgeber/umzug-vorbereiten-7-schritte",
    "ratgeber/wann-lohnt-sich-umzugsfirma",
    "ratgeber/moebeltransport-sicher",
    "ratgeber/umzug-tipps-familien",
    "ratgeber/reinigung-nach-umzug",
    "ratgeber/umzug-kosten-rechner",
    "ratgeber/umzug-anmelden-ummelden",
    "ratgeber/umzug-versicherung",
    "ratgeber/wohnungsaufloesung-tipps",
    "ratgeber/umzug-im-winter",
    "ratgeber/umzug-erste-wohnung",
    "blog",
    "blog/umzug-kosten-regensburg",
    "blog/entrumpelung-kosten-bayern",
    "blog/umzug-checkliste",
    "blog/umzug-tipps-bayern",
    "blog/wohnungsaufloesung-was-tun",
    "blog/umzug-planen-schritt-fuer-schritt",
    "blog/umzugskosten-senken-7-tipps",
    "blog/wohnungsuebergabe-protokoll-guide",
    "blog/fernumzug-bayern-nrw-tipps",
    "blog/umzug-mit-kindern-stressfrei",
] as const;

/** Signature services (dynamic route /signature/[slug]) */
export const SIGNATURE_SERVICES = [
    "ritual-exit-box",
    "clean-start",
    "new-neighbour-kit",
    "first-48h",
    "buerokratie-schutz",
    "moebel-optimierung",
    "reinigungsgarantie",
    "lager-rotation",
    "kinder-umzugsbox",
    "24h-umzugsservice",
    "damen-team",
    "erinnerungskapsel",
    "vielleicht-box",
    "schluesseluebergabe",
] as const;

/** Legal pages */
export const LEGAL_PAGES = [
    "impressum",
    "datenschutz",
    "agb",
    "widerruf",
    "buchungsbedingungen",
] as const;

export interface SitemapUrl {
    loc: string;
    lastmod: string;
    changefreq: "daily" | "weekly" | "monthly" | "yearly";
    priority: string;
    pagePath: string;
}

/** Final sitemap files in the current architecture (DE-only) */
export const SITEMAP_SEGMENTS = [
    "sitemap.xml",
    "sitemap-de.xml",
] as const;