import type { LocalSeoCityRecord } from "./types";

const indexableM1 = {
  indexStatus: "index",
  maturityLevel: "M1",
  passedChecks: [
    "eindeutige Suchintention",
    "lokaler Einstieg",
    "konkrete Leistungen",
    "FAQ vorhanden",
    "interne Links vorhanden",
    "keine lokale Standortbehauptung",
  ],
} as const;

const indexableM2 = {
  indexStatus: "index",
  maturityLevel: "M2",
  passedChecks: [
    "eindeutige Suchintention",
    "lokaler Einstieg",
    "konkrete Leistungen",
    "Kundensituationen",
    "Ablauf",
    "Angebotsprüfung",
    "FAQ vorhanden",
    "strukturierte Daten",
  ],
} as const;

export const localSeoCities = {
  duesseldorf: {
    slug: "duesseldorf",
    displayName: "Düsseldorf",
    region: "duesseldorf",
    parentHub: "/region-duesseldorf",
    serviceFocus: ["Reinigung", "Grundreinigung", "Putzfirma", "Büroreinigung", "Praxisreinigung", "Angebotsprüfung"],
    nearbyCities: ["Neuss", "Meerbusch", "Ratingen", "Hilden", "Erkrath", "Köln"],
    districts: ["Heerdt", "Oberkassel", "Bilk", "Pempelfort", "Derendorf", "Benrath"],
    customerTypes: ["Privathaushalte", "Büros", "Praxen", "Kanzleien", "Hausverwaltungen", "Gewerbeflächen"],
    relevantServices: ["reinigung", "grundreinigung", "putzfirma", "reinigungsdienst", "wohnungsreinigung", "angebot-vergleichen"],
    specialCases: ["Reinigung vor Übergabe", "Grundreinigung nach Renovierung", "Geruchsneutralisation", "Angebotsprüfung"],
    localIntro:
      "Düsseldorf ist das Hauptzentrum für FLOXANT-Reinigung. Entscheidend sind Stadtteil, Objektart, Zugang, Fotos, Termin und der gewünschte Zielzustand.",
    localProofNotes: [
      "Düsseldorf besitzt einen eigenen Reinigungsbereich mit lokaler Adresse.",
      "Umzugssignale werden getrennt von Reinigung geführt.",
      "Heerdt, Oberkassel, Bilk und Pempelfort werden nicht als austauschbare Textliste behandelt.",
    ],
    maturity: indexableM2,
  },
  koeln: {
    slug: "koeln",
    displayName: "Köln",
    region: "duesseldorf",
    parentHub: "/region-duesseldorf",
    serviceFocus: ["Büroreinigung", "Praxisreinigung", "Wohnungsreinigung", "Grundreinigung", "Treppenhausreinigung", "Gewerbereinigung"],
    nearbyCities: ["Leverkusen", "Bonn", "Hürth", "Frechen", "Pulheim", "Düsseldorf"],
    districts: ["Innenstadt", "Ehrenfeld", "Lindenthal", "Nippes", "Deutz", "Rodenkirchen"],
    customerTypes: ["Büros", "Praxen", "Privathaushalte", "Hausverwaltungen", "Gewerbeflächen"],
    relevantServices: ["reinigung", "grundreinigung", "wohnungsreinigung", "treppenhausreinigung", "angebot-vergleichen"],
    specialCases: ["Büroflächen mit Randzeiten", "Praxisflächen", "Wohnungsübergabe", "bestehendes Reinigungsangebot"],
    localIntro:
      "Köln wird als eigener Großstadtmarkt behandelt. FLOXANT betreut Reinigungsanfragen in Köln im Rahmen des regionalen Einsatzgebiets, ohne eine Kölner Filiale zu behaupten.",
    localProofNotes: [
      "Köln braucht eigene Prioritäten: Büro, Praxis, Wohnung, Grundreinigung und Treppenhaus.",
      "Leverkusen, Bonn, Hürth, Frechen und Pulheim werden als regionale Bezugspunkte genannt.",
      "Angebotsprüfung wird als zweiter Einstieg genutzt, wenn bereits ein Angebot vorliegt.",
    ],
    maturity: indexableM1,
  },
  neuss: {
    slug: "neuss",
    displayName: "Neuss",
    region: "duesseldorf",
    parentHub: "/region-duesseldorf",
    serviceFocus: ["Wohnungsreinigung", "Büroreinigung", "Grundreinigung", "Treppenhausreinigung", "Praxisreinigung"],
    nearbyCities: ["Meerbusch", "Kaarst", "Dormagen", "Grevenbroich", "Düsseldorf-Heerdt"],
    districts: ["Innenstadt", "Furth", "Norf", "Reuschenberg", "Grimlinghausen"],
    customerTypes: ["Mieter", "Vermieter", "Büros", "Praxen", "Hausverwaltungen"],
    relevantServices: ["reinigung", "wohnungsreinigung", "grundreinigung", "treppenhausreinigung", "angebot-vergleichen"],
    specialCases: ["Reinigung nach Auszug", "Wohnungsübergabe", "Treppenhaus", "Angebotsprüfung"],
    localIntro:
      "Neuss liegt im Rhein-Kreis Neuss direkt am Düsseldorfer Einsatzgebiet. Häufig geht es um Wohnungsreinigung, Büroflächen und Übergabetermine.",
    localProofNotes: [
      "Düsseldorf-Heerdt ist als naher Bezugspunkt relevant.",
      "Meerbusch, Kaarst, Dormagen und Grevenbroich werden als Nachbarorte mitgedacht.",
      "Die Seite behauptet keinen eigenen Standort in Neuss.",
    ],
    maturity: indexableM1,
  },
  meerbusch: {
    slug: "meerbusch",
    displayName: "Meerbusch",
    region: "duesseldorf",
    parentHub: "/region-duesseldorf",
    serviceFocus: ["Haushaltsreinigung", "Büroreinigung", "Praxisreinigung", "Treppenhausreinigung", "Grundreinigung"],
    nearbyCities: ["Düsseldorf", "Neuss", "Kaarst", "Krefeld", "Willich"],
    districts: ["Büderich", "Osterath", "Lank-Latum", "Strümp", "Ilverich"],
    customerTypes: ["Privathaushalte", "Praxen", "Büros", "Hausverwaltungen"],
    relevantServices: ["reinigung", "haushaltsreinigung", "grundreinigung", "treppenhausreinigung", "angebot-vergleichen"],
    specialCases: ["regelmäßige Haushaltsreinigung", "Praxisflächen", "Treppenhaus", "Angebot vergleichen"],
    localIntro:
      "Meerbusch-Anfragen werden im Düsseldorfer Einsatzgebiet eingeordnet. Besonders wichtig sind Büderich, Osterath, Lank-Latum sowie die Nähe zu Düsseldorf und Neuss.",
    localProofNotes: [
      "Privathaushalte, Praxen und Hausverwaltungen werden getrennt angesprochen.",
      "Der lokale Bezug entsteht über Stadtteile und typische Objektarten.",
      "Es wird keine Meerbuscher Filiale behauptet.",
    ],
    maturity: indexableM1,
  },
  duisburg: {
    slug: "duisburg",
    displayName: "Duisburg",
    region: "duesseldorf",
    parentHub: "/region-duesseldorf",
    serviceFocus: ["Gewerbereinigung", "Büroreinigung", "Wohnungsreinigung", "Grundreinigung", "Treppenhausreinigung"],
    nearbyCities: ["Düsseldorf", "Oberhausen", "Mülheim an der Ruhr", "Krefeld", "Moers"],
    districts: ["Innenstadt", "Duissern", "Neudorf", "Wanheimerort", "Rheinhausen"],
    customerTypes: ["Gewerbe", "Büros", "Privathaushalte", "Hausverwaltungen"],
    relevantServices: ["reinigung", "grundreinigung", "wohnungsreinigung", "gebaeudereinigung", "angebot-vergleichen"],
    specialCases: ["Reinigung nach Auszug", "Entrümpelung plus Reinigung", "Geruchsneutralisation", "Angebotsprüfung"],
    localIntro:
      "Duisburg verbindet Ruhrgebiet und Düsseldorfer Einzugsgebiet. Reinigungsanfragen betreffen oft Gewerbe, Büro, Wohnung, Treppenhaus oder Grundreinigung.",
    localProofNotes: [
      "Ruhrgebiets- und Düsseldorf-Bezug werden sachlich erklärt.",
      "Gewerbe, Büro und Wohnung werden nicht in einen Standardtext geworfen.",
      "Geruchsneutralisation wird vorsichtig ohne Garantieversprechen genannt.",
    ],
    maturity: indexableM1,
  },
  moenchengladbach: {
    slug: "moenchengladbach",
    displayName: "Mönchengladbach",
    region: "duesseldorf",
    parentHub: "/region-duesseldorf",
    serviceFocus: ["Haushaltsreinigung", "Büroreinigung", "Praxisreinigung", "Grundreinigung", "Treppenhausreinigung"],
    nearbyCities: ["Düsseldorf", "Neuss", "Viersen", "Korschenbroich", "Willich"],
    districts: ["Rheydt", "Eicken", "Wickrath", "Hardterbroich", "Odenkirchen"],
    customerTypes: ["Privathaushalte", "Büros", "Praxen", "Hausverwaltungen"],
    relevantServices: ["reinigung", "haushaltsreinigung", "grundreinigung", "treppenhausreinigung", "angebot-vergleichen"],
    specialCases: ["Wohnung vor Übergabe", "Büroflächen", "Praxisreinigung", "bestehendes Angebot prüfen"],
    localIntro:
      "Mönchengladbach wird im Niederrhein-Kontext betrachtet. FLOXANT prüft Reinigung nach Objekt, Fotos, Termin und Nähe zu Düsseldorf, Neuss oder Viersen.",
    localProofNotes: [
      "Rheydt, Eicken und Wickrath geben der Seite lokalen Bezug.",
      "Niederrhein und Düsseldorf werden als Einsatzkontext erklärt.",
      "Keine lokale Filiale wird behauptet.",
    ],
    maturity: indexableM1,
  },
  krefeld: {
    slug: "krefeld",
    displayName: "Krefeld",
    region: "duesseldorf",
    parentHub: "/region-duesseldorf",
    serviceFocus: ["Büroreinigung", "Gewerbereinigung", "Grundreinigung", "Wohnungsreinigung", "Treppenhausreinigung"],
    nearbyCities: ["Meerbusch", "Düsseldorf", "Duisburg", "Willich", "Kempen"],
    districts: ["Innenstadt", "Bockum", "Uerdingen", "Fischeln", "Oppum"],
    customerTypes: ["Büros", "Gewerbe", "Hausverwaltungen", "Privathaushalte"],
    relevantServices: ["reinigung", "grundreinigung", "gebaeudereinigung", "wohnungsreinigung", "angebot-vergleichen"],
    specialCases: ["Gewerbeflächen", "Büroflächen", "Wohnungsübergabe", "Angebotsprüfung"],
    localIntro:
      "Krefeld liegt im Niederrhein-Kontext mit Nähe zu Meerbusch, Düsseldorf und Duisburg. Für Reinigung zählen Objektart, Turnus, Fotos und Zugang.",
    localProofNotes: [
      "Bockum, Uerdingen und Fischeln bieten lokale Einordnung.",
      "Gewerbe und Büro werden als eigene Suchintention behandelt.",
      "Angebotsprüfung ist der klare Conversion-Weg.",
    ],
    maturity: indexableM1,
  },
  ratingen: {
    slug: "ratingen",
    displayName: "Ratingen",
    region: "duesseldorf",
    parentHub: "/region-duesseldorf",
    serviceFocus: ["Büroreinigung", "Praxisreinigung", "Gewerbereinigung", "Treppenhausreinigung", "Grundreinigung"],
    nearbyCities: ["Düsseldorf", "Mettmann", "Heiligenhaus", "Essen", "Duisburg"],
    districts: ["Mitte", "Lintorf", "Tiefenbroich", "Hösel", "West"],
    customerTypes: ["Büros", "Gewerbe", "Praxen", "Hausverwaltungen"],
    relevantServices: ["reinigung", "grundreinigung", "gebaeudereinigung", "treppenhausreinigung", "angebot-vergleichen"],
    specialCases: ["Büros in Flughafen-Nähe", "Gewerbeobjekte", "Praxisflächen", "Treppenhaus"],
    localIntro:
      "Ratingen ist für Büro, Gewerbe und Praxis durch die Nähe zu Düsseldorf und zum Flughafen besonders relevant. FLOXANT prüft nach Raumliste, Turnus und Zugang.",
    localProofNotes: [
      "Flughafen-Nähe wird als realistischer Gewerbefaktor benannt.",
      "Lintorf, Tiefenbroich und Hösel werden mitgedacht.",
      "Die Seite bewirbt keinen eigenen Standort in Ratingen.",
    ],
    maturity: indexableM1,
  },
  hilden: {
    slug: "hilden",
    displayName: "Hilden",
    region: "duesseldorf",
    parentHub: "/region-duesseldorf",
    serviceFocus: ["Wohnungsreinigung", "Treppenhausreinigung", "Büroreinigung", "Grundreinigung"],
    nearbyCities: ["Düsseldorf", "Erkrath", "Langenfeld", "Solingen", "Haan"],
    districts: ["Mitte", "Süd", "Ost", "West", "Nord"],
    customerTypes: ["Mieter", "Vermieter", "Büros", "Hausverwaltungen"],
    relevantServices: ["reinigung", "wohnungsreinigung", "grundreinigung", "treppenhausreinigung", "angebot-vergleichen"],
    specialCases: ["Reinigung vor Übergabe", "Treppenhaus", "Büro", "Angebot prüfen"],
    localIntro:
      "Hilden liegt zwischen Düsseldorf, Erkrath, Langenfeld und Solingen. Typisch sind Wohnungsreinigung, Treppenhaus, Büro und Grundreinigung vor Übergabe.",
    localProofNotes: [
      "Der lokale Korridor Richtung Erkrath, Langenfeld und Solingen wird erklärt.",
      "Wohnungsübergabe und Hausverwaltung sind als Kundensituationen sichtbar.",
      "Angebotsprüfung wird als risikoarmer Einstieg genannt.",
    ],
    maturity: indexableM1,
  },
  erkrath: {
    slug: "erkrath",
    displayName: "Erkrath",
    region: "duesseldorf",
    parentHub: "/region-duesseldorf",
    serviceFocus: ["Wohnungsreinigung", "Hausverwaltungen", "Treppenhausreinigung", "Grundreinigung"],
    nearbyCities: ["Düsseldorf", "Hilden", "Mettmann", "Haan", "Ratingen"],
    districts: ["Alt-Erkrath", "Hochdahl", "Unterfeldhaus", "Trills", "Millrath"],
    customerTypes: ["Mieter", "Vermieter", "Hausverwaltungen", "Privathaushalte"],
    relevantServices: ["reinigung", "wohnungsreinigung", "grundreinigung", "treppenhausreinigung", "angebot-vergleichen"],
    specialCases: ["Wohnungsübergabe", "Treppenhaus", "Hausverwaltung", "Grundreinigung"],
    localIntro:
      "Erkrath wird mit Düsseldorf, Hilden und Mettmann zusammen gedacht. Für Reinigung zählen Wohnung, Treppenhaus, Zugang, Fotos und Übergabetermin.",
    localProofNotes: [
      "Hochdahl und Unterfeldhaus schaffen konkrete lokale Nähe.",
      "Hausverwaltungen werden als Zielgruppe benannt.",
      "Keine eigene Erkrather Filiale wird behauptet.",
    ],
    maturity: indexableM1,
  },
  regensburg: {
    slug: "regensburg",
    displayName: "Regensburg",
    region: "regensburg",
    parentHub: "/region-regensburg",
    serviceFocus: ["Umzug", "Umzugsservice", "Umzugskosten", "Seniorenumzug", "Wohnungsauflösung", "Reinigung nach Umzug"],
    nearbyCities: ["Straubing", "Landshut", "Kelheim", "Schwandorf", "Amberg", "Neumarkt"],
    districts: ["Altstadt", "Westenviertel", "Kumpfmühl", "Prüfening", "Burgweinting", "Reinhausen"],
    customerTypes: ["Privatkunden", "Senioren", "Angehörige", "Vermieter", "Erben", "Unternehmen"],
    relevantServices: ["umzug", "umzugsservice", "umzug-kosten", "seniorenumzug", "wohnungsaufloesung", "angebot-vergleichen"],
    specialCases: ["Umzugsangebot prüfen", "Wohnungsauflösung mit Reinigung", "Seniorenumzug", "Reinigung nach Auszug"],
    localIntro:
      "Regensburg ist das Hauptzentrum für Umzug, Entrümpelung, Wohnungsauflösung und Reinigung nach Umzug. Volumen, Etage, Zugang, Fotos und Termin entscheiden den Ablauf.",
    localProofNotes: [
      "Regensburg hat die zentrale FLOXANT-Unternehmensadresse.",
      "Stadtteile und Landkreis werden nach Machbarkeit eingeordnet.",
      "Düsseldorf-Reinigung bleibt getrennt.",
    ],
    maturity: indexableM2,
  },
  landshut: {
    slug: "landshut",
    displayName: "Landshut",
    region: "regensburg",
    parentHub: "/region-regensburg",
    serviceFocus: ["Privatumzug", "Seniorenumzug", "Firmenumzug", "Möbeltransport", "Entrümpelung", "Wohnungsauflösung", "Reinigung nach Umzug"],
    nearbyCities: ["Regensburg", "München", "Freising", "Moosburg", "Vilsbiburg"],
    districts: ["Altstadt", "Nikola", "West", "Achdorf", "Wolfgang"],
    customerTypes: ["Privathaushalte", "Senioren", "Angehörige", "Unternehmen", "Vermieter"],
    relevantServices: ["umzug", "umzugsservice", "seniorenumzug", "wohnungsaufloesung", "reinigung-nach-umzug"],
    specialCases: ["Umzugsangebot prüfen", "Umzug mit Reinigung", "Seniorenumzug", "Entrümpelung vor Umzug"],
    localIntro:
      "Landshut wird im Regensburger Einsatzgebiet mit Blick auf Niederbayern, München, Freising, Moosburg und Vilsbiburg eingeordnet.",
    localProofNotes: [
      "Niederbayern und der Korridor Richtung München werden realistisch benannt.",
      "Umzug, Entrümpelung und Reinigung nach Umzug werden zusammen gedacht, aber getrennt beschrieben.",
      "Keine Landshuter Filiale wird behauptet.",
    ],
    maturity: indexableM1,
  },
  straubing: {
    slug: "straubing",
    displayName: "Straubing",
    region: "regensburg",
    parentHub: "/region-regensburg",
    serviceFocus: ["Privatumzug", "Seniorenumzug", "Wohnungsauflösung", "Entrümpelung", "Transport", "Reinigung nach Auszug"],
    nearbyCities: ["Regensburg", "Deggendorf", "Bogen", "Dingolfing", "Landshut"],
    districts: ["Zentrum", "Kagers", "Ittling", "Alburg", "Hornstorf"],
    customerTypes: ["Privathaushalte", "Senioren", "Angehörige", "Erben", "Vermieter"],
    relevantServices: ["umzug", "umzugsservice", "seniorenumzug", "wohnungsaufloesung", "reinigung-nach-umzug"],
    specialCases: ["Angebot vergleichen", "Nachlasswohnung", "Auszug mit Reinigung", "kleiner Transport"],
    localIntro:
      "Straubing-Anfragen werden mit Regensburg, Deggendorf, Bogen und Dingolfing zusammen betrachtet. Häufig geht es um Umzug, Auflösung und Reinigung nach Auszug.",
    localProofNotes: [
      "Straubing bekommt eigene Nachbarorte und Kundensituationen.",
      "Wohnungsauflösung und Reinigung werden als typische Zusatzthemen genannt.",
      "Angebotsvergleich ist ein klarer CTA.",
    ],
    maturity: indexableM1,
  },
  ingolstadt: {
    slug: "ingolstadt",
    displayName: "Ingolstadt",
    region: "regensburg",
    parentHub: "/region-regensburg",
    serviceFocus: ["Privatumzug", "Firmenumzug", "Seniorenumzug", "Entrümpelung", "Wohnungsauflösung"],
    nearbyCities: ["Regensburg", "Neuburg", "Eichstätt", "Manching", "Pfaffenhofen"],
    districts: ["Mitte", "Nordost", "Südwest", "Mailing", "Gerolfing"],
    customerTypes: ["Privathaushalte", "Unternehmen", "Senioren", "Angehörige"],
    relevantServices: ["umzug", "umzugsservice", "umzug-kosten", "seniorenumzug", "wohnungsaufloesung"],
    specialCases: ["Umzugskosten prüfen", "Firmenumzug", "Seniorenumzug", "Entrümpelung vor Auszug"],
    localIntro:
      "Ingolstadt wird als eigener Oberbayern-Markt im Regensburger Servicegebiet eingeordnet. Kosten, Volumen und Zugang sind oft die wichtigsten Fragen.",
    localProofNotes: [
      "Oberbayern, Neuburg, Eichstätt und Manching schaffen den lokalen Rahmen.",
      "Kostenprüfung wird als Hauptintention priorisiert.",
      "Keine falsche Ingolstädter Filiale.",
    ],
    maturity: indexableM1,
  },
  neumarkt: {
    slug: "neumarkt",
    displayName: "Neumarkt in der Oberpfalz",
    region: "regensburg",
    parentHub: "/region-regensburg",
    serviceFocus: ["Privatumzug", "Seniorenumzug", "Entrümpelung", "Wohnungsauflösung", "Transport"],
    nearbyCities: ["Regensburg", "Nürnberg", "Parsberg", "Berching", "Postbauer-Heng"],
    districts: ["Stadtmitte", "Woffenbach", "Pölling", "Hasenheide", "Wolfstein"],
    customerTypes: ["Privathaushalte", "Senioren", "Angehörige", "Vermieter"],
    relevantServices: ["umzug", "umzugsservice", "umzug-kosten", "seniorenumzug", "wohnungsaufloesung"],
    specialCases: ["Umzugsangebot prüfen", "kleiner Transport", "Wohnungsauflösung", "Seniorenumzug"],
    localIntro:
      "Neumarkt liegt zwischen Regensburg und Nürnberg. FLOXANT prüft Umzüge nach Volumen, Strecke, Zugang, Fotos und Zusatzleistungen.",
    localProofNotes: [
      "Oberpfalz und Nürnberg-Regensburg-Achse sind der lokale Kontext.",
      "Seniorenumzug, Wohnungsauflösung und Transport werden getrennt erklärt.",
      "Der CTA führt zur Angebotsprüfung.",
    ],
    maturity: indexableM1,
  },
  weiden: {
    slug: "weiden",
    displayName: "Weiden in der Oberpfalz",
    region: "regensburg",
    parentHub: "/region-regensburg",
    serviceFocus: ["Privatumzug", "Seniorenumzug", "Firmenumzug", "Entrümpelung", "Wohnungsauflösung"],
    nearbyCities: ["Amberg", "Schwandorf", "Regensburg", "Tirschenreuth", "Neustadt an der Waldnaab"],
    districts: ["Altstadt", "Hammerweg", "Moosbürg", "Rehbühl", "Stockerhut"],
    customerTypes: ["Privathaushalte", "Senioren", "Unternehmen", "Angehörige"],
    relevantServices: ["umzug", "umzugsservice", "seniorenumzug", "wohnungsaufloesung", "angebot-vergleichen"],
    specialCases: ["Angebot prüfen", "Seniorenumzug", "Firmenumzug", "Räumung plus Reinigung"],
    localIntro:
      "Weiden wird im Oberpfalz-Kontext mit Amberg, Schwandorf und Regensburg betrachtet. Wichtig sind Strecke, Volumen, Etage, Fotos und Terminfenster.",
    localProofNotes: [
      "Oberpfalz-Bezug ist klar sichtbar.",
      "Privat-, Senioren- und Firmenumzug werden unterschieden.",
      "Keine lokale Standortbehauptung.",
    ],
    maturity: indexableM1,
  },
  schwandorf: {
    slug: "schwandorf",
    displayName: "Schwandorf",
    region: "regensburg",
    parentHub: "/region-regensburg",
    serviceFocus: ["Privatumzug", "Wohnungsauflösung", "Entrümpelung", "Möbeltransport", "Reinigung nach Auszug"],
    nearbyCities: ["Regensburg", "Amberg", "Burglengenfeld", "Cham", "Nabburg"],
    districts: ["Mitte", "Dachelhofen", "Fronberg", "Kreith", "Klardorf"],
    customerTypes: ["Privathaushalte", "Vermieter", "Senioren", "Angehörige"],
    relevantServices: ["umzug", "umzugsservice", "wohnungsaufloesung", "entruempelung", "reinigung-nach-umzug"],
    specialCases: ["Anfrage starten", "Wohnungsauflösung", "Entrümpelung", "Auszugsreinigung"],
    localIntro:
      "Schwandorf liegt im Regensburger Einsatzkorridor Richtung Amberg, Burglengenfeld und Cham. Häufig hängen Umzug, Räumung und Reinigung zusammen.",
    localProofNotes: [
      "Regionale Nähe zu Regensburg und Amberg wird konkret benannt.",
      "Wohnungsauflösung und Reinigung nach Auszug sind sichtbare Zusatzfälle.",
      "Die Seite bleibt nutzerorientiert statt nur Keyword-Seite.",
    ],
    maturity: indexableM1,
  },
  amberg: {
    slug: "amberg",
    displayName: "Amberg",
    region: "regensburg",
    parentHub: "/region-regensburg",
    serviceFocus: ["Privatumzug", "Seniorenumzug", "Firmenumzug", "Entrümpelung"],
    nearbyCities: ["Schwandorf", "Weiden", "Regensburg", "Sulzbach-Rosenberg", "Kümmersbruck"],
    districts: ["Altstadt", "Bergsteig", "Gailoh", "Raigering", "Luitpoldhöhe"],
    customerTypes: ["Privathaushalte", "Senioren", "Unternehmen", "Angehörige"],
    relevantServices: ["umzug", "umzugsservice", "umzug-kosten", "seniorenumzug", "entruempelung"],
    specialCases: ["Umzugskosten prüfen", "Seniorenumzug", "Firmenumzug", "Entrümpelung"],
    localIntro:
      "Amberg wird im Oberpfalz-Kontext mit Schwandorf, Weiden und Regensburg eingeordnet. Für Umzug zählen Volumen, Etage, Strecke und Zusatzleistungen.",
    localProofNotes: [
      "Amberg erhält eigene Nachbarorte und Leistungsprioritäten.",
      "Kostenfragen werden ohne erfundene Festpreise beantwortet.",
      "Keine lokale Filiale wird behauptet.",
    ],
    maturity: indexableM1,
  },
  kelheim: {
    slug: "kelheim",
    displayName: "Kelheim",
    region: "regensburg",
    parentHub: "/region-regensburg",
    serviceFocus: ["Privatumzug", "Seniorenumzug", "kleinere Transporte", "Entrümpelung", "Wohnungsauflösung"],
    nearbyCities: ["Regensburg", "Abensberg", "Bad Abbach", "Mainburg", "Riedenburg"],
    districts: ["Altstadt", "Affecking", "Kelheimwinzer", "Weltenburg", "Thaldorf"],
    customerTypes: ["Privathaushalte", "Senioren", "Angehörige", "Vermieter"],
    relevantServices: ["umzug", "umzugsservice", "seniorenumzug", "wohnungsaufloesung", "angebot-vergleichen"],
    specialCases: ["Angebot vergleichen", "kleiner Transport", "Seniorenumzug", "Wohnungsauflösung"],
    localIntro:
      "Kelheim wird mit Regensburg, Abensberg, Bad Abbach und Mainburg gedacht. Oft geht es um kleinere Umzüge, Seniorenumzug oder Wohnungsauflösung.",
    localProofNotes: [
      "Der Kelheim-Regensburg-Korridor ist konkret benannt.",
      "Kleinere Transporte werden realistisch als möglicher Einsatzfall erklärt.",
      "Angebotsvergleich bleibt der risikoarme Einstieg.",
    ],
    maturity: indexableM1,
  },
} as const satisfies Record<string, LocalSeoCityRecord>;
