import type { LocalSeoCityRecord } from "./types";

const indexableM2 = {
  indexStatus: "index",
  maturityLevel: "M2",
  passedChecks: [
    "eindeutige Suchintention",
    "lokaler Einstieg",
    "konkrete Leistungen",
    "Kundensituationen",
    "Ablauf",
    "Angebotsprüfung",
    "FAQ vorhanden",
    "strukturierte Daten",
    "keine lokale Standortbehauptung",
  ],
} as const;

export const localSeoCities = {
  duesseldorf: {
    slug: "duesseldorf",
    displayName: "Düsseldorf",
    region: "duesseldorf",
    parentHub: "/duesseldorf/reinigung",
    serviceFocus: [
      "Reinigung",
      "Büroreinigung",
      "Gewerbereinigung",
      "Praxisreinigung",
      "Fensterreinigung",
      "Grundreinigung",
      "Bauendreinigung",
      "Unterhaltsreinigung",
      "Treppenhausreinigung",
      "Angebotsprüfung",
    ],
    nearbyCities: ["Neuss", "Ratingen", "Meerbusch", "Hilden", "Erkrath", "Mettmann"],
    districts: [
      "Altstadt",
      "Stadtmitte",
      "Pempelfort",
      "Derendorf",
      "Oberkassel",
      "Bilk",
      "Benrath",
      "Kaiserswerth",
    ],
    customerTypes: ["households", "offices", "practices", "property managers", "shops", "companies"],
    relevantServices: [
      "reinigung",
      "bueroreinigung",
      "gewerbereinigung",
      "praxisreinigung",
      "wohnungsreinigung",
      "grundreinigung",
      "gebaeudereinigung",
      "angebot-vergleichen",
    ],
    specialCases: [
      "apartment handover",
      "office schedules",
      "commercial properties",
      "post-construction cleaning",
      "quote review",
    ],
    localIntro:
      "Düsseldorf cleaning requests are assessed by property type, district, access, timing and the required result.",
    localProofNotes: [
      "FLOXANT does not claim an additional office or walk-in location in Düsseldorf.",
      "Home, office, practice and commercial cleaning are separated by actual scope.",
      "Property type, size, photos, access, timing and the desired result determine feasibility.",
    ],
    maturity: indexableM2,
  },
  regensburg: {
    slug: "regensburg",
    displayName: "Regensburg",
    region: "regensburg",
    parentHub: "/region-regensburg",
    serviceFocus: [
      "Reinigung",
      "Bueroreinigung",
      "Gewerbereinigung",
      "Praxisreinigung",
      "Treppenhausreinigung",
      "Endreinigung",
      "Umzug",
      "Entruempelung",
      "Wohnungsaufloesung",
      "Angebotsprüfung",
    ],
    nearbyCities: [
      "Neutraubling",
      "Lappersdorf",
      "Pentling",
      "Obertraubling",
      "Regenstauf",
      "Kelheim",
      "Schwandorf",
      "Straubing",
    ],
    districts: [
      "Innenstadt",
      "Stadtamhof",
      "Reinhausen",
      "Ostenviertel",
      "Galgenberg",
      "Kumpfmuehl-Ziegetsdorf-Neupruell",
      "Westenviertel",
      "Burgweinting-Harting",
    ],
    customerTypes: [
      "Privatkunden",
      "Bueros",
      "Praxen",
      "Hausverwaltungen",
      "Gewerbe",
      "Vermieter",
      "Unternehmen",
    ],
    relevantServices: [
      "reinigung",
      "bueroreinigung",
      "gewerbereinigung",
      "praxisreinigung",
      "treppenhausreinigung",
      "reinigung-nach-umzug",
      "umzug",
      "entruempelung",
      "wohnungsaufloesung",
      "angebot-vergleichen",
    ],
    specialCases: [
      "Reinigung vor Uebergabe",
      "Buero- und Praxisflaechen",
      "Treppenhaus und Hausverwaltung",
      "Reinigung nach Umzug",
      "Angebotsprüfung",
    ],
    localIntro:
      "Regensburg ist der feste lokale Schwerpunkt. Reinigungsservices werden nur fuer Regensburg, Stadtteile, Landkreisgemeinden und Orte im 50-km-Umkreis eingeordnet.",
    localProofNotes: [
      "FLOXANT behauptet keine zusaetzlichen lokalen Bueros in Umlandorten.",
      "Reinigung wird getrennt von ueberregionalen Umzugs- und Entruempelungsleistungen gefuehrt.",
      "Ort, Objektart, Fotos, Zugang, Termin und gewuenschter Zielzustand entscheiden die Machbarkeit.",
    ],
    maturity: indexableM2,
  },
} as const satisfies Record<string, LocalSeoCityRecord>;
