import type { LocalSeoIntentCluster, LocalSeoIntentType, LocalSeoLanguage, LocalSeoRegionKey } from "./types";

type StrategyInput = LocalSeoIntentCluster & {
  path: string;
  locale: LocalSeoLanguage;
  region: LocalSeoRegionKey;
  serviceLabel: string;
};

type FallbackInput = {
  path: string;
  locale: LocalSeoLanguage;
  region: LocalSeoRegionKey;
  cityName: string;
  serviceName: string;
  serviceSearchIntents: readonly string[];
  localModifiers: readonly string[];
};

function strategy(input: StrategyInput): StrategyInput {
  return input;
}

function ctas(locale: LocalSeoLanguage, service: string) {
  if (locale === "en") {
    return [
      `Send ${service} request`,
      "Send photos via WhatsApp",
      "Review an existing quote",
      "Clarify scope before booking",
    ];
  }

  return [
    `${service} anfragen`,
    "Fotos per WhatsApp senden",
    "Angebot prüfen lassen",
    "Umfang vor Beauftragung klären",
  ];
}

function h2Topics(locale: LocalSeoLanguage, service: string, city: string) {
  if (locale === "en") {
    return [
      `${service} in ${city}: what matters first`,
      "Scope, access and timing",
      "Typical cases and customer situations",
      "Quote review before booking",
      "FAQ for international customers",
    ];
  }

  return [
    `${service} in ${city}: lokale Einordnung`,
    "Leistungsumfang, Zugang und Termin",
    "Typische Einsatzfälle",
    "Angebot sachlich prüfen",
    "Häufige Fragen",
  ];
}

function nearMe(city: string, service: string) {
  return [
    `${service} in der Nähe ${city}`,
    `${service} Nähe ${city}`,
    `${service} near me ${city}`,
  ];
}

const duesseldorfCustomerProblems = [
  "unklarer Leistungsumfang bei Büro, Praxis, Wohnung oder Gewerbefläche",
  "Preis ohne Fotos, Stadtteil, Zugang oder Turnus schwer vergleichbar",
  "kurzfristiger Termin vor Übergabe, Öffnung oder Wochenstart",
  "bestehendes Reinigungsangebot wirkt unvollständig",
] as const;

const regensburgCustomerProblems = [
  "Umfang, Volumen, Etage und Laufweg sind vor dem Angebot unklar",
  "Umzug, Wohnungsauflösung und Reinigung werden in einem Preis vermischt",
  "Angebot enthält offene Zusatzkosten oder unklare Positionen",
  "Termin und Übergabe müssen ruhig vorbereitet werden",
] as const;

export const localSeoKeywordStrategies = [
  strategy({
    path: "/duesseldorf/reinigung",
    locale: "de-DE",
    region: "duesseldorf",
    serviceLabel: "Reinigung",
    primaryKeyword: "reinigung düsseldorf",
    secondaryKeywords: ["reinigungsfirma düsseldorf", "putzfirma düsseldorf", "reinigungsdienst düsseldorf"],
    longTailKeywords: ["reinigung düsseldorf wohnung büro praxis", "reinigung in düsseldorf mit fotos anfragen"],
    nearMeKeywords: nearMe("Düsseldorf", "Reinigung"),
    englishKeywords: ["cleaning service Düsseldorf", "cleaning company Düsseldorf"],
    mixedLanguageKeywords: ["cleaning Düsseldorf Anfrage", "cleaning service Düsseldorf WhatsApp"],
    searchConsoleSignals: ["reinigung düsseldorf", "putzfirma düsseldorf", "reinigungsfirma düsseldorf"],
    customerProblems: duesseldorfCustomerProblems,
    conversionCtas: ctas("de-DE", "Reinigung Düsseldorf"),
    localModifiers: ["Heerdt", "Oberkassel", "Bilk", "Pempelfort", "Derendorf", "Neuss", "Meerbusch", "Ratingen"],
    h2Topics: h2Topics("de-DE", "Reinigung", "Düsseldorf"),
    intentType: "local",
  }),
  strategy({
    path: "/duesseldorf/reinigungsfirma",
    locale: "de-DE",
    region: "duesseldorf",
    serviceLabel: "Reinigungsfirma",
    primaryKeyword: "reinigungsfirma düsseldorf",
    secondaryKeywords: ["gewerbereinigung düsseldorf", "büroreinigung düsseldorf", "praxisreinigung düsseldorf"],
    longTailKeywords: ["reinigungsfirma düsseldorf angebot prüfen", "zuverlässige reinigungsfirma düsseldorf"],
    nearMeKeywords: nearMe("Düsseldorf", "Reinigungsfirma"),
    englishKeywords: ["cleaning company Düsseldorf", "commercial cleaning Düsseldorf"],
    mixedLanguageKeywords: ["cleaning company Düsseldorf Angebot", "Düsseldorf cleaning firm"],
    searchConsoleSignals: ["reinigungsfirma düsseldorf", "gewerbereinigung düsseldorf", "angebot reinigung"],
    customerProblems: duesseldorfCustomerProblems,
    conversionCtas: ctas("de-DE", "Reinigungsfirma Düsseldorf"),
    localModifiers: ["Stadtmitte", "MedienHafen", "Oberkassel", "Bilk", "Pempelfort", "Neuss", "Ratingen"],
    h2Topics: h2Topics("de-DE", "Reinigungsfirma", "Düsseldorf"),
    intentType: "commercial",
  }),
  strategy({
    path: "/duesseldorf/gewerbereinigung",
    locale: "de-DE",
    region: "duesseldorf",
    serviceLabel: "Gewerbereinigung",
    primaryKeyword: "gewerbereinigung düsseldorf",
    secondaryKeywords: ["reinigung gewerbe düsseldorf", "reinigung gewerbeflächen düsseldorf", "gebäudereinigung düsseldorf"],
    longTailKeywords: ["gewerbereinigung düsseldorf angebot prüfen", "gewerbeflächen reinigen lassen düsseldorf"],
    nearMeKeywords: nearMe("Düsseldorf", "Gewerbereinigung"),
    englishKeywords: ["commercial cleaning Düsseldorf", "business cleaning Düsseldorf"],
    mixedLanguageKeywords: ["commercial cleaning Düsseldorf Angebot", "office and commercial cleaning Düsseldorf"],
    searchConsoleSignals: ["gewerbereinigung düsseldorf", "reinigung gewerbeflächen düsseldorf"],
    customerProblems: duesseldorfCustomerProblems,
    conversionCtas: ctas("de-DE", "Gewerbereinigung Düsseldorf"),
    localModifiers: ["MedienHafen", "Stadtmitte", "Flingern", "Derendorf", "Heerdt", "Neuss"],
    h2Topics: h2Topics("de-DE", "Gewerbereinigung", "Düsseldorf"),
    intentType: "commercial",
  }),
  strategy({
    path: "/duesseldorf/praxisreinigung",
    locale: "de-DE",
    region: "duesseldorf",
    serviceLabel: "Praxisreinigung",
    primaryKeyword: "praxisreinigung düsseldorf",
    secondaryKeywords: ["reinigung praxis düsseldorf", "reinigungsfirma praxis düsseldorf"],
    longTailKeywords: ["praxisreinigung düsseldorf empfang wartebereich sanitär", "praxis reinigen lassen düsseldorf"],
    nearMeKeywords: nearMe("Düsseldorf", "Praxisreinigung"),
    englishKeywords: ["medical office cleaning Düsseldorf", "practice cleaning Düsseldorf"],
    mixedLanguageKeywords: ["practice cleaning Düsseldorf Anfrage", "medical office cleaning Düsseldorf quote"],
    searchConsoleSignals: ["praxisreinigung düsseldorf", "reinigungsfirma düsseldorf"],
    customerProblems: duesseldorfCustomerProblems,
    conversionCtas: ctas("de-DE", "Praxisreinigung Düsseldorf"),
    localModifiers: ["Pempelfort", "Derendorf", "Bilk", "Oberkassel", "Stadtmitte", "Ratingen"],
    h2Topics: h2Topics("de-DE", "Praxisreinigung", "Düsseldorf"),
    intentType: "commercial",
  }),
  strategy({
    path: "/duesseldorf/bueroreinigung",
    locale: "de-DE",
    region: "duesseldorf",
    serviceLabel: "Büroreinigung",
    primaryKeyword: "büroreinigung düsseldorf",
    secondaryKeywords: ["büro reinigen düsseldorf", "reinigungskraft büro düsseldorf", "reinigungsfirma büro düsseldorf"],
    longTailKeywords: ["büroreinigung düsseldorf angebot prüfen", "büro reinigen lassen düsseldorf randzeiten"],
    nearMeKeywords: nearMe("Düsseldorf", "Büroreinigung"),
    englishKeywords: ["office cleaning Düsseldorf", "office cleaner Düsseldorf"],
    mixedLanguageKeywords: ["office cleaning Düsseldorf Angebot", "office cleaning Düsseldorf WhatsApp"],
    searchConsoleSignals: ["büroreinigung düsseldorf", "reinigungsfirma düsseldorf"],
    customerProblems: duesseldorfCustomerProblems,
    conversionCtas: ctas("de-DE", "Büroreinigung Düsseldorf"),
    localModifiers: ["Stadtmitte", "MedienHafen", "Derendorf", "Heerdt", "Oberkassel", "Neuss"],
    h2Topics: h2Topics("de-DE", "Büroreinigung", "Düsseldorf"),
    intentType: "commercial",
  }),
  strategy({
    path: "/duesseldorf/grundreinigung",
    locale: "de-DE",
    region: "duesseldorf",
    serviceLabel: "Grundreinigung",
    primaryKeyword: "grundreinigung düsseldorf",
    secondaryKeywords: ["grundreinigung wohnung düsseldorf", "reinigung nach auszug düsseldorf", "bodenreinigung düsseldorf"],
    longTailKeywords: ["grundreinigung düsseldorf nach renovierung", "grundreinigung wohnung vor übergabe düsseldorf"],
    nearMeKeywords: nearMe("Düsseldorf", "Grundreinigung"),
    englishKeywords: ["deep cleaning Düsseldorf", "move out cleaning Düsseldorf"],
    mixedLanguageKeywords: ["deep cleaning Düsseldorf Wohnung", "move out cleaning Düsseldorf Übergabe"],
    searchConsoleSignals: ["grundreinigung düsseldorf", "wohnungsreinigung düsseldorf"],
    customerProblems: duesseldorfCustomerProblems,
    conversionCtas: ctas("de-DE", "Grundreinigung Düsseldorf"),
    localModifiers: ["Bilk", "Pempelfort", "Oberkassel", "Benrath", "Heerdt", "Meerbusch"],
    h2Topics: h2Topics("de-DE", "Grundreinigung", "Düsseldorf"),
    intentType: "transactional",
  }),
  strategy({
    path: "/duesseldorf/kanzleireinigung",
    locale: "de-DE",
    region: "duesseldorf",
    serviceLabel: "Kanzleireinigung",
    primaryKeyword: "kanzleireinigung düsseldorf",
    secondaryKeywords: ["büroreinigung kanzlei düsseldorf", "reinigung kanzlei düsseldorf"],
    longTailKeywords: ["kanzleireinigung düsseldorf diskret randzeiten", "kanzlei reinigen lassen düsseldorf"],
    nearMeKeywords: nearMe("Düsseldorf", "Kanzleireinigung"),
    englishKeywords: ["law office cleaning Düsseldorf", "legal office cleaning Düsseldorf"],
    mixedLanguageKeywords: ["law office cleaning Düsseldorf quote", "kanzlei cleaning Düsseldorf"],
    searchConsoleSignals: ["kanzleireinigung düsseldorf", "büroreinigung düsseldorf"],
    customerProblems: duesseldorfCustomerProblems,
    conversionCtas: ctas("de-DE", "Kanzleireinigung Düsseldorf"),
    localModifiers: ["Carlstadt", "Stadtmitte", "Oberkassel", "Pempelfort", "MedienHafen"],
    h2Topics: h2Topics("de-DE", "Kanzleireinigung", "Düsseldorf"),
    intentType: "commercial",
  }),
  strategy({
    path: "/duesseldorf/putzfirma",
    locale: "de-DE",
    region: "duesseldorf",
    serviceLabel: "Putzfirma",
    primaryKeyword: "putzfirma düsseldorf",
    secondaryKeywords: ["putzfirma in düsseldorf", "zuverlässige putzfirma düsseldorf", "reinigungsfirma düsseldorf"],
    longTailKeywords: ["putzfirma für wohnung büro praxis düsseldorf", "putzfirma angebot vergleichen düsseldorf"],
    nearMeKeywords: nearMe("Düsseldorf", "Putzfirma"),
    englishKeywords: ["cleaning company Düsseldorf", "cleaner Düsseldorf"],
    mixedLanguageKeywords: ["cleaner Düsseldorf Wohnung Büro", "cleaning company Düsseldorf offer"],
    searchConsoleSignals: ["putzfirma düsseldorf", "reinigungsfirma düsseldorf"],
    customerProblems: duesseldorfCustomerProblems,
    conversionCtas: ctas("de-DE", "Putzfirma Düsseldorf"),
    localModifiers: ["Heerdt", "Bilk", "Pempelfort", "Oberkassel", "Derendorf", "Benrath"],
    h2Topics: h2Topics("de-DE", "Putzfirma", "Düsseldorf"),
    intentType: "commercial",
  }),
  strategy({
    path: "/duesseldorf/wohnungsreinigung",
    locale: "de-DE",
    region: "duesseldorf",
    serviceLabel: "Wohnungsreinigung",
    primaryKeyword: "wohnungsreinigung düsseldorf",
    secondaryKeywords: ["wohnung reinigen lassen düsseldorf", "grundreinigung wohnung düsseldorf", "reinigung nach auszug düsseldorf"],
    longTailKeywords: ["reinigung vor wohnungsübergabe düsseldorf", "wohnung reinigen lassen vor auszug düsseldorf"],
    nearMeKeywords: nearMe("Düsseldorf", "Wohnungsreinigung"),
    englishKeywords: ["apartment cleaning Düsseldorf", "move out cleaning Düsseldorf"],
    mixedLanguageKeywords: ["apartment cleaning Düsseldorf Übergabe", "move out cleaning Düsseldorf quote"],
    searchConsoleSignals: ["wohnungsreinigung düsseldorf", "reinigung düsseldorf"],
    customerProblems: duesseldorfCustomerProblems,
    conversionCtas: ctas("de-DE", "Wohnungsreinigung Düsseldorf"),
    localModifiers: ["Bilk", "Oberkassel", "Pempelfort", "Derendorf", "Benrath", "Heerdt"],
    h2Topics: h2Topics("de-DE", "Wohnungsreinigung", "Düsseldorf"),
    intentType: "transactional",
  }),
  strategy({
    path: "/duesseldorf/treppenhausreinigung",
    locale: "de-DE",
    region: "duesseldorf",
    serviceLabel: "Treppenhausreinigung",
    primaryKeyword: "treppenhausreinigung düsseldorf",
    secondaryKeywords: ["treppenreinigung düsseldorf", "reinigung hauseingang düsseldorf", "hausflurreinigung düsseldorf"],
    longTailKeywords: ["treppenhaus reinigen lassen düsseldorf", "treppenhausreinigung düsseldorf hausverwaltung"],
    nearMeKeywords: nearMe("Düsseldorf", "Treppenhausreinigung"),
    englishKeywords: ["stairwell cleaning Düsseldorf", "building entrance cleaning Düsseldorf"],
    mixedLanguageKeywords: ["stairwell cleaning Düsseldorf Hausverwaltung", "building entrance cleaning Düsseldorf"],
    searchConsoleSignals: ["treppenhausreinigung düsseldorf", "treppenreinigung düsseldorf", "reinigung hauseingang düsseldorf"],
    customerProblems: duesseldorfCustomerProblems,
    conversionCtas: ctas("de-DE", "Treppenhausreinigung Düsseldorf"),
    localModifiers: ["Heerdt", "Oberkassel", "Bilk", "Derendorf", "Pempelfort", "Neuss"],
    h2Topics: h2Topics("de-DE", "Treppenhausreinigung", "Düsseldorf"),
    intentType: "commercial",
  }),
  strategy({
    path: "/duesseldorf/gebaeudereinigung",
    locale: "de-DE",
    region: "duesseldorf",
    serviceLabel: "Gebäudereinigung",
    primaryKeyword: "gebäudereinigung düsseldorf",
    secondaryKeywords: ["gebäudereinigung düsseldorf heerdt", "objektreinigung düsseldorf", "gewerbereinigung düsseldorf"],
    longTailKeywords: ["gebäudereinigung düsseldorf heerdt angebot", "gebäudereinigung für objekt und treppenhaus düsseldorf"],
    nearMeKeywords: nearMe("Düsseldorf", "Gebäudereinigung"),
    englishKeywords: ["building cleaning Düsseldorf", "facility cleaning Düsseldorf"],
    mixedLanguageKeywords: ["building cleaning Düsseldorf Heerdt", "facility cleaning Düsseldorf quote"],
    searchConsoleSignals: ["gebäudereinigung düsseldorf heerdt", "reinigung düsseldorf"],
    customerProblems: duesseldorfCustomerProblems,
    conversionCtas: ctas("de-DE", "Gebäudereinigung Düsseldorf"),
    localModifiers: ["Heerdt", "Oberkassel", "Derendorf", "Bilk", "Pempelfort", "Meerbusch"],
    h2Topics: h2Topics("de-DE", "Gebäudereinigung", "Düsseldorf"),
    intentType: "commercial",
  }),
  strategy({
    path: "/duesseldorf/gewerbeflaechen-reinigung",
    locale: "de-DE",
    region: "duesseldorf",
    serviceLabel: "Gewerbeflächen-Reinigung",
    primaryKeyword: "reinigung gewerbeflächen düsseldorf",
    secondaryKeywords: ["gewerbeflächen reinigen lassen", "reinigung gewerbe düsseldorf", "gewerbereinigung düsseldorf"],
    longTailKeywords: ["reinigung gewerbeflächen düsseldorf angebot prüfen", "gewerbeflächen reinigen lassen düsseldorf"],
    nearMeKeywords: nearMe("Düsseldorf", "Gewerbeflächen-Reinigung"),
    englishKeywords: ["commercial space cleaning Düsseldorf", "retail space cleaning Düsseldorf"],
    mixedLanguageKeywords: ["commercial space cleaning Düsseldorf Angebot", "retail cleaning Düsseldorf quote"],
    searchConsoleSignals: ["reinigung gewerbeflächen düsseldorf", "gewerbereinigung düsseldorf"],
    customerProblems: duesseldorfCustomerProblems,
    conversionCtas: ctas("de-DE", "Gewerbeflächen-Reinigung Düsseldorf"),
    localModifiers: ["MedienHafen", "Stadtmitte", "Flingern", "Derendorf", "Heerdt", "Neuss"],
    h2Topics: h2Topics("de-DE", "Gewerbeflächen-Reinigung", "Düsseldorf"),
    intentType: "commercial",
  }),
  strategy({
    path: "/duesseldorf/reinigung-heerdt",
    locale: "de-DE",
    region: "duesseldorf",
    serviceLabel: "Reinigung Heerdt",
    primaryKeyword: "reinigung düsseldorf heerdt",
    secondaryKeywords: ["gebäudereinigung düsseldorf heerdt", "putzfirma düsseldorf heerdt", "reinigungsfirma heerdt"],
    longTailKeywords: ["reinigung in düsseldorf heerdt anfragen", "gebäudereinigung heerdt angebot prüfen"],
    nearMeKeywords: nearMe("Düsseldorf-Heerdt", "Reinigung"),
    englishKeywords: ["cleaning service Düsseldorf Heerdt", "building cleaning Heerdt"],
    mixedLanguageKeywords: ["cleaning Heerdt Düsseldorf", "building cleaning Düsseldorf Heerdt quote"],
    searchConsoleSignals: ["gebäudereinigung düsseldorf heerdt", "reinigung düsseldorf"],
    customerProblems: duesseldorfCustomerProblems,
    conversionCtas: ctas("de-DE", "Reinigung Düsseldorf-Heerdt"),
    localModifiers: ["Heerdt", "Oberkassel", "Lörick", "Niederkassel", "Neuss", "Meerbusch"],
    h2Topics: h2Topics("de-DE", "Reinigung Heerdt", "Düsseldorf"),
    intentType: "local",
  }),
  strategy({
    path: "/duesseldorf/angebot-vergleichen",
    locale: "de-DE",
    region: "duesseldorf",
    serviceLabel: "Reinigungsangebot prüfen",
    primaryKeyword: "reinigungsangebot prüfen",
    secondaryKeywords: ["reinigungsangebot vergleichen", "angebot für reinigungsarbeiten", "reinigungsfirma angebote"],
    longTailKeywords: ["putzfirma angebot vergleichen düsseldorf", "gebäudereinigung angebot prüfen düsseldorf"],
    nearMeKeywords: ["reinigungsangebot prüfen düsseldorf", "reinigungsfirma angebot in der nähe prüfen"],
    englishKeywords: ["cleaning quote review Düsseldorf", "cleaning offer review Düsseldorf"],
    mixedLanguageKeywords: ["cleaning quote review Düsseldorf Angebot", "cleaning offer prüfen Düsseldorf"],
    searchConsoleSignals: ["angebot für reinigungsarbeiten", "reinigungsfirma angebote", "reinigungsangebot prüfen", "reinigungsangebot vergleichen"],
    customerProblems: duesseldorfCustomerProblems,
    conversionCtas: ctas("de-DE", "Reinigungsangebot"),
    localModifiers: ["Düsseldorf", "Heerdt", "Bilk", "Pempelfort", "Neuss", "Ratingen"],
    h2Topics: h2Topics("de-DE", "Reinigungsangebot", "Düsseldorf"),
    intentType: "quote-check",
  }),
  strategy({
    path: "/angebot-vergleichen-duesseldorf",
    locale: "de-DE",
    region: "duesseldorf",
    serviceLabel: "Reinigungsangebot vergleichen",
    primaryKeyword: "reinigungsangebot vergleichen",
    secondaryKeywords: ["angebot für reinigungsarbeiten", "reinigungsfirma angebote", "reinigungsangebot prüfen"],
    longTailKeywords: ["putzfirma angebot vergleichen", "gebäudereinigung angebot prüfen", "angebot reinigung vergleichen düsseldorf"],
    nearMeKeywords: ["reinigungsangebot prüfen in der nähe düsseldorf", "putzfirma angebot prüfen düsseldorf"],
    englishKeywords: ["cleaning quote comparison Düsseldorf", "cleaning estimate review Düsseldorf"],
    mixedLanguageKeywords: ["cleaning quote Vergleich Düsseldorf", "cleaning estimate prüfen Düsseldorf"],
    searchConsoleSignals: ["angebot für reinigungsarbeiten", "reinigungsfirma angebote", "reinigungsangebot vergleichen"],
    customerProblems: duesseldorfCustomerProblems,
    conversionCtas: ctas("de-DE", "Reinigungsangebot"),
    localModifiers: ["Düsseldorf", "Heerdt", "Bilk", "Pempelfort", "Neuss", "Meerbusch"],
    h2Topics: h2Topics("de-DE", "Reinigungsangebot", "Düsseldorf"),
    intentType: "quote-check",
  }),
  strategy({
    path: "/regensburg/bueroreinigung",
    locale: "de-DE",
    region: "regensburg",
    serviceLabel: "Büroreinigung",
    primaryKeyword: "büroreinigung regensburg",
    secondaryKeywords: ["reinigung regensburg büro", "reinigungsfirma regensburg", "gewerbereinigung regensburg"],
    longTailKeywords: ["büroreinigung regensburg angebot einholen", "büro reinigen lassen regensburg"],
    nearMeKeywords: nearMe("Regensburg", "Büroreinigung"),
    englishKeywords: ["office cleaning Regensburg", "commercial cleaning Regensburg"],
    mixedLanguageKeywords: ["office cleaning Regensburg Angebot", "commercial cleaning Regensburg quote"],
    searchConsoleSignals: ["büroreinigung regensburg", "reinigung düsseldorf"],
    customerProblems: regensburgCustomerProblems,
    conversionCtas: ctas("de-DE", "Büroreinigung Regensburg"),
    localModifiers: ["Altstadt", "Westenviertel", "Kumpfmühl", "Prüfening", "Burgweinting", "Neutraubling"],
    h2Topics: h2Topics("de-DE", "Büroreinigung", "Regensburg"),
    intentType: "commercial",
  }),
  strategy({
    path: "/regensburg/wohnungsaufloesung",
    locale: "de-DE",
    region: "regensburg",
    serviceLabel: "Wohnungsauflösung",
    primaryKeyword: "wohnungsauflösung regensburg",
    secondaryKeywords: ["haushaltsauflösung regensburg", "entrümpelung regensburg", "nachlass räumung regensburg"],
    longTailKeywords: ["wohnungsauflösung regensburg mit reinigung", "wohnung auflösen lassen regensburg"],
    nearMeKeywords: nearMe("Regensburg", "Wohnungsauflösung"),
    englishKeywords: ["house clearance Regensburg", "apartment clearance Regensburg"],
    mixedLanguageKeywords: ["house clearance Regensburg Angebot", "apartment clearance Regensburg cleaning"],
    searchConsoleSignals: ["wohnungsauflösung regensburg", "umzugsunternehmen regensburg"],
    customerProblems: regensburgCustomerProblems,
    conversionCtas: ctas("de-DE", "Wohnungsauflösung Regensburg"),
    localModifiers: ["Altstadt", "Westenviertel", "Kumpfmühl", "Prüfening", "Landkreis Regensburg"],
    h2Topics: h2Topics("de-DE", "Wohnungsauflösung", "Regensburg"),
    intentType: "transactional",
  }),
  strategy({
    path: "/regensburg/umzugsunternehmen",
    locale: "de-DE",
    region: "regensburg",
    serviceLabel: "Umzugsunternehmen",
    primaryKeyword: "umzugsunternehmen regensburg",
    secondaryKeywords: ["umzugsfirma regensburg", "umzug regensburg", "umzugsangebot prüfen regensburg"],
    longTailKeywords: ["umzugsunternehmen regensburg angebot prüfen", "umzug regensburg kosten einschätzen"],
    nearMeKeywords: nearMe("Regensburg", "Umzugsunternehmen"),
    englishKeywords: ["moving company Regensburg", "moving service Regensburg"],
    mixedLanguageKeywords: ["moving company Regensburg quote", "moving service Regensburg Angebot"],
    searchConsoleSignals: ["umzugsunternehmen regensburg", "wohnungsauflösung regensburg"],
    customerProblems: regensburgCustomerProblems,
    conversionCtas: ctas("de-DE", "Umzugsunternehmen Regensburg"),
    localModifiers: ["Altstadt", "Westenviertel", "Kumpfmühl", "Prüfening", "Burgweinting", "Landkreis Regensburg"],
    h2Topics: h2Topics("de-DE", "Umzugsunternehmen", "Regensburg"),
    intentType: "commercial",
  }),
  strategy({
    path: "/regensburg/reinigungsfirma",
    locale: "de-DE",
    region: "regensburg",
    serviceLabel: "Reinigungsfirma",
    primaryKeyword: "reinigungsfirma regensburg",
    secondaryKeywords: ["büroreinigung regensburg", "reinigung nach umzug regensburg", "gewerbereinigung regensburg"],
    longTailKeywords: ["reinigungsfirma regensburg angebot prüfen", "reinigung regensburg nach auszug"],
    nearMeKeywords: nearMe("Regensburg", "Reinigungsfirma"),
    englishKeywords: ["cleaning company Regensburg", "cleaning service Regensburg"],
    mixedLanguageKeywords: ["cleaning company Regensburg Angebot", "cleaning after moving Regensburg"],
    searchConsoleSignals: ["büroreinigung regensburg", "reinigungsfirma angebote"],
    customerProblems: regensburgCustomerProblems,
    conversionCtas: ctas("de-DE", "Reinigungsfirma Regensburg"),
    localModifiers: ["Altstadt", "Westenviertel", "Kumpfmühl", "Prüfening", "Burgweinting", "Neutraubling"],
    h2Topics: h2Topics("de-DE", "Reinigungsfirma", "Regensburg"),
    intentType: "commercial",
  }),
  strategy({
    path: "/regensburg/angebot-vergleichen",
    locale: "de-DE",
    region: "regensburg",
    serviceLabel: "Angebot prüfen",
    primaryKeyword: "angebot prüfen regensburg",
    secondaryKeywords: ["umzugsangebot prüfen", "reinigungsangebot prüfen", "wohnungsauflösung angebot prüfen"],
    longTailKeywords: ["umzugsangebot prüfen regensburg", "angebot für reinigungsarbeiten regensburg prüfen"],
    nearMeKeywords: ["angebot prüfen regensburg", "angebot in der nähe prüfen regensburg"],
    englishKeywords: ["moving quote review Regensburg", "cleaning quote review Regensburg"],
    mixedLanguageKeywords: ["moving quote prüfen Regensburg", "cleaning quote Regensburg Angebot"],
    searchConsoleSignals: ["reinigungsfirma angebote", "angebot für reinigungsarbeiten", "umzugsunternehmen regensburg"],
    customerProblems: regensburgCustomerProblems,
    conversionCtas: ctas("de-DE", "Angebot Regensburg"),
    localModifiers: ["Regensburg", "Altstadt", "Kumpfmühl", "Prüfening", "Neutraubling", "Lappersdorf"],
    h2Topics: h2Topics("de-DE", "Angebot", "Regensburg"),
    intentType: "quote-check",
  }),
  strategy({
    path: "/angebot-vergleichen-regensburg",
    locale: "de-DE",
    region: "regensburg",
    serviceLabel: "Angebot vergleichen",
    primaryKeyword: "angebot vergleichen regensburg",
    secondaryKeywords: ["umzugsangebot prüfen regensburg", "reinigungsangebot prüfen regensburg", "wohnungsauflösung angebot prüfen"],
    longTailKeywords: ["angebot regensburg prüfen lassen", "umzugsunternehmen angebot vergleichen regensburg"],
    nearMeKeywords: ["angebot prüfen in der nähe regensburg", "umzugsangebot prüfen regensburg"],
    englishKeywords: ["quote comparison Regensburg", "moving estimate review Regensburg"],
    mixedLanguageKeywords: ["quote review Regensburg Angebot", "moving quote prüfen Regensburg"],
    searchConsoleSignals: ["reinigungsfirma angebote", "umzugsunternehmen regensburg"],
    customerProblems: regensburgCustomerProblems,
    conversionCtas: ctas("de-DE", "Angebot Regensburg"),
    localModifiers: ["Regensburg", "Altstadt", "Westenviertel", "Neutraubling", "Landkreis Regensburg"],
    h2Topics: h2Topics("de-DE", "Angebot", "Regensburg"),
    intentType: "quote-check",
  }),

  strategy({
    path: "/en/duesseldorf/cleaning",
    locale: "en",
    region: "duesseldorf",
    serviceLabel: "Cleaning service",
    primaryKeyword: "cleaning service Düsseldorf",
    secondaryKeywords: ["cleaning company Düsseldorf", "cleaner Düsseldorf", "commercial cleaning Düsseldorf"],
    longTailKeywords: ["English speaking cleaning service Düsseldorf", "cleaning service Düsseldorf for apartment office practice"],
    nearMeKeywords: ["cleaning service near me Düsseldorf", "cleaning company near me Düsseldorf"],
    englishKeywords: ["cleaning service Düsseldorf", "cleaning company Düsseldorf"],
    mixedLanguageKeywords: ["cleaning Düsseldorf Angebot", "cleaning service Düsseldorf Anfrage"],
    searchConsoleSignals: ["putzfirma düsseldorf", "reinigungsfirma düsseldorf", "reinigung düsseldorf"],
    customerProblems: ["German quote terms are hard to compare", "photos, access and timing need a clear first check"],
    conversionCtas: ctas("en", "cleaning"),
    localModifiers: ["Heerdt", "Oberkassel", "Bilk", "Pempelfort", "Derendorf", "Neuss"],
    h2Topics: h2Topics("en", "Cleaning service", "Düsseldorf"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/duesseldorf/office-cleaning",
    locale: "en",
    region: "duesseldorf",
    serviceLabel: "Office cleaning",
    primaryKeyword: "office cleaning Düsseldorf",
    secondaryKeywords: ["commercial cleaning Düsseldorf", "office cleaner Düsseldorf", "business cleaning Düsseldorf"],
    longTailKeywords: ["office cleaning Düsseldorf with photo based quote", "English office cleaning request Düsseldorf"],
    nearMeKeywords: ["office cleaning near me Düsseldorf", "commercial cleaner near me Düsseldorf"],
    englishKeywords: ["office cleaning Düsseldorf", "commercial cleaning Düsseldorf"],
    mixedLanguageKeywords: ["office cleaning Düsseldorf Angebot", "Büroreinigung Düsseldorf English"],
    searchConsoleSignals: ["büroreinigung düsseldorf", "gewerbereinigung düsseldorf"],
    customerProblems: ["unclear office scope, kitchen, sanitary areas and after-hours access"],
    conversionCtas: ctas("en", "office cleaning"),
    localModifiers: ["Stadtmitte", "MedienHafen", "Derendorf", "Heerdt", "Neuss"],
    h2Topics: h2Topics("en", "Office cleaning", "Düsseldorf"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/duesseldorf/apartment-cleaning",
    locale: "en",
    region: "duesseldorf",
    serviceLabel: "Apartment cleaning",
    primaryKeyword: "apartment cleaning Düsseldorf",
    secondaryKeywords: ["move out cleaning Düsseldorf", "flat cleaning Düsseldorf", "deep apartment cleaning Düsseldorf"],
    longTailKeywords: ["apartment cleaning before handover Düsseldorf", "move out apartment cleaning Düsseldorf English"],
    nearMeKeywords: ["apartment cleaning near me Düsseldorf", "move out cleaning near me Düsseldorf"],
    englishKeywords: ["apartment cleaning Düsseldorf", "move out cleaning Düsseldorf"],
    mixedLanguageKeywords: ["Wohnungsreinigung Düsseldorf English", "apartment cleaning Düsseldorf Übergabe"],
    searchConsoleSignals: ["wohnungsreinigung düsseldorf", "reinigung nach auszug düsseldorf"],
    customerProblems: ["handover cleaning needs rooms, condition, photos and timing"],
    conversionCtas: ctas("en", "apartment cleaning"),
    localModifiers: ["Bilk", "Pempelfort", "Oberkassel", "Heerdt", "Benrath"],
    h2Topics: h2Topics("en", "Apartment cleaning", "Düsseldorf"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/duesseldorf/deep-cleaning",
    locale: "en",
    region: "duesseldorf",
    serviceLabel: "Deep cleaning",
    primaryKeyword: "deep cleaning Düsseldorf",
    secondaryKeywords: ["deep apartment cleaning Düsseldorf", "move out cleaning Düsseldorf", "intensive cleaning Düsseldorf"],
    longTailKeywords: ["deep cleaning after renovation Düsseldorf", "deep cleaning before apartment handover Düsseldorf"],
    nearMeKeywords: ["deep cleaning near me Düsseldorf", "intensive cleaning near me Düsseldorf"],
    englishKeywords: ["deep cleaning Düsseldorf", "move out cleaning Düsseldorf"],
    mixedLanguageKeywords: ["Grundreinigung Düsseldorf English", "deep cleaning Düsseldorf Angebot"],
    searchConsoleSignals: ["grundreinigung düsseldorf", "wohnungsreinigung düsseldorf"],
    customerProblems: ["strong dirt, renovation dust or move-out condition needs realistic assessment"],
    conversionCtas: ctas("en", "deep cleaning"),
    localModifiers: ["Bilk", "Pempelfort", "Heerdt", "Oberkassel", "Meerbusch"],
    h2Topics: h2Topics("en", "Deep cleaning", "Düsseldorf"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/duesseldorf/move-out-cleaning",
    locale: "en",
    region: "duesseldorf",
    serviceLabel: "Move-out cleaning",
    primaryKeyword: "move out cleaning Düsseldorf",
    secondaryKeywords: ["end of tenancy cleaning Düsseldorf", "apartment handover cleaning Düsseldorf"],
    longTailKeywords: ["move out cleaning before apartment handover Düsseldorf", "cleaning after moving out Düsseldorf English"],
    nearMeKeywords: ["move out cleaning near me Düsseldorf", "end of tenancy cleaning near me Düsseldorf"],
    englishKeywords: ["move out cleaning Düsseldorf", "end of tenancy cleaning Düsseldorf"],
    mixedLanguageKeywords: ["Übergabereinigung Düsseldorf English", "move out cleaning Düsseldorf Übergabe"],
    searchConsoleSignals: ["reinigung nach auszug düsseldorf", "wohnungsreinigung düsseldorf"],
    customerProblems: ["handover date, keys, photos and visible result need coordination"],
    conversionCtas: ctas("en", "move-out cleaning"),
    localModifiers: ["Bilk", "Pempelfort", "Oberkassel", "Heerdt", "Benrath"],
    h2Topics: h2Topics("en", "Move-out cleaning", "Düsseldorf"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/duesseldorf/stairwell-cleaning",
    locale: "en",
    region: "duesseldorf",
    serviceLabel: "Stairwell cleaning",
    primaryKeyword: "stairwell cleaning Düsseldorf",
    secondaryKeywords: ["building entrance cleaning Düsseldorf", "hallway cleaning Düsseldorf"],
    longTailKeywords: ["stairwell cleaning for property management Düsseldorf", "building entrance cleaning Düsseldorf quote"],
    nearMeKeywords: ["stairwell cleaning near me Düsseldorf", "building entrance cleaning near me Düsseldorf"],
    englishKeywords: ["stairwell cleaning Düsseldorf", "building entrance cleaning Düsseldorf"],
    mixedLanguageKeywords: ["Treppenhausreinigung Düsseldorf English", "stairwell cleaning Düsseldorf Hausverwaltung"],
    searchConsoleSignals: ["treppenhausreinigung düsseldorf", "reinigung hauseingang düsseldorf"],
    customerProblems: ["property management needs recurring scope, floors and entrance access"],
    conversionCtas: ctas("en", "stairwell cleaning"),
    localModifiers: ["Heerdt", "Oberkassel", "Bilk", "Derendorf", "Pempelfort"],
    h2Topics: h2Topics("en", "Stairwell cleaning", "Düsseldorf"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/duesseldorf/odor-removal",
    locale: "en",
    region: "duesseldorf",
    serviceLabel: "Odor removal",
    primaryKeyword: "odor removal Düsseldorf",
    secondaryKeywords: ["smell removal apartment Düsseldorf", "pet odor removal Düsseldorf", "smoke smell removal Düsseldorf"],
    longTailKeywords: ["odor removal after move-out Düsseldorf", "apartment smell assessment Düsseldorf English"],
    nearMeKeywords: ["odor removal near me Düsseldorf", "smell removal near me Düsseldorf"],
    englishKeywords: ["odor removal Düsseldorf", "smell removal apartment Düsseldorf"],
    mixedLanguageKeywords: ["Geruchsneutralisation Düsseldorf English", "odor removal Düsseldorf Angebot"],
    searchConsoleSignals: ["geruchsneutralisation wohnung düsseldorf", "gerüche entfernen düsseldorf"],
    customerProblems: ["smell source, surfaces, duration and expectations need careful checking before promises"],
    conversionCtas: ctas("en", "odor removal"),
    localModifiers: ["Bilk", "Pempelfort", "Heerdt", "Oberkassel", "Benrath"],
    h2Topics: h2Topics("en", "Odor removal", "Düsseldorf"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/koeln/cleaning",
    locale: "en",
    region: "duesseldorf",
    serviceLabel: "Cleaning service",
    primaryKeyword: "cleaning service Cologne",
    secondaryKeywords: ["cleaning company Cologne", "apartment cleaning Cologne", "office cleaning Cologne"],
    longTailKeywords: ["English cleaning service Cologne with quote review", "cleaning service Cologne apartment office practice"],
    nearMeKeywords: ["cleaning service near me Cologne", "cleaning company near me Cologne"],
    englishKeywords: ["cleaning service Cologne", "cleaning company Cologne"],
    mixedLanguageKeywords: ["Reinigung Köln English", "cleaning Cologne Angebot"],
    searchConsoleSignals: ["cleaning service Cologne", "cleaning company Cologne"],
    customerProblems: ["Cologne cleaning scope, access, timing and photos need a clear first check"],
    conversionCtas: ctas("en", "cleaning"),
    localModifiers: ["Innenstadt", "Ehrenfeld", "Lindenthal", "Nippes", "Deutz", "Leverkusen"],
    h2Topics: h2Topics("en", "Cleaning service", "Cologne"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/neuss/cleaning",
    locale: "en",
    region: "duesseldorf",
    serviceLabel: "Cleaning service",
    primaryKeyword: "cleaning service Neuss",
    secondaryKeywords: ["cleaning company Neuss", "apartment cleaning Neuss", "office cleaning Neuss"],
    longTailKeywords: ["English cleaning request Neuss near Düsseldorf", "cleaning service Neuss quote review"],
    nearMeKeywords: ["cleaning service near me Neuss", "cleaning company near me Neuss"],
    englishKeywords: ["cleaning service Neuss", "cleaning company Neuss"],
    mixedLanguageKeywords: ["Reinigung Neuss English", "cleaning Neuss Angebot"],
    searchConsoleSignals: ["cleaning service Neuss", "cleaning company Neuss"],
    customerProblems: ["Neuss cleaning requests often need apartment, office or stairwell scope separated"],
    conversionCtas: ctas("en", "cleaning"),
    localModifiers: ["Innenstadt", "Furth", "Norf", "Meerbusch", "Kaarst", "Düsseldorf-Heerdt"],
    h2Topics: h2Topics("en", "Cleaning service", "Neuss"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/meerbusch/cleaning",
    locale: "en",
    region: "duesseldorf",
    serviceLabel: "Cleaning service",
    primaryKeyword: "cleaning service Meerbusch",
    secondaryKeywords: ["cleaning company Meerbusch", "home cleaning Meerbusch", "office cleaning Meerbusch"],
    longTailKeywords: ["English cleaning request Meerbusch with photos", "cleaning service Meerbusch quote review"],
    nearMeKeywords: ["cleaning service near me Meerbusch", "cleaning company near me Meerbusch"],
    englishKeywords: ["cleaning service Meerbusch", "home cleaning Meerbusch"],
    mixedLanguageKeywords: ["Reinigung Meerbusch English", "cleaning Meerbusch Angebot"],
    searchConsoleSignals: ["cleaning service Meerbusch"],
    customerProblems: ["home, practice and office cleaning in Meerbusch need access and timing clarity"],
    conversionCtas: ctas("en", "cleaning"),
    localModifiers: ["Büderich", "Osterath", "Lank-Latum", "Düsseldorf", "Neuss", "Krefeld"],
    h2Topics: h2Topics("en", "Cleaning service", "Meerbusch"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/duisburg/cleaning",
    locale: "en",
    region: "duesseldorf",
    serviceLabel: "Cleaning service",
    primaryKeyword: "cleaning service Duisburg",
    secondaryKeywords: ["cleaning company Duisburg", "commercial cleaning Duisburg", "apartment cleaning Duisburg"],
    longTailKeywords: ["English commercial cleaning request Duisburg", "cleaning service Duisburg quote review"],
    nearMeKeywords: ["cleaning service near me Duisburg", "commercial cleaning near me Duisburg"],
    englishKeywords: ["cleaning service Duisburg", "commercial cleaning Duisburg"],
    mixedLanguageKeywords: ["Reinigung Duisburg English", "cleaning Duisburg Angebot"],
    searchConsoleSignals: ["cleaning service Duisburg", "cleaning company Duisburg"],
    customerProblems: ["commercial, office and apartment cleaning in Duisburg need separate scope before pricing"],
    conversionCtas: ctas("en", "cleaning"),
    localModifiers: ["Innenstadt", "Duissern", "Neudorf", "Rheinhausen", "Düsseldorf", "Oberhausen"],
    h2Topics: h2Topics("en", "Cleaning service", "Duisburg"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/duesseldorf/cleaning-quote-review",
    locale: "en",
    region: "duesseldorf",
    serviceLabel: "Cleaning quote review",
    primaryKeyword: "cleaning quote review Düsseldorf",
    secondaryKeywords: ["cleaning quote comparison Düsseldorf", "review cleaning offer Düsseldorf"],
    longTailKeywords: ["compare cleaning quote in Düsseldorf before booking", "English cleaning quote review Düsseldorf"],
    nearMeKeywords: ["cleaning quote review near me Düsseldorf", "cleaning estimate review Düsseldorf"],
    englishKeywords: ["cleaning quote review Düsseldorf", "cleaning quote comparison Düsseldorf"],
    mixedLanguageKeywords: ["Reinigungsangebot prüfen English", "cleaning quote Düsseldorf Angebot prüfen"],
    searchConsoleSignals: ["reinigungsangebot prüfen", "reinigungsangebot vergleichen", "angebot für reinigungsarbeiten"],
    customerProblems: ["quote line items, recurring scope and extra costs are unclear"],
    conversionCtas: ctas("en", "cleaning quote review"),
    localModifiers: ["Düsseldorf", "Heerdt", "Bilk", "Pempelfort", "Neuss"],
    h2Topics: h2Topics("en", "Cleaning quote review", "Düsseldorf"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/regensburg/moving",
    locale: "en",
    region: "regensburg",
    serviceLabel: "Moving service",
    primaryKeyword: "moving service Regensburg",
    secondaryKeywords: ["moving company Regensburg", "relocation service Regensburg"],
    longTailKeywords: ["moving service Regensburg with photos and quote review", "English moving request Regensburg"],
    nearMeKeywords: ["moving service near me Regensburg", "moving company near me Regensburg"],
    englishKeywords: ["moving service Regensburg", "moving company Regensburg"],
    mixedLanguageKeywords: ["Umzug Regensburg English", "moving Regensburg Angebot"],
    searchConsoleSignals: ["umzugsunternehmen regensburg", "umzug regensburg"],
    customerProblems: regensburgCustomerProblems,
    conversionCtas: ctas("en", "moving"),
    localModifiers: ["Altstadt", "Westenviertel", "Kumpfmühl", "Prüfening", "Landkreis Regensburg"],
    h2Topics: h2Topics("en", "Moving service", "Regensburg"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/regensburg/moving-company",
    locale: "en",
    region: "regensburg",
    serviceLabel: "Moving company",
    primaryKeyword: "moving company Regensburg",
    secondaryKeywords: ["moving service Regensburg", "relocation company Regensburg"],
    longTailKeywords: ["moving company Regensburg quote review", "English speaking moving company Regensburg"],
    nearMeKeywords: ["moving company near me Regensburg", "movers near me Regensburg"],
    englishKeywords: ["moving company Regensburg", "movers Regensburg"],
    mixedLanguageKeywords: ["Umzugsunternehmen Regensburg English", "moving company Regensburg Angebot"],
    searchConsoleSignals: ["umzugsunternehmen regensburg", "umzugsfirma regensburg"],
    customerProblems: regensburgCustomerProblems,
    conversionCtas: ctas("en", "moving company"),
    localModifiers: ["Altstadt", "Westenviertel", "Kumpfmühl", "Prüfening", "Burgweinting"],
    h2Topics: h2Topics("en", "Moving company", "Regensburg"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/regensburg/moving-costs",
    locale: "en",
    region: "regensburg",
    serviceLabel: "Moving costs",
    primaryKeyword: "moving costs Regensburg",
    secondaryKeywords: ["moving quote Regensburg", "moving estimate Regensburg"],
    longTailKeywords: ["moving costs Regensburg volume stairs access", "review moving quote Regensburg English"],
    nearMeKeywords: ["moving quote near me Regensburg", "moving estimate near me Regensburg"],
    englishKeywords: ["moving costs Regensburg", "moving quote Regensburg"],
    mixedLanguageKeywords: ["Umzugskosten Regensburg English", "moving costs Regensburg Angebot"],
    searchConsoleSignals: ["umzugsunternehmen regensburg", "umzugskosten regensburg"],
    customerProblems: regensburgCustomerProblems,
    conversionCtas: ctas("en", "moving costs"),
    localModifiers: ["Regensburg", "Altstadt", "Kumpfmühl", "Prüfening", "Neutraubling"],
    h2Topics: h2Topics("en", "Moving costs", "Regensburg"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/regensburg/house-clearance",
    locale: "en",
    region: "regensburg",
    serviceLabel: "House clearance",
    primaryKeyword: "house clearance Regensburg",
    secondaryKeywords: ["apartment clearance Regensburg", "flat clearance Regensburg"],
    longTailKeywords: ["house clearance Regensburg with cleaning after moving", "apartment clearance Regensburg quote review"],
    nearMeKeywords: ["house clearance near me Regensburg", "apartment clearance near me Regensburg"],
    englishKeywords: ["house clearance Regensburg", "apartment clearance Regensburg"],
    mixedLanguageKeywords: ["Wohnungsauflösung Regensburg English", "house clearance Regensburg Angebot"],
    searchConsoleSignals: ["wohnungsauflösung regensburg", "entrümpelung regensburg"],
    customerProblems: regensburgCustomerProblems,
    conversionCtas: ctas("en", "house clearance"),
    localModifiers: ["Regensburg", "Altstadt", "Westenviertel", "Landkreis Regensburg"],
    h2Topics: h2Topics("en", "House clearance", "Regensburg"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/regensburg/cleaning-after-moving",
    locale: "en",
    region: "regensburg",
    serviceLabel: "Cleaning after moving",
    primaryKeyword: "cleaning after moving Regensburg",
    secondaryKeywords: ["move out cleaning Regensburg", "handover cleaning Regensburg"],
    longTailKeywords: ["cleaning after moving Regensburg apartment handover", "move out cleaning Regensburg English"],
    nearMeKeywords: ["move out cleaning near me Regensburg", "cleaning after moving near me Regensburg"],
    englishKeywords: ["cleaning after moving Regensburg", "move out cleaning Regensburg"],
    mixedLanguageKeywords: ["Reinigung nach Umzug Regensburg English", "move out cleaning Regensburg Übergabe"],
    searchConsoleSignals: ["reinigung nach umzug regensburg", "büroreinigung regensburg"],
    customerProblems: regensburgCustomerProblems,
    conversionCtas: ctas("en", "cleaning after moving"),
    localModifiers: ["Regensburg", "Altstadt", "Kumpfmühl", "Prüfening", "Neutraubling"],
    h2Topics: h2Topics("en", "Cleaning after moving", "Regensburg"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/regensburg/apartment-clearance",
    locale: "en",
    region: "regensburg",
    serviceLabel: "Apartment clearance",
    primaryKeyword: "apartment clearance Regensburg",
    secondaryKeywords: ["flat clearance Regensburg", "junk removal Regensburg", "apartment clear-out Regensburg"],
    longTailKeywords: ["apartment clearance Regensburg with cleaning after clearance", "English apartment clearance quote review Regensburg"],
    nearMeKeywords: ["apartment clearance near me Regensburg", "junk removal near me Regensburg"],
    englishKeywords: ["apartment clearance Regensburg", "junk removal Regensburg"],
    mixedLanguageKeywords: ["Wohnungsauflösung Regensburg English", "apartment clearance Regensburg Angebot"],
    searchConsoleSignals: ["wohnungsauflösung regensburg", "entrümpelung regensburg"],
    customerProblems: regensburgCustomerProblems,
    conversionCtas: ctas("en", "apartment clearance"),
    localModifiers: ["Regensburg", "Altstadt", "Westenviertel", "Kumpfmühl", "Prüfening", "Burgweinting"],
    h2Topics: h2Topics("en", "Apartment clearance", "Regensburg"),
    intentType: "english-service",
  }),
  strategy({
    path: "/en/regensburg/moving-quote-review",
    locale: "en",
    region: "regensburg",
    serviceLabel: "Moving quote review",
    primaryKeyword: "moving quote review Regensburg",
    secondaryKeywords: ["moving quote comparison Regensburg", "review moving estimate Regensburg"],
    longTailKeywords: ["review moving quote in Regensburg before booking", "English moving quote review Regensburg"],
    nearMeKeywords: ["moving quote review near me Regensburg", "moving estimate review Regensburg"],
    englishKeywords: ["moving quote review Regensburg", "moving quote comparison Regensburg"],
    mixedLanguageKeywords: ["Umzugsangebot prüfen Regensburg English", "moving quote Regensburg Angebot prüfen"],
    searchConsoleSignals: ["umzugsunternehmen regensburg", "reinigungsfirma angebote"],
    customerProblems: regensburgCustomerProblems,
    conversionCtas: ctas("en", "moving quote review"),
    localModifiers: ["Regensburg", "Altstadt", "Kumpfmühl", "Neutraubling", "Lappersdorf"],
    h2Topics: h2Topics("en", "Moving quote review", "Regensburg"),
    intentType: "english-service",
  }),
] as const satisfies readonly StrategyInput[];

export const localSeoKeywordStrategyByPath = new Map(
  localSeoKeywordStrategies.map((item) => [item.path, item]),
);

export const prioritySeoStrategyPaths = localSeoKeywordStrategies.map((item) => item.path) as readonly string[];

export function getSeoIntentCluster(path: string, fallback: FallbackInput): LocalSeoIntentCluster {
  const normalizedPath = path.startsWith("/") ? path : `/${path}`;
  const explicit = localSeoKeywordStrategyByPath.get(normalizedPath);
  if (explicit) return explicit;

  return buildFallbackSeoIntentCluster(fallback);
}

export function getSeoStrategyMeta(path: string) {
  const normalizedPath = path.startsWith("/") ? path : `/${path}`;
  return localSeoKeywordStrategyByPath.get(normalizedPath);
}

function buildFallbackSeoIntentCluster(input: FallbackInput): LocalSeoIntentCluster {
  const isEnglish = input.locale === "en";
  const city = input.cityName;
  const service = input.serviceName;
  const baseKeyword = isEnglish ? `${service} ${city}` : `${service.toLowerCase()} ${city}`.trim();
  const localModifiers = input.localModifiers.slice(0, 8);
  const fallbackIntentType: LocalSeoIntentType =
    input.serviceName.toLowerCase().includes("angebot") || input.path.includes("angebot")
      ? "quote-check"
      : isEnglish
        ? "english-service"
        : "local";

  return {
    primaryKeyword: baseKeyword,
    secondaryKeywords: input.serviceSearchIntents.map((intent) => `${intent} ${city}`),
    longTailKeywords: [
      isEnglish ? `${service} ${city} with photos and quote review` : `${service} ${city} mit Fotos und Angebotsprüfung`,
      isEnglish ? `${service} ${city} scope access timing` : `${service} ${city} Umfang Zugang Termin`,
    ],
    nearMeKeywords: isEnglish ? [`${service} near me ${city}`] : nearMe(city, service),
    englishKeywords: [`${service} ${city}`, `${service} near me ${city}`],
    mixedLanguageKeywords: isEnglish ? [`${service} ${city} Angebot`] : [`${service} ${city} English`],
    searchConsoleSignals: input.serviceSearchIntents,
    customerProblems: isEnglish
      ? ["scope, timing, access and quote details need a clear first check"]
      : ["Umfang, Termin, Zugang, Fotos und Angebot müssen vor einer Zusage klar sein"],
    conversionCtas: ctas(input.locale, service),
    localModifiers,
    h2Topics: h2Topics(input.locale, service, city),
    intentType: fallbackIntentType,
  };
}
